- build_package.py
action='store_true' sets False as default value automatically.
At some places the default values were strings instead of booleans, making it impossible to build the ld-logger for 64 bit only.
> Removed redundant and/or incorrect default arguments.

- README.md
- tests/package_test.md
- thrift_api/thrift_api.md
-Extended main page to better explain what codechecker provides
-Extended thrift API descriptions with links to thrift files
> Extending documentation

- codechecker_lib/analyzer.py
- codechecker_lib/client.py
* Better skip file handling:
Skip files using the last event's location. This resolves Ericsson/codechecker#20 .
* Set skip messages to debug log level from info.
* Don't write out python object ids
> Better ship file handling (issue #20)

- codechecker_lib/build_action.py
- codechecker_lib/log_parser.py
resolves Ericsson/codechecker#34
Uses a hash to compare if a compilation command was already found in the build log file.
> filter duplicate compilation commands from the build action log (issue #34)

- codechecker/CodeChecker
- codechecker_lib/arg_handler.py
a temporary directory will be created before the check to store the original build environment and cleaned up after the analysis is finished
Fixes  Ericsson/codechecker#37
> original build env is saved to a new place (issue #37)

- codechecker_lib/analyzer.py
- codechecker_lib/client.py
- db_model/orm_model.py
- storage_server/report_server.py
- tests/regression_test/test_regression_run_results.py
- thrift_api/report-storage-server.thrift
- thrift_api/report-viewer-server.thrift
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewGrid.js
- viewer_server/client_db_access_handler.py
module name and build target was not filled out during the check caused some bugs in the viewer
remove module name, build target from the database and cleanup filtering and thrift API
Fixes  #33
> clean report filtering (issue  #33)

- thrift_api/report-viewer-server.thrift
- viewer_clients/web-client/index.html
- viewer_clients/web-client/scripts/codecheckerviewer/CodeCheckerViewer.js
- viewer_clients/web-client/scripts/codecheckerviewer/FileViewBC.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewTC.js
- viewer_clients/web-client/scripts/codecheckerviewer/Util.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/MenuButton.js
- viewer_server/client_db_access_handler.py
__Viewer Thrift API changes__
- New method on codeCheckerDBAccess service: _getReport_
- API version changed from 3.0 to 4.0
Other changes:
- Permalinks for tabs including run list, bug overview, and file view
- Browser back/forward support
- Open documentation on new browser tab
Resolves Ericsson/codechecker#32 .
> Permalink and browser back/forward support

- codechecker_lib/log_parser.py
Exemple:
coercing to Unicode: need string or buffer, file found
> Catch the exception 'TypeError' when parse_compile_commands_json fails

- tests/regression_test/test_regression_getall_wrapper.py
- tests/test_helper/__init__.py
- tests/test_helper/thrift_client_to_db.py
I've been putting `run_performance_test.py` in shape, for which I need unlimited versions (aka getAll) of `getRunResults, getNewResults, getResolvedResults, getUnresolvedResults`.
Since these functions are very similar I added an universal `getAll` function to the test helper to minimize redundant code.
> Work on test helper

- codechecker_lib/arg_handler.py
check for psycopg2 module at start to see if every dependency is available and codechecker is ready to start
> check for psycopg2 module at start

- build_package.py
- codechecker/CodeChecker.py
- codechecker_lib/arg_handler.py
- add extra package version information at package build time (package build date, last git commit hash)
- new command line option to get version information:
"CodeChecker version"
fixes #56
> package version

- storage_server/report_server.py
Do not delete build actions with the same command if the check command is
different:
- add check_cmd to the query filter
- add a FIXME before the deleteBuildAction call
This fixes Ericsson/codechecker#107
> Hotfix for #107

- codechecker_lib/option_parser.py
- external-source-deps/build-logger/src/ldlogger-logger.c
- external-source-deps/build-logger/src/ldlogger-util.c
- Remove incorrect space escaping from ldlogger
- Add quotation marks around arguments with spaces
- Use shlex for splitting command line arguments
Fixes Ericsson/codechecker#62
> Fix command line escaping

- codechecker_lib/debug_reporter.py
- codechecker_lib/pgpass.py
- codechecker_lib/util.py
- storage_server/report_server.py
- viewer_server/client_db_access_server.py
- Add a parser for PostgreSQL Password File
- Support PGPASSFILE with pg8000 engine
- Do not log the connection string
- Use SQLAlchemy URL class for connection string composition
This resolves Ericsson/codechecker#147
> Add PostgreSQL Password File support

- external-source-deps/ext_source_deps_config.json
- viewer_clients/web-client/scripts/codecheckerviewer/Editor.js
- viewer_clients/web-client/style/codecheckerviewer.css
Search overlay in CodeMirror based Editor is now persistent, has prev and next buttons, and is also more intelligent.
FIXES Ericsson/codechecker#124
> Better search overlay in CodeMirror

- codechecker_lib/option_parser.py
Added the following flags to be filtered upon build:
-maccumulate-outgoing-args
-fno-toplevel-reorder
-fcall-saved-*
FIXES Ericsson/codechecker#221
> Filtered some build options

- init/init.sh
Logged does not follow symlinks, so common symlink names should be logged as well. This fixes #234.
> Add more compiler names to log.

- README.md
Added dependency wget which is needed during the installation of python modules. /`external/source-deps/ext_source_deps_config.json` declares that `wget `is to be used to get dependencies.
Also the pip install command  should be executed after the codechecker repo is cloned so that it can read the requirements and install them.
> Dependency addition plus fix of ordering of instructions to run during setup

- config/package_layout.json
In a previous commit it has been solved that sourcing init.sh is unnecessary.
In that commit the init.sh script was also deleted, but the init directory is
still there. This is now fixed.
> An empty init directory shouldn't be created in the package.

- codechecker_lib/database_handler.py
- docs/user_guide.md
This commit fixes #235. Now the PostgreSQL server output is written to a postgresql.log file into the workspace directory
> PostgreSQL server output in debug log level.

- tests/quickcheck_test/multi_error.en1.output
- tests/quickcheck_test/multi_error.en2.output
- tests/quickcheck_test/multi_error.output
- tests/quickcheck_test/multi_error.steps.output
- tests/quickcheck_test/nofail.output
- tests/quickcheck_test/nofail.steps.output
- tests/quickcheck_test/simple1.output
- tests/quickcheck_test/simple1.steps.output
- tests/quickcheck_test/simple2.output
- tests/quickcheck_test/simple2.steps.output
turn off g++ warnings for quickcheck tests, not relevant for the tests
> turn off g++ warnings for quickcheck tests, not needed

- viewer_server/client_db_access_handler.py
FIXES Ericsson/codechecker#250
> A proper link to clangSA or clangTidy doc when local doc is missing.

- viewer_clients/web-client/scripts/codecheckerviewer/BugStoreModelTree.js
- viewer_clients/web-client/scripts/codecheckerviewer/FileViewBC.js
This commit fixes #277. All bugs are now shown in the bug tree even if
they have the same bugHash. This happens when a bug is reached on
differet bug paths.
> Show all bugs in bug tree

- codechecker_lib/arg_handler.py
This commit fixes #298. It would be nice to print only those PostgreSQL
parameters which differ from the default ones, but unfortunately at this
point we don't have this information.
> Fix server starting hint command

- codechecker_lib/arg_handler.py
This commit fixes #297. The workspace directory has to exist so SQLite
database can be created there. When CodeChecker server is started
without a previously created workspace, then it causes an error.
> SQLite version server start bugfix

- tests/test_packages/functional/package_cmdline_test/test_cmdline.py
A new test file is added which calls the command line help.
Currently only the result of the call is checked not the content. Could be extended later.
Resolves #283
> add new test for command line help

- .travis.yml
Use [llvm-backport ppa](https://launchpad.net/~adrozdoff/+archive/ubuntu/llvm-backport?field.series_filter=trusty) to install clang 3.7 until other llvm sources will be available travis-ci/apt-source-whitelist#156.
> use llvm-backport ppa for clang 3.7

- codechecker/CodeChecker.py
- codechecker_lib/arg_handler.py
- codechecker_lib/util.py
* In case the PostgresSQL database is started on a remote server the script should not exit if there is no local workspace (because the default workspace value is set in the argument parser)
* local workspace should only be created if a local SQLite or a local PostgreSQL database is used
> if db is remote start server but do not create workspace dir

- codechecker_lib/analyzers/analyzer_types.py
- docs/user_guide.md
This commit fixes #302. If HELLO variable is set in the environment,
then in the config files given by --saargs and --tidyargs all occurences
of $(HELLO) are replaced to its value.
> --saargs and --tidyargs can contain env vars

- tests/test_packages/functional/package_test/test_suppress.py
- viewer_server/client_db_access_handler.py
Suppressing the same bug twice should not fail.
For the second suppression nothing should change.
The suppress comment from the first suppression is kept.
Resolves  #334
Added test for double suppression
> fix the suppressiong handling for the same bug

- external-source-deps/build-logger/src/ldlogger-hooks.c
It is possible that the logged exec call has more than 2048 arguments. In that case the preloaded shared library will crash the original process. The maximum argument count number was increased but further increase might be needed in the future.
> Logger arg size increase

- codechecker_lib/analysis_manager.py
The check might fail for some reason.
Wrong return values were returned in case of error.
Resolves #354
> Fix return value in case of error during check

- codechecker_lib/skiplist_handler.py
the warning about the empty lines is unnecessary
> skiplist fix - do not list empty lines

- codechecker_lib/analyzers/analyzer_clang_tidy.py
The latest clang-tidy (3.9) release enables clang static analyzer
checkers by default. They must be disabled explicitly.
Resolves #371
> Disable clang static analyzer checkers in clang-tidy

- codechecker_lib/analyzers/analyzer_clang_tidy.py
Disable clang static analyzer checkers in clang tidy
Fix #371
> Fix missing dash

- viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js
There was an error in drawing bug path arrows when there were multiple
steps in the same row (e.g. in case of a loop).
> Bugfix for array drawing

- .ci/basic_python_requirements
- .ci/python_requirements
- .travis.yml
- codechecker/CodeChecker.py
- codechecker_lib/arg_handler.py
- codechecker_lib/build_manager.py
- tests/functional/package_test/__init__.py
- tests/functional/quickcheck_test/quickcheck_test_files/Makefile
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error.en1.output
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error.en2.output
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error.output
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error.steps.output
- tests/functional/quickcheck_test/quickcheck_test_files/nofail.output
- tests/functional/quickcheck_test/quickcheck_test_files/nofail.steps.output
- tests/functional/quickcheck_test/quickcheck_test_files/simple1.output
- tests/functional/quickcheck_test/quickcheck_test_files/simple1.steps.output
- tests/functional/quickcheck_test/quickcheck_test_files/simple2.output
- tests/functional/quickcheck_test/quickcheck_test_files/simple2.steps.output
- tests/functional/quickcheck_test/test_quickcheck.py
- tests/test_projects/test_files/Makefile
Fix OSX and Linux errors:
- freeze required python module versions (the newer psycopg2 failed with the older PostgreSQL in the current setup)
- modify test makefiles so intercept build can log them
- use new xcode8 where there is already a proper python
- installing python reinstalls libreadline which broke psql commands
- reinstalling postgresql could update to the proper libreadline but the default postgresql database setup is done before the install part so the initialized database might not be compatible with the reinstalled version
Other:
- quiet-build option was added which is useful for tests
- some pep8 warnings were cleaned up
- dos file format was changed to unix for a few source files
> Fix Travis ci

- codechecker_lib/analysis_manager.py
Special characters in the run name might cause problems at directory creation
where temporary files are stored during the analysis.
> Replace special characters in run name

- codechecker_lib/analysis_manager.py
- codechecker_lib/analyzer.py
- codechecker_lib/analyzers/result_handler_plist_to_db.py
- codechecker_lib/arg_handler.py
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error.en1.output
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error.en2.output
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error.output
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error.steps.output
- tests/functional/quickcheck_test/quickcheck_test_files/nofail.output
- tests/functional/quickcheck_test/quickcheck_test_files/nofail.steps.output
- tests/functional/quickcheck_test/quickcheck_test_files/simple1.output
- tests/functional/quickcheck_test/quickcheck_test_files/simple1.steps.output
- tests/functional/quickcheck_test/quickcheck_test_files/simple2.output
- tests/functional/quickcheck_test/quickcheck_test_files/simple2.steps.output
Fixes  #370.
Some notes to the changes:
- Shared memory values can not be passed as function arguments, that is the reason for the globals.
- They could be moved into an empty imported module
- Result handler no longer prints successful analysis message. It was asymmetric. Now successful and unsuccessful results are printed from the same location.
- Result handler only invoked to process results, when the analysis succeeded. Updated the code to reflect this.
- Invoke the process pool implementation from the quickcheck command. This way multiprocess checking with quickcheck can be implemented in the future. (We might need to lock the standard output for concurrent writes.)
> Analysis progress reporting.

- .ci/auth_requirements
- .ci/basic_python_requirements
- .ci/python_requirements
- README.md
- build_package.py
- codechecker_lib/arg_handler.py
- codechecker_lib/session_manager.py
- config/config.md
- config/session_client.json
- config/session_config.json
- docs/authentication.md
- run_tests.sh
- tests/functional/package_test/__init__.py
- tests/functional/package_test/test_authentication.py
- tests/test_utils/thrift_client_to_db.py
- thrift_api/authentication.thrift
- thrift_api/shared.thrift
- thrift_api/thrift_api.md
- viewer_clients/cmdline_client/authentication_helper.py
- viewer_clients/cmdline_client/cmd_line_client.py
- viewer_clients/cmdline_client/thrift_helper.py
- viewer_server/client_auth_handler.py
- viewer_server/client_db_access_server.py
This merge requests contains the privileged access infrastructure &mdash; closes #339.
If a user **is** authenticated (via any means described below), full access to the server is given: they can view results and destroy them. If the user **is not** authenticated, the entire access is denied &ndash; there are no further fine-graining, as per discussed with @dkrupp and @gyorb.
* A new *Thrift* endpoint at `/Authentication` was implemented, this handles authentication requests
* Authentication can happen against a username-password storage, an LDAP server or the local PAM chain.
* Existing interface was **not** changed, though an invalid session, on a **privileged** server, returns a HTTP error code which can make the `CodeChecker cmd` client fail on an exception &mdash; clients are …
> Privileged access subsystem

- codechecker_lib/database_handler.py
Handle alembic command error. Fixes #384.
> Handle alembic command error.

- codechecker_lib/build_manager.py
The ld logger will not log properly if not the whole absolute path is set
for the log file.
If the user uses a workspace path like this '../workspace' the logger will not
find the log file where the compilation commands should be written.
> Use absolute path for the compilation command file

- storage_server/report_server.py
Some checkers may have no name. This can be caused by misinterpreting a
plist file or by the fault of a checker. In the long terms if such a
missing name is found, it should be checked individually for the given
checker. This commit is mainly for GUI purposes, because in this case a
dangling node appears in the filter field and choosing it results
selecting all findings.
This commit fixes #422.
> Store checker ID "NOT FOUND" if not found.

- README.md
- build_package.py
- codechecker_lib/session_manager.py
- docs/usage.md
- tests/unit/plist_test_files/gen_plist/gen_plist.md
- thrift_api/thrift_api.md
Fixed the following Doxygen warnings:
```
/home/egborho/codechecker-sources/codechecker/tests/unit/plist_test_files/gen_plist/README.md:1: warning: found more than one \mainpage comment block! Skipping this block.
/home/egborho/codechecker-sources/codechecker/docs/usage.md:33: warning: explicit link request to 'suppress' could not be resolved
/home/egborho/codechecker-sources/codechecker/docs/usage.md:34: warning: explicit link request to 'the' could not be resolved
/home/egborho/codechecker-sources/codechecker/docs/usage.md:40: warning: explicit link request to 'clang' could not be resolved
/home/egborho/codechecker-sources/codechecker/docs/usage.md:41: warning: explicit link request to 'is' could not be resolved
/home/egborho/codechecker-sources/codechecker/docs/usage.md:42: warning: …
```
> Fix doxygen warnings.

- codechecker_lib/analyzers/analyzer_clang_tidy.py
- codechecker_lib/analyzers/analyzer_clangsa.py
- codechecker_lib/analyzers/analyzer_types.py
- codechecker_lib/analyzers/config_handler.py
- codechecker_lib/generic_package_context.py
- config/package_layout.json
Cleanups to the invocation of clang-tidy and the static analyzer:
* There can be only one resource dir.
* Do not add resource dir as include path.
* Made the code more compact.
> Command line cleanup

- codechecker_lib/analyzers/analyzer_clangsa.py
Currently it is not enough to forward the compiler resource dir only
with the -resource-dir argument to clang in the current setup.
The resource dir should be set as an isystem argument too to find the
necessary headers.
> Add resource path as isystem path

- codechecker_lib/analyzers/analyzer_clang_tidy.py
The resource dir should be set with the isystem flag too
to find the necessary include paths.
> Clang tidy resource dir as isystem argument

- .travis.yml
coreutils is already available in the base OSX install in travis, no extra install step is needed.
> Remove already installed coreutils

- README.md
Otherwise, you'll get a compilation error about missing "Python.h"
when building one of the dependencies.
> Add Python development headers to requirements

- .travis.yml
After a homebrew thrift package update to thrift 0.10, the build broke because the of the thrift python package and the installed thrift compiler version mismatch.
Set back the thrift compiler to an older version until a [thrift python package v0.10](https://pypi.python.org/pypi/thrift) will be released.
> fix travis OSX thrift version

- codechecker_lib/logger.py
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error.en1.output
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error.en2.output
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error.output
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error.steps.output
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error_skipped.output
- tests/functional/quickcheck_test/quickcheck_test_files/multi_error_suppress.output
- tests/functional/quickcheck_test/quickcheck_test_files/nofail.output
- tests/functional/quickcheck_test/quickcheck_test_files/nofail.steps.output
- tests/functional/quickcheck_test/quickcheck_test_files/simple1.output
- tests/functional/quickcheck_test/quickcheck_test_files/simple1.steps.output
- tests/functional/quickcheck_test/quickcheck_test_files/simple2.output
- tests/functional/quickcheck_test/quickcheck_test_files/simple2.steps.output
- tests/functional/quickcheck_test/quickcheck_test_files/tidy_check.output
- tests/functional/quickcheck_test/test_quickcheck.py
Timestamps give more information about the analysis and build
process than the current log levels. Resolves #465
> Use timestamps in the logs

- codechecker/CodeChecker.py
- codechecker_lib/arg_handler.py
At the end of checking and parsing plist files a hint is shown which
helps the user how to start the CodeChecker server.
Fixes #413.
> Display server start hint at the end of checking.

- codechecker_lib/analyzers/result_handler_plist_to_db.py
- codechecker_lib/build_action.py
- codechecker_lib/client.py
- codechecker_lib/debug_reporter.py
- db_model/orm_model.py
- storage_server/report_server.py
- tests/functional/package_test/__init__.py
- tests/functional/package_test/test_update_mode.py
- thrift_api/report_storage_server.thrift
- viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js
- viewer_server/client_db_access_handler.py
In the previous releases the whole original build command from the compilation
command json file was stored. It could take too much space in the database
if the build commands were long (no compression was used).
To address this issue in the commit ffef1ebfb1a831d84d925bef8df9dd78b8ae2ed7
storing the build command was only done in debug mode.
With that solution the update mode did not work correctly because it
depends on the build command right now.
With this commit the hashed build command from the compilation database
is stored to address the storage size problem and the update mode can
use the stored hash values.
> Build command storage changed to build cmd hash

- viewer_clients/web-client/scripts/codecheckerviewer/ListOfBugs.js
- viewer_clients/web-client/style/codecheckerviewer.css
Simply removing `direction: rtl;` would cause the ellipses to appear on the left again on small screen. This now properly makes the ellipses work and forces the foreslash to appear on the left.
Solution via [http://stackoverflow.com/a/27961022/1428773](http://stackoverflow.com/a/27961022/1428773).
----
Follow-up for #507, this fixes #502.
> Fix webgui file path having '/' on the right

- viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js
CodeMirror renders only the currently visible lines (+-)10 lines by
default. This means that in case of a bug path arrow the source or the
target of the arrow is not rendered where one of the end of the arrow
can bind. Here we raise number of rendered lines. 1000 is an empirical
value. Loading the file and rendering these lines seems to be fast
enough, and the arrows have stopped blinking too.
Fixes #518
> Fixing blinking arrows.

- viewer_clients/web-client/scripts/codecheckerviewer/ListOfBugs.js
- viewer_clients/web-client/style/codecheckerviewer.css
If the path is modified then in the bug list on the next page can't be
queried, since the filtering happens based on this path. So this change
has to be done with CSS. Fixes #502.
> Yet another fix for slash replacement

- viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js
When the page is reloaded and a result is shown in the text view then in
the bug path viewer at the left all bugs of the project were shown.
Fixes #517.
> Show only bugs in the current file on page reload

- codechecker_lib/analyzer.py
- codechecker_lib/arg_handler.py
- codechecker_lib/context_base.py
- viewer_clients/cmdline_client/cmd_line_client.py
The context reads the severity map file so the clients don't need to
reproduce this code.
The plist importer now also can use this severity map.
Fixes #499
> Fix bug classification in the plist importer

- Makefile
- scripts/build_package.py
There were some duplicate instances of `$(CURRENT_DIR)/build` used instead of `$(BUILD_DIR)`.
> Use BUILD_DIR in Makefile everywhere it's applicable

- .gitignore
- Doxyfile.in
- Makefile
Use a local Makefile to set environment variables, makes testing easier.
Doxygen documentation should not be generated for the external
dependecies.
> Improve makefile, fix Doxyfile

- README.md
There is a newer thrift compiler v0.10 available in OSX,
and we depend on an older compiler until this new version
will be available in Ubuntu LTS release.
> change thift compiler version for OSX install

- viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js
It is unnecessary to redraw arrows in the bug viewer when the clicked
step is in the same file. This makes the GUI faster.
Fixes #516
> Omit unnecessary path redraws

- storage_server/report_server.py
When the suppress file and the source code both contain a suppression
for the same bug then both are inserted to the database resulting a
duplicate.
Fixes #504
> Fix duplicate suppression insertions

- codechecker/CodeChecker
In most of the errorneous cases where CodeChecker exits via `sys.exit()`, the bootstrap does not remove saved environments from `/tmp`, which, over long-running machines, created a real clutter.
After this patch, every user-graceful exit of CodeChecker will properly remove the pickle dir.
> Fix environment not getting cleaned up

- viewer_server/client_db_access_handler.py
In commit ec48481e10e5286094bd62c21b4ecb63999c040e, there was a string extraction to a variable but it's use location wasn't named accordingly, thus creating an error in the server if _Show documentation_ is clicked.
> [10:51] - Waiting for client requests on [localhost:8001]
> [ERROR] [10:54] - global name 'sa_checkers_link' is not defined
This didn't result in a server death, only the user not seeing anything when the button is clicked.
(Fixes #566.)
> Fix accidentally unchanged bad variable for 'Show documentation' feature

- codechecker_lib/util.py
Handle OSError exception, the called command might be missing.
> Better error handling for calling external commands

- Makefile
Accidental change in #583 included the separate Makefile in a bad location which made `make` run `make tests`, not `make default` which means `make package`.
> Fix bad Makefile include overriding default target

- scripts/build_package.py
There are some old distros with old certs where this might fail.
> Do not check certificates

- codechecker_lib/arg_handler.py
- storage_server/report_server.py
- tests/functional/diff/test_regression_diff.py
- tests/functional/report_viewer_api/test_get_run_results.py
- tests/functional/report_viewer_api/test_report_filter.py
- tests/functional/update/test_update_mode.py
- viewer_clients/cmdline_client/cmd_line_client.py
The user can delete multiple runs by name, by date (before/after), and
by date based on a name (all runs checked after/before a given run.)
Fixes #453.
> Add options to delete multiple runs.

- Makefile
Do not use the hardcoded full path.
In some machines you might not want to use that python version.
> Use the python2 from the environment (more flexible)

- tests/readme.md
It is more visible together with the other commands.
> Move test running example into the cmd list table

- Makefile
- tests/Makefile
Configurable virtualenvs with Makefile.local
Run tests with no virtualenv instead of automatic virtualenv selection
if dependecies are already installed or virtualenv is set
manually.
> Running test with configurable or no virtualenv

- .travis.yml
This makes sure the OSX test fails as soon as possible if, for example (we've seen it happen quite some times), the LLVM servers are not connectable.
> Reorder OSX before_install to download everything first

- bin/CodeChecker
- bin/CodeChecker.py
- bin/codechecker-log
- libcodechecker/analyze/log_parser.py
- libcodechecker/arg_handler.py
- libcodechecker/host_check.py
- libcodechecker/log.py
- libcodechecker/log/build_manager.py
- libcodechecker/log/host_check.py
- scripts/build_package.py
- scripts/create_new_subcommand.py
- scripts/resources/command_template.py
- scripts/resources/entrypoint_template.py
This PR introduces a new command infrastructure to help in further compartmentalising CodeChecker which begun in #584. Closes #593.
New CodeChecker entrypoints are introduced, following the "usual scheme" set out by the giants ahead of us. In line with, e.g. how Git works (`git log` and `git-log` are both commands), we will now have each "part"/"subcommand"/"feature" of CodeChecker as a direct entry point, such as `codechecker-log`. This, in the future, will help us create more dynamic helps, such as _man pages_ for a Debian package, or a TAB autocompletion support (#576).
In reality, `codechecker-log` and `CodeChecker log` has the same behaviour, `codechecker-log` is just a directly callable wrapper script that is also put in the `PATH`.
> AKA: The decline of `arg_handler.py`. :wink: …
> New subcommand infrastructure + splitting out log command

- www/scripts/codecheckerviewer/codecheckerviewer.js
The menu in the GUI now contains a link which directly navigates to the
GitHub new issue page.
Fixes #585
> "Report a bug here" link in the GUI

- libcodechecker/arg_handler.py
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/output_formatters.py
- libcodechecker/util.py
Introduce a more reusable module for formatting 2d-array data matrices to various formats, such as:
* `rows`: minimal formatting, just rows printed after each other (currently analogue to how `CodeChecker checkers`) output
* `table`: `libcodechecker.util.print_table`
* `dictlist`: _zip_ (the list-to-tuple, not the archiver) the "header" row and each "data" rows into a list of dict objects
* `json`: the `dictlist` in JSON format
`dictlist_to_twodim` is the inverse of `dictlist`.
----
Some of these functions might appear unused as of now, they are getting used in features that I'm introducing later. The reason for this PR is to tighten the scope of features added.
> Refurbish 2d-array to (table|json|csv) converters

- Makefile
The simple clean did not deleted the vendor projects.
There are separate clean targets because during development it is usually enough to clean just the package so you do not have to wait for download of the vendor projects.
Resolves #625
> Separate clean target for package and vendor.

- libcodechecker/storage/report_server.py
Storing Unicode chars for failure messages fails with the current schema.
This is a temporary solution until the new schema is done.
Resolves #618
> escape unicode chars from failure messages

- libcodechecker/analyze/log_parser.py
* From `#define __VERSION__ "5.4.0 20160609"`, `20160609` would be understood as a file or folder name, resulting in clang erroring away.
* Newer versions of GCC/G++ define `__has_include_next` to `__has_include_next__` which is not understood by Clang, as it supplies its **own** `__has_include_next` internally and does **not** define the postfix `__` version.
Thus, such macro definition retrieved from GCC &mdash; which would inevitably lead to a `undefined macro` error &mdash; should not be passed to clang.
> Fix various --add-compiler-defaults errors

- libcodechecker/analyze/log_parser.py
- libcodechecker/log/option_parser.py
- tests/unit/logparser_test_files/intercept-new.json
- tests/unit/logparser_test_files/intercept-old.json
- tests/unit/logparser_test_files/ldlogger-new.json
- tests/unit/logparser_test_files/ldlogger-old.json
- tests/unit/test_log_parser.py
- vendor/build-logger/src/ldlogger-logger.c
- vendor/build-logger/src/ldlogger-util.c
Consider the following file:
```c++
int main()
{
if ( VARIABLE == "a b" )
{
int *p = 0;
*p = 42;
}
}
```
built with `g++ -DVARIABLE='"a b"' main.cpp`.
If we use _LD_LOGGER_, the resulting output will show no errors, as the string in the `build.json` is `"-DVARIABLE="a b""` (one escape level higher, so after stripping the escapes put in by the JSON serializer!) and the options parser will understand this entry as a _file_ (instead of a _compiler option_) in [`log_parser.py#130`](https://github.com/Ericsson/codechecker/blob/d3e53ff1254509770a7cc535a4a58b53bd9be31c/libcodechecker/analyze/log_parser.py#L130). This way, the define never reaches into the analyzer invocation &mdash; thus the macro expansion is never made.
The same issue arises with _intercept-build_ **newest version**, as in …
> Fix escaping multiword string literals, once again

- www/scripts/codecheckerviewer/BugViewer.js
When in the same file another report is clicked then the arrows and bubbles weren't redrawn.
Resolves #641
> Arrow drawing bugfix

- docs/authentication.md
- libcodechecker/session_manager.py
Instance configuration is saved already as `~/.codechecker.instances.json`. Due to having the session token and credential file under `~`, there is no use to have the username in the file. This way, all CodeChecker files are in line with each other, in terms of the name format in the users' home.
> Rename authentication config files to .codechecker.foobar.json format

- libcodechecker/analyze/analyzers/analyzer_types.py
If relative path is available in the configuration the analyzer detection failed.
check_clang returns True if everything is ok.
> fix analyzer detection

- tests/functional/delete_runs/__init__.py
The next check in delete test might fail if the previous failed to fully stop the
locally started PostgreSQL instance.
> Wait for PostgreSQL shutdown after each check

- tests/Makefile
- tests/libtest/env.py
- tests/libtest/project.py
Test projects directory can be configured in the Makefile.local
for different test environments.
> configurable test projects directory

- libcodechecker/analyze/analyzers/result_handler_plist_to_db.py
- libcodechecker/analyze/tidy_output_converter.py
- tests/unit/tidy_output_test_files/tidy1.plist
- tests/unit/tidy_output_test_files/tidy2.plist
- tests/unit/tidy_output_test_files/tidy3.plist
The tidy output parser created control nodes with even if the edges were
empty. Without range information a control section can not be used.
The result storage handler assumed that if a control node exists there
will be edges in it. If there is no edge no information can be stored
about the source positions.
Tidy output parser is modified to do not create a control sections if no
edge is available and storage handler will skip control nodes without
any edges in it.
> Tidy output converter

- .ci/python_requirements_psql_pg8000
- .ci/python_requirements_psql_psycopg2
- .travis.yml
- Makefile
- tests/Makefile
Instead of having two instances on Travis to test Linux and OSX, we can make a bigger build matrix for all three database configurations, totalling 6 different instances.
Why is this good?
* Better separation of errors that _might_ result only in a particular backend. Currently, if `sqlite` tests fail, `psql` tests are never touched.
* Better resillience against OSX-test particularities: instead of one download failure from LLVM/Clang, we can now fail three separate times.
Unfortunately, there wasn't an easy way of generating the new build matrix, due to the peculiarities of cross-OS building &mdash; hence the apparently heavy duplication in `.travis.yml`.
----
I have also cleaned up the install script because it used to install, or at least _check if is installed_ dependencies multiple …
> Speed up CI

- bin/CodeChecker.py
- bin/codechecker-version
- libcodechecker/arg_handler.py
- libcodechecker/version.py
An extra argument was introduced, so the user can request the version in the "usual" table-output formats.
> Move version command to new structure

- .ci/basic_python_requirements
- .ci/python_requirements
- .ci/python_requirements_psql_pg8000
- .ci/python_requirements_psql_psycopg2
Update some of the dependencies.
In case of portalocker, there is a crash fix with python 3.6, see https://github.com/WoLpH/portalocker/releases/tag/v1.1.0
> Update some dependencies.

- libcodechecker/suppress_handler.py
- tests/unit/test_source_suppress.py
If a `SourceSuppressHandler` is constructed for a reportid-checker name-bughash-location tuple and the `get_suppressed()` method is called multiple times on this object, the **first** one will report the actual suppression 3-tuple, but every subsequent call reported `None`. This PR fixes this issue.
Issue arose from the fact that the checker-name specifier `[all]` in the source code was appended multiple times to the list of ignored checkers for the given suppression.
> Make source suppress handler report suppression if asked multiple times

- libcodechecker/analyze.py
Running `CodeChecker analyze nonexistent.file` removed potentially valid results while not replacing them with new ones.
> Don't remove results folder if no analysis could be ran

- libcodechecker/analyze/analyzers/result_handler_plist_to_stdout.py
- libcodechecker/generic_package_suppress_handler.py
- libcodechecker/report.py
After the refactor in #635, the suppression feature in `CodeChecker parse` broke, as the new `report` object didn't contain the data that was needed to check if the file is suppressed according to the suppress file.
> Fix suppress feature in parse broken by plist_parser refactoring

- config/config.json
These two checkers give too many false-positives
> Turn off two ClangTidy checkers

- libcodechecker/analyze.py
- libcodechecker/check.py
- libcodechecker/quickcheck.py
- libcodechecker/store.py
In the current solution the update mode depends on the compilation
commands. If not given to the store command cleaning up the
previous reports will not work properly.
Introduce a new argument for the store command where the
compilation database (json) generated by the log can be used to
get the compilation commands for each source file.
> update compilation command handling

- Doxyfile.in
- config/version.json
There were some important bug fixes what we wanted to be in v5.8 that is why the version increase was reverted previously and the v5.8 tag was moved to another commit.
> working version 5.9

- Doxyfile.in
- docs/deps.md
- docs/usage.md
This will eliminate the warnings given by Doxygen in the build process.
> Fix directory rename missing in Doxyfile

- www/scripts/codecheckerviewer/BugViewer.js
Show tooltip on label instead of dom node at bug viewer.
> Show tooltip on label instead of dom node at bug viewer.

- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/libhandlers/cmd.py
- tests/functional/diff/__init__.py
- tests/functional/diff/test_regression_diff.py
- tests/libtest/codechecker.py
- tests/projects/cpp/project_info.json
> Local compare mode added to CodeChecker cmd diff mode.

- libcodechecker/libhandlers/store.py
- libcodechecker/server/client_db_access_handler.py
If the `compile_cmd.json` is not found in the folder from which `store` stores the data, the update mode can result in different plists considered the same, i.e. an empty result set overwriting actual reports stored from _another_ plist already in the database.
This patch **restores** the pre-5.8 behaviour _in this case_. Because we don't know which build action generated the plist, we assign a good-enough unique identifier, the plist's name, and use that to know which reports to replace with the new ones. This can result in bug duplication, but this behaviour were apparent in pre-5.8 too.
> Fix storing plists without build.json deleting all results already in database

- api/report_server.thrift
- libcodechecker/analyze/analyzers/result_handler_plist_to_db.py
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/server/client_db_access_handler.py
- tests/functional/report_viewer_api/test_get_run_results.py
- tests/functional/report_viewer_api/test_hash_clash.py
- tests/performance/run_performance_test.py
- www/scripts/codecheckerviewer/BugViewer.js
Issue appeared to @dkrupp when doing the "show bug's line in diff" for #723.
For example, in _FFMpeg_, some files' header contains the following line:
```c
* Copyright (c) 2013 Clément Bœsch
```
`œ` is encoded in Unicode as `\u0153`, but Thrift's python client used by `CodeChecker cmd` [only accepts `\u00xy` in the transmitted JSON](https://gist.github.com/fdelbos/3948701#file-tjsonprotocol-py-L206-L211), otherwise, an `Unexpected token: 1` is thrown and the connection dies.
Solution is to introduce a new method to encode the file output (optionally) as a _base64_ string, which in turn can be sent over Thrift via no exceptions and decoded later on.
> Handle a Thrift exception if file content contains Unicode char that escapes as \u01?? by b64ing source text

- tests/functional/delete_runs/__init__.py
E.g.:
| id | date | name |
|----|-------|----------|
|1| 2017-07-18 15:27:47.505669 | simple_0|
|2| **2017-07-18 15:27:48.205769** | simple_1|
|3| **2017-07-18 15:27:48.895728** | simple_2|
|4| 2017-07-18 15:27:49.236572 | simple_3|
|5| 2017-07-18 15:27:49.296572 | simple_4|
In delete runs test cases we first remove runs after **simple_2** (*datetime > 2017-07-18 15:27:48*):
Remaining runs: [simple_0, simple_1, simple_2] :heavy_check_mark:
Secondly, we remove runs before **simple_2** (*datetime < 2017-07-18 15:27:48*):
Remaining runs: [simple_1, simple_2] :x:
> Fix delete runs test cases.

- api/report_server.thrift
Follow-up for #726. There is no such thing as an `optional` **argument** of a function call in Thrift.
This pull request only removes the _warning_ emitted and does not constitute behaviour change, as the argument was enforced by the server and handled by the clients properly, already.
> There is no such thing as an optional argument in Thrift

- Doxyfile.in
- api/report_server.thrift
- config/version.json
- libcodechecker/analyze/analyzers/result_handler_plist_to_db.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/libhandlers/server.py
- libcodechecker/log/build_action.py
- libcodechecker/orm_model.py
- libcodechecker/server/client_db_access_handler.py
- tests/functional/analyze/test_analyze.py
- tests/functional/report_viewer_api/test_hash_clash.py
- tests/functional/update/test_update_mode.py
- www/scripts/codecheckerviewer/BugViewer.js
In this commit the BuildAction is removed as a concept. This also means
that update mode doesn't work any more, because a report is connected to
a run instead of the build action. If a report is already found in the
run then it won't be updated, but skipped. Later in this case the
detection status of the report will be updated.
> Removing BuildAction table and related elements.

- libcodechecker/database_handler.py
- libcodechecker/libhandlers/server.py
Fixes #741, which broke in #682.
With the onset of the `--host` and `--port` specification in #717, only one module still uses databases, that being `server`.
If the wrapper `--workspace` argument is used, the PostgreSQL database is started in `WORKSPACE/pgsql_data`, which was the behaviour since ages ago. (Assuming `--postgresql` mode is used.)
If `--sqlite` is specified, now the server properly uses the explicitly specified database as backend.
**No** calls to the `db_handler` gives an `args` that contains a `workspace` key anymore. The `--workspace` argument in `server` expands to multiple configuration options, but afterwards has to be removed from the dict.
> Fix server ignoring direct --sqlite db specification

- config/session_client.json
- docs/authentication.md
There were a few errors in the docs, mainly formatting and grammar, and a filename presented was bogus.
> Update authentication documentation

- libcodechecker/libhandlers/server.py
- tests/functional/instance_manager/__init__.py
- tests/functional/instance_manager/test_instances.py
The refactoring in #655 introduced a crash if `codechecker-server --stop-all` was called due to `--stop` and `--stop-all` being an `argparse.SUPPRESS` argument and thus raising a `KeyError` if `args.stop` would be used when `--stop` was **not** given.
I've also refactored the ugly long conditional to two early returns.
> Minor fix for server --stop-all

- libcodechecker/analyze/analysis_manager.py
- tests/functional/analyze/test_analyze.py
A ZIP file is created instead of the `[plist_name].error` file which contains the following data:
- The original `build-command` and `analyzer-command`
- The `return-code` of the analyzer
- The `stdout` and `stderr` output (if was present)
- Every file that was `#include`d into the analysed file (along with the source file, of course) in the `source-root` folder, with *full* path.
- If this "dependency" generation fails, a `no-sources` file containing the error reason.
Closes #736.
> Compress full source and metadata if analysis failed

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzers/analyzer_types.py
- libcodechecker/analyze/analyzers/result_handler_base.py
- libcodechecker/analyze/analyzers/result_handler_plist_to_stdout.py
- libcodechecker/libhandlers/analyze.py
- libcodechecker/libhandlers/check.py
- libcodechecker/libhandlers/parse.py
- libcodechecker/libhandlers/quickcheck.py
- libcodechecker/libhandlers/store.py
- tests/functional/analyze/test_analyze.py
- tests/functional/analyze/test_files/simple.cpp
- tests/functional/analyze_and_parse/test_files/multi_error.en1.output
- tests/functional/analyze_and_parse/test_files/multi_error.en2.output
- tests/functional/analyze_and_parse/test_files/multi_error.output
- tests/functional/analyze_and_parse/test_files/multi_error.steps.output
- tests/functional/analyze_and_parse/test_files/multi_error_suppress.output
- tests/functional/analyze_and_parse/test_files/nofail.output
- tests/functional/analyze_and_parse/test_files/nofail.steps.output
- tests/functional/analyze_and_parse/test_files/simple1.output
- tests/functional/analyze_and_parse/test_files/simple1.steps.output
- tests/functional/analyze_and_parse/test_files/simple2.output
- tests/functional/analyze_and_parse/test_files/simple2.steps.output
- tests/functional/analyze_and_parse/test_files/tidy_check.output
- tests/functional/diff/__init__.py
- tests/libtest/codechecker.py
This commit resolves #702 issue.
> Add incremental mode to analysis command.

- www/scripts/codecheckerviewer/ListOfRuns.js
- www/style/codecheckerviewer.css
> Use two columns radio buttons instead of checkboxes at diff.

- bin/CodeChecker.py
Due to the available subcommands being read from file, the option string for the subcommand is considered an Unicode string. Defining true unicode subcommands will definitely not be a case in the long run because CodeChecker is an English system.
The only effect of this fix is that if the user typos the command to use or types in a subcommand that does not exist, the error message will look instead of this:
```
$ CodeChecker whisperity
usage: CodeChecker [-h]
{checkers,analyze,analyzers,check,cmd,log,parse,plist,quickcheck,
server,store,version}
...
CodeChecker: error: invalid choice: 'whisperity' (choose from 'checkers',
u'analyze', u'analyzers', u'check', u'cmd', u'log', u'parse', u'plist', u'quickcheck',
u'server', u'store', u'version')
```
like this:
```
$ CodeChecker whisperity …
```
> Fix invalid subcommand choice printing ustring to commandline

- tests/functional/ctu/__init__.py
- tests/functional/ctu/test_ctu.py
Test infrastructure cannot read configuration file. If `package_layout.json` is written **only in the package made**, (so the one in the source code directory is intact), the test can't reliably load the modified `clang-func-mapping` path.
Instead, for now, we believe that `analyze` can accurately detect if the binary exists, and run the test accordingly.
> CTU test cannot be ran if clang-func-mapping's location is edited in the built package

- libcodechecker/server/client_db_access_handler.py
- tests/functional/report_viewer_api/test_run_filter.py
> Case insensitive run name search

- libcodechecker/server/client_db_access_handler.py
- tests/functional/comment/__init__.py
- tests/functional/comment/test_comment.py
- tests/functional/comment_unauth/__init__.py
- tests/functional/comment_unauth/test_comment_unauth.py
- tests/libtest/codechecker.py
An integer was returned instead of the proper exception type in case of an error.
> Fix exception

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzers/analyzer_base.py
- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/analyze/tidy_output_converter.py
- libcodechecker/log/option_parser.py
- tests/functional/analyze/__init__.py
- tests/functional/analyze/test_analyze.py
> Closes #793.
- Certain build systems, such as that of Linux and Apache Xerces, make `make` make dependency files on the fly. These directives are recorded in the build action, and they derail our dependency list generation which would create the source files in the `failed.zip`.
- If the crash happens in CTU, the dependency list only contains the files originally found by G++/Clang to be a dependency for the build action... Additional to this, we now parse the analyzer output with a regular expression matching lines that mention files, and add these files to the ZIP too.
- A nonexistent dependency file reported by the compiler would crash the current analyzer call. This has been fixed in a way that we explicitly append to the archive, under `failed-sources-root/<filename>` the reason …
> Improve dependency generation at failed analyses

- www/scripts/codecheckerviewer/BugViewer.js
Fixes #767.
This was broken in #768. @csordasmarton Could you review this?
> Fix bug tree showing all bugs in the project

- libcodechecker/server/client_db_access_server.py
- tests/functional/comment/__init__.py
- tests/functional/comment_unauth/__init__.py
It is possible that the workspace was removed before the
server was stopped in that case an IOError was thrown
by the instance manager during the rewriting the configuration
files.
If stopping the server takes more time in the comment tests
the cleanup fails beacause there are files used by the server.
> fix if workspace is removed before server stop

- docs/usage.md
Howto is extended to describe frequently occurring usage error.
> Howto instructions extended for the case when the buildlog is empty.

- www/scripts/codecheckerviewer/BugViewer.js
I improved the performance of drawing bugpath by using CodeMirror `operation` function: http://codemirror.net/doc/manual.html#operation. 
Bubbles (num) | Lines (num) | Current time (ms) | Improved time (ms)
-- | -- | -- | --
25 | 22 | 149.45 | 77.65
31 | 28 | 4102.05 | 2242.63
35 | 31 | 4954.74 | 2797.91
43 | 38 | 6108.59 | 3304.29
47 | 42 | 6716.03 | 3703.16
52 | 46 | 7571.04 | 4196.20
56 | 49 | 7375.35 | 4190.46
54 | 48 | 8973.17 | 4487.09
> Improve performance of drawing bugpath

- www/scripts/codecheckerviewer/ListOfBugs.js
#817 contained a minor oversight. While it fixed the severity field being unsortable, it did not take into account a crucial thing:
https://github.com/Ericsson/codechecker/blob/068c206a01d756b7870d0e1c6d737e9c276787e1/www/scripts/codecheckerviewer/BugViewer.js#L381-L386
When a bug was clicked on in the bug list, the code crashed in `ListOfBugs.js` because the new formatter function was called with the severity **string** (such as `low` or `high`) instead of the severity **enum value** (such as `30`).
I have appended this exact same routine to the changes of #817.
> Fix severity string crashing when a bug is loaded

- api/report_server.thrift
- libcodechecker/analyze/store_handler.py
- libcodechecker/libhandlers/analyze.py
- libcodechecker/libhandlers/check.py
- libcodechecker/libhandlers/quickcheck.py
- libcodechecker/libhandlers/store.py
- libcodechecker/logger.py
- libcodechecker/server/client_db_access_handler.py
- tests/functional/detection_status/test_detection_status.py
- tests/functional/report_viewer_api/test_files/metadata.json
- tests/functional/report_viewer_api/test_hash_clash.py
- tests/projects/simple/Makefile
- tests/projects/simple/project_info.json
> Contains changes of #824 too, as those issues were made apparent on `version6` branch. The `(cherry-picked)` commit will be eliminated at the next rebase of `version6`.
On macOS, the temporary folder is in an entirely different location: `/var/folders/my/[some random string?]/T/tmp[random token]`. :exclamation:
Due to this, `/tmp` must not be hardcoded for the ZIP system. Also, there was some nasty hack of `store` assembling a structure over `/tmp/tmpXXXXX` and zipping it as `tmpXXXXX/reports/*.plist` and so on. On the server, it was saved to `/tmp/tmpYYYYY.zip` which was unzipped to `/tmp/tmpXXXXX` (even if it existed earlier!) and then this path was used later on to find the files.
Instead of this, Python module [`tempfile`](https://docs.python.org/2/library/tempfile.html) is used in …
> Fix store using /tmp for ZIP paths

- libcodechecker/server/client_db_access_handler.py
- libcodechecker/server/client_db_access_server.py
Fixing utf8 parsing errors at store (which makes the storage fail) and showing Exception stack trace when processing thrift POST calls. Will be useful for debugging production environment... 
Fixes #820
> Skipping and replacing non-utf8 characters from source files.

- www/scripts/codecheckerviewer/BugViewer.js
- www/style/codecheckerviewer.css
I changed the report tree to show the actual Detection Status icon instead of list icon.
Old:
New:
What do you think about this?
> Show detection status icon in the report tree

- www/scripts/codecheckerviewer/BugViewer.js
> Fix bug event numbering restarts when the bug path changes file

- .travis.yml
There is no need to download the full Clang history for the macOS tests. This speeds up from 10 minutes to 1 minute to fetch `scan-build-py`, as only ~40k objects need to be downloaded instead of ~700k.
It will also make the macOS cases more resilient against timeouts.
> Make Travis faster by only downloading shallow LLVM on OSX

- api/report_server.thrift
- libcodechecker/server/client_db_access_handler.py
- tests/functional/diff/test_diff.py
If the run id list is empty:
* the results will be returned from all or the runs
* the metrics will be counted for all of the runs
* in compare mode all of the runs will be used as a baseline
excluding the runs in compare data.
New separate api call to count the reports for the runs.
> if no run id is set return/count all reports

- tests/functional/report_viewer_api/test_report_counting.py
Checker messages can change quite rapidly with new clang releases.
Tests can fail quite easily if we depend on them.
> Remove hardcoded checker messages

- api/report_server.thrift
- libcodechecker/analyze/store_handler.py
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/orm_model.py
- libcodechecker/server/client_db_access_handler.py
- tests/functional/report_viewer_api/test_get_run_results.py
- tests/libtest/result_compare.py
- www/scripts/codecheckerviewer/BugViewer.js
- www/scripts/codecheckerviewer/ListOfBugs.js
To get the last bug events is a costly query just to view the line number on the UI.
The Report table is extended with the line and column data for faster query.
The api to get the reports was changed to get the report events only if they really needed.
Resolves #816
> Improve result query performance

- .travis.yml
- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/util.py
There was an issue that if the user had `clang-tidy-3.5` installed whereas `clang-tidy` in the PATH was a newer one, we still used the `-3.5` version.
This has been changed so that the **automatic detection** favours the "non-versioned" binary names, and if one is found, uses the earliest of such in the PATH.
----
Travis need to be changed back so that the custom-installed `clang-3.8` is used instead of `clang` (which is a `clang-3.5` automatically installed by the system). The symbolic link in the home folder takes care of that.
> Find basenamed binary in PATH if present, instead of versioned one

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/plist_parser.py
- tests/functional/diff/test_diff.py
- tests/functional/diff/test_regression_diff.py
- tests/functional/report_viewer_api/test_report_counting.py
- tests/functional/report_viewer_api/test_report_filter.py
- tests/functional/report_viewer_api/test_report_filter_v2.py
- tests/functional/skip/__init__.py
- tests/functional/skip/test_skip.py
- tests/projects/cpp/Makefile
- tests/projects/cpp/project_info.json
- tests/projects/cpp/skip.h
- tests/projects/cpp/skip_header.cpp
- tests/projects/cpp/skip_list
Skipping reports in header files included by a c/cpp
file can be done only after the analysis is done and the
plist output is generated.
With this modification if there is a skip file with headers
in it, the reports from the header will be removed from the
generated plist file.
resolves #812
> fix skip for header files

- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/scripts/productlist/ListOfProducts.js
- www/scripts/productlist/productlist.js
The #773 pull request has broken the commenting and the review status feature,  because it renamed the CC_AUTH_SERVICE to AUTH_SERVICE but in some file it didn't.
We should use the same naming convention in javascript files for CodeChecker services (`CC_` prefix).
> Use the same naming convention at CodeChecker javascript services

- libcodechecker/analyze/store_handler.py
- libcodechecker/server/client_db_access_handler.py
Fixes #878
In the CTU parsing there happened to be a path which goes threw a file
twice, including another file between these two. In the previous
implementation we had a dictionary which contained the files as keys,
but according to the precondition of `collect_path_events()` function
the keys of this dictionary have to be the file list in the same order
as in the plist file including multiple occurrences.
> Fix a storage bug

- api/report_server.thrift
- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libhandlers/cmd.py
- libcodechecker/server/client_db_access_handler.py
- tests/functional/diff/test_diff.py
- tests/functional/report_viewer_api/test_report_counting.py
- www/index.html
- www/scripts/codecheckerviewer/BugFilterView.js
- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
> Checker summary view

- libcodechecker/server/client_db_access_handler.py
At storage the file path has to be normalized in case it contains '..'
part (e.g. a/b/../c/d).
> Foreign key bugfix

- .travis.yml
- libcodechecker/util.py
- tests/projects/cpp/project_info.json
As of 7 September, 2017, Travis has updated the Ubuntu Trusty (14.04) images (automatically loaded at every job start). [Travis news](https://docs.travis-ci.com/user/build-environment-updates/2017-09-06/)
The only important change for us is that now, they automatically ship Clang `3.9` in the image.
This means that our test projects could be updated to use Clang-3.9 hashes, and there is no longer a need to manually install `clang-3.8` in the image. (This further speeds up Travis tests!)
> Update test project for Clang-3.9 on Travis

- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/analyze/analyzers/ctu_triple_arch.py
- libcodechecker/analyze/log_parser.py
- libcodechecker/log/build_action.py
Inclusion of target-specific defines is disabled.
> Auto-detect compiler target and add it to the analyze command.

- libcodechecker/log/option_parser.py
Preserving asserts will improve the quality of the analysis. Fixes #380.
> Preserve asserts. Fixes #380.

- libcodechecker/cmd/cmd_line_client.py
- tests/functional/diff/__init__.py
- tests/functional/diff/test_diff.py
- tests/projects/cpp/call_and_message.cpp
- tests/projects/cpp/project_info.json
> Local compare mode takes in-code-suppressions into consideration.

- libcodechecker/libhandlers/server.py
Initially `root.user` file doesn't exist. If the server is started with
`--reset-root` flag then this file is removed which produces an
exception if the file doesn't exist.
> Fixing root.user file deletion exception

- libcodechecker/server/client_db_access_handler.py
- tests/functional/comment/test_comment.py
Comments are added based on report hash. There were
no bugs with the same hash in the test suite, with the
newly added test files this changed and the comment tests
needed to be updated.
> fix pep8 and broken comment test because of uniqueing

- tests/functional/comment/__init__.py
- tests/functional/comment/test_comment.py
Both run names should have been saved to run the `test_same_bug_hash` test.
Resolves #934.
> Fix test_same_bug_hash test in the comment tests

- libcodechecker/analyze/plist_parser.py
If the 'files' array is modified all of the control, event ...
nodes should be re indexed.
To fix the error caused by wrong indexes to the files array
we keep the file array section as it is for now
even if the source file is skipped.
> do not modify files array in plist at skip

- libcodechecker/analyze/analyzers/result_handler_plist_to_stdout.py
- tests/functional/analyze_and_parse/test_files/multi_error.en1.output
- tests/functional/analyze_and_parse/test_files/multi_error.en2.output
- tests/functional/analyze_and_parse/test_files/multi_error.output
- tests/functional/analyze_and_parse/test_files/multi_error.steps.output
- tests/functional/analyze_and_parse/test_files/multi_error_suppress.output
- tests/functional/analyze_and_parse/test_files/saargs_forward.output
- tests/functional/analyze_and_parse/test_files/simple1.output
- tests/functional/analyze_and_parse/test_files/simple1.steps.output
- tests/functional/analyze_and_parse/test_files/simple2.output
- tests/functional/analyze_and_parse/test_files/simple2.steps.output
- tests/functional/analyze_and_parse/test_files/tidy_check.output
In the parse command also show the severity of the bug like:
```bash
[HIGH] tinyxml.cpp:1884:12: Dereference of null pointer (loaded from variable 'something') [core.NullDereference]
int *something=new int;
```
Resolves #960
> Show severity of the report at parse command

- libcodechecker/analyze/store_handler.py
If the tag is reused in a run, just assign the tag to the new store event,
do not reject the storage itself.
Closes #963
> Update run tag if the same tag is used in one run

- www/scripts/codecheckerviewer/ListOfBugs.js
Use proper run id if we select a report at the same report selector and use
report hash to identify a tab in the ui.
> Fix same report hash selector

- libcodechecker/analyze/store_handler.py
- libcodechecker/server/client_db_access_handler.py
On server side at storage the plist files were parsed twice: once for
gathering the files and once for collecting bug paths and events. The
first phase is not necessary since the .zip file already contains the
file paths and hashes.
> Unnecessary plist parsing on server side.

- libcodechecker/analyze/store_handler.py
- libcodechecker/libhandlers/store.py
- libcodechecker/server/run_db_model.py
The metadata.json was not copied to the .zip file so the duration
information was not sent to the server. Moreover even if this
information is sent, it was always overwritten by the duration of
storage session.
Fixes #883
> Fix analysis duration display in GUI

- www/scripts/codecheckerviewer/BugViewer.js
- www/style/codecheckerviewer.css
If the file path is too long and there is not enough space in the editor header
it is being truncated.
> Handle long file path at the editor header UI.

- libcodechecker/libhandlers/parse.py
If I am parsing a plist file I am getting an error which says that metadata_dict
is not defined.
> Fix non existing metadata_dict at parse

- www/scripts/codecheckerviewer/BugViewer.js
- www/scripts/codecheckerviewer/ListOfBugs.js
If a report is selected from a diff view the report steps are not shown on the
left in the BugTree.
Closes #986
> Report steps are not shown at diff view

- libcodechecker/libhandlers/store.py
context.version is read as a unicode value which can not be sent through thrift string type in python2.
The unicode value should be converted to string.
Resolves #1005
> fix unicode value on thrift api

- libcodechecker/cmd/cmd_line_client.py
- tests/functional/cmdline/__init__.py
- tests/functional/cmdline/test_cmdline.py
> fix cmdline sum command and and test

- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/RunHistory.js
If someone clicks on one of the elements in the run history tab the view does not switch on the Bug Overview tab. The filters are updated at the Bug Overview tab.
Closes #1017
> Switch tab fails on run history selection

- libcodechecker/cmd/cmd_line_client.py
CodeChecker cmd diff, when called with --new should only show bug with
unresolved, new, reopened status.
Closes #1022
> CodeChecker cmd diff --new shows resolved bugs

- www/scripts/codecheckerviewer/BugFilterView.js
- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
Initially, load only the current tab data for some performance reason. For example load checker statistics data if the user opens the relevant tab.
Closes #1019
> Load only the current tab data.

- libcodechecker/analyze/analyzers/analyzer_clangsa.py
> clang should not warn on unused gcc/g++ argumemts

- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
When we run the clang static analyzer there will be no compilation, so there is no point passing `-c`.
> Ignore unused arguments for tidy. Remove redundant argument from SA.

- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/style/codecheckerviewer.css
If I am initializing a dojo CheckedMultiSelect with a store and adding multiple (~500) item to it, it behaves slowly. For performance reason we set the store of the CheckedMultiSelect after items are added to it.
This commit also set the maximum height of the CheckedMultiSelect and resolves the height of the checker statistics tab.
> Fix checker statistics performance

- libcodechecker/libhandlers/store.py
When there are no reports in the report directory then an empty list
will be uploaded which maybe unintentionally sets every reports to
resolved.
Fixes #1000
> Warn the user if empty result list will be stored

- libcodechecker/server/api/report_server.py
We shouldn't wait for file storage to notice that another storage with
the same name is already going.
Fixes #1013
> Check at the beginning of store if another is ongoing

- libcodechecker/analyze/analysis_manager.py
The number of failed build actions should be printed even if it was a
reanalized action.
Fixes #1043
> Print number of failed actions even if reanalized

- libcodechecker/libhandlers/store.py
- libcodechecker/server/api/report_server.py
- libcodechecker/util.py
> Refuse uploading too big .zip files

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzers/analyzer_base.py
> Print analyzer stdout and stderr on debug_analyze loglevel

- libcodechecker/analyze/tidy_output_converter.py
- tests/unit/test_tidy_output_converter.py
- tests/unit/tidy_output_test_files/tidy4.out
Clang-tidy has an output of the following format:
/path/to/file:<line>:<col> message [checker-name]
code_fragment(42);
^~~~~~~~~~~~~
The output may contain an optional fixit. Several groups of these lines
may follow each other.
In case of bugprone-undefined-memory-manipulation checker it happened
that in the last group only the first line appeared. The tidy output
converter assumed that the following lines are also present. If not then
it was an infinite loop.
Fixes #1064
> Workaround for wrong clang-tidy output

- www/scripts/codecheckerviewer/ListOfBugs.js
If I select a report, all of the reports in the current file are shown, on the bug tree view. The report steps are closed for all of the reports, for the currently selected one too. This commit resolves this problem.
Closes #1033
> Bug path is not shown on the UI

- .travis.yml
- tests/Makefile
- tests/libtest/env.py
Closes #984.
The test scripts will automatically create (and in case of a successful test, clean up) configuration databases. This way both PSQL tests can be run without user intervention.
They also use a separate database, postfixed with the DB driver's name.
> Automatically create configuration database for both Postgres tests

- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/server/api/report_server.py
This is the part of the #1038 issue.
> Increase report filter performance

- www/scripts/codecheckerviewer/ListOfRuns.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/style/codecheckerviewer.css
> View run count at the list of runs view

- config/config.json
Enabling cert-err34-c and cppcoreguidelines-pro-type-vararg together
causes an infinite loop. Until this issue is solved, the vararg checker
is removed from all profiles so that it needs to be individually enabled
and thus less likely to trigger the problem.
Fixes #1080.
> Exclude cppcoreguidelines-pro-type-vararg from all profiles

- tests/Makefile
In a prevous commit a Makefile variable was removed but a usage was left
in the code. This made an error at `run_test` make target usage.
> Fix run_test target in Makefile

- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/libhandlers/cmd.py
Local Compare mode should be able to generate HTML files with bug path.
Closes #748
> Local Compare mode HTML output files

- www/index.html
- www/products.html
- www/scripts/browsersupport.js
- www/scripts/codecheckerviewer/BugFilterView.js
- www/scripts/codecheckerviewer/CommentView.js
- www/scripts/codecheckerviewer/RunHistory.js
- www/scripts/codecheckerviewer/hashHelper.js
The latest supported Firefox version is 22.0 (https://ftp.mozilla.org/pub/firefox/releases/22.0/linux-x86_64/en-US/). I have increased the supported browser version to this.
Closes #1084
> Increase Firefox supported version to 22.0

- libcodechecker/server/api/product_server.py
- libcodechecker/server/api/report_server.py
- libcodechecker/util.py
- tests/functional/report_viewer_api/__init__.py
- tests/functional/report_viewer_api/test_run_filter.py
> Escape sql special like characters

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/analyze/analyzers/analyzer_types.py
- libcodechecker/analyze/host_check.py
- tests/functional/ctu/ctu_failure/__init__.py
- tests/functional/ctu/ctu_failure/test_ctu_failure.py
- tests/functional/ctu/test_ctu.py
- tests/functional/host_check/__init__.py
- tests/functional/host_check/test_host_check.py
- tests/projects/ctu_failure/buildlog.json
- tests/projects/ctu_failure/lib.c
- tests/projects/ctu_failure/main.c
* Since https://github.com/Ericsson/clang/pull/199/files we can track which source files corresponding AST had been loaded before a crash.
Therefore, it is no longer needed to have complex regex matching in `get_analyzer_mentioned_files`.
* We put absolute paths into the failed zip under sources-root, because all analyzer runs are using absolute paths.
> Update analyzer mentioned files

- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/analyze/log_parser.py
- libcodechecker/log/option_parser.py
- tests/unit/test_log_parser.py
This fixes a bug where if a compilation db contained multiple
different compilation targets, only one of them was used for
all files.
> Compilation target is registered per build action.

- www/scripts/codecheckerviewer/CheckerStatistics.js
Fix missing offset parameter in the `getCheckerCounts` function at statistics UI module.
> Bad function parameter call at statistics

- www/scripts/productlist/ListOfProducts.js
The DataGrid sort method was throwing an error message because some item wasn't rendered properly.
I have also removed the first `onLoaded` call from the `_populateProducts` function because it is enough to call it after the items are added to the store.
Closes #1101
> Fix sort problem of product listing page

- libcodechecker/analyze/log_parser.py
- libcodechecker/libhandlers/analyze.py
- tests/functional/analyze/test_analyze.py
- tests/unit/test_buildcmd_escaping.py
- tests/unit/test_log_parser.py
Make it possible to load the compiler system includes and target info from a file.
This is good for two reasons:
* We can ctu collect the content of a failed report, since the system includes are stored in `sources-root` dir
* We can analyze independently anytime after a build log. If for some reason the compiler is not available, we can just simply feed the previously saved compiler includes and target files (this is the case with the investigation of a fail zip as well)
> Compiler info from file

- vendor/plist_to_html/Makefile
Instead of executing the `curl` calls all the time, act like how `Makefile`s usually behave: if the "built" files already exist, don't rebuild them. This makes quickly rebuilding CodeChecker a lot faster, and, if more job threads are given, the `curl` calls will also be multithreaded.
> Improve plist-to-html's Makefile for multijob and no redundant downloads

- www/scripts/codecheckerviewer/ListOfRuns.js
Some cases the browser doesn't set the run filter properly. This commit fixes this problem.
> Set run filter by opening a run

- libcodechecker/analyze/plist_parser.py
For some reason, on Firefox, I do experience that in some files. Don't now why but having the plist file is necessary to do anything wrt that.
> When check name is empty, shows in which file it is empty

- libcodechecker/analyze/plist_parser.py
- libcodechecker/analyze/store_handler.py
- libcodechecker/analyze/tidy_output_converter.py
- libcodechecker/report.py
- libcodechecker/server/api/report_server.py
- libcodechecker/util.py
- tests/unit/tidy_output_test_files/tidy1.plist
- tests/unit/tidy_output_test_files/tidy2.plist
- tests/unit/tidy_output_test_files/tidy3.plist
On server side the linecache Python module cached the files from which
it returned a given line. If the file changed and the file was queried
from the cache then the given line returned from the old file version.
In case of ClangTidy the bug hash is generated by CodeChecker. Because
of the previous bug a false bug hash was generated if the line number of
the bug event changed. So now the bug hash is computed on client side
and is written to the .plist file. Server will use this hash instead of
generating it again.
When a bug path changed because it is shifted a few lines downer then
the corresponding line number was only updated in BagPathEvent and
BugReportPoint tables, but not in Report table. This caused a GUI
glitch, i.e. it didn't jump to the correct position when a report was …
> Tidy hash generation bugfixes

- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/ListOfRuns.js
When the browser window is too big then sometimes only a few results
appear. This was because of GUI table rendering issues.
> Fix big screen bug

- docs/user_guide.md
- libcodechecker/libhandlers/server.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/db_cleanup.py
- libcodechecker/server/server.py
- tests/functional/db_cleanup/__init__.py
- tests/functional/db_cleanup/test_db_cleanup.py
- tests/functional/instance_manager/__init__.py
- tests/functional/instance_manager/test_instances.py
- tests/libtest/codechecker.py
When starting server with `--db_cleanup` flag a garbage collection is
run which collects dangling files (i.e. the ones which don't belong to
a bug path any more).
Fixes #785
> Garbage file collection at server startup

- www/scripts/codecheckerviewer/BugFilterView.js
For example when selecting one file in the file filter, the file filter hover box should not be updated. This will allows the user to select multiple items based on a filter.
Closes #1122
> Don't update filter tooltip by clicking on an item

- tests/functional/instance_manager/test_instances.py
DB cleanup consumes some time and in this amount of time the server
can't register in the instance manager, thus the tests might fail.
> Don't cleanup DB in instance manager test

- libcodechecker/server/api/report_server.py
When clicked on a filename in uniqueand non unique mode, the bug list of the file does not appear. This was because we missed the run_id parameter from the getRunResults function.
Closes #1127
> Fix missing run id in getRunResults

- tests/functional/instance_manager/test_instances.py
On some machine it may fail the tests if the server can't register
itself to instance manager too fast. TODO: This should be implemented by
polling the server.
> Sleep more in instance manager test.

- docs/permissions.md
- docs/postgresql_setup.md
- docs/products.md
- libcodechecker/server/permissions.py
> Closes #1137.
Guests will have the `SUPERUSER` permission automatically, and this will be checked against when authentication is not enabled.
The existence of an `auth_session` in `has_permission` (`permissions.py` line 206) is enforced by the server. This will **always** be something if a user is authenticated and always be `None` if the server runs in not authenticated mode.
The behaviour of `default enabled` does not change, but from now on only applies to authentication-enabled servers. If authentication is `ON`, `SUPERUSER` will only be given to *root* and to those explicitly given.
> Give everyone SUPERUSER permission if authentication is not enabled

- scripts/debug_tools/README.md
- scripts/debug_tools/failure_lib.py
- scripts/debug_tools/prepare_all_cmd_for_ctu.py
- scripts/debug_tools/prepare_analyzer_cmd.py
- scripts/debug_tools/prepare_compile_cmd.py
- scripts/debug_tools/prepare_compiler_includes.py
- scripts/debug_tools/prepare_compiler_target.py
These scripts may be used to aid debugging of clang crashes during analysis.
The goal is to reproduce the crash locally, i.e. using the source files in the
failure zip. During the process we take the original compile command database,
compiler includes and compiler target files and we create the modified version
of them (with `_DEBUG` postfix).  These modified files contain the paths
prefixed with the root of the source directory which holds the dependent source
files (`sources-root`).
`prepare_analyzer_cmd.py` creates a new analyzer command which may be executed
immediately, if cross translation unit (CTU) was disabled.  However, to debug
CTU analysis related crashed in clang we have to synthetise the AST dump files
too, so other phases are needed which are done in …
> Add debug tools for ctu

- libcodechecker/server/api/report_server.py
- www/scripts/codecheckerviewer/BugFilterView.js
The checker name filter options should not be limited, because there is no full overview about the number of issues found by the checkers.
Closes #1153
> Do not limit checker name filter options

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzer_env.py
- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/analyze/analyzers/analyzer_types.py
- libcodechecker/analyze/analyzers/ctu_triple_arch.py
- libcodechecker/analyze/host_check.py
> Fix resource dir issue

- libcodechecker/cmd/cmd_line_client.py
- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/util.js
- www/style/codecheckerviewer.css
- Showing severity report count at the statistics page.
- Statistics can be exported to CSV.
Closes #1104
> Severity statistics and csv export

- www/scripts/codecheckerviewer/ListOfBugs.js
If file is opened from the All reports tab, bugs are shown from all runs.
This commit solves the problem to open only those bugs, which is valid for that opened specific run.
Closes #1117
> Show only relevant bugs in the bug tree

- README.md
- docs/feature_comparison.md
This is something I intended to do for a long while now... A quick overview on what subfeatures of CodeChecker is available in the cmd and on the webgui. Seeing as, for example, @Xazax-hun recently messed up in mentioning suppression through cmd in the "False positives guide".
> Feature comparison of cmd and webgui

- tests/performance/run_server_performance_test.py
> Server performance test

- libcodechecker/server/api/report_server.py
- www/scripts/codecheckerviewer/ListOfBugs.js
Ordering by File when Unique reports are enabled should give an alphabetical order.
Closes #1198
> Fix ordering by File in Unique reports mode

- libcodechecker/libclient/authentication_helper.py
- libcodechecker/libclient/product_helper.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/server/server.py
Internal errors in POST (used for thirft) requests were returned
as http errors which could not be parsed by thrift client
(results are expected in json format).
Convert the errors to TApplicationException which can be
processed by the thrift clients.
> POST errors to thrift exceptions in http server

- api/v6/report_server.thrift
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/server/api/report_server.py
- libcodechecker/version.py
- tests/functional/report_viewer_api/test_get_lines_in_file.py
- www/scripts/version.js
This commit introduces new API function to get line content information for multiple files in different positions.
This way we do not make a lot of API call to get line content information when getting resolved bugs from the command line client.
Measurement:
- Old time: 1m17.498s
- New time: 0m1.568s
Closes #956
> Get line content information for multiple files

- tests/functional/report_viewer_api/test_get_lines_in_file.py
Because of copy-and-paste class name was not renamed (#1177). This commit renames the copied class to a unique one.
> Rename get lines function test class

- libcodechecker/server/api/report_server.py
- tests/functional/report_viewer_api/test_run_data.py
> Closes #1202
Show number of unique reports in the run list page.
This commit also fixes non existing type reference to DetectStatus because it has been moved to the report server types from shared.
> Show number of unique reports in the run list page

- libcodechecker/analyze/analyzers/result_handler_plist_to_stdout.py
- libcodechecker/suppress_handler.py
There were issues with the caching property of linecache which
caused errors when source file contents were read. The
already cached source file content was returned instead of the
changed new content.
> remove linecache usage

- tests/Makefile
- vendor/build-logger/Makefile.manual
- vendor/build-logger/src/ldlogger-tool-gcc.c
- vendor/build-logger/test/test_logger.sh
Include paths can also be given via environment variables. The logger
should collect these too.
Fixes #1184
> Fetch include paths from environment variables

- libcodechecker/server/api/report_server.py
- tests/functional/suppress/test_suppress_generation.py
If a file is not present in the zip the content of the file was not changed so no reparse is required when getting suppressions in the code.
> Do not reparse unchanged files to get suppression

- libcodechecker/analyze/analysis_manager.py
> Related to #1219. *Not sure yet if this closes it!*
When a file is added multiple times to a ZIP, at the `.close()` of the `ZipFile` context manager, warnings are raised about this. (ZIP files seemingly can contain the same path twice, but clients can get nondeterministic about which actual content to use if the contents differ between the paths!)
I am absolutely unsure **why** the analysis manager for @sylvestre attempts to put the same file twice into the ZIP. But instead of letting the warnings flow at the end of failure-zip creation, we preemptively check if the file already contains a path, and show a message about this fact.
> Don't attempt to add the same file multiple times to the ZIP

- libcodechecker/analyze/plist_parser.py
- libcodechecker/server/api/report_server.py
Use files from the zip to generate report hash in case of storing run.
> Generate report hash fix

- api/v6/products.thrift
- libcodechecker/server/api/product_server.py
- tests/functional/products/test_products.py
Product `connected` field should be set for backward compatibility reason.
> Product connection backward compatibility fix

- libcodechecker/libclient/client.py
- libcodechecker/server/api/product_server.py
- libcodechecker/server/server.py
- tests/functional/products/test_config_db_share.py
- tests/libtest/codechecker.py
> Closes #876.
Previously, if (at least) two servers were started with the same configuration database, and a product was, through only one server
* added: a warning was issued when the new product was accessed through the other server that even though it is in the database, no connection existed for it
* removed: the user couldn't access the product anymore through neither servers, but the database connection was kept, dangling
This is solved in this patch. In case *any* access request is given to a product that exists in the database but the server has no connection to, the server will try to connect, instead of issuing a warning.
In case of deleted products, the user will be barred access through the "other" servers which no longer find the product in the configuration database but …
> Gracefully handle the addition and removal of products if Config DB is shared

- libcodechecker/server/api/report_server.py
- libcodechecker/server/api/store_handler.py
- tests/functional/detection_status/test_detection_status.py
- tests/functional/report_viewer_api/test_hash_clash.py
- tests/libtest/codechecker.py
Instead of path updates in a storage session we remove all reports with
the given bug hash unless those are set to resolved.
> New report storage method

- libcodechecker/server/api/report_server.py
Client does not handle general exception from the server. This commit solves this problem by using `RequestFailed` type.
> Fix server general exception

- libcodechecker/libhandlers/server.py
- libcodechecker/server/server.py
If not the proper environment is set it is possible that not all
of the database operations are run in the same environment.
This can cause cause version mismatches (not the same psql command
version is used in all cases).
Resolves #1251
> run database operations in the proper environment

- config/config.json
This is the first step of a complex checker, it does not do any useful in its current state.
> Remove alpha.cpluscplus.IteratorRange from all profiles

- .travis.yml
- CONTRIBUTING.md
- libcodechecker/analyze/analyzer_env.py
- libcodechecker/libauth/cc_ldap.py
- libcodechecker/libclient/client.py
- libcodechecker/libhandlers/server.py
- libcodechecker/logger.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/database/config_db_model.py
- libcodechecker/server/server.py
- libcodechecker/util.py
- scripts/create_new_subcommand.py
- tests/Makefile
- tests/requirements.txt
pep8 is deprecated, pycodestyle should be used instead of pep8
There can be an overlap in the changes with #1236
Resolves #1188
> use pycodestyle instead of pep8

- libcodechecker/server/api/report_server.py
If the user tries to get diff hashes for new bugs, where no bugs found in the plist files gets an error message in case of pgsql because empty array is given to the pgsql `unnest` function. This commit solves this problem by returning an empty list.
> Fix get diff hashes for new bugs

- libcodechecker/log/option_parser.py
- tests/unit/test_option_parser.py
Some of the gcc compilation options that
accept files or directories
as arguments (-I,-idirafter, -include ...)
are accepted with and without space between the option
and the option argument. The handling of these
options corrected now.
> Fixing the argument parsing gcc arguments

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzer.py
Using a plain dictionary shared between processes
is not safe and can cause performance degradation too.
Proxy objects should be used.
Move BuildAction preprocessing to analyzer module where
the other build action processing is done.
> use manager to share data between processes

- libcodechecker/analyze/plist_parser.py
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/report.py
"CodeChecker cmd diff" command can generate HTML output
even if the new report set is a local report directory.
Fixes #1277
> HTML format bug report for local compare

- libcodechecker/log/option_parser.py
- tests/unit/test_option_parser.py
In some cases Clang is stricter than GCC regarding the warning messages.
-Werror flag converts these to error messages which thus fail the
analysis. That's why -Werror will be ignored from now on.
> Ignore -Werror

- api/v6/report_server.thrift
- libcodechecker/server/api/report_server.py
- libcodechecker/version.py
- tests/functional/report_viewer_api/test_report_counting.py
- tests/functional/run_tag/__init__.py
- tests/functional/run_tag/test_run_tag.py
- www/scripts/codecheckerviewer/BugFilterView.js
- www/scripts/version.js
If a report is fixed and the date of run tag is older than report's fixed at date, the report should not be shown when the tag is selected in the run history.
Closes #1264
> Fix run tag

- libcodechecker/server/api/report_server.py
Select run history id instead of run id when getting run history tag count.
> Fix run history tag count query

- libcodechecker/server/api/report_server.py
- tests/functional/diff/test_diff.py
> Closes: #1281
The maximum number of compound select in sqlite is 500 by default. We tried to increase SQLITE_MAX_COMPOUND_SELECT limit but when the number of compound select was larger than 8435 sqlite threw a `Segmentation fault` error. For this reason we create queries with chunks.
> Fix diff command fails (sqlite)

- api/v6/report_server.thrift
- libcodechecker/server/api/report_server.py
- libcodechecker/version.py
- tests/functional/report_viewer_api/test_get_run_results.py
- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/util.js
- www/scripts/version.js
- www/style/codecheckerviewer.css
> Closes #1160
Add bug path length column to `Bug overview` table to indicate how long the report path is.
Screenshot:
> Add bug path length column to Bug overview

- www/scripts/codecheckerviewer/RunHistory.js
Set the correct filter name if the user clicks on a run history tag.
> Fix run history tag click event

- www/scripts/codecheckerviewer/BugViewer.js
> Closes #1275
Do not use ComperData object when getting reports for bug tree. Get bug tree reports only by the report run id and file.
> Show reports in bug tree when viewing diff view

- libcodechecker/analyze/plist_parser.py
- tests/unit/test_plist_parser.py
Create a new parameter for plist parsing function to allow the caller to disable plist file update.
> Note: if I ran the unit tests (`make test_unit`), plist parser updated `tests/unit/plist_test_files/clang-3.7.plist` file. I disabled these updates for this unit test.
> Disable plist update on plist parsing unit tests

- tests/functional/ctu_failure/__init__.py
- tests/functional/ctu_failure/test_ctu_failure.py
The test workspace has a lingering `ctu_failure` project folder due to test code layout error.
If you check the output with `nocapture=1` in the `.noserc` (and use the rename of the class in this patch), the following is printed:
```
Test the failure zip contains the source of imported TU ... Running TestCtuFailure tests in /home/<username>/CodeChecker/codechecker/build/workspace/ctu_failure-s7so2I
'analyze' reported CTU-compatibility? False
Has -analyzer-display-ctu-progress? False
SKIP: CTU is not supported
Test the failure zip contains the source of imported TU and all the ... Running TestCtuFailure tests in /home/<username>/CodeChecker/codechecker/build/workspace/ctu_fail
ure-s7so2I
'analyze' reported CTU-compatibility? False
Has -analyzer-display-ctu-progress? False
SKIP: CTU is not …
```
> Fix ctu_failure test not removing its test folder

- tests/functional/ctu/test_ctu.py
- tests/functional/ctu_failure/test_ctu_failure.py
#1303 broke the build because an undefended `os.chdir()` code was moved to an upper folder in the hierarchy.
**No `os.chdir()` calls should be unguarded in the test suite because the working folder is global state!** Having the working folder removed means that subsequent folder changes kill the tests.
> Fix tests being broken due to working directory change

- www/scripts/codecheckerviewer/ListOfBugs.js
Remove `Review comment` column from the `List of bugs` view and move the tooltip to the `Review status` column.
> Remove review comment column from List of bugs

- docs/script_daily.md
- docs/script_update.md
The change to the `WAS_OUTPUT` variable in the previous code was not affecting the parent shell, thus never carrying the change where it should have. We now use a throwaway file in the job's workspace for this.
> Fix the daily analysis integration template script always saying there are new bugs

- libcodechecker/server/api/product_server.py
`dbpass` key is non exist in database connection string. This way the old connection string and the new connection string was different and the server tried to reconnect the product. If the user does not have superuser access, the server throws a `not authorized` exception.
> Fix product editing

- config_db_migrate/versions/150800b30447_share_sessions_through_the_database.py
- libcodechecker/libclient/authentication_helper.py
- libcodechecker/libclient/client.py
- libcodechecker/libclient/credential_manager.py
- libcodechecker/libclient/product_helper.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/libhandlers/server.py
- libcodechecker/server/api/authentication.py
- libcodechecker/server/database/config_db_model.py
- libcodechecker/server/server.py
- libcodechecker/server/session_manager.py
- libcodechecker/util.py
- libcodechecker/version.py
- tests/libtest/thrift_client_to_db.py
> Closes #1145.
Along with the existing storage in the server's memory, user authentication session tokens will also be saved to the *configuration* database, in a new table. This way, if multiple servers are used, the user can authenticate through either and still receive the same token as they had before.
When a session cookie is presented, the following steps are taken to verify it:
* Check if the token exists in the server's memory. If so, previous procedures apply.
* Check if the token exists in the database. If the user is authenticated properly and the token exists, we create a **local** session by reusing the token in the database.
Session expiry times in the configuration file apply to how tokens *in the database* also expire. Expired tokens are not reused, at the attempt of …
> Share user sessions through the database

- docs/user_guide.md
- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzer.py
- libcodechecker/analyze/analyzers/analyzer_base.py
- libcodechecker/libhandlers/analyze.py
- libcodechecker/libhandlers/check.py
- libcodechecker/util.py
- tests/unit/test_subprocess_timeout.py
> Resolves #1168.
`CodeChecker analyze [...] --timeout 600` will set a 600 seconds (10 minutes, this is the default value!) timeout for **each and every** analyzer invocation made by CodeChecker.
If the analysis takes longer than this timeout, the process is killed, and the analysis is considered a *failed* one, with all the "failure-ZIP-creation" and other code executing.
* The `return-code` will be `-1`.
* The `stderr` will contain the following prefix before the analyzer's real stderr:
`>>> CodeChecker: Analysis timed out after 600 seconds. <<<`
----
@sylvestre This method sounds good to you? This will also, hopefully, make it easier to debug **why** a particular analysis invocation failed.
> Terminate analyzer invocation once a timeout passes to prevent hanging

- scripts/debug_tools/prepare_all_cmd_for_ctu.py
When creating the content of the ctu-dir the target architecture was
used to which compilation happened. If the analysis runs on a different
architecture (e.g. for debugging reasons) then the analyzer can't find
the necessary files of which the paths are named after the architecture.
> Use arch of the analizer machine instead of the original one.

- libcodechecker/cmd/cmd_line_client.py
`runs` and `sum` subcommands of the command line client has been forgotten to set up the correct logger. This way the user always got a `No handlers could be found for logger` error message on these command line options.
> Fix setup logger for command line

- libcodechecker/server/api/store_handler.py
Fix typo of argument name introduced in #1286.
> Fix typo of argument name resulting in name error

- libcodechecker/libclient/credential_manager.py
KeyError exception was thrown if there was no token for the
given host:port.
Handling removal more gracefully.
> fix token remove KeyError

- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/cmd/product_client.py
The global LOG should be initialized only after the setup_logger
call which reads up the log config.
If the LOG is initialized at module import time it will use the
default Python logging config. By default this will print the
messages to the standard output which might not be a problem.
Some log messages might go to the wrong place (stdout) before the
logging config is read up in setup_logger if the default setting
in the log config forwards the log messages not to the stdout.
> fix logger initialization

- libcodechecker/libclient/credential_manager.py
If the session config file does not exist in the home directory of the user, do not throw warning message.
> Handle non existing session config file

- config/server_config.json
Do not limit the number of runs which can be stored on the server for a product by default.
> Do not limit run count for server by default

- scripts/debug_tools/failure_lib.py
- scripts/debug_tools/prepare_analyzer_cmd.py
Some standard header files should be present during the analysis from
the standard library. The location of these is now added to the prepared
analysis command.
> Add Clang include path in debug scripts

- www/scripts/codecheckerviewer/ListOfBugs.js
If a bug can be found on different files, uniquing will show only one file. If the user clicks on this bug, we should get the report by setting the file path filter.
> Fix clicking on a uniqued bug

- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libhandlers/cmd.py
* Adding new command line filters for detection status and review status.
* Mark `suppressed` option of the command line client as deprecated.
> Extend command line filters

- db_migrate/versions/dd9c97ead24_share_the_locking_of_runs.py
- libcodechecker/libhandlers/store.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/api/store_handler.py
- libcodechecker/server/database/db_cleanup.py
- libcodechecker/server/database/run_db_model.py
- libcodechecker/server/server.py
> Retry of #1147. Closes #1138.
Instead of using the run table and "shadow" records for the lock, use a proper lock table that locks individual run names.
Instead of wrapping one session into another, deliberately put the lock at the beginning of `massStoreRun`, and remove it at the end of this function. This way, the lock operations are **completely** independent of the transaction buffer that collects the data of the run getting stored, and the *tables* that are accessed by this buffer.
Otherwise, same as #1147.
> Lock runs through the database that are undergoing a store operation

- libcodechecker/cmd/cmd_line_client.py
When using the commmand line to get results only one json should
be returned which can be parsed by other tools.
> fix command line json output

- docs/authentication.md
- docs/products.md
- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/cmd/product_client.py
- libcodechecker/libhandlers/analyze.py
- libcodechecker/libhandlers/analyzers.py
- libcodechecker/libhandlers/check.py
- libcodechecker/libhandlers/checkers.py
- libcodechecker/libhandlers/log.py
- libcodechecker/libhandlers/parse.py
- libcodechecker/libhandlers/server.py
- libcodechecker/libhandlers/store.py
- libcodechecker/libhandlers/version.py
- libcodechecker/logger.py
Remove the default log level from command line arguments because it had always overridden the log level which came from the logger configuration file.
This way if the log level is not specified in the command line it will come from the configuration file. If the log level is specified in the command line it will set the log level of handlers and loggers to this.
> Remove the default log level

- api/v6/authentication.thrift
- libcodechecker/libclient/client.py
- libcodechecker/server/routing.py
- libcodechecker/server/server.py
- libcodechecker/version.py
- www/login.html
- www/scripts/codecheckerviewer/HeaderPane.js
- www/scripts/login/login.js
- www/scripts/version.js
- www/style/codecheckerviewer.css
- www/style/login.css
> Closes #1220.
Instead of prompting the user for `WWW-Authenticate` (the normal browser popup window authentication), use a facade put together in Dojo to ask for user credentials. This way, it is the Thrift API that handles the login of the user, the same way the command-line client does it.
Browsers cache the credentials of a `Authenticate` header which is very hacky to remove. Thanks to dropping that whole functionality, we can now introduce a *Log out* feature, which this patch also does.
> Login window instead of WWW-Authenticate

- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libhandlers/cmd.py
- libcodechecker/server/api/report_server.py
- tests/functional/report_viewer_api/__init__.py
- tests/functional/report_viewer_api/test_run_data.py
User can get command line results for multiple runs by using Python regex expression.
> Multiple run name by using regex at cmd

- config/server_config.json
- docs/authentication.md
- libcodechecker/server/api/authentication.py
- libcodechecker/server/server.py
- libcodechecker/server/session_manager.py
#1301's removal of `WWW-Authenticate` broke the session handling logic that enabled us to have a soft and a hard life-time. (If the user had a session that soft-expired but didn't hard expire, the login window was infintiely looping.) Due to the server not storing anything user session specific within the session itself (it is just only used to allow privileged access), the soft lifetime's reason *"with a login the user could get back settings stored for their session"* is moot.
`soft_expire` has been removed completely from usage. If `soft_expire` is found in the server configuration, it is ignored. The previous logic of `session_expire` being a hard expire now becomes the *only* expire countdown. If this expires, the user has to log in again no matter what.
If soft-expire is ever to be …
> Remove soft session lifetime completely

- www/scripts/login/login.js
- www/scripts/productlist/PermissionList.js
- www/scripts/productlist/ProductSettingsView.js
`Lambda` functions and array `includes` function supported by only modern browsers.
IE explorer doesn't even support these functions.
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes
> https://developer.mozilla.org/hu/docs/Web/JavaScript/Reference/Functions/Arrow_functions
> Fix browser compatibility

- vendor_projects.json
- www/index.html
From version 5.20.0 a git checkout no longer contains a working `codemirror.js` so we download it from the cdn instead of building it with npm.
Closes #1355
> Upgrade codemirror to 5.25.0

- www/scripts/codecheckerviewer/BugFilterView.js
Fix regex search if search string contains multiple stars.
E.g.: `*word*`
Closes #1352
> Fix regex search filter

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/plist_parser.py
- libcodechecker/libhandlers/parse.py
- libcodechecker/libhandlers/store.py
- libcodechecker/util.py
- tests/functional/source_change/__init__.py
- tests/functional/source_change/test_source_change.py
- tests/libtest/codechecker.py
- vendor/plist_to_html/plist_to_html/PlistToHtml.py
> Closes #1320
If the source file content changes between the analysis and the store
the results will not be shown properly after store or parse.
File content changes are checked before:
* store (store will fail if there is a change)
* parse (reports with a source file change will not be printed and
will not count into the statistics)
* plistToHtml (html files will only be generated for the reports where
the source files did not change)
> check source file content change before store/parse/plistToHtml

- libcodechecker/server/api/report_server.py
- libcodechecker/server/api/store_handler.py
* reading up the severity configuration file should
be done only once not for each report
(each get_context call reads up the configuration files rigth now)
> improve storage (severity handling)

- db_migrate/versions/101a9cb747de_add_bug_event_and_point_report_index.py
- libcodechecker/server/database/run_db_model.py
With the new indexes deleting the reports should be much faster.
Storing the reports in update mode (using the same run name) and
deleting a run should be much faster.
> bug event and point to report id index

- libcodechecker/server/api/report_server.py
- www/scripts/codecheckerviewer/ListOfBugs.js
When clicking to the bug report show the report instance with this shortest path among the many similar ones.
Closes #1365
> Fix to select the actual report in unique mode

- docs/user_guide.md
- libcodechecker/libhandlers/parse.py
> Closes #1343
Do not accept 0 positional arguments for parse command as it can lead misleading behavior as it will not find reports as neither `CodeChecker analyze` or `CodeChekcer check` has default output report directory.
> Remove default report directory from parse command

- libcodechecker/server/database/database.py
* For PostgreSQL the default allowed max connection is **100**. If we have to many products and multiple servers then we can reach this limit very easily because we create 5 pool for each product by default.
E.g.: **2 servers** (load balanced) with a _shared database_ which contains **10 products** and **1 config database** will create maximum (10 + 1) * 5 * 2 = **110** pool. In this case we can reach the default connection limit and PostgreSQL will not allow more connections.
* For SQlite we use the NullPool which doesnt pool connections.
> Set sqlalchemy pool size

- libcodechecker/server/api/report_server.py
* use separate sessions for each run deletion
* wich the synchronize_session=False deletion can be speed up
because we do not need the runs in the session anymore,
just cleaning up everything
> change run deletion (session/synchronize)

- www/scripts/codecheckerviewer/ListOfRuns.js
If the check command is too long the popup window of the check command sticks to right. This commit fixes this problem.
Closes #1393
> Set check command dialog maximum width

- www/scripts/login/login.js
- www/scripts/productlist/ProductSettingsView.js
The `error` callback is deprecated since jQuery 1.8. We have to use the `fail` callback instead of this.
> Handle thrift error with fail callback

- libcodechecker/server/permissions.py
`managed_by` field is not set properly for `superuser` which causes an error when user tries to edit global permissions. The bug happened in #1403
> Fix non existing field for superuser

- libcodechecker/analyze/analysis_manager.py
There are empty arguments in the executed command, which are handled by the compiler as positional arguments, i.e. it tries to find files with the name which is equal to the empty string.
Hence the strange errors `c++: error: : No such file or directory`.
This is how the command looks like in one case:
```
[u'g++', '-E', '-M', '-MT', '__dummy', u'', u'-DHAVE_CONFIG_H=1', u'-DXERCES_BUILDING_LIBRARY=1', u'-D_FILE_OFFSET_BITS=64', u'-D_THREAD_SAFE=1', u'-Dxerces_c_EXPORTS', u'-I.', u'-I../src', u'-Isrc', u'-isystem', u'/usr/include/x86_64-linux-gnu', u'', u'', u'-Wall', u'-Wcast-align', u'-Wcast-qual', u'-Wctor-dtor-privacy', u'-Wextra', u'-Wformat=2', u'-Wmissing-declarations', u'-Wno-long-long', u'-Woverlength-strings', u'-Woverloaded-virtual', u'-Wredundant-decls', u'-Wreorder', …
```
> Fix dependency gen problem in xerces

- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libhandlers/cmd.py
- tests/functional/diff/test_diff.py
* Filter runs on the server side.
* Use consistent run name filters.
> Use consistent run name filter at cmd line

- www/scripts/codecheckerviewer/ListOfRuns.js
> Closes #1409
Instead of exact match use prefix search at the List of runs page for filtering runs.
> Use prefix search for run name at the List of runs

- libcodechecker/libhandlers/check.py
> Closes #1421
If the `clean` option is specified for the `CodeChecker check` command clear the output directory.
> Fix check command clean option

- api/v6/products.thrift
- config_db_migrate/versions/bb5278995f41_run_limitation_for_products.py
- libcodechecker/server/api/product_server.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/database/config_db_model.py
- libcodechecker/version.py
- www/scripts/productlist/ProductSettingsView.js
- www/scripts/version.js
> Closes #1410
Run limit can be configured on each product separately.
> Configurable run limit on products.

- libcodechecker/libhandlers/log.py
- libcodechecker/log/build_manager.py
- vendor/build-logger/src/ldlogger-tool-gcc.c
- vendor/build-logger/src/ldlogger-util.c
- vendor/build-logger/src/ldlogger-util.h
The logger can be given a flag if the user wants to keep the linking
actions in the compilation database.
> Don't log linking build actions by default.

- .travis.yml
- Makefile
- tests/Makefile
- tests/README.md
* package target creates a clean package (removes every dependecy and
downloads them again)
* the package needs to be build before the tests explicitly, the
test targets will not build the package
> modify make targets

- config_db_migrate/versions/6b9f832d0b20_add_user_name_and_group_to_session.py
- libcodechecker/server/database/config_db_model.py
- libcodechecker/server/session_manager.py
- tests/functional/products/test_config_db_share.py
Store user specific information in the database (user name, groups) to create local session objects. This way if the user has a valid session token there is no need to login again on server restart.
> Create local auth session by database session

- api/v6/report_server.thrift
- docs/user_guide.md
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/libhandlers/store.py
- libcodechecker/server/api/report_server.py
- libcodechecker/util.py
- tests/unit/test_trim_path_prefix.py
> Closes #1411
Removes leading path from files which will be stored. If multiple prefix is given, the longest match will be removed.
> Trim leading path from stored results

- www/scripts/codecheckerviewer/ListOfBugs.js
> Closes #1466
In diff mode we should get the report data based on baseline and newcheck run ids.
> Fix diff view

- www/scripts/codecheckerviewer/filter/DiffTypeFilter.js
We should reset the filter tooltip items of the diff type filter on filter change.
> Reset diff type filter items on change

- libcodechecker/suppress_file_handler.py
- tests/functional/suppress/test_suppress_generation.py
- tests/projects/suppress/suppress.expected
* Add new test case to test old source code comment file format.
* If status is not found in the source code comment file use `false_positive` by default.
> Support old suppress comment format files

- vendor/build-logger/src/ldlogger-tool-gcc.c
When the build command contains a --include flag with a header file as a
parameter then another build action will belong to that header too. This
is unnecessary, so we include these in this commit.
> Exclude build actions which would compile a header file.

- libcodechecker/analyze/analyzers/analyzer_clangsa.py
Clang 6.0 has new parameters to trigger CTU functionality. Also the API was renamed from XTU to CTU. This puts both 5.0 and 6.0 compatible parameters into the clangsa call, so all clang versions will work.
> Add ctu-clang6 compatibility

- www/scripts/codecheckerviewer/filter/BugFilterView.js
We have to use members instead of global objects at `Bug filter view` because each `Bug overview tab` should have separate state.
> Do not use globals at bug filter view

- www/scripts/codecheckerviewer/filter/SelectFilter.js
- www/style/bugfilter.css
- www/style/icons.css
During CSS code refactoring (#1495) pencil icon was used instead of cogwheel for filter option icons.
> Use cogwheel for filter option icon

- libcodechecker/cmd/cmd_line_client.py
* List out the latest version tag at `cmd runs` command.
* Rename table columns of `cmd runs` command to be consistent with the UI.
This pull request is part of #1485
> List out latest version tag at runs command

- libcodechecker/server/api/report_server.py
- www/scripts/codecheckerviewer/BugViewer.js
- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/util.js
- www/style/codecheckerviewer.css
> Closes #1505
Show bug path length for a report in bug report selection at bug tree and same report selector.
Screenshots:
> Show bug path length for a report

- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/libhandlers/cmd.py
Creates a separate command to get run history of multiple runs.
Closes #1485
> Run history command

- libcodechecker/analyze/plist_parser.py
- libcodechecker/generic_package_suppress_handler.py
- libcodechecker/source_code_comment_handler.py
- tests/functional/analyze_and_parse/test_files/Makefile
- tests/functional/analyze_and_parse/test_files/source_code_comments.cpp
- tests/functional/analyze_and_parse/test_files/source_code_comments.output
> Closes #1484
Do not show bugs which was suppressed as `false poistive` or `intentional` in the source code when using the `parse` command.
> Do not show false positive and intentional bugs at parse

- www/scripts/codecheckerviewer/BugViewer.js
The file path filter is not properly set if the file path contained a white space. This commit fixes this problem.
> Fix UI file path filter for run results

- vendor/build-logger/src/ldlogger-util.c
* handle additional values which should be escaped in the
generated compile command json
> extend build command escaping in the logger

- libcodechecker/libhandlers/server.py
The sqlite database path for the Default product was set up and stored
as a relative path. Any config modification on the UI caused an error.
The sqlite db path is converter to absolute path every time a change
is requested but it did not match the relative path stored in the database.
> fix Default product config modification

- libcodechecker/libauth/cc_ldap.py
- tests/requirements.txt
- tests/unit/test_ccldap.py
* better error handling in case of
- wrong ldap config
- username or credentials are missing
* add ldap authentication test
> ldap hardening and tests

- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/RunHistory.js
> Closes #1481
`_runNameFilter` member has been renamed to `_runBaseLineFilter` at `BugFilterView.js` (#1510) but in some places (CheckerStatistics, RunHistory) we forgot to use the new member.
> Fix non existing filter member

- libcodechecker/log/option_parser.py
Some standard headers are not found by clang-tidy if -flto flag is
given.
> Apply ignore first, and ignore -flto flag.

- libcodechecker/server/routing.py
- tests/functional/products/test_products.py
Product endpoint names can be started with digits or underscores.
> Allow more product endpoint names to be valid

- libcodechecker/libhandlers/store.py
If source files are missing from the system which are in the plist file we should write out the missing file paths too.
> Give better message when source files are missing

- docs/user_guide.md
- libcodechecker/analyze/plist_parser.py
- libcodechecker/libhandlers/parse.py
- vendor/plist_to_html/plist_to_html/PlistToHtml.py
> Closes #1423
Do not generate report for `false_positive` and `intentional` bugs when using html output of parse command.
> Fix inline source comment in html output

- docs/user_guide.md
- libcodechecker/libhandlers/cmd.py
We should not list html output for command line commands which do not support this (`products list`, `runs`, `sum` etc).
> Allow html output only for diff and results at cmd

- libcodechecker/source_code_comment_handler.py
- tests/functional/analyze_and_parse/test_files/Makefile
- tests/functional/analyze_and_parse/test_files/multi_error_suppress_typo.cpp
- tests/functional/analyze_and_parse/test_files/multi_error_suppress_typo.output
If the valid review status comment is part of the misspelled
review status comment it will be detected as a mark but parsing the
comment will fail.
> fix review status comment typo handling

- libcodechecker/analyze/log_parser.py
- tests/unit/logparser_test_files/include.json
- tests/unit/test_log_parser.py
If the logged build command contains an include like "-I relative_path", it is logged into the compile.json as relative to the build directory. However, if other CodeChecker commands try to use this compile.json outside the build directory, includes with relative path will not be available at the defined location. This fix tries to solve this by prepending the build directory if the include path does not represent a directory on the disk.
> Issues with relative path in the compile json

- docs/usage.md
- libcodechecker/analyze/plist_parser.py
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libhandlers/parse.py
- libcodechecker/report.py
- libcodechecker/server/api/report_server.py
- tests/functional/analyze_and_parse/test_files/Makefile
- tests/functional/analyze_and_parse/test_files/simple1.deduplication.output
- tests/projects/cpp/Makefile
- tests/unit/test_report_path_hash.py
In the command line (diff and print commands ) the results in the same header files should be shown and counted only once even if they were found multiple times because multiple c/cpp files included them.
Closes #1465 and Closes #1512.
> Command line deduplication

- api/v6/report_server.thrift
- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libhandlers/cmd.py
- libcodechecker/server/api/report_server.py
- libcodechecker/source_code_comment_handler.py
- tests/functional/report_viewer_api/test_run_data.py
- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/ListOfRuns.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/scripts/codecheckerviewer/filter/BugFilterView.js
- www/scripts/codecheckerviewer/filter/UniqueFilter.js
- www/style/codecheckerviewer.css
> Closes #1443 and Closes #1541
Consistent report counting
* `Number of reports` should be `Number of unresolved reports` and should be equal with `non unique all reports - resolved - false positive - intentional`.
* Disable uniqueing at detection status count on the Runs page.
* Disable uniqueing at the left hand side filter by default.
* Set default filter set to the following values:
- Review status: Unreviewed, Confirmed
- Detection status: New, Reopened, Unresolved
* Uniqueing can be disabled at the command line and UI.
> Consistent report counting

- www/scripts/codecheckerviewer/filter/FilterTooltip.js
If an item is selected and the user clicks on that item to deselect it we should first toggle the class of the tooltip item because deselecting the filter item will call the deselect of the tooltip item which cause bad behaviour.
> Fix UI filter tooltip toggling items

- libcodechecker/analyze/plist_parser.py
- tests/functional/analyze_and_parse/test_analyze_and_parse.py
> Closes #1559 and Closes #1062
Show full file path in `CodeChecker parse` ouptut.
> Show full file path in parse output

- www/scripts/codecheckerviewer/RunHistory.js
- www/scripts/codecheckerviewer/filter/SelectFilter.js
If the user clicks on a run history item select default filter values for review status and detection status.
> Set default filter values on run history click

- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/scripts/codecheckerviewer/filter/BugFilterView.js
If the user clicks on a run at the Run page, it will not filter the results by runs only by other filters. We should set the correct run values in the initialization time when the Bug viewer tab first being opened.
> Init run filters with the correct values

- vendor/plist_to_html/plist_to_html/PlistToHtml.py
Plist to HTML parser should use the correct file path from the main section of the report.
> Use file path from main section at plist-to-html

- vendor/plist_to_html/plist_to_html/PlistToHtml.py
Creates a new id column in the `index.html` page for reports.
> New column id in index.html at plistToHtml parser

- www/scripts/codecheckerviewer/ListOfBugs.js
> Closes #1392 
Reset URL query parameter values with correct values if Run history tab is active.
> Reset URL parameters when history tab is active

- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/filter/UniqueFilter.js
- www/scripts/codecheckerviewer/util.js
- www/style/codecheckerviewer.css
- www/style/icons.css
Show a tooltip which describes the meaning of unique checkbox by hovering on unique checkbox label.
> Show tooltip by hovering on unique checkbox label

- www/scripts/codecheckerviewer/filter/BugFilterView.js
- www/scripts/codecheckerviewer/filter/DetectionStatusFilter.js
- www/scripts/codecheckerviewer/filter/UniqueFilter.js
- www/style/bugfilter.css
- www/style/icons.css
> Closes #1513 and Closes #1337
A detection status belongs to a report. If uniqueing is enabled multiple detection statuses can belong to the same bug. With this patch report count for detection status filtering will be disabled if uniqueing is enabled.
> Disable detection status counts in unique mode

- www/scripts/codecheckerviewer/filter/BugFilterView.js
- www/scripts/codecheckerviewer/filter/ReportCount.js
- www/style/bugfilter.css
Refactoring filter UI:
* Put Unique reports filter to a new line.
* Bolden the label of Unique reports filter and report count.
Screenshot:
> Refactoring filter UI

- libcodechecker/libclient/client.py
- libcodechecker/server/api/product_server.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/database/database.py
- tests/functional/products/test_config_db_share.py
- www/scripts/productlist/ListOfProducts.js
`getProducts` API function extended the filters with '%' wildcards. This way we couldn't do exact match on product names and endpoints. Client should set wildcards instead of the server.
> Fix getProducts API function to do exact match

- libcodechecker/server/api/report_server.py
PGSQL throws the following exception when using source component filter: `subquery in FROM must have an alias`.
> Fix source component filter query in pgsql

- www/scripts/codecheckerviewer/ListOfBugs.js
Show `detected at` and `fixed at` dates over the detection status icons at `Bug overview` page.
> Show detection status dates in tooltip

- libcodechecker/log/build_action.py
Since version 6.3 the build action hash contains the build output, which led to multiple analysis of files with essentially the same build actions compiled into different outputs (due to their different hash). This is unnecessary, since the output does not change the analysis, and results in a performance drawback. Removing the build output from the hash seems to increase the performance without affecting the analysis results.
> Remove the build output from the build action hash.

- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/filter/BugFilterView.js
> Closes #1603
Problem: list of reports hadn't been filtered with the default filter values (e.g.: false positive) when the user clicked on a run at the Run page.
Report filter should be initialized when the user opens a run on the Run list page and should set the correct baseline and newcheck values.
> Init filter values on show event of Bug overview

- libcodechecker/libhandlers/cmd.py
> Closes #1432
Set default filter values (Review status - *Unreviewed*, *Confirmed*; Detection status - *New*, *Reopened*, *Unresolved*) for `CodeChecker parse` and `CodeChecker diff` command line tool.
> Set default filter values for parse and diff

- www/scripts/codecheckerviewer/ListOfBugs.js
This commit fixes the following problem:
- Click to All reports tab
- Click to Run history tab
- Click to Runs tab
- Click again to the All reports tab but it will remain to the Runs tab.
> Fix run history tab value in the URL on show event

- libcodechecker/analyze/log_parser.py
- libcodechecker/log/build_action.py
- tests/unit/test_log_parser.py
When there are two build actions which differ only in the manner of the
action (complation/preprocess) then only the first one will be included:
g++ -M main.cpp
g++ -c main.cpp
The second one is the relevant from analysis point of view.
> Distinguish BuildAction objects on original build command

- www/scripts/codecheckerviewer/BugViewer.js
If getting the items of bug tree takes a long time it will not expand the correct node. For this reason we have to set the path attribute of bug tree after items are added to it.
> Set file path after items are added to bug tree

- libcodechecker/libhandlers/check.py
Most of the flags under CodeChecker analyze should be also provided
under CodeChecker check. The --stats and related flags were missing.
Fixes #1643
> Add statistics checkers' flags to CodeChecker check sub-command

- libcodechecker/analyze/tidy_output_converter.py
- tests/unit/test_tidy_output_converter.py
- tests/unit/tidy_output_test_files/tidy6.out
If the output contained multiple notes after an error the tidy output converter generated a report for the error and the notes too. This commit resolves this problem by changing the message line regex.
> Fix tidy output converter

- vendor/plist_to_html/Makefile
- vendor/plist_to_html/plist_to_html/PlistToHtml.py
- vendor/plist_to_html/plist_to_html/dist/index.html
- vendor/plist_to_html/plist_to_html/dist/js/browsersupport.js
- vendor/plist_to_html/plist_to_html/dist/js/bugviewer.js
- vendor/plist_to_html/plist_to_html/dist/layout.html
Show warning message if the browser is not supported when looking html files generated by Plist to HTML parser.
> Plist to html browser support

- www/scripts/codecheckerviewer/ListOfBugs.js
> Closes #1469
If no report can be found based on the given URL, remove the report hash and the report id from the URL.
> Fix non existing report in the GUI

- docs/usage.md
- tests/functional/analyze_and_parse/test_files/compiler_warning_no_warn.output
- tests/functional/analyze_and_parse/test_files/compiler_warning_simple.output
- tests/functional/analyze_and_parse/test_files/compiler_warning_wno_group.output
- tests/functional/analyze_and_parse/test_files/compiler_warning_wno_simple1.output
- tests/functional/analyze_and_parse/test_files/compiler_warning_wno_simple2.output
- tests/functional/analyze_and_parse/test_files/compiler_warning_wunused.output
#1648 changed the analyzer output format but we forgot to change the format in some test cases and user guide.
> Fix compiler warning test cases

- www/scripts/codecheckerviewer/CheckerStatistics.js
Call `getSeverityCounts` API function with the correct number of parameter.
See:
https://github.com/Ericsson/codechecker/blob/fecec6f4dca8c24b7030645212a95eec9a8016e5/api/v6/report_server.thrift#L400-L403
> Call getSeverityCounts correctly

- libcodechecker/analyze/log_parser.py
The --sysroot flag can be given a directory these ways, but only the
first one was supported by CodeChecker when fetching implicit include
paths:
--sysroot=/path/to/sysroot
--sysroot /path/to/sysroot
> sysroot parameter can be given multiple ways

- tests/libtest/codechecker.py
The sleep function should only be called when a new server is really
started. Due to the wrong indentation this sleep always occurred.
> Fasten tests

- vendor/plist_to_html/plist_to_html/PlistToHtml.py
- vendor/plist_to_html/plist_to_html/dist/js/bugviewer.js
- www/scripts/codecheckerviewer/BugViewer.js
Both 'parse' and 'store' ignored newlines. This patch fixes that.
> Multiline messages are displayed properly

- libcodechecker/log/option_parser.py
- tests/unit/test_option_parser.py
> Ignore target dependent -mabi compiler option.

- libcodechecker/analyze/plist_parser.py
- libcodechecker/generic_package_context.py
- libcodechecker/libhandlers/checkers.py
- libcodechecker/server/api/store_handler.py
- tests/functional/analyze_and_parse/test_files/compiler_warning_simple.output
- tests/functional/analyze_and_parse/test_files/compiler_warning_wno_group.output
- tests/functional/analyze_and_parse/test_files/compiler_warning_wno_simple1.output
- vendor/plist_to_html/plist_to_html/PlistToHtml.py
Set severity level of `MEDIUM` for compiler warnings by default.
> Set default severity level for compiler warnings

- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libhandlers/parse.py
- vendor/plist_to_html/plist_to_html/PlistToHtml.py
Pass the checker severiy map dictionary (instance of SeverityMap) to the PlistToHtml parser instead of the file path. This way we will get default severity levels for clang warnings and for unspecified checker names by using this map.
> Pass severity map dictionary instead of the file

- www/scripts/codecheckerviewer/filter/BugFilterView.js
- www/scripts/codecheckerviewer/util.js
> Closes  #1666
Shorter syntax for method definitions on objects are introduced in ES2015 which is not supported in older browsers. This pull request fixes this problem.
> Fix JavaScript old browser compatibility

- libcodechecker/analyze/plist_parser.py
- libcodechecker/libhandlers/parse.py
Refactoring the code to print the parse statistics at the end of parse command not in the `PlistToPlaintextFormatter`.
> Print statistics at the end of parse command

- docs/checker_and_analyzer_configuration.md
- docs/usage.md
- docs/user_guide.md
> add checker and analyzer configuration documentation

- www/scripts/codecheckerviewer/ListOfBugs.js
When opening a product, all reports are queried even if "All reports"
tab is not active. In case of >200000 reports this runs a huge query in
the background which occupies a whole thread for a relatively long time.
With this modification the reports are queried only when the grid is
shown.
> Query reports only when shown.

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzer.py
- libcodechecker/analyze/pre_analysis_manager.py
When the analysis stops with Ctrl-C then the subprocesses in the process
pool are not terminated. The reason is that the shared data structures
managed by multiprocess.managers.SyncManager() type die before the
termination of processes. This causes an exception in pool.terminate()
which makes the subprocesses of the pool zombies.
> Zombie processes remain on analysis interruption

- api/v6/report_server.thrift
- config/server_config.json
- docs/server_config.md
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/libhandlers/store.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/session_manager.py
- tests/functional/storage_of_analysis_statistics/__init__.py
- tests/functional/storage_of_analysis_statistics/test_storage_of_analysis_statistics.py
- tests/libtest/env.py
> Upload analyzer statistics information

- docs/user_guide.md
- libcodechecker/libhandlers/cmd.py
- libcodechecker/server/api/report_server.py
- tests/functional/component/test_component.py
* filtering sub path values was not handled properly
if there are test, test_proj, test_files, test_data directories
the following filter did not work properly, results from test_data
and test_proj were shown in the results list after the filtering
+*/test*
+*/test_files/*
+*/test_data/*
-*/test_p*
> change component filtering behavior

- docs/user_guide.md
- libcodechecker/analyze/analyzer.py
- libcodechecker/analyze/pre_analysis_manager.py
- libcodechecker/analyze/statistics_collector.py
- libcodechecker/libhandlers/analyze.py
- libcodechecker/libhandlers/check.py
- tests/functional/statistics/test_statistics.py
- tests/projects/cpp/Makefile
- tests/projects/cpp/statistical_checkers.c
- tests/unit/test_statistics_collectors.py
New configuration options are introduced for statistical
checker counting: stats-min-sample-count, stats-relevance-threshold
Resolves #1589
> New configuration options for statistical counting

- www/changelog.html
- www/style/changelog.css
> Describe new features of v6.8

- libcodechecker/version.py
- www/scripts/version.js
In some pull request (e.g.: #1649, #1721) we forgot to increase the API version.
> Increase API version

- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/CheckerStatisticsFilter.js
- www/scripts/codecheckerviewer/filter/BugFilterView.js
- www/scripts/codecheckerviewer/filter/ReviewStatusFilter.js
- www/scripts/codecheckerviewer/filter/SeverityFilter.js
> Closes #1684
Add `Detection status`, `Review status` and `Severity level` filters to the statistics page.
> Refactoring Checker statistics page

- www/scripts/codecheckerviewer/ListOfRuns.js
- www/style/codecheckerviewer.css
Show labels for `ctu` and `statistics` beside the run name it these are enabled during the analysis.
> Show ctu and stats labels besides the run name

- api/v6/report_server.thrift
- db_migrate/versions/39f9e96071c0_analyzer_statistics.py
- db_migrate/versions/9987aa593ca7_add_codechecker_version_to_run_history.py
- libcodechecker/analyze/analysis_manager.py
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/api/store_handler.py
- libcodechecker/server/database/run_db_model.py
- libcodechecker/version.py
- www/changelog.html
- www/scripts/codecheckerviewer/AnalyzerStatisticsDialog.js
- www/scripts/codecheckerviewer/ListOfRuns.js
- www/scripts/codecheckerviewer/RunHistory.js
- www/scripts/version.js
- www/style/codecheckerviewer.css
- www/style/icons.css
- www/style/runhistory.css
> Closes #565
* Add CodeChecker version to the run history table and shows this at the Run and Run history pages.
* Create an analyzer statistic table which stores the number of failed and successfully analyzed files for each analyzer types.
* Show analyzer statistics at the run history and run pages.
> Analyzer statistics

- libcodechecker/server/api/report_server.py
`PostgreSQL` database throws an error message which says that columns must appear in the `GROUP BY` clause. This commit fixes this problem.
> Fix sql query

- libcodechecker/log/option_parser.py
- tests/unit/test_option_parser.py
Essential for checking the Chromium project.
Without this patch `-Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers`
becomes (for clangsa options parser) `-mllvm -fcomplete-member-pointers` which is incorrect.
> Skip '-Xclang <opt>'

- vendor/plist_to_html/plist_to_html/PlistToHtml.py
If the plist to html converter was used separately from CodeChecker the missing severity levels caused problems during the html generation.
> fix plist to html converter missing severity

- www/scripts/codecheckerviewer/ListOfBugs.js
> Closes #1748 
There was an error when changing run tab:
- Open a run.
- Open a bug in the previously opened run tab.
- Open another run.
- We can not see the results in the firstly opened run tab.
This commit solves this problem by set the correct tab value in the URL.
> Fix changing run tab

- libcodechecker/util.py
- tests/functional/analyze_and_parse/test_files/source_code_comments.cpp
- tests/unit/test_source_code_comment.py
If there is a non breakable space character in the
review status comment the parsing and the comment handling fails.
> fix non breakable space character

- libcodechecker/server/api/report_server.py
- libcodechecker/util.py
- tests/unit/test_slugify_file_name.py
If run name contained a non-alpha character (for example a slash) the storage of analysis statistics failed because a directory name can not contain such characters. This commit fixes this problem by normalizing the run name.
> Slugify run name when storing analysis statistics

- requirements_py/dev/requirements.txt
In order to run make test we also need pycodestyle, so I think it would make sense to have it in the dev requirements.
> Add missing requirement.

- libcodechecker/server/api/report_server.py
If the analyze command doesn't exit in the `metadata.json` file use an empty string instead of the server command when storing analysis results.
> Fix storing check command

- libcodechecker/log/option_parser.py
- tests/unit/test_option_parser.py
Preserve '-nostdinc++' in command line, the same as done for  '-nostdinc'.
Essential for checking the Chromium project.
> Preserve -nostdinc++ in command line, the same as for -nostdinc

- libcodechecker/server/api/report_server.py
Convert exception to string instead of using message attribute because some exception doesn't set this attribute correctly (e.g.: `UnicodeDecodeError`).
> Fix exception message printing at server

- vendor/plist_to_html/plist_to_html/dist/js/bugviewer.js
Show forward arrow at bug steps when generating html with PlistToHtml parser and set error style for the last bug step.
> Fix plist to html parser

- libcodechecker/analyze/log_parser.py
- tests/unit/test_log_parser.py
In pull request #1553 the relative include paths have been changed to absolute based on the working directory from the build json file. The intention was to accomplish as less modifications on the provided build command as possible. However, leaving relative paths in a plist interferes with the skipfile functionality:
project files:
```
/absolute/path/to/the/project/a/b/f.h
/absolute/path/to/the/project/main.cpp
```
good build command: `g++ -I/absolute/path/to/the/project/a main.cpp`
bad build command: `g++ -I./a main.cpp`
main.cpp:
```cpp
#include "b/f.h"
int main() { ... }
```
skipfile:
```
-/absolute/path/to/the/project/a*
```
This configuration doesn't skip the reports from subdirectory "a" with the bad build command.
> Convert relative include paths to absolute

- libcodechecker/server/api/store_handler.py
When storing runs to the database with the --force flag enabled, not
flushing the database session after deletion seems to cause the
following insert operation to fail in case of PostgreSQL.
Fixes #1802
> Fix database error when storing with force flag enabled

- libcodechecker/report.py
- libcodechecker/util.py
file encoding errors can happen because of platform and
environment encoding mismatch, to handle this try to encode
source file line reading to utf-8 and replace characters
where the encoding failed with '?'
resolves #1800
> handle file encoding errors

- docs/user_guide.md
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/analyze/analyzers/analyzer_types.py
- libcodechecker/analyze/analyzers/config_handler.py
- libcodechecker/analyze/analyzers/result_handler_clangsa.py
- libcodechecker/libhandlers/analyze.py
- libcodechecker/libhandlers/check.py
- tests/functional/analyze_and_parse/test_files/Makefile
- tests/functional/analyze_and_parse/test_files/context_free_hash.output
- tests/functional/analyze_and_parse/test_files/context_hash.cpp
- tests/functional/analyze_and_parse/test_files/context_sensitive_hash.output
> Closes #1801
The bug identification hash generated by `Clang Static Analyzer` contains the function name in the hash calculation. This is not appropriate for projects where the name of the functions change frequently. This commit introduces a new argument for the analyze and check subcommands which would calculate the hash value as `Clang Tidy`. If this switch is used, the bugs will be identified with the CodeChecker generated context free hash even though the `Clang Static Analyzer` generated a context sensitive hash.
> Context free hash

- tests/Makefile
without sourcing the python virtual environment the
pycodestyle command was not found
> source venv before pycodestyle

- .travis.yml
If the boost package is installed by the thrift package (dependency)
it will be build from source which takes to much time on travis without
any output so the travis jobs fail.
> ugrade boost before thrift install

- .travis.yml
boost build is really slow and times out with xcode8
upgrading to a newer xcode fixes the problem
the previous try to split the boost build/upgrade
into a separate step was not enough #1821
> fix slow boost build in travis

- tests/performance/run_server_performance_test.py
There was an unnecessary signal handling in the performance test which
is now eliminated.
> Unnecessary signal handling in performance test.

- config/config.json
- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzer.py
- libcodechecker/analyze/analyzer_env.py
- libcodechecker/analyze/analyzers/analyzer_base.py
- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/analyze/analyzers/analyzer_types.py
- libcodechecker/analyze/analyzers/config_handler.py
- libcodechecker/analyze/host_check.py
- libcodechecker/analyze/pre_analysis_manager.py
- libcodechecker/analyze/statistics_collector.py
- libcodechecker/host_check.py
- libcodechecker/libhandlers/analyze.py
- libcodechecker/libhandlers/check.py
- libcodechecker/libhandlers/checkers.py
- libcodechecker/log/option_parser.py
- libcodechecker/package_context.py
- libcodechecker/server/api/report_server.py
- libcodechecker/util.py
Another step towards https://github.com/Ericsson/codechecker/issues/1760
Also fixed a bug along the way. If clang-6.0 was available in the path but not clang, and clang-6.0 was not configured in the package config, we failed on the statistics feature check (not finding the binary).
It is hard to add a test for this scenario as there are lots of dependencies on the environment.
> Constructing config handler is the analyzer classes' responsibility

- scripts/gerrit_jenkins/parse_output_parser.py
Jenkins environment import removes backslash escapes which makes the JSON file invalid if C string literals are present in the error line. To overcome this we put extra backslashes before double parentheses in the error lines.
> [Gerrit] Output parser workaround for Jenkins bug

- config/checker_severity_map.json
- config/config.json
See https://clang.llvm.org/extra/clang-tidy/checks/bugprone-parent-virtual-call.html
> Add bugprone-parent-virtual-call check for clang-tidy v7+

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/util.py
- tests/unit/test_subprocess_timeout.py
Clang-sa spawns a child process which in turn spawns another child process.
Using os.kill kills only the parent letting child clang-sa to continue.
It's not what we expect from timeout.
Using killpg kills parent, its children and their children too.
> Fix --timeout as clang-sa spawned child processes are not killed now

- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/util.py
- vendor/plist_to_html/plist_to_html/PlistToHtml.py
using "replace" to handle encoding errors is less robust
because the replacement character used in python2 and python3
are different
This could change the generated hash in case the the file encoding changes and reading the source file as utf8 fails.
> ignore encoding errors

- libcodechecker/analyze/ctu_manager.py
When running clang analysis, the __clang_analyzer__ macro
needs to be defined. This should also be true for CTU imported TUs.
> Add __clang_analayzer__ macro to CTU imported tus

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/pre_analysis_manager.py
- libcodechecker/log/log_parser.py
- libcodechecker/util.py
- tests/unit/test_log_parser.py
The BuildAction objects are immutable so they should contain all attributes in
a form so they can be passed directly to the analyzers. For example the source
file path should be kept escaped.
> Whitespace escaping in source path

- config_db_migrate/versions/3335ff7593cc_disable_review_status_change.py
In SQLite boolean values are stored as integers 0 (false) and 1 (true). Creating the following column `Column('col', Boolean(), server_default=text(u'false'))` will insert `false` value into the SQLite database by default which will cause bad behaviour. Using `sql.false()` for server default will solve this problem.
Same problem here: https://github.com/sqlalchemy/sqlalchemy/issues/2368
> Fix default value of Boolean column at migration

- libcodechecker/analyze/analyzers/analyzer_clangsa.py
> Closes #1539
Parsing notes from the plist files is supported now this conversion to events is not required anymore
> Do not convert notes to events

- libcodechecker/analyze/statistics_collector.py
CodeChecker analyze --stats-collect creates trash
.plist files in the current working directory.
This patch fixes that.
> Tash files are created in cwd by --stats-collect

- libcodechecker/analyze/analyzers/analyzer_clangsa.py
We need to enable the expand-macros feature so clang
generates macro expansion into plist files.
> Enabling expand-macros feature of clang

- libcodechecker/analyze/analyzers/ctu_triple_arch.py
CTU analyzes in two phases. The first phase where the AST dumps are created
should happen with the same C/C++ standard version which may be implicit.
Fixes #1838
> Default standard in first CTU phase.

- libcodechecker/log/log_parser.py
- tests/unit/test_log_parser.py
In this commit we follow the rule of BuildAction objects: these should contain
the final form of every used value. In this case the analyzer options should be
escaped so it will be passed correctly to the analyzer.
> Fix escaping in command line arguments

- libcodechecker/analyze/analysis_manager.py
The failure zip file names reflect the failure type.
Analyzer/checker crash or compilation errors are handled.
resolves #1829
> separate failure zip in case of crash or compile error

- vendor/plist_to_html/plist_to_html/dist/js/bugviewer.js
* Draw bubble for the second bug event too.
* On left arrow click jump to the previous bug event.
> Fix PlistToHTML arrows

- vendor/plist_to_html/plist_to_html/PlistToHtml.py
In the built CodeChecker package there is a symlink to the plist-to-html
converter vendor script. This uses a relative path to the layout.html file
which is not correct when the symlink in the path is used.
> Fix HTML converter layout file default path

- config/config.json
the checker crashes on bitcoin with clang7 and newer.
it is removed from the extreme profile until further investigation
> remove CallAndMessageUnInitRefArg from extreme profile

- libcodechecker/libhandlers/store.py
Earlier the implicit compiler information went to compiler_target.json
and compiler_includes.json. Now there is only one file:
compiler_info.json. This has to be uploaded with fail zips too.
> Upload compiler_info.json

- libcodechecker/libhandlers/store.py
Do not store analysis statistics if it doesn't contain any failed zip.
> Store statistics if it contains failed zips

- libcodechecker/libclient/client.py
During the log formatting accidentally the
password request message was formatted in a wrong way.
> Fix password request for cmd

- libcodechecker/analyze/analyzers/analyzer_clangsa.py
Reverts Ericsson/codechecker#1885
> Revert "Enabling expand-macros feature of clang"

- libcodechecker/log/log_parser.py
`next` method implemented the Iterator protocol in python2
but is now a normal method in python3.
With the alias it will work in python2 too.
https://docs.python.org/3/tutorial/classes.html?highlight=iterator#iterators
> py3 fix iterator protocol (next method change)

- libcodechecker/libhandlers/store.py
- libcodechecker/util.py
In python3 the objects returned by keys(), values(), items() are
view objects but we use and need lists here.
https://docs.python.org/3/library/stdtypes.html#dict-views
> fix dict.items referenced when not iterating py3

- libcodechecker/server/server.py
There was still a dict usage where change is needed.
In python3 the objects returned by keys(), values(), items() are
view objects but we use and need lists here.
https://docs.python.org/3/library/stdtypes.html#dict-views
> fix dict item was referenced when not iterating py3

- Makefile
- scripts/build/create_commands.py
- scripts/build_package.py
Create separate python scripts to copy CodeChecker sub-commands and create a `commands.json` file which will contain all the available sub-commands.
> Create commands.json for sub-commands

- scripts/debug_tools/renew_info_files.py
This new script can be called with a directory that contains a
`compiler_includes.json` and a `compiler_target.json` file, and will create
a `compiler_info.json` file compatible with new CodeChecker versions.
Open questions:
- Is there a need to specify includes/target file names on the command line
or is their dir sufficient? (e.g. do we want to also process debug versions
of such files that have different names?)
- Should old includes/target files be erased? (`--clean` option)
- Are old-format `compiler_info.json` files ever encountered? These
would only need some post-processing, which is easy to add.
> Tool to create new compiler info files from old ones.

- analyzer/codechecker/analyze/analysis_manager.py
We assumed that the type of the `source` attribute of a build action is a list but it was changed in #1814 pull request to string.
> Fix failed source list of analysis statistics

- webserver/server/codechecker/server/api/store_handler.py
Do not store failed source files when using CodeChecker 6.9.0 because there was an error in #1814 which splits every source file into characters.
> Do not store failed files when using 6.9.0 version

- libcodechecker/libhandlers/version.py
CodeChecker version prints analyzer and webserver versions. In this commit we handle the use case when one of them is not available, for example when creating a separate package.
> Fix CodeChecker version after split up

- web/tests/Makefile
> Closes #1978 
Use separate workspace for the sqlite and postgresql tests. It would allow to run the tests parallel.
> Allow to set workspace for web tests

- analyzer/codechecker_analyzer/cmd/analyze.py
there is no python package named codechecker anymore
analysis related packages are moved under codechecker_analyzer
> fix analyzer_statistics module import

- analyzer/tests/libtest/env.py
- docs/tests/README.md
- web/tests/Makefile
- web/tests/libtest/env.py
the previously introduced WORKSPACE env var the base directory can be
set for the tests, every temporary directory should be created
under the base workspace dir for the functional tests
> allow to set the base wp dir from env variable for tests

- .travis.yml
`llvm@7` was removed from the brew formulae so we have to upgrade     to the latest one which is `llvm@8`.
> Update travis llvm version

- tools/plist_to_html/Makefile
By default make begins by processing the first target. We included the test Makefile which contain multiple targets. So make called the first target from this Makefile. To solve this problem we put the default target to be the first target in the Makefile.
> Fix default target call

- codechecker_common/util.py
- web/tests/functional/authentication/__init__.py
- web/tests/functional/db_cleanup/test_db_cleanup.py
- web/tests/functional/instance_manager/test_instances.py
- web/tests/functional/products/test_config_db_share.py
- web/tests/functional/ssl/__init__.py
- web/tests/functional/storage_of_analysis_statistics/__init__.py
- web/tests/libtest/codechecker.py
- Use `start_server` function from `codechecker` module to start a server.
- Wait until the server process is still running on server stop.
- Remove unnecessary sleeps.
> Improve web test performance

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/unit/test_option_parser.py
When a compilation action contains -c which indicates that this is a
compilation, and also contains some preprocessor related flags like -MP
then the action was considered as a preprocessor action. So this action
was skipped when running the checkers. This commit fixes this issue.
> Compile action contains bot compiler and preprocessor flags

- analyzer/codechecker_analyzer/buildlog/log_parser.py
returning None caused problems later when trying to split
up the output.
> return an empty string at getting compiler includes

- .travis.yml
- Makefile
- analyzer/Makefile
- analyzer/tests/Makefile
- docs/tests/README.md
- tools/plist_to_html/Makefile
- tools/plist_to_html/tests/Makefile
- web/Makefile
- web/server/tests/Makefile
- web/tests/Makefile
There are two targets for each tests the default target assumes
an anlready sourced virtualenv with all the dependecies.
The target names ending *in_env will automatically setup
and source a virtualenv to run the tests.
In travis ci nose needs to be installed explicitly because
pip detects an already installed version under numpy but that binary
is not visible in the PATH.
> cleanup make targets with/without virtualenv

- analyzer/codechecker_analyzer/buildlog/log_parser.py
The target information should be processed and replaced before it
is collected as a simple compiler flag.
> Processing target architecture first in log parser

- tools/plist_to_html/Makefile
- tools/tu_collector/Makefile
setup.py requires setuptools which is available only in a virtualenv
or needs to be installed separately.
Getting the name and the version command did run always for every target
in the Makefile.
> call setup.py only in the target

- analyzer/codechecker_analyzer/buildlog/build_action.py
- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- analyzer/tests/functional/analyze/test_analyze.py
- analyzer/tests/unit/test_buildcmd_escaping.py
- analyzer/tests/unit/test_log_parser.py
- docs/analyzer/user_guide.md
CTU analysis does not tolerate if a source file is
included multiple times in the compilation database.
Because in this case it is ambigous, which
compiled file shall be inlined.
> Introducing --compile-uniqueing parameter

- analyzer/tools/build-logger/src/ldlogger-util.c
- analyzer/tools/build-logger/src/ldlogger-util.h
- analyzer/tools/build-logger/test/test_logger.sh
The quote marks need an extra escape character because the JSON strings
are also surrounded by quotes.
> Yet another logger fix

- docs/web/authentication.md
the passwords json file was renamed previously but the
documentation was not updated
> rename passwords json file in the doc

- web/server/codechecker_server/routing.py
with this change a product named docs can not be created
the url will forward to the documentation
> add docs as a special route

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/tests/functional/analyze/test_analyze.py
- analyzer/tests/unit/test_buildcmd_escaping.py
- analyzer/tests/unit/test_log_parser.py
- docs/analyzer/user_guide.md
- web/client/codechecker_client/cmd/store.py
This option was removed by 5519409 under the assumption that it is not
used anywhere. The truth is that this flag is very useful for debugging
purposes and some debug tools in the /scripts directory do use it.
This commit re-introduces the --compiler-info-file option on top of the
refactored log parser.
> Resurrect --compiler-info-file analyze flag.

- analyzer/codechecker_analyzer/analyzers/config_handler.py
If there was a checker or checker group
name conflict the listing of the profile failed.
With this change only a warning is given.
This is a partial solution for #2056
> fix profile listing on name conflict

- analyzer/codechecker_analyzer/cmd/checkers.py
Building tools on top of CodeChecker is easier
if proper error codes are returned.
> return error in case of wrong checker profile name

- analyzer/codechecker_analyzer/buildlog/log_parser.py
If ccache is the compiler in a build action then the architecture
target can't be queried.
> A compmiler doesn't provide an architecture target.

- analyzer/tests/unit/test_option_parser.py
Adding a test case for a build action which contains a dependency
file after -MF flag and it is a compilation action too.
Fixes #2050
> Test for dependency file

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/unit/test_option_parser.py
The idea is that in skip-list we are enumerating the flags which
are consumed by GCC but not by Clang. Theoretically there shouldn't
be any skipped flag if the original command used Clang since these
are known only by GCC.
However, in case of Clang we'd like to skip flags starting with
-Xclang which is also listed in our skip-list. -Xclang -emit-llvm is
such a flag that makes Clang emit an LLVM IR instead of the PList file.
> The skipped flags are skipped in case of Clang too

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/unit/test_option_parser.py
Precompilation options are needed for clang too.
Example from the Chromium project:
```
...
"command": "bin/clang++ -MMD -MF new_tab_page_navigation_throttle.o.d -DUSE_UDEV -DUSE_AURA=1
...
```
> [clang] Skip sources argument when parsing the precompilation options

- tools/plist_to_html/Makefile
- tools/tu_collector/Makefile
Assignment inside a target will be executed as a shell command,     which gives an error. To solve this problem, we need to use the `eval` function.
For more information see: https://stackoverflow.com/questions/6519234/cant-assign-variable-inside-recipe
> [fix][makefile] Fix pip upload targets at tools

- web/requirements.txt
- web/requirements_py/db_pg8000/requirements.txt
- web/requirements_py/db_psycopg2/requirements.txt
- web/requirements_py/dev/requirements.txt
- web/requirements_py/osx/requirements.txt
SQLAlchemy through 1.2.17 and 1.3.x through 1.3.0b2 allows SQL Injection
via the order_by parameter.
See: https://nvd.nist.gov/vuln/detail/CVE-2019-7164
SQLAlchemy 1.2.17 has SQL Injection when the group_by parameter can be
controlled.
See: https://nvd.nist.gov/vuln/detail/CVE-2019-7548
> security update for SQLAlchemy

- analyzer/codechecker_analyzer/cmd/parse.py
- codechecker_common/plist_parser.py
- docs/analyzer/user_guide.md
- tools/plist_to_html/plist_to_html/PlistToHtml.py
This --trim_path_prefix option allows to trim path of reported files as
it acts in store command.
Example:
CodeChecker parse --trim-path-prefix=/path -e html -o ./html_report ./results
> Add --trim_path_prefix option for parser command

- analyzer/codechecker_analyzer/cmd/parse.py
This fixes `--ignore skipfile` option for parser command with HTML output as it was already ok with stdout output.
Function `skip_html_report_data_handler` has been moved after analysis of `skipfile` option and then `skip_html_report_data_handler` can also apply filtering according to `skipfile`.
> Fix skipfile for parser command with html output (issue #2077)

- tools/tu_collector/tests/project/compile_command.json
- tools/tu_collector/tests/tu_collector_test.py
The current tests depends on a built CodeChecker package.
The tu_collector tests should be independent from that.
The CodeChecker log command is removed and the compile command
json is added to the repository.
resolves #2093
> package independent tu_collector tests

- analyzer/Makefile
> Closes #2100 
The ldlogger symlink under the built package should be relative the path is set to an absolute path during package build time.
> [fix] Fix ldlogger symlink

- analyzer/codechecker_analyzer/buildlog/log_parser.py
Since there is a common skip list and white list for GCC and Clang
commands, there is no need for handling Clang commands separately.
The idea is to interpret skip list as "flags which are not needed
for analysis".
Fixes #2103
Fixes #2097
> No need for handling Clang commands separately

- scripts/debug_tools/failure_lib.py
mkdir fails if the parent dir is non-existent.
> mkdir -> makedirs

- analyzer/Makefile
Older version of `ln` command doesn't have `-r`, `--relative` option. We need to find another solution to solve this problem.
Reverts Ericsson/codechecker#2108
> Revert "[fix] Fix ldlogger symlink"

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/unit/test_option_parser.py
Having spaces in between "-isystem /bla/bla/path" in compiler_info.json resulted in a wrong passing of arguments.
The fix is to split it into "-isystem", "/bla/bla/path" in the list of arguments.
> Fix compiler_info.json parsing

- analyzer/codechecker_analyzer/cmd/analyzer_version.py
- analyzer/codechecker_analyzer/cmd/analyzers.py
- analyzer/codechecker_analyzer/cmd/checkers.py
- codechecker_common/logger.py
- web/client/codechecker_client/cmd_line_client.py
- web/client/codechecker_client/product_client.py
- web/client/codechecker_client/source_component_client.py
- web/client/codechecker_client/token_client.py
- web/codechecker_web/cmd/web_version.py
> Closes #1453 
Redirect logger's output to the `stderr` if the given output format  is not `table`, so the output of the commands will not be an invalid `json`, `csv`, etc. because of the log messages.
> [cmd] Redirect output to stderr if the output format is not table

- analyzer/codechecker_analyzer/analyzers/analyzer_types.py
- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangsa/config_handler.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- docs/analyzer/checker_and_analyzer_configuration.md
- docs/analyzer/user_guide.md
> Closes #2087
Create new options for the analyzer and check commands which allow us to enable the Z3 solver backend for Clang Static Analyzer if it's supports Z3 analyzer constraints option.
> [analyzer] Z3 constraint solver support

- web/server/www/scripts/codecheckerviewer/util.js
> This problem is related to #2057
Is it possible for example when the server is not available that the `handleThriftException` gets an object rather than a string as an exception. This commit fixes this problem by checking the parameter type before calling the `indexOf` function on it.
> Fix thrift exception handling

- docs/web/user_guide.md
- web/client/codechecker_client/cmd_line_client.py
* Redirect `CodeChecker cmd sum` command output to the stderr if the given output format is not table so the output of the commands will not be an invalid json, csv, etc. because of the log messages.
* Extend the web userguide with this feature and add an example how to use this.
> Redirect the cmd sum command output to the stderr

- web/client/codechecker_client/client.py
We call the `setup_product_client` function after the `setup_auth_client` function call which will return a session token. With this commit now we will forward this session token to the `setup_auth_client` function so we do not create an extra authentication API request to the server.
> [cli] Use already generated session token in CLI

- tools/tu_collector/tests/project/compile_command.json
- tools/tu_collector/tests/project/main.c
- tools/tu_collector/tu_collector/tu_collector.py
The compiler can emit the files of a translation unit with the help
of the preprocessor. The output of the compiler call thus can be a
file list: gcc -E -M -MT __dummy main.c
However, if there is a compiler warning at the beginning of this
command's output then TU collector considered the words of the
warning message as file names.
> TU collector crash when preprocess warning

- web/client/codechecker_client/cmd_line_client.py
- web/client/codechecker_client/product_client.py
- web/client/codechecker_client/source_component_client.py
- web/client/codechecker_client/token_client.py
- web/tests/functional/cmdline/test_cmdline.py
This commit pass the output stream to the `setup_logger` function so errors will be written to the correct output stream.
> [fix] Fix redirect output to stderr

- .pylintrc
Add `web`, `web/client` and `web/server` directories to the `sys.path` in the `.pylintrc` file.
> [pylint] Add more path to sys.path in .pylintrc

- analyzer/codechecker_analyzer/cmd/check.py
- docs/analyzer/user_guide.md
- web/tests/functional/diff/__init__.py
- web/tests/libtest/codechecker.py
> Closes #2125
`CodeChecker check` command has a `--force` argument which is outdated. The check command does not store results, so the force flag is not needed here. Mark this option as a deprecated argument and remove it in a future version of CodeChecker.
> [cli] Mark --force option of check command as deprecated argument

- analyzer/tools/build-logger/src/ldlogger-tool-gcc.c
- analyzer/tools/build-logger/test/test_logger.sh
The build environment can be set so "g++" is a symlink to
/usr/bin/ccache. CCache can detect whether it was run through this
symlink or it was run directly. In the former case CCache forwards
the command line arguments to the original g++ compiler. This way
we can query the implicit include paths from the compiler later in
CodeChecker. If we resolve the symlink, then the implicit include
path getter command line arguments go to CCache binary. The solution
is not to resolve the symlinks in the logger.
> Don't follow symlink in the logger

- web/server/codechecker_server/api/config_handler.py
- web/server/codechecker_server/api/product_server.py
Unfortunately we forgot to close `run_db_session` database session in the `__get_product` function which caused idle database transactions. To solve this problem now we are using `DBSession` object to create
new sessions which will be automatically closed.
> [server] Use DBSession object to create new session

- web/server/codechecker_server/server.py
- web/server/www/scripts/codecheckerviewer/util.js
- web/tests/functional/authentication/test_authentication.py
- web/tests/functional/ssl/test_ssl.py
Send back a valid Thrift error response message to the client if the user is unauthorized. This way on the Javascript side have to check and handle this error message differently on API call failure:
- On async call the `responseText` field of the xhr object will contain the error message.
- On sync call a `TApplicationException` will be thrown.
> [server] Send back a valid Thrift error response

- web/server/codechecker_server/api/report_server.py
- web/server/codechecker_server/server.py
Getting the context through webserver_context resulted
loading all of the server config files (parsing json)
in each massStoreRun api call, this extra work should not
be done in the request handling methods.
Loading the config files should be done only once
at the server start or when the reload is triggered
by an external signal.
> optimize context creation in massStoreRun api call

- web/tests/functional/source_change/test_source_change.py
Storage should be successful if a non report related file changed.
Checking the modification time stamps should be done only for
the source files mentioned in the report plist files.
Modifying any non report related file should not prevent the storage
of the reports.
This is a test for a previous fix in: 5cb63595
resolves #2152
depends on #2156
> New test for storage with file modification

- web/tests/functional/statistics/test_statistics.py
The test project should be cleaned before logging the compiler commands.
With the changed makefile for incremental build in the test project
not all the build commands are triggered if there was a previous build.
The statistics tests need the statistical_checkers.cpp file to be
logged and analyzed.
> fix statistics tests

- web/client/codechecker_client/cmd_line_client.py
In an earlier commit (7d56fab) the Checker statistics page was refactored in the UI. This commit refactores the Checker statistics results in the CLI too by removing the `Resolved` column and to move the `All reports` column to the end of the table.
> [cli] Refactoring checker statistics results

- docs/web/server_config.md
- web/server/codechecker_server/server.py
- web/server/codechecker_server/session_manager.py
- web/server/config/server_config.json
Now we are able to configure the number of worker processes from the server config file which will control how many processes will be started on the server to process API requests.
> [server] Configure worker processes from config file

- .travis.yml
Previously if a script failed other scripts are still being run. Now if a script gives a command error than travis will immediately stop the build process.
> [travis] Stop travis job after script command error

- web/client/codechecker_client/cmd_line_client.py
- web/tests/functional/diff_local_remote/test_diff_local_remote.py
Print a similar summary at the end of `CodeChecker cmd diff` command as at the `CodeChecker parse` command.
> [client] Print summary at cmd diff

- docs/web/permissions.md
- web/server/codechecker_server/permissions.py
- web/tests/Makefile
- web/tests/functional/comment/__init__.py
- web/tests/functional/component/__init__.py
- web/tests/functional/products/__init__.py
- web/tests/functional/products/test_config_db_share.py
- web/tests/functional/server_configuration/__init__.py
- web/tests/libtest/codechecker.py
- web/tests/libtest/env.py
> Closes #2083 
Previously some permissions were default granted if the server was started with authentication, which means that initially, every user has the permission. With these changes all permissions are `default not granted`, which means that only users whom are explicitly given the permission have it.
By default, the `start_or_get_server` function in the test cases created a server which required authentication. With these changes  we will create 2 servers - with authentication and without it. The `add_test_package_product` function will also give permissions for the current product to some users.
> [server] Fix default permissions

- web/client/codechecker_client/client.py
- web/client/codechecker_client/cmd/store.py
There were many extra authentication calls before the actual store
or other report related api calls just to check if everything is right.
With these changes just the essential authentication api calls are done.
If the user does not have store or access rights the actual store
or query api calls will fail, no extra check is done before.
The local authentication related config files (password, session token)
were read up multiple times during the authentication process
before connecting the server. This was cleaned up in this changes.
Every authentication related configuration file should be checked
and read up only once.
> authentication api call simplification

- web/server/www/scripts/codecheckerviewer/filter/ReportHashFilter.js
Report hash filter query parameter is always set in the URL even if the value is an empty string (`http://localhost:8001/Default&report-hash=`).
With this commit we solve this problem and we set this parameter only if the report hash filter is set.
> [ui] Fix report hash filter url state

- web/requirements_py/db_psycopg2/requirements.txt
- web/requirements_py/dev/requirements.txt
Update `psycopg2` and use `psycopg2-binary` as  package name because `psycopg2` starting from release `2.8`, the binary packages will only be released under psycopg2-binary.
> [dep] Update psycopg2

- .pylintrc
- Makefile
- analyzer/tests/Makefile
- web/tests/Makefile
Use the pylint configuration file (`.pylintrc`) to disable all checkers and enable only specific checkers instead of command line options.
> [pylint] Enable checkers in .pylintrc file

- web/api/v6/report_server.thrift
- web/codechecker_web/shared/version.py
- web/server/codechecker_server/api/report_server.py
- web/server/www/scripts/codecheckerviewer/ListOfRuns.js
- web/server/www/scripts/codecheckerviewer/RunHistory.js
- web/server/www/scripts/codecheckerviewer/util.js
- web/server/www/scripts/version.js
Use `DataGrid` and `Store` at Run history page to show the items. This will allow us to load run history on page scroll.
Create a new API function called `getRunHistoryCount` to get the number of run history based on a filter set. This is needed by the `DataGrid` to support page scroll.
> [server] Run history limitation

- web/server/codechecker_server/api/report_server.py
- introduce checking the query limit value for getRunHistory api call
- change the log level to warning if a client requests more than
than the allowed query limit size
> improve query limit checking

- Doxyfile.in
`docs/checker_docs` is moved under `docs/web/checker_docs` but
at the INPUT tag values we already listed the parent directory
(`docs`) of this directory which is enough, so we remove this
directory at all.
> [doc] Fix missing input tag at Doxygen config

- analyzer/tools/build-logger/src/ldlogger-tool-gcc.c
- analyzer/tools/build-logger/src/ldlogger-tool-javac.c
- analyzer/tools/build-logger/src/ldlogger-tool.c
- analyzer/tools/build-logger/src/ldlogger-tool.h
- analyzer/tools/build-logger/src/ldlogger-util.c
- analyzer/tools/build-logger/test/test_logger.sh
The compiler name was indicated as toolName several places in the
logger. This was just the name of the binary without an absolute
path at the beginning. This toolName was also stored in the
LoggerAction objects, but it was not used anywhere, so it has been
removed.
The loggerGccParserCollectActions() and
loggerJavacParserCollectActions() functions had 3 parameters: prog_,
toolName_ and argv_. The first one is the program name caught by the
exec* commands, i.e. the compiler, usually with an absolute path that
may contain symlinks in it. The second one is the longest postfix of
prog_ which doesn't contain a "/" character. The third one is the
original argv_ array which also contains the compiler name at the 0th
position in its original form as it was called.
In this commit I removed the …
> Logger: compiler on absolute path + refactoring

- web/server/www/scripts/codecheckerviewer/ListOfRuns.js
- web/server/www/scripts/codecheckerviewer/filter/FilterTooltip.js
- web/server/www/scripts/productlist/ListOfProducts.js
In case a text box requires a regex in the search fields, we sould put
an implicit * joker character at the beginning. This is a usability
enhancment so the user doesn't have to put this character there
explicitly.
Fixes #2134
> Implicit joker at the beginning of text field

- analyzer/tests/unit/test_log_parser.py
> Closes #2069 
Remove the generated `compiler_info.json` file at the end of `test_log_parse.py` analyzer unit test.
> [test] Remove compiler_info.json file at the end of analyzer unit test

- web/server/codechecker_server/api/report_server.py
- web/server/codechecker_server/api/store_handler.py
the content of the received source files at the server were read even if:
- the content was not used to generate the content hash
- the content was not stored
> [server] read file content only if really needed

- analyzer/requirements_py/dev/requirements.txt
- analyzer/requirements_py/osx/requirements.txt
- codechecker_common/plist_parser.py
- web/requirements.txt
- web/requirements_py/db_pg8000/requirements.txt
- web/requirements_py/db_psycopg2/requirements.txt
- web/requirements_py/dev/requirements.txt
- web/requirements_py/osx/requirements.txt
Use `lxml` library to parse plist files.
The benefit of this library that this is faster than other libraries so it will improve the performance of the plist parsing.
**Measurement:**
Original plist parser:
```
----=================----
Total number of reports: 24216
----=================----
real	2m8,736s
user	2m5,753s
sys	0m2,682s
```
Plist parser with lxml:
```----=================----
Total number of reports: 24216
----=================----
real	1m23,167s
user	1m20,807s
sys	0m2,292s
```
> [plist] Use lxml library to parse plist files

- web/server/codechecker_server/server.py
If we print something after the `ThreadPool` is terminated first the server is being stopped, the terminal will be active and the message will be printed to the active terminal. To reproduce this problem, start a server and hit Ctrl+C.
With these changes we do not print a message after the HTTP server is terminated.
E.g.:
```sh
[INFO 2019-06-26 13:42] - Server waiting for client requests on [localhost:8001]
^C[INFO 2019-06-26 13:42] - Received shutdown request.
[INFO 2019-06-26 13:42] - Shutting down...
username@hostname ~/codechecker $ [INFO 2019-06-26 13:42] - WEB server is shut down.
```
> [server] Print an info message when the server is shutting down

- web/api/v6/report_server.thrift
- web/server/codechecker_server/api/report_server.py
- web/server/www/scripts/codecheckerviewer/ListOfRuns.js
- web/server/www/scripts/codecheckerviewer/RunHistory.js
At the `getRunData` and `getRunHistory` functions we returned the
whole analysis statistics but we used only the number of failed and
successfully analyzed files fields. To reduce the response message
size of these API functions we created a separate API function called
`getAnalysisStatistics` to get analysis stastistics for a run which
will be called when the user clicks on the Show link on the Run List
and Run History pages.
> [server] Create separate API function to get analysis statistics

- web/client/codechecker_client/cmd/cmd.py
The `CodeChecker cmd sum` subcommand should also use the default filter
values like `CodeChecker cmd results`.
> Default filter values under CodeChecker cmd sum

- web/api/v6/report_server.thrift
- web/codechecker_web/shared/version.py
- web/server/codechecker_server/api/report_server.py
- web/server/www/scripts/codecheckerviewer/ListOfRuns.js
- web/server/www/scripts/codecheckerviewer/RunHistory.js
- web/server/www/scripts/version.js
- web/tests/functional/update/test_update_mode.py
This commit introduces a new API function to get check command for a run or a run history. This will reduce the HTTP response message size because we will not send back the check command to the client when getting run data or run history data.
In the web client code we will use this function to get the check command when the user clicks on the Show link on the run or run history pages.
> [server] New API function for get check command

- web/server/www/scripts/codecheckerviewer/ListOfBugs.js
- web/server/www/scripts/codecheckerviewer/ListOfRuns.js
- web/server/www/scripts/codecheckerviewer/RunHistory.js
`rowsPerPage` attribute of the dojo `DataGrid` controlls how many
pages will be rendered. It is adviced to render only a small subset
(perhaps 25-50) records of the entire dataset. In this commit we will
set this value to `50` so it will increase the performance of the UI.
> [server] Set rowsPerPage attribute to a lower value

- Makefile
- analyzer/Makefile
- docs/README.md
> Closes #2101
With the current setup we only build the ldlogger.so for that architecture where the package was built, but during runtime in a different environment it is possible that the 32bit shared objects are needed too.
With these changes `make package` by default will build ldlogger shared objects for `32bit` and `64bit` too. We also introduced a new environment variable `BUILD_LOGGER_64_BIT_ONLY` what you can
set to `YES` before the package build to build and package `64 bit only` shared objects and ldlogger binary.
> [makefile] Build logger libraries for multiple targets

- web/server/www/scripts/codecheckerviewer/BugViewer.js
Do not throw an exception when highlighting the bug step at the
Bug Tree view when it is failed to get 'Returning from' item from
the stack just write a warning message to the console.
> [server] Do not throw an exception when highlighting the bug step

- analyzer/tests/functional/skip/__init__.py
- analyzer/tests/functional/skip/test_files/Makefile
- analyzer/tests/functional/skip/test_files/file_to_be_skipped.cpp
- analyzer/tests/functional/skip/test_files/skip.h
- analyzer/tests/functional/skip/test_files/skip_header.cpp
- analyzer/tests/functional/skip/test_files/skipfile
- analyzer/tests/functional/skip/test_skip.py
- codechecker_common/plist_parser.py
- web/client/codechecker_client/cmd/store.py
- web/client/codechecker_client/cmd_line_client.py
- web/server/codechecker_server/api/report_server.py
- web/server/tests/unit/test_plist_parser.py
- web/server/tests/unit/test_report_path_hash.py
- web/server/tests/unit/test_store_handler.py
The intoduced new plist xml parsing method with lxml
was not introduced for the use cases where the a skip file
was used. In case of a skip file the report plist files
can be rewritten (the reports based on the skip file content)
are removed.
Previous tests did not fail because a second skip is done
at the server side during storage and the server skip tests
worked on the stored reports.
> fix plist parsing for skip files

- docs/web/user_guide.md
- web/client/codechecker_client/cmd/cmd.py
- web/client/codechecker_client/cmd_line_client.py
- web/tests/functional/cmdline/test_cmdline.py
> Part of #2113
Filtering and getting the results for run names with colon punctuation mark does not work properly. If there is a timestamp in the run name we want to filter "myrun-12:23:12" the punctuation mark will be used as a delimiter of multiple run names even if this is not the case.
For this reason we set the `nargs` option to `+` for the run names option of the `CodeChecker cmd results` subcommand so we will be able to get results for run names which contains colon punctuation marks.
E.g: `CodeChecker cmd results myrun-12:23:12 myrun-22:00:10`
> [cli] Gettings results for runs which contain colons

- codechecker_common/plist_parser.py
In case of fallback to the builtin plistlib.
In python2 can not handle file objects opened
with io which return the content of a file in unicode on read().
To fix this we read and encode the file content before parsing
by the plistlib.
> encode file content for plistlib

- web/server/www/userguide/userguide.md
> Closes #2096 
In the web user guide there were some broken links to the other user
guides after the repository and documentation split. With this commit
we fix these broken links.
> [doc] Fix documentation links in the web userguide

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangsa/config_handler.py
- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_autodetection.py
It is possible that environment variables (LD_LIBRARY_PATH) required
for clang are modified/extended in the environment built from the
context. If not the same environment is used running the
other tools to detect additional analyzer features might fail.
> use the environment from context for ctu detection

- analyzer/codechecker_analyzer/analyzer.py
- analyzer/codechecker_analyzer/checkers.py
- analyzer/tests/functional/analyze/test_analyze.py
- analyzer/tests/unit/test_checkers.py
It is possible that there is typo in the checker name
or the checker was removed/renamed in a newer clang version.
The analysis starts but the user will not get any results
because there is no checker with that name.
To prevent this exit before the analysis if a checker name is missing.
Every checker argument is checked because it is possible
that multiple checkers are missing or there are multiple typos.
> exit on missing checker or profile names

- analyzer/codechecker_analyzer/analyzer.py
- analyzer/tests/functional/analyze/test_analyze.py
Do not stop the analysis in case of a typo in the checker names.
Checker severity levels and profiles should be handled
based on the clang versions because of checker renaming or removal.
> give warning only for now if a checker is missing

- web/server/codechecker_server/api/report_server.py
Previously in the `_setReviewStatus` function we checked the required permissions. The problem was here that this function was called multiple times in the `__store_reports` function which was called by the `massStoreRun` function but this was unnecessary because we already checked the required permissions in the `massStoreRun` function.
The `_setReviewStatus` function is also called in the `changeReviewStatus` so now we check the required permissions in the begining of this function too.
> [server] Refactoring review status change permission check

- tools/tu_collector/tests/project/compile_command.json
- tools/tu_collector/tu_collector/tu_collector.py
This flag can be given a .specs file which contains the config options of
cc1, cc1plus, as, ld, etc. Sometimes this file is just a temporary during
the compilation. However, if the file doesn't exist, this flag fails the
compilation. Since this flag is not necessary for dependency generation,
we can skip it.
> Skipping -specs flag in TU collector

- codechecker_common/plist_parser.py
- codechecker_common/source_code_comment_handler.py
- web/client/codechecker_client/cmd/store.py
- web/client/codechecker_client/cmd_line_client.py
- web/server/codechecker_server/api/report_server.py
- web/server/tests/unit/test_source_code_comment.py
`SourceCodeCommentHandler` object was created multiple times when iterating over reports because we had to pass the source file path to the constructor. With this patch we refactored the `SourceCodeCommentHandler` class to pass the source file name for each function which are require it so there is no need to create new object so many times.
> [web] Refactoring source code comment handler

- analyzer/codechecker_analyzer/analyzers/analyzer_types.py
- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_autodetection.py
- analyzer/codechecker_analyzer/host_check.py
- analyzer/tests/functional/ctu_failure/test_ctu_failure.py
- analyzer/tests/functional/host_check/test_host_check.py
The ctu-display-progress flag did change in clang8.
The argument is turned on in case of ctu failure to
collect the source files used by ctu for analysis.
Not just the flag but the analyzer output format did
changed in clang8 too.
> ctu display progress flag changed in clang8

- analyzer/codechecker_analyzer/analysis_manager.py
- analyzer/codechecker_analyzer/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_triple_arch.py
- analyzer/codechecker_analyzer/analyzers/clangsa/statistics_collector.py
- analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
- analyzer/codechecker_analyzer/analyzers/flag.py
- analyzer/codechecker_analyzer/buildlog/build_action.py
- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/functional/analyze/test_analyze.py
- analyzer/tests/unit/test_flag.py
- analyzer/tests/unit/test_option_parser.py
- scripts/debug_tools/renew_info_files.py
If the same compiler was used multiple times in a
compile command json but compiled multiple source
files for differerent languages (C and C++) the implicit
compiler information was collected only when first detected
(only for C).
With this change when a compiler is first found the include
paths, default build targets and compiler standards
will be detected for both languages. So the information can
be used when the same compiler is compiling for a
different language.
Additional changes were done to set the include paths,
build targets and compiler standard at multiple analysis
stages like, statistis collection, ctu pre analysis and
for setting the clang tidy arguments.
New PR replacing #1908
> Collect compiler information for multiple languages

- analyzer/codechecker_analyzer/analyzers/analyzer_types.py
Z3 refutation availability is checked by reading the help page of
Clang analzer options. However, it is possible that the analyzer
option exists, but Clang itself is not compiled with Z3. So we
consider Clang Z3 refutation capable if it was also compiled with
Z3.
Fixes #2229
> Fix Z3 refutation detection

- analyzer/codechecker_analyzer/checkers.py
- analyzer/tests/unit/test_checkers.py
In case an enabled/disabled checker name contains a regex character,
CodeChecker threw an exception. For example "-d Wc++11-extensions"
where "+" should be escaped.
> Exception on regex characters in checker name

- scripts/test/check_clang.py
The Clang version matching regex didn't handle the case when Clang
version is a two digin number (Clang 10).
> Fix Clang version regex in tests

- web/server/codechecker_server/session_manager.py
We are using `worker_processes` config key name in the template
`server_config.json` file and in the documentations but we have
tried to get the value of this key with the `worker_process` key
name. This commit fixes this problem.
> [server] Fix reading worker_processes config value

- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_autodetection.py
In ctu_autodetection.py file, the LOG.debug() was called as LOG.DEBUG() and caused an error in cli.
> Fix LOG.debug

- codechecker_common/report.py
all the whitespaces are removed not just whitespaces
from the beginning of the source lines
> fix context free report hash generation doc

- analyzer/codechecker_analyzer/arg.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- codechecker_common/util.py
- web/client/codechecker_client/cmd/cmd.py
RawDescriptionDefaultHelpFormatter was copied to the
analyzer and web parts.
Additionally a new arg module was created for the analyzer part to have
argument parsing related classes and function there,
OrderedCheckersAction was moved there too.
> remove argument handling class from common module

- tools/tu_collector/tests/tu_collector_test.py
tu_collector is tested in the codechecker package
through the failure zip tests.
Running the tests independently from the codechecker failed
previously because the test project was not found.
With this change the test project is searched relative to the
test file and the tests can run independently.
> tu_collector tests can be run independently

- analyzer/codechecker_analyzer/analysis_manager.py
- analyzer/tests/unit/test_subprocess_timeout.py
- codechecker_common/util.py
- web/server/codechecker_server/cmd/server.py
Process timeout handling is only done in the analyzer part.
Related functions and tests are moved to the analyzer package.
> move proc timeout functions and tests to analyzer

- .travis.yml
- Makefile
- web/tests/Makefile
Additional tests are introduced and they do not fit
into the time limit for one job, splitting them
to multiple jobs help.
Each supported database type is tested in separate jobs.
> enable build matrix for travis

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
- analyzer/codechecker_analyzer/env.py
- codechecker_common/util.py
this function is only used in the analyzer package no need for it
to be in the codechecker_common.util
> move get_binary_in_path to analyzer module

- web/tests/Makefile
In the `PG8000_TEST_CMD` `PSYCOPG2` variable was used instead of `PG8000` to set the CodeChecker database driver. This commit fixes this problem.
> [makefile] Fix pg8000 test command

- web/server/www/scripts/codecheckerviewer/BugViewer.js
- web/server/www/scripts/codecheckerviewer/HtmlTree.js
- web/server/www/style/codecheckerviewer.css
> Closes #2269
- Indent bug tree items after each function call items in the bug tree.
- Reduce the indentation size for bug tree items.
Screenshot:
> [server] Indent item in bug tree view

- web/server/www/scripts/codecheckerviewer/CommentView.js
> Closes #2264
When we opened a bug which had a comment and we clicked on the edit button, changed the comment message and pressed the `Save` button nothing happened. The problem was that we tried to call the `replace` function on the dojo `ContentPane` object not on the content itself (See #2262). With this commit we fix this problem.
> [server] Fix comment update

- web/server/www/scripts/login/login.js
In Firefox the login form autocompletion didn't work. The problem was that the `autocomplete` attribute of the `username` input field was set to `off`. In this commit we set it to `on`.
We are also using the `get` function on the input fields to get the values because the value field wasn't set properly in Firefox.
> [server] Fix login form autocompletion

- analyzer/tests/functional/analyze_and_parse/test_files/multi_error.cpp
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error.en1.output
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error.en2.output
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error.output
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error.steps.output
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error_suppress.cpp
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error_suppress.output
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error_suppress_cstyle.cpp
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error_suppress_cstyle.output
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error_suppress_typo.cpp
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error_suppress_typo.output
There is a bug in clang9 where the core.StackAddressEscape
checker reports the results as core.StackAddrEscapeBase
to be able to run the tests with newer clang versions
the StackAddressEscape checker was replaced by the
DivideZero checker in the analyzer tests.
> replace StackAddressEscape checker in analyzer tests

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangsa/clang_options.py
- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_autodetection.py
- analyzer/codechecker_analyzer/analyzers/clangsa/version.py
- analyzer/tests/unit/test_clang_version_parsing.py
Option names and behaviour can change between clang versions
with the new changes listing of the checkers can be
done based on clang versions
clang9 introduced a change in the listing of the
checker options, alpha and debug checkers require
additional options to list them.
> Introduce clang version dependent options

- Makefile
- scripts/build/wrap_binary_in_venv.py
Standalone package implicitly uses the virtualenv of the venv target.
The wrapper uses exec to allow signals to reach the original CodeChecker
binary.
> Add standalone package target

- web/api/v6/report_server.thrift
- web/client/codechecker_client/cmd_line_client.py
- web/client/codechecker_client/thrift_helper.py
- web/codechecker_web/shared/version.py
- web/server/codechecker_server/api/report_server.py
- web/server/www/scripts/version.js
- web/tests/functional/diff_local_remote/__init__.py
- web/tests/functional/diff_remote/test_diff_remote.py
Let's suppose that a report can be found in the database in a run with
detection status of `Resolved` and this report reappeared again in the
report directory. If we do comparison between this report directory
and the remote run the newly introduced report will not be shown as
new report because it is already can be found in the database.
This commit will solve this problem by filtering out reports which
have detection status of `Resolved`, `Off` or `Unavailable` when
getting diff report hashes for `NEW` and `UNRESOLVED` diff types.
> [fix] Fix getDiffResultsHash API function

- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error_skipped.output
- analyzer/tests/functional/skip/test_skip.py
If the compile command json is empty CodeChecker
returned with 1 which indicates and error which is might
not the case.
The compiler command json can be empty for several reasons:
- logging the compile commands failed for some reason
- no compilation actions were called by the buid system (noting changed)
> return 0 in case no analysis is needed

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_triple_arch.py
- analyzer/codechecker_analyzer/analyzers/clangsa/statistics_collector.py
- analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
- analyzer/codechecker_analyzer/env.py
- docs/README.md
adding the the resource dir manually might mess up the
include path order, let clang manage it, the builtin
include files should be at the righ place relative
to the clang binaries.
See:
https://clang.llvm.org/docs/LibTooling.html#libtooling-builtin-includes
> clang searches for builtin includes relative to the binary

- analyzer/tools/build-logger/Makefile.manual
- analyzer/tools/build-logger/src/ldlogger-hooks.c
- analyzer/tools/build-logger/src/ldlogger-tool-gcc.c
The logger contained a crash based on a type conversion bug.
> Fix ld_logger crash

- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_triple_arch.py
- analyzer/tests/unit/test_triple_arch.py
The output of "clang -### ..." command can't always be split with
shlex.split() so we now use the simple split().
The output of "clang -### ..." command may contain the invocation of
the linker if the original build command didn't have "-c" flag. This
last line doesn't contain "-triple" flag but the previous one does.
So now we try to find "-triple" in the whole output instead of using
only its last line.
> Crash in splitting output of "clang -### ..."

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_triple_arch.py
- analyzer/codechecker_analyzer/analyzers/clangsa/statistics_collector.py
- analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
- analyzer/codechecker_analyzer/analyzers/flag.py
- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- analyzer/tests/functional/analyze/test_analyze.py
- analyzer/tests/unit/test_option_parser.py
- docs/analyzer/user_guide.md
There are some implicit include directories which are omitted
explicitly by CodeChecker. See the details in
/docs/analyzer/gcc_incompatibilities.md.
In this commit the user can keep these directories by providing an
extra flag to CodeChecker [analyze|check] commands.
> Keep GCC include-fixed dirs in include paths

- web/server/www/scripts/codecheckerviewer/SourceComponentManager.js
While the `cmd` help contained that for allowing or denying entire directories a trailing `/*` must be present, this was missing from the web placeholder text.
> Make placeholder help for source components more descriptive

- analyzer/tools/build-logger/src/ldlogger-tool.c
- analyzer/tools/build-logger/test/test_logger.sh
- docs/analyzer/user_guide.md
In case a compiler in CC_LOGGER_?_LIKE environment variable contains
slash (/) character, then we assume that this is a postfix of a
compiler's path. Otherwise we check if it is the infix of the compiler
name like in case of the original behavior.
Fixes #2315
> ld_logger improvement

- docs/script_daily.md
Log output of the diff command was redirected to the stderr if the output type is not table (See: #1534).
In this case the `No results` line was not in the output so we though that we found some bugs.
Redirecting the `stderr` to `stdout` will solve this problem.
> [doc] Fix daily script

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_triple_arch.py
- analyzer/codechecker_analyzer/analyzers/clangsa/statistics_collector.py
- analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
- analyzer/tests/functional/analyze/test_analyze.py
This fixes issues when isystem already presents in command line,
for example Chromium.
> Replace adding '-isystem' with '-isystem-after'

- web/server/codechecker_server/auth/cc_ldap.py
- web/server/codechecker_server/server.py
- web/server/www/scripts/codecheckerviewer/codecheckerviewer.js
> Closes #2332 
Is it possible that a Python exception was raised in a Thrift API
function. We will catch this exception in the do_POST function and
we will try to send back a valid thrift message to the client. First
we try to call the `readMessageBegin` function on the input protocol
(iprot) but it will wait indefinitely because we have called this
function in the `processor.process(iprot, oprot)` function already
and no newer message can be found in the buffer.
To solve this problem we will create a new JSON protocol (`iprot`) by
using the value from the previous one and send a thrift exception
by using this new input protocol.
> [server] Handle exceptions in do_POST

- config/package_layout.json
> Closes #2330 
Remove `ctu_func_map_cmd` and `gdb_config_file` entries from
the `package_layout.json` config file because we do not use
these anymore.
> [config] Remove unused entries from config file

- analyzer/codechecker_analyzer/cmd/parse.py
> Closes #2358 
Fixed the bug where 'CodeChecker parse --print-steps' shows incorrect file names for some steps when the report ranges across multiple translation units.
> fixed 'CodeChecker parse --print-steps' filename bug

- analyzer/codechecker_analyzer/buildlog/log_parser.py
If the compiler invocation is given an absolute path then the output
Plist file will also contain absolute paths.
> Plist files should contain absolute paths

- codechecker_common/source_code_comment_handler.py
- web/server/tests/unit/source_code_comment_test_files/test_file_1
- web/server/tests/unit/test_source_code_comment.py
If the message of the source code comment contained a closing square
bracket (`]`) the source code comment parsing regex behaved badly.
For example on the following source code comment
`codechecker_suppress [ my_checker ] t[x] is null` the parsed checker
name was `my_checker ] t[x` instead of `my_checker`.
This commit will fix the regex, so the first closing square bracket
will mark the end of the checker name list.
> [server] Fix source code comment regex

- analyzer/codechecker_analyzer/analyzer.py
- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- docs/analyzer/user_guide.md
> Closes #2299 
Don't apply the skip list to CTU and statistical pre-analysis
by default, because it makes the analysis broken.
Skip list can be applied explicitly for these phases
if analyze is called with --ctu-collect or --stats-collect
skip list will not be used in the pre-analysis phase if only --ctu or --statistics parameter is given.
> Do not apply skip list to CTU pre-analysis

- analyzer/codechecker_analyzer/analyzer.py
Typo: `stats_outptut` was used instead of `stats_output`.
> [analyzer] Fix non existing argument name

- config/config.json
So removing it from the sensitive profile.
> Removing MallocOverflow throws too many FPs

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- analyzer/tests/unit/test_option_parser.py
- docs/analyzer/gcc_incompatibilities.md
- docs/analyzer/user_guide.md
--skip-gcc-fix-include flag has been renamed to
--keep-gcc-include-fixed. The goal of this flag is to add the GCC
specific include-fixed directories to the analyzer command.
When determining implicit include paths of a compiler, the result
list is affected by -nostdinc and -nostdinc++ flags.
There was a bug in the addition of implicit include paths: there
were some -isystem flags added without a path as parameter.
> Implicit include path handling

- web/client/codechecker_client/cmd_line_client.py
Remove whitespace characters from the checker message of the `CodeChecker cmd results` command and avoid too long cell contents.
> [cmd] Remove whitespace characters at cmd results

- web/server/codechecker_server/api/store_handler.py
When storing an analysis result with CodeChecker, on the server
at the detail on which files failed to analyze, the CodeChecker
version "6.9.1" or "6.11.0" is stored, not the analyzer
binaries' own reported version.
> [server] Store analyzer version instead of CodeChecker version

- .travis.yml
Travis failed on the OSX test cases on with the following error message:
.../kernel_require.rb:55:in `require': cannot load such file --
active_support/core_ext/object/blank (LoadError)
Solution: https://stackoverflow.com/questions/54888582/ruby-cannot-load-such-file-active-support-core-ext-object-blank
> [travis] Fix travis failure

- analyzer/requirements.txt
Using lxml can increase the plist parsing speed
the dependency was missing the requirements.txt.
It was listed at the dev and osx requirements.
> add missing lxml dependency to the analyzer

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/tests/unit/test_log_parser.py
If the compilation command is not needed by any other
later step (pre-analysis, actual analysis) do not
parse it.
resolves #2396
> do not parse the compile command if not needed later

- analyzer/codechecker_analyzer/analysis_manager.py
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error_skipped.output
Sample:
Before:
```
[1/2] clangsa analyzed simple1.cpp successfully.
```
After:
```
[1/1] clangsa analyzed simple1.cpp successfully.
```
> Do not count a number of skipped actions in progress log

- web/client/codechecker_client/client.py
Try to use a previously saved credential from configuration file when using `CodeChecker cmd login` command if autologin is enabled.
> [cmd] Use saved credentials if autologin is enabled

- docs/web/authentication.md
Whenever this doc seems to be ok, when published in https://codechecker.readthedocs.io/en/latest/web/authentication/ there as missing newlines.
> Update authentication.md for codechecker.readthedocs.io publishing

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangsa/clang_options.py
- analyzer/codechecker_analyzer/analyzers/clangsa/config_handler.py
- analyzer/codechecker_analyzer/analyzers/clangsa/version.py
> Closes #2390 
`aggressive-binary-operation-simplification` option is only available since Clang 8.
This option should not be passed to clang with earlier versions.
> [analyzer] aggressive-binary-operation-simplification should be clang version dependent

- docs/web/authentication.md
- web/client/codechecker_client/credential_manager.py
- web/server/tests/unit/test_credentials.py
Add a note and a new example for the credentials sections which tells the user not to use protocols when adding new credentials entries.
> [doc] Add more example how to use credentials

- analyzer/codechecker_analyzer/analysis_manager.py
- analyzer/tests/functional/analyze/test_analyze.py
In the analysis manager we used `tu_collector` to create failed zip
but after it added source files to the zip we opened this zip file
again in write mode to add some files but it cleared the zip so
the collected source files were removed from the zip.
To solve this problem we need to open the zip file in append mode.
> [analyzer] Fix failure zip

- analyzer/codechecker_analyzer/analyzer_context.py
- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_autodetection.py
- analyzer/codechecker_analyzer/host_check.py
If one of the registered analyzer binary (e.g: clang-tidy) was missing
from user host machine, in CodeChecker we tried to get the full binary
path from the user's `PATH` environment variable for this binary by using
the `find_executable` function but it returned with `None` and we tried
to get the `realpath` of it but the parameter of this function cannot be
`None` so we got an exception.
This commit will solve this issue by checking the return value of the
`find_executable` function and if it returned with `None` we will
print a warning message to the user.
> [analyzer] Fix missing analyzer binary

- analyzer/codechecker_analyzer/cmd/parse.py
- web/client/codechecker_client/cmd_line_client.py
During the report generation the file list is in no determinate order
when the results counts otherwise match. This change sorts the result
lines based on the base name of the file.
> [analyzer] Sort report lines for files

- analyzer/tests/functional/host_check/test_host_check.py
OSError is no longer rethrown inside has_analyzer_option method of
host_check.py. Instead, False is returned in case of an error.
The test case is modified to accomodate to this change.
> [analyzer] Fix test case for has_analyzer_option

- analyzer/tests/unit/test_option_parser.py
Skip testing g++ include path for 'include-fixed' in its implicit
include path.
> [analyzer] OSX does not have include-fixed in its include path

- .travis.yml
Currently if an analysis is performed on a linux platform, the results of
functional, unit and tu_collector tests are ignored, and the job can
succeed even if the tests failed. This modification makes sure that the job
is only successful if every test passes.
> [CI] Fix travis error code handling.

- analyzer/codechecker_analyzer/buildlog/log_parser.py
File path after the -include flag should not be converted to absolute path.
Only the flags with include path directories should be converted.
If every other include directory flag is set properly the
file set by -include should be found too.
Resolves #2440
> do not convert to absolute path the files after -include

- scripts/test/check_clang.py
the minimal required clang version to run the tests
is clang v9
> bump up the minimal required clang version

- analyzer/codechecker_analyzer/analyzers/clangsa/version.py
- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/tests/functional/analyze/test_analyze.py
- analyzer/tests/unit/ctu_autodetection_test_files/gcc_version
- analyzer/tests/unit/test_clang_version_parsing.py
- analyzer/tests/unit/test_option_parser.py
If clang compiler is used to build and to analyze a project
do not filter the compiler options, keep them all.
The compiler installed dir and major versions are compared
to detect if the same clang is used for compilation and
analysis.
clang and clang++ are handled as they were the same binaries.
if the compiler is the same as the analyzer only a minimal
compiler option filtering is done.
- source, output and other files are removed from the compile command
- include paths are converted to absolute path required for the reports
- preprocessor flags are filtered out (the same way as for gcc/g++)
The list of filtered preprocessor flags is extended to remove -MD, -MG
options.
__collect_clang_compile_opts was introduced to
collect all the compile options should be run at
last everything …
> keep all flags if the analyzer is the same as the compiler

- analyzer/codechecker_analyzer/buildlog/log_parser.py
The -M flag is used for dependency generation.
-MG assumes missing header files are generated files and adds them to the
dependency list without raising an error.
> detect -MG as a precompilation flag

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/unit/test_log_parser.py
- analyzer/tools/build-logger/src/ldlogger-tool-gcc.c
- analyzer/tools/build-logger/test/test_logger.sh
Compilers like Clang supports passing extra flags using so-called response files that you specify with the `@file` syntax. We need to read the arguments from the given file and extend the argument list with these options too.
> [logger] Support response files

- web/server/www/scripts/codecheckerviewer/ListOfRuns.js
> Closes #2473 
The server side run sort feature changed the Thrift API and introduced a
new paramter for `getRunData` function. In the `ListOfRuns.js` file
we forgot to change this function call in one place so the browser
is thrown the following exception:
codeCheckerDBAccess.js:102 Uncaught TypeError: this.sortMode.write is not a function
This commit fix the `getRunData` function call in the GUI's code.
> [gui] Fix delete run

- analyzer/codechecker_analyzer/cmd/analyze.py
If there is a codechecker config file in the users home directory
it will be printed out which breaks the tests.
The users home directory is always included.
> the existence of a config file influences the test

- analyzer/codechecker_analyzer/cmd/parse.py
- codechecker_common/report.py
- web/tests/functional/report_viewer_api/test_get_run_results.py
- web/tests/projects/cpp/new_delete.cpp
> Closes #2454
When the source line contained a non ascii character where a checker reported a bug the hash generation failed. To solve this problem we encode the string to `utf-8` and ignore the errors.
> [analyzer] Fix encoding string when genering hash

- docs/web/user_guide.md
- web/api/v6/report_server.thrift
- web/client/codechecker_client/cmd/cmd.py
- web/client/codechecker_client/cmd_line_client.py
- web/client/codechecker_client/thrift_helper.py
- web/server/codechecker_server/api/report_server.py
- web/server/www/scripts/codecheckerviewer/ListOfRuns.js
- web/tests/functional/delete_runs/test_delete_runs.py
- web/tests/functional/detection_status/test_detection_status.py
- web/tests/functional/report_viewer_api/test_hash_clash.py
- web/tests/functional/report_viewer_api/test_remove_run_results.py
* Extend Thrift API to be able to filter runs on multiple conditions.
* Add the same filter command line options to the `CodeChecker cmd runs`
as the `CodeChecker cmd del` command.
* Add new test cases.
> [web] New filter options for CodeChecker cmd runs command

- analyzer/codechecker_analyzer/analyzers/clangsa/statistics_collector.py
Clang 9 enables package options beside analyzer and checker options.
This allows us to use package option instead of analyzer option for
passing the path of the YAML files needed by the statistics-based
checkers. The advantage of this approach is that the plugin now works
with the official Clang 9 release, no patching is needed. Since the
statistics-based checkers are in the same package, the option needs only
to be passed once for the whole analysis.
This patch adjust CodeChecker to work correctly with the new plugin.
> [Statistics] Replace analyzer option `api-metadata-path` with package option `APIMetadataPath`

- web/client/codechecker_client/cmd/store.py
- web/tests/functional/cppcheck/__init__.py
- web/tests/functional/cppcheck/test_cppcheck.py
- web/tests/functional/cppcheck/test_proj/Makefile
- web/tests/functional/cppcheck/test_proj/divide_zero.cpp
- web/tests/functional/cppcheck/test_proj/divide_zero.plist
- web/tests/functional/cppcheck/test_proj/lib.h
cppcheck can generate plist reports but no bug identifier
hash is generated. A 0 value is generated by cppcheck as a bug hash.
This change allows to generate the report hash if the plist report
contains onl results where all the hashes are 0.
The generated report hash will be written to the plist report files.
> store cppcheck plist reports (generate hash)

- analyzer/tools/build-logger/README.md
- analyzer/tools/build-logger/src/ldlogger-tool-gcc.c
- analyzer/tools/build-logger/src/ldlogger-util.c
- analyzer/tools/build-logger/src/ldlogger-util.h
- analyzer/tools/build-logger/test/test_logger.sh
Some paths are converted to absolute path in the build command by
the logger if CC_LOGGER_ABS_PATH=1 given.
> Logger absolute include paths

- config/config.json
This checker is only a demo checker.
The real checker is alpha.unix.SimpleStream
> Remove SimpleStream checker from sensitive profile

- analyzer/codechecker_analyzer/analyzer_context.py
- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/config_handler.py
Do not load the plugin when `CC_ANALYZERS_FROM_PATH` is turned on because
it might be incompatible.
> [analyzer] Do not load plugins when CC_ANALYZERS_FROM_PATH is used

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/unit/test_option_parser.py
warnings should be configured through CodeChecker.
If there is any -w or -Werror compilation flags skip
them if the compiler was gcc or clang.
Because the warning flag skipping is needed for clang
compilation flag skipping is introduced for compilation
actions where the compiler is clang.
> skip -w, -Werror flags for gcc and clang too

- codechecker_common/plist_parser.py
We need to set `encoding` to `utf-8` when using `io.open` because
it is possible that we are reading a non `utf-8` encoded plist file.
> [analyzer] Set io.open encoding to utf-8

- analyzer/codechecker_analyzer/analysis_manager.py
- analyzer/codechecker_analyzer/analyzer.py
- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/tests/functional/analyze_and_parse/test_files/context_free_hash.output
- analyzer/tests/functional/analyze_and_parse/test_files/context_sensitive_hash.output
- analyzer/tests/unit/test_buildcmd_escaping.py
- analyzer/tests/unit/test_log_parser.py
if a skip file is used but no pre analysis step is executed
the pre analysis skip handler will not be used.
In the analyze.py the statistics collector flag
status was only checked if the ctu_phases was in the args.
The two of them should be checked independently because
stats and ctu can be executed independently.
stats can be enabled even if ctu is not enabled.
> less argument processing if skip file used without ctu and stats

- web/api/v6/report_server.thrift
- web/codechecker_web/shared/version.py
- web/codechecker_web/shared/webserver_context.py
- web/config/system_comment_kinds.json
- web/server/codechecker_server/api/report_server.py
- web/server/codechecker_server/database/run_db_model.py
- web/server/codechecker_server/migrations/report/versions/6cb6a3a41967_system_comments.py
- web/server/www/scripts/codecheckerviewer/CommentView.js
- web/server/www/scripts/version.js
- web/server/www/style/codecheckerviewer.css
- web/server/www/style/comment.css
- web/tests/functional/comment/test_comment.py
> Closes #746
Show system comments at bugs.
Screenshot:
> System comments

- web/server/www/scripts/codecheckerviewer/filter/SelectFilter.js
If we set a new source component filter and we move the mouse over
this item a tooltip will be shown. If I remove this filter the tooltip
will not be removed and it will be visible constantly.
This commit solves this problem and hides the tooltip when the source
component filter item is being removed.
> [fix] Fix hiding tooltip of the source component filter item

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/unit/test_option_parser.py
With these Xclang constructs the generated output format
will not be plist, so it can not be parsed.
-Xclang -module-file-info
-Xclang -S main.cpp
-Xclang -emit-llvm main.cpp
-Xclang -rewrite-objc main.cpp
> some specific Xclang arguments modify the output

- analyzer/codechecker_analyzer/analyzers/analyzer_types.py
> Closes #2505
Handle the use case when only Clang Tidy is installed on the users machine and Clang SA is not available.
> [fix] Handle use case when ClangSA is not available

- .gitmessage
- Makefile
Add a commit message template file to the repository and create a target
in the main `Makefile` which will set this template as a default commit
message template on package build target.
> [cfg] Set commit message template

- Doxyfile.in
- analyzer/config/analyzer_version.json
- web/config/web_version.json
increment version on the new upcoming release branch 
The few commits already merged to v6.11.0 should be cherry picked to the new release-v6.11.1 branch after the version is updated.
> bump up version to v6.11.1

- tools/tu_collector/tests/project/compile_command.json
Among the build commands of the tu-collector test files there was
a compilation action which compiled a .c file with -std=c++11 flag.
Such a mix of the languages cause a warning in some compiler on
some platforms.
> [tu-collector][test][fix] Fix warning in tu-collector test

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/unit/test_log_parser.py
- codechecker_common/skiplist_handler.py
The analyzed source file path needs to be normalized before skip matching. Also the paths in the skipfile is normalized too. With this way of working, the result of the skipfile usage is the same as before.
> Skipfile normalization fix

- analyzer/codechecker_analyzer/cmd/parse.py
- tools/plist_to_html/plist_to_html/PlistToHtml.py
> Closes #2539
Running `CodeChecker parse -e html reports -o html_reports` will convert
the reports to html but the `Total number of reports: 0` even if there
were reports. This commit will fix this and will print the number of reports
and summary header in the source code of the `plist-to-html` tool and not in
the CodeChecker parse command.
> [plist2html] Print total number of reports in plist-to-html

- codechecker_common/output_formatters.py
- web/tests/functional/cmdline/test_cmdline.py
In the format specification `0` means fill default to `0` and align to `=`.
If the format string looks like `{i:0}`, we will get the following error
message: '=' alignment not allowed in string format specifier.
For this reason we do not put `:0` in the format specification.
> [fix] Fix row output type in command line

- tools/tu_collector/tests/project/compile_command.json
- tools/tu_collector/tests/project/hello.c
- tools/tu_collector/tests/tu_collector_test.py
- tools/tu_collector/tu_collector/tu_collector.py
When the build command compiles with CCache, the tu-collector tries to
use it as preprocessor in order to gather the files of the translation
unit. This fails the TU collection, so in this commit we find the
original compiler.
> [tu-collector] Recognize CCache in build command

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- analyzer/tests/unit/test_option_parser.py
- docs/analyzer/gcc_incompatibilities.md
- docs/analyzer/user_guide.md
There are two kinds of GCC-specific implicit include header files. One
is "include-fixed" and the other are those which contain an ...intrin.h
header files. Until now both of these have been skipped by default and
both could have been kept by --keep-gcc-include-fixed flag during
analysis.
It is clear that ...intrin.h headers are very much GCC-specific, so for
sure these have to be skipped most of the time. These header files
contain some function symbols on vectoriztaion operations (such as
_mm_xor_ps) of which the implementation is an 1-to-1 mapping to a
__buildin... GCC symbol. Of course these built-ins can't be seen by
Clang, however, Clang provides its own headers with the same
_mm_xor_ps-like functions that have some straightforward implementation
(i.e. no __builtin symbols used). …
> [analyzer] Handle two kinds of implicit includes differently

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/unit/test_option_parser.py
There can be include directories with *intrin.h header files
not only at the implicit includes, this change
filters out any include directories containing *intrin.h header files.
> filter out include directories containing *intrin.h header files

- web/client/codechecker_client/credential_manager.py
It is easy to mistype the name of the `.codechecker.passwords.json` file
and use `.codechecker.password.json` file name instead of it. This patch
will warn the user in this happend.
> [cmd] Give warning to the user if passwords.json file is mistyped

- analyzer/tools/build-logger/src/ldlogger-tool-gcc.c
- analyzer/tools/build-logger/test/test_logger.sh
with this change not only the include paths but the source file
path is converted to absolute path in the compile command database.
> convert the source file to abs path if CC_LOGGER_ABS_PATH is set

- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- docs/analyzer/user_guide.md
The statistics-based feature proved stable enough to remove the
EXPERIMENTAL flag from it. Flag is now removed from help texts and
docs.
> [analyzer] Remove EXPERIMENTAL tag from the statistics-based feature

- analyzer/codechecker_analyzer/buildlog/log_parser.py
Handle the error when the logged compiler binary is missing from the PATH.
> [fix] OSError exception was not handled if a binary is missing from PATH

- tools/report-converter/codechecker_report_converter/cli.py
If we run report-converter (cli.py) in an environment where
'codechecker_report_converter' module is not available we should add
the grandparent directory of the cli.py file to the system path. So
python will find the module correctly.
This problem is possible when we call report-converter from the build
directory of CodeChecker: `build/CodeChecker/bin/report-converter`.
> [fix][report-converter] Fix finding module in report-converter

- analyzer/codechecker_analyzer/buildlog/build_manager.py
- analyzer/codechecker_analyzer/cmd/log.py
- analyzer/tools/build-logger/Makefile.manual
- analyzer/tools/build-logger/README.md
- analyzer/tools/build-logger/src/ldlogger-logger.c
- analyzer/tools/build-logger/src/ldlogger-tool.c
- analyzer/tools/build-logger/src/ldlogger-util.c
- analyzer/tools/build-logger/src/ldlogger-util.h
- analyzer/tools/build-logger/test/test_logger.sh
- docs/analyzer/user_guide.md
With these changes if the CodeChecker log command will be run in
verbose mode then a new debug log file will be created which will
contain messages related to the build logger.
> [build-logger] Support debug logging

- analyzer/codechecker_analyzer/analyzers/result_handler_base.py
- analyzer/tests/functional/analyze_and_parse/test_files/Makefile
- analyzer/tests/functional/analyze_and_parse/test_files/filename_collision.output
- analyzer/tests/functional/analyze_and_parse/test_files/filename_collision/a/f.cpp
- analyzer/tests/functional/analyze_and_parse/test_files/filename_collision/b/f.cpp
- analyzer/tests/functional/analyze_and_parse/test_files/filename_collision/main.cpp
> Closes #2435 
Source files with equal filename generates and overwrites the
filename.plist result file during analysis step. The main problem
is that the filename hash generation contains only the filename and
not the file path.
This commit will solve this problem and include the buildaction
directory (removes the users home directory from the path) to the
filename hash.
> [analyzer] Fix plist file name collision

- web/server/www/scripts/codecheckerviewer/filter/SelectFilter.js
There was a bug in the UI when we set a file path filter for example
to `*` and we reloaded the page. Unfortunately we forgot to set the limit
and query parameters so it tried to get all the items from the server
which can be really large and a browser can be freezed.
This commit will solve this problem.
> [gui] Set limit and query when getting filter items

- docs/README.md
- docs/supported_code_analyzers.md
> Closes #2555
Highligh in the documentation that CodeChecker can only execute ClangSA
and Clang Tidy analyzers but supports the storage of multiple analyzer
results.
> [doc] Refactoring doc of supported analyzers

- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- analyzer/tests/functional/analyze_and_parse/test_files/multi_error_skipped_in_cmd.output
- docs/analyzer/user_guide.md
- docs/usage.md
> Closes #2543
This feature is similar to the skip list feature but can be easier to
quickly analyze only a few files not the whole compile command json.
E.g.: `CodeChecker analyze -o reports compile_command.json --files test.cpp test2.cpp`.
> [cmd] Select which file to analyze from the compile command json

- analyzer/tests/functional/cmdline/test_cmdline.py
- bin/CodeChecker.py
> Closes #2594
CodeChecker will throw the following exception when no subcommand is
given for the CodeChecker command:
```
Traceback (most recent call last):
File "/cc_bin/CodeChecker.py", line 127, in main
args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```
This patch will fix this problem and print the help message instead of
this exception.
> [fix][cmd] Fix empty CodeChecker invocation

- analyzer/codechecker_analyzer/analyzers/clangsa/result_handler.py
- analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangtidy/result_handler.py
- analyzer/codechecker_analyzer/arg.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- analyzer/tests/functional/analyze_and_parse/test_files/context_free_hash_v2_clang_tidy.output
- analyzer/tests/functional/analyze_and_parse/test_files/context_free_hash_v2_clangsa.output
- docs/analyzer/user_guide.md
Clang Tidy never used context free hash even if I am enabled it
when calling the analyze command:
`CodeChecker analyze -o ~/reports/ ~/build.json --report-hash context-free`.
To solve this problem we need to set the `report_hash` attribute of the
`ClangTidyConfigHandler` by using the given `args` in
`construct_config_handler` function.
> [analyzer] Fix Clang Tidy context free hash generation

- analyzer/codechecker_analyzer/cmd/log.py
- analyzer/tools/build-logger/README.md
- docs/analyzer/user_guide.md
The documentation of LD_LOGGER_KEEP_LINK was missing.
Fixes #2617
> [doc] Adding some documentation to ld-logger

- web/Makefile
`codechecker_report_hash` module is missing from the package when we
create a package only from the web part. This commit add this module
to the package.
> [web] Add report hash lib when packaging only web

- web/server/codechecker_server/cmd/server.py
There is a problem with the server when we do the following:
- Start a web server by using postgresql database.
- Add a new product by using sqlite database.
- Remove the sqlite database.
- Restart the server.
- The following exception will be thrown:
```
output_formatters.py", line 114, in twodim_to_table
str_parts.append(print_string.format(*line))
TypeError: unsupported format string passed to NoneType.__format__
```
The problem at here that the schema version will be None and we try to
print it in a format string: "{0:0}.format(schema_ver)". To solve this
problem we will convert the schema version to string before print.
> [server] Fix printing product statuses

- analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py
- codechecker_common/plist_parser.py
> Closes #2598
Give a better log message when the user parses an invalid plist file.
> [cmd] Fix parsing invalid plist file

- analyzer/codechecker_analyzer/cmd/check.py
> Closes #2238
The `--ctu-reanalyze-on-failure` option which allows for reanalizing
in non-ctu mode if the ctu mode fails is available in the `analyze`
subcommand of CodeChecker, but it is not in the 'check' subcommand.
This commit introduce it to the check subcommand.
> [cmd] CTU reanalyze option on failure for check command

- analyzer/tools/build-logger/src/ldlogger-hooks.c
Currently if the # of arguments is >= CC_LOGGER_MAX_ARGS, the logger segfaults.
This patch uses heap allocated array for arguments,
if the required count is more than CC_LOGGER_MAX_ARGS -1.
Otherwise the static array is utilised.
> [ldlogger] Allow more than 'CC_LOGGER_MAX_ARGS' in commands.

- analyzer/tools/build-logger/src/ldlogger-logger.c
- analyzer/tools/build-logger/src/ldlogger-tool-gcc.c
- analyzer/tools/build-logger/src/ldlogger-tool.c
- Print debug messages when no source file found when processing a command
or when processing a response file.
- Terminate log print expressions with `;`.
> [ld-logger] Improve debug messages

- tools/codechecker_report_hash/codechecker_report_hash/hash.py
- tools/codechecker_report_hash/tests/unit/codechecker_report_hash/codechecker_report_hash_test.py
- web/client/codechecker_client/cmd/store.py
- Do not call the replace_report_hash function when the plist file
does not contain any diagnostic.
- Keep the plist file valid when replacing report hash and the plist
file does not contain any diagnostic.
- Add new unit test case which test that the plist file will be valid
after calling the replace_report_hash function on it.
> [store] Keep plist file valid when replacing report hash

- web/server/codechecker_server/migrations/config/env.py
- web/server/codechecker_server/migrations/report/env.py
Running alembic on config database will fail with the following import
error: `ModuleNotFoundError: No module named 'codechecker_common'`.
This commit will fix this problem by adding the root directory to the sys.path.
> [cfg] Fix migration script generation for config db

- web/server/codechecker_server/api/report_server.py
- web/tests/functional/review_status/test_review_status.py
If we called the `changeReviewStatus` API function where the message
was `None` the server trown an error which said that we can not call
`encode` function on None. This commit will handle the use case when
no review status message is given for this API function.
> [server] Fix empty review status message

- web/server/codechecker_server/cmd/server.py
> Closes #1046
If relative sqlite file path is given for the server, convert this file path to absolute.
> [server] Fix relative sqlite file path

- web/server/codechecker_server/api/report_server.py
- web/tests/functional/diff_remote/test_diff_remote.py
If a run history filter is given for getRunHistory API function where
the tagNames are given we will do an exact match and we cannot much tag
names by using regexes. This commit will change this behaviour.
> [server] Allow to filter run history tag names by regex
