Ericsson/codechecker

web/server/codechecker_server/server.py
I got the following exception when I tried to reach `/live` or `ready` routes:
```
TypeError: a bytes-like object is required, not 'str'
```
This commit will fix this problem.
=> [server] Fix liveness and readyness urls

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzers/config_handler.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/parse.py, analyzer/tests/functional/analyze_and_parse/test_files/context_sensitive_hash_clang_tidy.output, docs/web/user_guide.md, web/client/codechecker_client/cmd/store.py, web/client/codechecker_client/metadata.py, web/server/codechecker_server/api/report_server.py, web/server/codechecker_server/metadata.py, web/server/tests/unit/metadata_test_files/v1.json, web/server/tests/unit/metadata_test_files/v2.json, web/server/tests/unit/metadata_test_files/v2_multiple.json, web/server/tests/unit/metadata_test_files/v2_multiple_cppcheck.json, web/server/tests/unit/test_metadata_merge.py, web/server/tests/unit/test_metadata_parser.py, web/server/www/scripts/codecheckerviewer/ListOfRuns.js, web/server/www/scripts/codecheckerviewer/RunHistory.js, web/tests/functional/detection_status/test_detection_status.py
* Allow the user to store multiple report directories with one `CodeChecker store` command.
* New metadata.json format.
* Tests for parsing and merging metadata.json files.
=> [web] Store multiple report directories with one command

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzer_context.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py, analyzer/tests/functional/analyze_and_parse/test_files/Makefile, analyzer/tests/functional/analyze_and_parse/test_files/compiler_error.cpp, analyzer/tests/functional/analyze_and_parse/test_files/compiler_error.output, analyzer/tests/functional/analyze_and_parse/test_files/context_sensitive_hash_clang_tidy.output, docs/analyzer/user_guide.md, tools/tu_collector/tu_collector/tu_collector.py, web/codechecker_web/shared/webserver_context.py
There are some constructions which GCC compiles but Clang gives a
compilation error. In case such a compilation error happens, then the
whole translation unit is not analyzed and the users may not be informed
about this. By this change compiler errors also become CodeChecker
reports.
=> [analyzer] Capture compiler errors as reports

bin/CodeChecker
Steps to reproduce the problem:
- Start a CodeChecker server
- Stop it by using `Ctrl + C` commands.
- An error message will be printed which says that it failed to remove
temporary directory and manual cleanup is required.
The problem at here that the `_remove_tmp` will be called twice. When it
will be called on the second time, an exception will be thrown because
the file already has been removed. In Python2 an `OSError` was thrown but
in Python3 a `FileNotFoundError` exception will be thrown which inherits
from `OSError`. For this reason we should use `isinstance` to check the
type.
=> [server] Fix failed to remove temp directory on server shutdown

web/server/vendor/Makefile
the prevous javascript api stub version was used during
packaging not the latest
=> [fix] using previous codechecker js api version

analyzer/tests/unit/test_remove_report_from_plist.py
If the builtin plistlib is used (because lxml is missing)
to parse the plist files it expects that the files will be open
in binary mode.
=> open plist file in binary mode

docs/jenkins_gerrit_integration.md
> Closes #2667
Template scripts are removed when we implemented the gerrit output format
support for CodeChecker cmd diff command but the userguide still mentioned
these files. This commit will remove this section from the user guide.
=> [doc] Remove template scripts section from gerrit docs

docs/analyzer/user_guide.md
> Closes #2664
Update the default values of the CC_LOGGER_GCC_LIKE environment variable
if the user guide.
=> [doc] Fix default values of CC_LOGGER_GCC_LIKE in user guide

analyzer/tests/unit/test_remove_report_from_plist.py
Without lxml in plistlib the plist parsing will fail
if the plist file was not opened in binary mode.
=> for plistlib the file needs to be opened in binary mode

analyzer/codechecker_analyzer/cmd/parse.py, analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py, codechecker_common/report.py, docs/analyzer/user_guide.md
> Part of the #2661.
Introducing `codeclimate` json output format for the `CodeChecker parse` command
which will make the CodeChecker Gitlab integration much easier.
=> [cmd] Support Code Climate format for parse command

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzers/clangtidy/config_handler.py, analyzer/tests/functional/analyze_and_parse/test_files/compiler_error_disabled.output, docs/analyzer/user_guide.md
In an earlier commit (#2652) a new feature has been introduced: compiler
errors can be captured as CodeChecker reports. The corresponding checker
name is clang-diagnostic-error. This type of report couldn't have been
disabled. In this commit these can be disabled too.
Warnings can be enabled and disabled as CodeChecker reports as well. For
example the warning about unused variables can be disabled by
-d Wunused-variable. This warning is captured as
clang-diagnostic-unused-variable and now this can be also disabled as
-d clang-diagnostic-unused-variable.
=> [analyzer] Compiler errors as reports can be disabled.

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzers/analyzer_types.py, analyzer/codechecker_analyzer/pre_analysis_manager.py
No sync manager is required anymore. The configs were already
shared in a read only way. A configuration change in one process
should not influence the config in another.
Every process will get its own local configuration instance in
the new setup and can modify it if needed.
Every configuration change which could influence the analysis
should be done before the worker pool starts the analysis jobs.
The refactoring was done to fix a hardly reproducible
problem with the sared configuration values between processes.
For some reason the socket belonging to the SyncManager was closed
by the SyncManager even if data was tried to be sent to be shared
between the processes.
File "<string>", line 2, in get
File ".../python3.8.2/multiprocessing/managers.py", line 844, in _callmethod …
=> refactor how the analyzer configs are passed for each process

tools/report-converter/README.md, tools/report-converter/codechecker_report_converter/analyzer_result.py, tools/report-converter/codechecker_report_converter/cli.py, tools/report-converter/tests/functional/cmdline/test_cmdline.py, tools/report-converter/tests/functional/cmdline/test_files/Makefile, tools/report-converter/tests/functional/cmdline/test_files/files/simple.go, tools/report-converter/tests/functional/cmdline/test_files/simple.out
Provide metada information which will be stored alongside the run when the
created report directory will be stored to a running CodeChecker server.
It has the following format: `key=value`. Valid key values are:
`analyzer_command`, `analyzer_version`.
=> [report-converter] Metadata

web/tests/functional/detection_status/test_detection_status.py
- Some test functions in the detection status test cases were set to
private or protected, so these test cases were never be run. This commit
will enable them.
- We should remove `.clang-tidy` configuration file before each test case
because it can give different results and test cases may fail.
=> [test] Fix detection status test cases

web/server/codechecker_server/api/authentication.py, web/tests/functional/authentication/test_authentication.py
It is possible that the `performLogin` function will be called by a different
client and when no auth string is given we will get the following exception:
```
CodeChecker/lib/python3/codechecker_server/api/authentication.py", line 86, in performLogin
user_name, _ = auth_string.split(':', 1)
AttributeError: 'NoneType' object has no attribute 'split'
```
To solve this problem we will raise an exception that no credentials
are supplied.
=> [server] Handle empty auth string on login

analyzer/codechecker_analyzer/cmd/log.py, analyzer/tests/functional/cmdline/test_cmdline.py, analyzer/tools/build-logger/src/ldlogger-logger.c, analyzer/tools/build-logger/test/test_logger.sh
It is possible that the log file will not be created or it will be empty
for example when the build command is an empty string or when there is no
compiler command to log. For this reason we will create this log file if
it does not exist at the beginning of the logging phase and we will insert
an empty array to it, to make sure that it will be a valid json file.
=> [analyzer] Always generate valid log file

analyzer/requirements.txt, analyzer/requirements_py/dev/requirements.txt, analyzer/requirements_py/osx/requirements.txt, tools/codechecker_report_hash/requirements_py/dev/requirements.txt, web/requirements.txt, web/requirements_py/db_pg8000/requirements.txt, web/requirements_py/db_psycopg2/requirements.txt, web/requirements_py/dev/requirements.txt, web/requirements_py/osx/requirements.txt, web/server/codechecker_server/database/database.py
New 3pp versions:
- sqlalchemy 1.3.16
- portalocker 1.7.0
- alembic 1.4.2
- pg8000 1.15.2
- psycopg2-binary 2.8.5
- psutil 5.7.0
- scan-build 2.0.19
client_encoding is a psycopg2 only argument added only if
that driver is used.
=> [analyzer][web][dependency] update 3pp python dependencies

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, docs/analyzer/user_guide.md
- If the log file does not exist we will print an error message and
exit with an error code.
- If multiple log files were given to the CodeChecker analyze command,
we print an error message that it is not supported yet and we exit
with an error code. Instead of this we can just remove the multiple
log files support from the argument parser so the user will not be
able to give multiple log files for this command.
=> [analyzer] Exit with an error code if the logfile does not exist

web/client/codechecker_client/credential_manager.py
Saved credentials are not worked properly when the url contained a special
non word character. For example: `https://codechecker-demo.cloudapp.azure.com/`
=> [cmd] Fix credential manager

analyzer/codechecker_analyzer/cmd/parse.py, codechecker_common/report.py, tools/codechecker_report_hash/codechecker_report_hash/hash.py, tools/codechecker_report_hash/tests/unit/codechecker_report_hash/codechecker_report_hash_test.py, web/client/codechecker_client/cmd_line_client.py, web/server/codechecker_server/api/report_server.py, web/server/tests/unit/test_report_path_hash.py
When a checker is alias of another then it is possible that two
checkers are reporting the same message. We wouldn't like to unique
them because it was random which checker won the possibility of
reporting. Now both checkers are emitting the report and the user can
explicitly choose to switch off any of them.
This commit also contains some improvement on checking "skipping". The
operator "|=" is not lazy and it is not always necessary to evaluate
the right hand side.
=> Distinguish reports of different checkers

web/client/codechecker_client/client.py, web/client/codechecker_client/thrift_call.py, web/client/codechecker_client/thrift_helper.py
> Closes #2706
If auto login is configured by using username and password but the session
token is expired the client will not login the user automatically just print
the following error message:
```
Internal server error: Error code 401: Unauthorized!
```
This patch will solve this problem on the following way: if the client
call an API request with an expired session token, we will catch the exception,
try to login the user and call the API function again.
With this solution no unnecessary API request will be made to the server if
the session token is not expired.
=> [web] Fix autologin when session expired

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, docs/analyzer/user_guide.md, web/tests/functional/detection_status/test_detection_status.py, web/tests/functional/report_viewer_api/test_report_counting.py, web/tests/functional/report_viewer_api/test_report_filter.py, web/tests/functional/skip/__init__.py, web/tests/functional/skip/test_skip.py, web/tests/libtest/codechecker.py, web/tests/projects/cpp/project_info.json
Use `-header-filter=.*` to display errors from all non-system headers.
=> [clang-tidy] Display errors from all non-system headers

docs/analyzer/user_guide.md
Add new example how to match exact compiler names, partial matches
can lead to log more binary executions than required.
resolves #2635
=> [documentation][analyzer] add exact compiler name match example

config/checker_severity_map.json
`misc-non-private-member-variables-in-classes` checker is defined multiple times
in the `checker_severity_map.json` file. This commit will keep only one.
=> [config] Remove duplicated entry from the checker severity map

web/Makefile
> Closes #2724
Add a new make target that will check that `codecheck_api` and `codechecker_api_shared`
python packages are up to date. If not, it will update these packages
and remove the JavaScript package from the vendor directory so the
`package_vendor` target will download the required version.
=> [makefile] Update codechecker_api dependencies automatically

web/api/README.md
Extend the documentation how we can publish stable release packages
from the thrift api stubs.
=> [doc] Extend thrift api stable release readme

docs/web/user_guide.md, web/client/codechecker_client/cmd/store.py, web/server/codechecker_server/cmd/server.py, web/tests/functional/cli_config/__init__.py, web/tests/functional/cli_config/test_server_config.py, web/tests/functional/cli_config/test_store_config.py, web/tests/libtest/codechecker.py
=> [web] Support config file

web/server/codechecker_server/auth/cc_ldap.py
If an `ldap.SERVER_DOWN` was thrown by the server for example when a wrong
connection url was given, the server tried to get the `message`
attribute of the exception an the following exception was thrown:
```
AttributeError: 'SERVER_DOWN' object has no attribute 'message'
```
The exception looked like this:
```
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server", 'errno': 107,
'info': 'Transport endpoint is not connected'}
```
This commit will remove the `log_ldap_error` function because it was
used only in one place and we just log the exception after converting
to str.
=> [server] Fix logging ldap error

web/server/vendor/Makefile
We tried to remove a wrong directory called `codechecker_api_js` on
`clean_vendor` makefile target instead of `codechecker-api-js`.
This commit solves this problem and removes the correct directory.
=> [makefile] Fix cleaning vendor directory

scripts/build/wrap_binary_in_venv.py
Still the python2 interpreter was used to execute
the script.
=> fix standalone package builder script py2 -> py3

scripts/build/wrap_binary_in_venv.py
The current permissions were probably a bit too strict.
With this change not only the owner can execute the
top level CodeChecker script.
=> change the standalone package top level script permissions

analyzer/tools/build-logger/src/ldlogger-tool.c
The return value of `getenv` function is not checked before using it in some places, so we tried to pass `NULL` to `printf` which is an undefined behaviour in C.
=> [ldlogger] Fix segmentation fault in logger

analyzer/codechecker_analyzer/cmd/parse.py
Earlier a `trim_path_prefixes` method was introduced in the `Report` class
which can be used at the parse command to trim path prefixes.
=> [cmd] Use report object to trim path prefixes at parse command

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/functional/analyze/test_files/extra_args.c, analyzer/tests/functional/analyze/test_files/saargs, analyzer/tests/functional/analyze/test_files/tidyargs
The content of tidyargs file is given to re.sub() function which doesn't
accept binary strings.
=> [fix] Fix tidyargs file encoding

analyzer/codechecker_analyzer/cmd/parse.py
The checker name is needed so the hash function can compute a hash for the
report. If this checker name is not the member of the Report object then hash
generation crashes.
=> [fix] Bugfix in HTML generator in parse command

web/server/codechecker_server/api/report_server.py, web/server/www/scripts/codecheckerviewer/filter/RunHistoryTagFilter.js
- Filter run history tags on the server side instead of client side.
- Previously the `runTag` attribute of the `ReportFilter` data was set
to list of strings when the user set a tag filter and refreshed the page.
This way the thrift api was thrown an exception. To solve this issue we will
always set this attribute to list of tag ids.
=> [server] Fix run history tag filter

docs/web/user_guide.md, web/client/codechecker_client/product.py, web/server/codechecker_server/cmd/server.py, web/server/codechecker_server/server.py, web/server/tests/unit/test_url_understanding.py
> Properly fixes #2708.
Adds support to listen on IPv6 addresses, if the user requests.
$ CodeChecker server  # as if started with --host localhost
$ netstat -tlp | grep 8001
tcp        0      0 localhost:8001          0.0.0.0:*               LISTEN      30020/python3
$ CodeChecker server --host ::1
$ netstat -tlp | grep 8001
tcp6       0      0 ip6-localhost:8001      [::]:*                  LISTEN      29734/python3
$ CodeChecker server --not-host-only  # now equal to: --host ::
$ netstat -tlp | grep 8001
tcp6       0      0 [::]:8001               [::]:*                  LISTEN      30860/python3
An IPv6 listening socket on all interfaces (`::`) also listens on all IPv4 interfaces (`0.0.0.0`), so there is no need to bind two sockets for most normal operation.
All IPv4 addresses are …
=> [server] Implement understanding IPv6 listen addresses

analyzer/codechecker_analyzer/analyzers/clangsa/result_handler.py
In case of compiler errors Clang Tidy analyzer will create reports
(plist files) from the standard output. Previously if we enabled the
Clang SA analyzer too and we used one of the context free hashes we
tried to open the plist file and override the report hashes in it
but no plist file was created by this analyzer. So an exception was
thrown that the plist file does not exist. This commit will handle
this use case too.
=> [analyzer] Create reports on compiler failure only in case of Clang Tidy

web/server/codechecker_server/api/report_server.py
On component update the following exception was thrown:
```
a bytes-like object is required, not 'str'
```
We forgot to encode the component value when we moved to Python 3 so
this commit will solve this problem.
=> [server] Fix source component update

web/server/codechecker_server/server.py
In #2712, two additional log lines were not properly updated by mistake. This patch should fix it. Thanks @irishrover for noticing!
=> [server] Fix auth log lines exception with IPv6

web/server/codechecker_server/api/report_server.py
When a comment was updated and the message wasn't changed we didn't
create a system comment object but we tried to use this variable later
so the following exception was thrown:
`local variable 'system_comment' referenced before assignment`
There was a bad indentantion in the source code and this commit fixes that.
=> [server] Fix update comments

web/server/codechecker_server/api/report_server.py
Earlier the "CodeChecker cmd diff..." command assembled an SQL query which
contained case insensitive pattern matching on the bug hashes with potential
joker characters. The number of these pattern matches is proportional to the
number of reports. This query could cause a timeout in the underlying SQL
server. The solution is checking equality instead of pattern matching.
=> [server] Improvement in a slow query preventing timeout

web/client/codechecker_client/cmd_line_client.py, web/server/codechecker_server/api/report_server.py
In case of plain text output the diff command queries the file contents from
the server. However the source code lines were queried to all reports again and
again. Of course always the same content was returned.
This commit also contains a minor bugfix: if a source file contains a special
character then the utf8 decoder function crashed.
=> [fix][cmd] Faster diff command + utf8 bugfix

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/tests/functional/analyze_and_parse/test_files/Makefile, analyzer/tests/functional/analyze_and_parse/test_files/multi_error_skipped_in_cmd.HPP, analyzer/tests/functional/analyze_and_parse/test_files/multi_error_skipped_in_cmd.cpp, analyzer/tests/functional/analyze_and_parse/test_files/multi_error_skipped_in_cmd.h, analyzer/tests/functional/analyze_and_parse/test_files/multi_error_skipped_in_cmd.output
When `--file` option was given to the CodeChecker analyze or check commands
at the backround a skip handler was created which included only the given
source file and skipped everything. The problem was when we found reports
in header files we skipped these reports too.
With this patch we will not skip results from the header files.
We will keep results in all the header files which have the following extenstions:
```
file.hh
file.H
file.hp
file.hxx
file.hpp
file.HPP
file.h++
file.tcc
```
For mor information see:
https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/Overall-Options.html#index-file-name-suffix-71
=> [analyzer] Fix analyzer --file option

web/server/codechecker_server/api/report_server.py, web/server/codechecker_server/metadata.py
- When the `num_of_report_dir` does not exist in the metadata we tried to
compare NoneType with a number, but Python3 will throw an exception in this case.
This commit will return 0 by default if this key doesn't exist in the metadata.
- This patch also print traceback to the server in case of exception.
=> [server] Fix exception in massStoreRun api

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangtidy/config_handler.py, analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/functional/analyze/test_files/compiler_warning.c
Now the reports starting with clang-diagnostic can be disabled all by
providing this "clang-diagnostic" like a checker group.
=> [cmd] Disable all warnings like checker groups.

analyzer/Makefile, analyzer/tools/build-logger/Makefile.manual
The ldlogger binary was built into a 32bit executable even if only the
64bit build was configured during the build.
resolves #2790
=> [fix][ldlogger] the ldlogger binary was built to 32bit instead of 64bit

docs/README.md, docs/install_macosx.md
- broken link from the readme
- missing space from the markdown heading
resolves #2811
=> [fix][doc] osx install guide

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, docs/analyzer/user_guide.md
Extend the help message of the CodeChecker analyze/check commands, and
improve the user guide with more examples how to use the --config option
of these commands.
=> [analyzer] Add more examples to analyzer --config option

analyzer/codechecker_analyzer/cmd/parse.py, analyzer/tests/functional/analyze_and_parse/test_files/multi_error_suppress_typo.output, codechecker_common/logger.py, codechecker_common/source_code_comment_handler.py, codechecker_common/util.py, web/client/codechecker_client/cmd/store.py, web/client/codechecker_client/cmd_line_client.py, web/server/codechecker_server/api/report_server.py, web/server/tests/unit/test_source_code_comment.py
The speedup is done mainly on the client side after some refactoring:
- parsing the plist files is done by a process pool in parallel,
using all the cpu cores on the machine
- the source files are checked for codechecker review comments
with a process poll using all the available cores
- a quick fast check (with a regex) was done to check if there
are any review comments in a source file and do the more
time consuming parsing in parallel if there is any
(this change was done on the server side too)
- every source file mentioned in the reports should be
opened only once to check for review comments
The error handling was a bit changed to easier propagate back
the spelling errors.
After some measurements the speedup can be seen if there are
more than ~2000 reports, below that report count …
=> [cmd][web] improve storage performance

web/server/codechecker_server/routing.py, web/server/vue-cli/config/webpack.dev.js
We put generated documentation files under the docs dir. If the user
would like to see these files we need to mark docs directory as non
product endpoint. This way if the user opens for example
`{host}:{port}/docs/checker_md_docs/core_division_by_zero.md` in his browser
the md file will be served by the server instead of index.html.
=> [server] Serve static files in docs directory as non product

web/server/vue-cli/.npmrc, web/server/vue-cli/package.json
This commit sets the minimal required node version to >=v10.0.0. If the
node version in the user's machine is older, npm install will terminate
and give a proper error message.
=> [web] Set minial node requirement

web/server/codechecker_server/api/report_server.py, web/server/codechecker_server/metadata.py, web/server/tests/unit/metadata_test_files/v2_multiple.json, web/server/tests/unit/test_metadata_parser.py
Mutliple reports directory can be given for the CodeChecker store command.
We will get metadata.json files from each report directory, we will merge
them together. The problem is that on the server we will put all the
version information to a list not a set so if all the report directory
were analyzed with the same CodeChecker version we will show the same version
multiple times.
This patch will use a set to filter out such duplicates in the version and
in the check command too.
=> [server] Filter out deduplicates from metadata.json

analyzer/codechecker_analyzer/cmd/parse.py
If a source file referenced by a plist does not exist, the CodeChecker parse
was thrown the following exception:
```
TypeError: '>' not supported between instances of 'NoneType' and 'float'
```
This commit solves this problems and check whether the variable is None.
=> [analyzer] Fix parse exception when file doesn't exist

config/config.json
Updating the security profile with all chekcers that have relevant findings on the Sei cert test suite.
Many of them are alpha.
Finding counts on our open source projects are indicated below
"security":[
"alpha.core.PointerSub",0
"alpha.core.PointerArithm",0
"alpha.core.Conversion", 44
"alpha.core.CastToStruct",0
"alpha.cplusplus.PlacementNew",0
"option.cplusplus.VirtualCall",35
"alpha.unix.Chroot",0
"alpha.security.ReturnPtrRange",9
"alpha.security.MallocOverflow",19
"alpha.security.taint.TaintPropagation",4
"alpha.security.ArrayBound",0
"alpha.security.ArrayBoundV2"0,
"alpha.unix.cstring.OutOfBounds",53
"alpha.unix.cstring.BufferOverlap",0
"alpha.unix.PthreadLock",12
"alpha.unix.Stream",218(!)
"alpha.ericsson.cpp.InvariablePtrBranch",0
"alpha.ericsson.IncompatiblePointerCast",0 …
=> adding all sei-cert checkers to the security profile

analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, docs/analyzer/user_guide.md
The ctu analysis is much stable now. The plan is
to remove this feature. First mark the flag as deprecated.
=> [analyzer] mark the --ctu-reanalyze-on-failure flag deprecated

analyzer/codechecker_analyzer/analyzers/analyzer_types.py, analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangsa/config_handler.py, analyzer/codechecker_analyzer/analyzers/clangsa/ctu_autodetection.py, analyzer/codechecker_analyzer/analyzers/clangsa/ctu_manager.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/codechecker_analyzer/pre_analysis_manager.py, analyzer/requirements.txt, analyzer/requirements_py/dev/requirements.txt, analyzer/requirements_py/osx/requirements.txt, analyzer/tests/functional/ctu/test_ctu.py, analyzer/tests/functional/ctu_failure/test_ctu_failure.py, docs/analyzer/user_guide.md
On-demand parsing of the ASTs can be now enabled if the relevant Phabricator patch lands. If enabled, on-the-fly analysis removes the need to create AST dumps, but in turn the compilation database must be provided to Clang. The CTU Index also changes if the option is enabled. The mapping form `function name (USR)` -> `AST dump file` becomes `function name (USR)` -> `path to source file`.
=> [analyzer] Add CTU On-demand analysis support

analyzer/codechecker_analyzer/buildlog/log_parser.py
> Closes #2819
The GCC compiler flag `-fno-extended-identifiers` is not supported by clang.
=> [analyzer] Fix unknown -fno-extended-identifiers clang option

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/tests/functional/analyze/test_analyze.py
Exit with error code if the compilation database given to the CodeChecker analyze
command is an invalid json file.
=> [analyzer] Exit with error code on invalid compilation database

web/server/codechecker_server/api/report_server.py, web/server/vue-cli/src/components/Report/ReportFilter/RemoveFilteredReports.vue, web/server/vue-cli/src/components/Report/ReportFilter/ReportFilter.vue
Unfortunately in the RemoveFilteredReports component the filter variables (runIds,
reportFilter, cmpData) weren't initalized properly so everything in the product were
removed. This commit will initalize this component with these variables and it
also add some logs on the server side about the remove event.
=> [server] Remove only filtered reports

web/server/codechecker_server/metadata.py, web/server/tests/unit/test_metadata_parser.py
In case of old version metadata the analyze command needs to be joined
together before putting it to a list otherwise the database will throw an
exception that we try to insert a list instead of string.
=> [server] Fix storing analyze command

web/server/vue-cli/src/views/Reports.vue
The checker name can be long and using a button doesn't break the content.
To avoid this we can use a span element instead of button and break the content
inside it.
=> [gui] Break word in checker name/message columns

web/server/vue-cli/src/views/ReportDetail.vue
> Closes #2840
Steps to reproduce:
- List reports.
- Turn on uniqueing.
- Click on a specific report to inspect it.
- Press "Back to reports" button.
The `report-hash` value from the URL is not removed so the "Report hash filter"
is filled and only that report is listed. We need to remove this filter option
manually if we want to see the original list.
To solve this problem we remove the `report-hash` value from the URL when the
report hash filter is not set.
=> [gui] Fix different filter option after clicking Back to reports

web/server/vue-cli/src/components/Report/SourceComponent/EditSourceComponentDialog.vue
> Closes #2846
When editing a source component the initial source component will not be
renamed but a new source component will be saved. To solve this problem
we remove the original component and create a new component.
=> [fix][gui] Rename source component

web/server/vue-cli/src/components/Product/ProductConfigForm.vue
Database user name and password are not set properly when adding a new
product with PostgreSQL database. These values should be encoded to base64
on the client side before sending to the server. Also wrong field names were
used: username instead of username_b64 and password instead of password_b64.
=> [gui] Fix adding product with postgresql database

web/server/vue-cli/src/components/Report/ReportFilter/Filters/NewcheckDiffTypeFilter.vue
We call the `getRunResultCount` API function for each diff type to get
diff type filter items even when no run ids or run tags are set. With this
patch we will call these API functions only if the run ids or run tags filters
are set.
=> [gui] Reduce API requests at diff type filter

web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/Items.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/ItemsSelected.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/SelectOption.vue
One item has to be always selected for diff type filter and do not allow
to deselect the actually selected item.
=> [gui] Mandatory selected item for diff type

web/server/vue-cli/src/store/modules/base-filter.js
Set cmpData API parameters to null when only the diff type is set and no
newcheck filter (run ids, tags) is set.
=> [gui][fix] Set cmpData to null when no newcheck filter is set

analyzer/codechecker_analyzer/analysis_manager.py
The process pool needs to be closed and joined otherwise the main wait()
function will wait for infinity in case there is no files to analyze in
a CTU analysis.
=> [cmd] Close and join process pool

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, bin/CodeChecker.py, docs/analyzer/user_guide.md, docs/web/user_guide.md, web/server/codechecker_server/cmd/server.py, web/tests/functional/cli_config/test_store_config.py
Expand environment variables in the config file given by the
--config option.
=> [cmd] Expand environment variables in config file

web/server/codechecker_server/database/run_db_model.py, web/server/codechecker_server/migrations/report/versions/2185167f8568_content_hash_index_for_files.py
If we use PostgreSQL database and we set the query timeout to 2 minutes the
database cleanup will be timed out when the server tries to remove unused
files and the database is to big.
The reason is that the database sequentially scanned the database to look
for foreign key constraints. To solve this problem we add index to the
content hash column on files table.
=> [db] Add index for content hash column on files table

analyzer/codechecker_analyzer/analyzer_context.py, analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/analyzers/config_handler.py, analyzer/codechecker_analyzer/host_check.py, analyzer/tests/unit/test_checker_handling.py, config/package_layout.json
The resource directory of Clang (lib/clang/<version>) was at a custom
location earlier inside CodeChecker package. However, it is found
relatively to "clang" binary by Clang, so it is not needed anymore to
store its location in our config file.
=> [analyzer] Clang resource dir not used in CodeChecker

web/server/codechecker_server/routing.py, web/server/codechecker_server/server.py, web/server/tests/unit/test_request_routing.py
"TypeError: 'NoneType' object is not iterable" exception was thrown
by the server if an invalid product endpoint was in the url.
In that case the split_client_POST_request function returned
only one None which could not be unpacked to multiple values
at the caller.
=> [server] improve endpoint handling

web/server/vue-cli/src/components/Report/ReportFilter/Filters/DetectionDateFilter.vue, web/server/vue-cli/src/views/RunHistoryList.vue
- We need to round the fix date upward because we will send the dates to the
server without milliseconds.
- Set detection date to the minimum date and the fix date to the maximum date
from the selected run history items during diff.
=> [gui] Fix setting detection date filter

web/server/codechecker_server/server.py, web/tests/functional/products/test_config_db_share.py
When a product is removed but a server is still connects to this product
we will try to disconnecting it by removing from the local cache.
We will iterate over the `self.__products` dictionary keys and we will
remove this product from the dictionary. In Python 2 it worked but in
Python 3 the following exception was thrown:
```
RuntimeError: dictionary changed size during iteration
```
The problem is that in Python 2 the `keys` makes a copy of the keys
what we can iterate over while modifying the dictionary. In Python 3
`keys` returns an iterator instead of a list. To solve this problem
we will create a force copy from the keys.
=> [server][fix] Fix disconnection product after remove

analyzer/codechecker_analyzer/analysis_manager.py
Previously if we analyzed a project and we gave a skip file and there was a
compiler failure, we didn't skipped the reports from the header files.
This patch solves this problem and skips reports from the header files on
compiler failures too.
=> [analyzer] Skip results with skip file on failure

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/codechecker_analyzer/cmd/parse.py, docs/analyzer/user_guide.md
CodeChecker analye|check|parse commands also support
CC_SEVERITY_MAP_FILE environment variable and this was not documented on
their help page.
=> [doc] Documentation about CC_SEVERITY_MAP_FILE environment variable

analyzer/tests/functional/config/test_config.py, bin/CodeChecker.py
With this change options specified on the command line after the --config option
will override options specified in the config file.
=> [cmd] Override --config file options from command line

web/server/vue-cli/src/components/Report/ReportFilter/Filters/DetectionDateFilter.vue
There are multiple scenarios when the selected filter items list of the detection
date filter need to be cleard:
- When the user clears the filter with the thrash icon.
- When the user clears the filters with the Clear all filters button.
- When the user changes the input one of the detection date filter input.
This way for example if the user selects the Today date and clear or change the
date filter he will be able to select the Today date again.
=> [gui] Clear detection date selected filter items on change

web/server/vue-cli/e2e/pages/report.js, web/server/vue-cli/e2e/specs/reports.js, web/server/vue-cli/src/components/Report/ReportFilter/Filters/BugPathLengthFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/DetectionDateFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/DetectionStatusFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/Layout/FilterToolbar.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/ReportHashFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/SelectOption.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/SelectedToolbarTitleItems.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/index.js, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SourceComponentFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/ReportFilter.vue
We already have many report filters on the UI and it is hard to see
through where is the filter what the user actually want to set. For
this reason with this patch we will show each filter in an expansion
panel and every filter will be closed by default. We will also show
the selected filter items in the filter header bar which will be trimmed
when too many filter items are selected.
Screenshot:
=> [gui] Show filters in expansion panels

analyzer/codechecker_analyzer/buildlog/log_parser.py
We should rather consider build actions containing -MD flag as
compilation because besides emitting precompilation infos, it also
accomplishes compilation.
=> [cmd] Revert -MD flag skip

web/server/vue-cli/src/views/Statistics.vue
Allow the same filters in the statistics page as in the reports page
=> [gui] Allow diff and review status filters in statistics page

web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/Items.vue
Some of the report filters support custom search with * quantifiers.
If the user types something to the input box then a custom filter item
is appeared with a regex icon at the top of the filter items which allows the user
to filter by wildcard pattern. This is actually not a regex expression so
the regex icon is a little bit misleading. To solve this problem this patch
will remove this icon.
=> [gui] Remove regex icon from the report filters

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/parse.py, analyzer/tests/functional/config/test_config.py, bin/CodeChecker.py, codechecker_common/cmd_config.py, config/codechecker.json, docs/analyzer/user_guide.md, docs/web/user_guide.md, web/client/codechecker_client/cmd/store.py, web/server/codechecker_server/cmd/server.py
Add support to use a config file by the parse subcommand.
The subcommand arguments can be saved and used from the
CodeChecker config file.
Common config file checking and parsing parts were
moved to the codechecker_common module because
the analyzer and the server parts use the same code.
=> [analyzer] config file option for the parse subcommand

web/server/vue-cli/src/App.vue, web/server/vue-cli/src/views/ProductDetail.vue
Use vue `keep-alive` built-in component to cache component states.
So for example when navigating from the Runs page to the Reports page
the state of the Runs page component is saved. So once we go back to the
Runs page component the user will see the previous state.
This will also help us to reduce API requests to the server.
=> [gui] Keepalive component states

docs/web/user_guide.md, web/api/js/codechecker-api-js/package.json, web/api/js/codechecker-api-node/package.json, web/api/py/codechecker_api/setup.py, web/api/py/codechecker_api_shared/setup.py, web/api/report_server.thrift, web/client/codechecker_client/cmd/cmd.py, web/client/codechecker_client/cmd_line_client.py, web/requirements.txt, web/requirements_py/db_pg8000/requirements.txt, web/requirements_py/db_psycopg2/requirements.txt, web/requirements_py/dev/requirements.txt, web/requirements_py/osx/requirements.txt, web/server/codechecker_server/api/report_server.py, web/server/vue-cli/e2e/pages/report.js, web/server/vue-cli/e2e/specs/history.js, web/server/vue-cli/e2e/specs/reports.js, web/server/vue-cli/package-lock.json, web/server/vue-cli/package.json, web/server/vue-cli/src/components/DateTimePicker.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/DetectionDateFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/FixDateFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/index.js, web/server/vue-cli/src/components/Report/ReportFilter/ReportFilter.vue, web/server/vue-cli/src/views/RunHistoryList.vue, web/tests/functional/report_viewer_api/__init__.py, web/tests/functional/report_viewer_api/test_report_filter.py
The old detection date filter options were not only filtered the detection/fix
dates but it is also depend on the detection status filter.
- With this patch new filter options will be introduced in the UI and in the
command line (--detected-before/--detected-after).
- The API and the server are able to filter by fix dates. These filters are not
shown in the UI and in the command line.
- The detection status dependency from the detection date filter is removed.
- New test cases are introduced.
=> [web] Introduce new detection date filter options

web/server/vue-cli/e2e/specs/reportDetail.js, web/server/vue-cli/src/components/Report/Report.vue, web/server/vue-cli/src/components/Report/SelectSameReport.vue
In the report detail view the same report hash drop down list contains
the actual report too. For this reason we rename the label to Found in.
=> [gui] Rename Also found in to Found in

web/server/vue-cli/src/views/Reports.vue
In the Reports page always show the expand button (down arrow) that will
show the other bugs with the same hash.
=> [gui] Always show down arrow, that will show the other bugs with the same hash

analyzer/codechecker_analyzer/analyzer.py, analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py
The list of applied checkers can be configured by -e, -d flags,
CodeChecker config files, etc. It is hard to see which checkers are
actually enabled during the analysis. Now the enabled checkers are
listed at the beginning of the analysis.
=> [cmd] Logging enabled checkers at the beginning of analysis

web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py
Previously the `Verified` label in the generated gerrit review file
was always be set to `1` which enables submission.
This commit changes this behaviour and if the report count is not
zero it will set this label to `-1` (similar to `Code-Review` label)
so it will block the submission.
=> [cmd] Set verified label properly for gerrit output

web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/Items.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/ItemsSelected.vue
Set title attribute of the filter items so on hover it will show the full
title in a tooltip even if title of the filter item is truncated.
=> [gui] Set title attribute of filter items

docs/web/user_guide.md, web/client/codechecker_client/cmd/cmd.py, web/server/vue-cli/src/assets/userguide/userguide.md, web/server/vue-cli/src/components/Report/ReportFilter/Filters/DetectionStatusFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/ReviewStatusFilter.vue, web/server/vue-cli/src/components/TooltipHelpIcon.vue, web/server/vue-cli/src/views/Reports.vue
> Closes #2907
Rename `Review status` to `Latest review status` and `Detection status`
to `Latest detection status` and show a tooltip icon beside the filters
which describes the filters.
=> [gui] Rename review status and detection status texts

analyzer/tests/functional/ctu/test_ctu.py, analyzer/tests/functional/ctu_failure/test_ctu_failure.py, analyzer/tests/libtest/ctu_decorators.py, analyzer/tests/libtest/decorators.py
Custom decorators should use functional.wraps for nose test runner to
detect decorated tests. CTU related decorators are extracted, removing
duplication in test suites ctu and ctu_failure.
=> [test] Fix custom decorator handling

web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/SelectOption.vue
Vue doesn't automatically bind functions passed to props property with
any Vue instance. For this reason we need to use this computed property
instead of apply function where we bind this to its parent Vue instance.
=> [fix] Fix applying filter options

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/ctu/test_ctu.py, analyzer/tests/functional/ctu_failure/test_ctu_failure.py, docs/analyzer/user_guide.md
Make the default mode of loading AST-s during CTU analysis
'parse-on-demand' in case the Clang SA used supports it.
Note that if there is no support for the `parse-on-demand` feature then the default `load-from-pch` mode is used instead. This could be the case if upstream Clang 10 or lower is used.
=> [analyzer] Make on-demand AST loading mode default

tools/plist_to_html/plist_to_html/PlistToHtml.py, tools/plist_to_html/plist_to_html/static/css/statistics.css, tools/plist_to_html/plist_to_html/static/statistics.html
In plist2html generator the severity is added to the static HTML
statistics page.
=> [plist2html] Adding severity to statistics page

web/server/codechecker_server/api/report_server.py, web/server/vue-cli/config/webpack.dev.js, web/server/vue-cli/config/webpack.prod.js, web/server/vue-cli/src/components/Layout/TheHeader.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SourceComponentFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/ReportFilter.vue, web/server/vue-cli/src/components/Report/SourceComponent/SourceComponentTooltip.vue, web/server/vue-cli/src/components/Report/SourceComponent/index.js, web/server/vue-cli/src/components/Statistics/BaseStatistics.vue, web/server/vue-cli/src/components/Statistics/CheckerStatistics.vue, web/server/vue-cli/src/components/Statistics/CheckerStatisticsTable.vue, web/server/vue-cli/src/components/Statistics/ComponentStatistics.vue, web/server/vue-cli/src/components/Statistics/ComponentStatisticsTable.vue, web/server/vue-cli/src/components/Statistics/ReportDiffCount.vue, web/server/vue-cli/src/components/Statistics/SeverityStatistics.vue, web/server/vue-cli/src/components/Statistics/SeverityStatisticsTable.vue, web/server/vue-cli/src/components/Statistics/StatisticsHelper.js, web/server/vue-cli/src/components/Statistics/index.js, web/server/vue-cli/src/index.html, web/server/vue-cli/src/router/index.js, web/server/vue-cli/src/views/Statistics.vue
- Show statistics in separate tabs.
- Component statistics.
- Compare statistics.
- Improve compare queries by using subqueries.
=> [gui][server] Statistics

web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineRunFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/ReportFilter.vue
- `initByUrl` is an async function which returns a Promise. Unfortunatelly
in the Run Filter it is called an async function (setSelectedItems) but we
forgot to wait for it. This way the filters are not initalized properly.
For example when we opened a product and clicked on a run name the reports
are not filtered by run name.
- `clear` functions can be async functions so we need to wait for them
before we update the report filters when clearing all reports filter.
=> [fix] Wait while filters are initalized and cleared properly

web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineRunFilter.vue
The `getTags` function in the run filter component expects two parameters:
tag ids and tag names. In one place this function was called in a wrong way:
only one parameter was given and it was a string (run name). This commit
solves this problem.
=> [fix] getTags function is called in a wrong way in the run filter

analyzer/codechecker_analyzer/buildlog/log_parser.py, analyzer/codechecker_analyzer/cmd/analyze.py
If different clang binaries are used for compilation and analyisis
collect the implicit include paths from the clang doing the
compilation with can be used by the clang doing the analysis.
It is possible that the clang doing the compilation was compiled
differently (using std lib headers from a non standard place)
compared to the clang which is doing the analysis.
In this case the clang executing the analysus tries to use
the system headers from the host which might not be compatible
with the project which was built.
=> [analyzer] collect implicit include paths in case of clang mismatch

analyzer/codechecker_analyzer/buildlog/log_parser.py
If for some reason the analyzer version is not set
assume that the compiler used to compile the project
and the analyzer used for analysis are not the same.
If the analyzer version could not be collected for
some reason there could be problems
later during the analysis too.
=> [fix] handle case when the analyzer version is not set

web/server/vue-cli/src/components/Statistics/CheckerStatisticsTable.vue, web/server/vue-cli/src/components/Statistics/ComponentStatisticsTable.vue, web/server/vue-cli/src/components/Statistics/SeverityStatisticsTable.vue
- Show a total reports row in each statistics table footer.
- Fix client side ordering (each item is an object which has a count
field so it should be used to identify the columns).
=> [gui] Show Total reports in the statistics table footer

web/tests/functional/report_viewer_api/test_report_filter.py
At the begining of the detection date filter tests we get one report from
the database based on the first two runs. The order of the result was
unspecified on the API call so the default order was by severity.
It was possible that on the first test run the report related to the
first run was queried from the database but on the second test run the
report related to the second run was queried. So this cause a
non-deteministic test run.
=> [test] Fix detection date filter test

web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_local/test_diff_local.py
If a source file is missing related to a report at the CodeChecker cmd diff
command, give a warning to the user.
=> [cmd] Handle missing source file at diff command

web/client/codechecker_client/cmd_line_client.py
The output will not be a valid json, csv or other format if there
is a log message at the end of them.
=> remove info logs because they can mess up the json and other outputs

web/client/codechecker_client/cmd_line_client.py
Reverts Ericsson/codechecker#2931
There should be no problem if these log messages are correctly sent to the stderr and do not mess up
the json and other output formats.
=> Revert "remove info logs because they can mess up the json and other outputs"

analyzer/tests/functional/fixit/test_fixit.py
`fixit` subcommand can get a JSON file from standard input which
describes which fixits should be applied. In Python there is a function
named os.isatty() which determines whether the input arrives from stdin.
For some reason running tests in Jenkins always give some (empty) string
to the process on standard input, so tests which assume no standard
input fail. Empty standard input is equivalend with an empty JSON list,
so we pass it to `fixit` commands explicitly.
=> [test] Fix fixit test in Jenkins

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/cmd/checkers.py, docs/analyzer/user_guide.md, docs/usage.md
CodeChecker checkers now shows configuration options for all available
checks instead of only default-enabled ones.
=> [clang-tidy][doc] Show config for all checks

scripts/debug_tools/prepare_all_cmd_for_ctu.py, scripts/debug_tools/prepare_analyzer_cmd.py, scripts/debug_tools/prepare_compiler_info.py
The debug_tools did not work with current version of files got from
clang and tu_collector. At least part of the problems is fixed.
The problems are related to file format changes and name of clang executable.
=> [fix] Fix bugs in debug_tools scripts

web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineRunFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineTagItems.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/CheckerMessageFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/CheckerNameFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/FilePathFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/Items.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/SelectOption.vue
> Closes #2862
In the report filter tooltips we show only 10 items for filters which
support searching by using * quantifiers. To identify that there can
be more results we show the number of filtered items at the bottom of
the filter items.
Screenshot:
=> [gui] Show number of filtered items in the tooltip

config/checker_severity_map.json
Reusing "modernize-use-default-member-init" severity but we could move it to LOW
as it has an impact on performance
=> Set severity for cppcoreguidelines-prefer-member-initializer

analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/buildlog/build_action.py, analyzer/codechecker_analyzer/buildlog/log_parser.py, analyzer/tests/unit/test_option_parser.py
The compilation target which could be different from the default
compiler target was not correctly parsed from the compilation command.
This could cause problems in case the project was cross compiled
to a different target.
The default compilation target is collected but that might be
different from the target used in the compile command.
resolves #2916
=> [analyzer] parse the compilation tag separately

web/codechecker_web/shared/convert.py, web/server/codechecker_server/api/report_server.py, web/tests/functional/report_viewer_api/test_get_run_results.py, web/tests/projects/cpp/call_and_message.cpp
If for some reason a file content was stored with a content
which can not be decoded to utf-8 ignore those characters.
New tests were added where a source file was saved with latin1
encoding to see if the file content can be loaded back
without any execeptions.
The characters which can not be encoded are ignored.
=> [server] ignore encoding errors for source file content

codechecker_common/logger.py
The log level verbosity goes from:
info -> debug_analyzer -> debug
The printed order should reflect that.
resolves #2922
=> [refactor] reorder how the log levels are printed

web/server/vue-cli/src/components/Report/ReportFilter/Filters/UniqueFilter.vue
- Use the TooltipHelpIcon to show the help icon beside the unique report filter.
- Mention that the same bug may appear in different runs too.
=> [gui] Refactor unique reports helper icon

web/server/codechecker_server/api/report_server.py, web/tests/functional/report_viewer_api/__init__.py, web/tests/functional/report_viewer_api/test_report_counting.py, web/tests/functional/report_viewer_api/test_report_filter.py, web/tests/projects/cpp/Makefile, web/tests/projects/cpp/project_info.json
Checkers that start with `clang-diagnostic-` are compiler warnings and these
are not in the metadata.json file when storing results. We didn't handle this
use case so we were not able to set analyzer names for these checkers previously.
This commits solves this problem and set the analyzer name field for these
checkers too.
=> [server] Set analyzer name for clang-diagnostic checkers

analyzer/tests/functional/fixit/test_fixit.py
touch() function call is not working properly in all environments, so
now the test file's timestamp is explicitly modified in fixit test.
=> Fix in fixit test related to file modification time

docs/README.md, docs/supported_code_analyzers.md, tools/report-converter/README.md, tools/report-converter/codechecker_report_converter/cli.py, tools/report-converter/codechecker_report_converter/smatch/__init__.py, tools/report-converter/codechecker_report_converter/smatch/analyzer_result.py, tools/report-converter/codechecker_report_converter/smatch/output_parser.py, tools/report-converter/tests/unit/smatch_output_test_files/files/sample.c, tools/report-converter/tests/unit/smatch_output_test_files/sample.expected.plist, tools/report-converter/tests/unit/smatch_output_test_files/sample.out, tools/report-converter/tests/unit/test_smatch_parser.py
Smatch report converter tool for parsing Smatch output of kernel sources
=> [report-converter] Smatch Parser 

docs/web/authentication.md, docs/web/user_guide.md, web/client/codechecker_client/cmd/store.py, web/client/codechecker_client/credential_manager.py, web/codechecker_web/shared/env.py, web/server/vue-cli/e2e/init.db.js
Some CI environments are not allowed to create files outside of their
designated workspace. This might include the home directory.
This commit allows users to overwrite the hardcoded path and name of
the session file by setting the CC_SESSION_FILE environment variable.
I didn't know where - if any - to put tests. If required, please tell me what kind of tests you'd like to see and where I should put them. I only tested locally and in our CI environment and it works as expected.
=> feat(credential_manager): allow users to overwrite location of session file

docs/README.md, docs/supported_code_analyzers.md, tools/report-converter/README.md, tools/report-converter/codechecker_report_converter/cli.py, tools/report-converter/codechecker_report_converter/kerneldoc/__init__.py, tools/report-converter/codechecker_report_converter/kerneldoc/analyzer_result.py, tools/report-converter/codechecker_report_converter/kerneldoc/output_parser.py, tools/report-converter/tests/unit/kerneldoc_output_test_files/files/sample.c, tools/report-converter/tests/unit/kerneldoc_output_test_files/sample.expected.plist, tools/report-converter/tests/unit/kerneldoc_output_test_files/sample.out, tools/report-converter/tests/unit/test_kerneldoc_parser.py
Kernel-Doc report converter tool for parsing Kernel-Doc output of kernel sources
=> [report-converter] Kernel-Doc Parser

tools/report-converter/README.md, tools/report-converter/codechecker_report_converter/coccinelle/output_parser.py, tools/report-converter/tests/unit/coccinelle_output_test_files/sample.expected.plist
The following pull request attaches the name `coccinelle.` before the checker name for making it easy for the users to identify the tool name easily as mentioned here: https://github.com/Ericsson/codechecker/pull/2968#issuecomment-713665718
=> [report-converter][fix] Coccinelle checker fix

tools/report-converter/codechecker_report_converter/smatch/output_parser.py, tools/report-converter/tests/unit/smatch_output_test_files/sample.expected.plist
The following pull request does not truncate the `smatch.` in front of the checker name, thus making it easy to identify the tool name as mentioned here: https://github.com/Ericsson/codechecker/pull/2968#issuecomment-713665718
=> [report-converter][fix] Smatch checker fix

web/client/codechecker_client/source_component_client.py, web/server/codechecker_server/api/report_server.py, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SourceComponentFilter.vue, web/server/vue-cli/src/components/Report/SourceComponent/ListSourceComponents.vue, web/server/vue-cli/src/components/Report/SourceComponent/SourceComponentTooltip.vue, web/server/vue-cli/src/components/Statistics/ComponentStatistics.vue, web/tests/functional/component/test_component.py
Introduce a default auto-generated other component that contains files
that are uncovered by the rest of the components.
=> [web] Introduce a default other component

bin/CodeChecker.py
Previously we handled the use case when no subcommand is given by catching
an Attribute exception (#2600). We cought this exception in our main script and
we print the help message of the CodeChecker command.
This is bad because the CodeChecker code can thrown this type of exception
a couple of ways. For example if we call a function on a NoneType variable.
For this reason we will print the help message of the given command only
if no subcommand is given.
=> [cmd] Catch and print every exceptions in the main script

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/pre_analysis_manager.py
Wrap analyzer options dictionary in multiprocessing manager proxy object to
ensure safe sharing.
=> [fix] Fix concurrency error by sharing config dict

.travis.yml
`thrift-compiler` is not required to build CodeChecker anymore so we can
remove it from the travis dependency list.
=> [travis] Remove thrift-compiler dependency

docs/web/user_guide.md, web/client/codechecker_client/cmd/cmd.py, web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineOpenReportsDateFilter.vue
- Rename open reports date filter to "Outstanding reports on a given date"
on the GUI.
- Add another name (--outstanding-reports-date) for the --open-reports-date
option in the CLI.
=> [web] Rename open reports date filter

web/server/vue-cli/src/views/Reports.vue
In unique mode the line number is not available for reports. This patch
will handle this use case and will not show the Line label beside the
file path in unique mode.
=> [gui] Show reports line number only in non unique mode

docs/web/authentication.md, web/server/codechecker_server/auth/cc_ldap.py, web/server/config/server_config.json
When searching for a user in the LDAP directory it is possible that
multiple DNs are found for a user. To select a prefered DN the
`user_dn_postfix_preference` value can be set at the server config and
it will return the first DN where the end of the DN matches
the user_dn_postfix_preference value.
=> [server][auth] user dn postfix preference

analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzers/config_handler.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/analyze/test_analyze.py, docs/analyzer/user_guide.md
There is a bugfix and a change in the two commits.
The bugfix is for printing the enabled checkers and the change is to remove more groups from the enable-all configuration.
=> Less checkers in enable all

web/server/vue-cli/src/components/Statistics/Overview/ComponentSeverityStatistics/ComponentSeverityStatistics.vue, web/server/vue-cli/src/components/Statistics/StatisticsHelper.js
Use `getSeverityCounts` and `getReviewStatusCounts` API functions to get
severity and review status statistics for a component instead of calling
separate API functions for each column.
For example in case of 1 server setup it will reduce the time to fetch data
from ~24668 milliseconds to ~8311 milliseconds.
This way the Checker statistics and the Product overiew pages will load much
faster than before.
=> [gui] Improve component statistics page load

analyzer/codechecker_analyzer/cmd/parse.py, analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py
> Closes #3019
- Create the output directory if it doesn't exist.
- Do not write empty reports.json file in case of HTML generation.
- Add new test case for HTML generation.
=> [cmd] Fix HTML generation of the CodeChecker parse command

analyzer/tests/functional/fixit/test_fixit.py
In some environments there may be a too old gcc standard library which
results compiler error in the compilation of the most basic source
files. So we use g++ with -std=c++98 flag in order to meet the least
requirements.
=> [test] Use -std=c++98 standard in fixit tests

web/tests/libtest/codechecker.py
after the exit code changes exit code 1 means there is a codechechecker
error other error codes mean if there are reports or there was
some analysis error
=> fix exit code check in the tests

analyzer/tools/statistics_collector/codechecker_statistics_collector/post_process_stats.py
If a header file is included into multiple source files in a C code,
its lines are counted multiple times when processing the statistics.
This leads to false positives if e.g. the return value of a function
is used in a header but not in the source files. This patch fixes it
by collecting all lines to a set first and then processing the set.
=> [analyzer][fix] Unique lines when collecting statistics

web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineRunFilter.vue
In the `BaselineRunFilter` component we called the `getRunIds` function
through the current instance but the function was moved to the `ccService`
module.
This way we were not be able to select the first item in the run list when we searched
by a regular expression.
=> [gui] Fix undefined getRunIds function in baseline run filter

docs/README.md, docs/supported_code_analyzers.md, tools/report-converter/README.md, tools/report-converter/codechecker_report_converter/cli.py, tools/report-converter/codechecker_report_converter/sphinx/__init__.py, tools/report-converter/codechecker_report_converter/sphinx/analyzer_result.py, tools/report-converter/codechecker_report_converter/sphinx/output_parser.py, tools/report-converter/tests/unit/sphinx_output_test_files/files/sample.rst, tools/report-converter/tests/unit/sphinx_output_test_files/sample.expected.plist, tools/report-converter/tests/unit/sphinx_output_test_files/sample.out, tools/report-converter/tests/unit/test_sphinx_parser.py
Sphinx report converter tool for parsing Sphinx output of kernel sources
=> [report-converter] Sphinx parser

Makefile, analyzer/Makefile, analyzer/tests/Makefile, analyzer/tools/merge_clang_extdef_mappings/Makefile, analyzer/tools/statistics_collector/Makefile, codechecker_common/tests/unit/Makefile, tools/codechecker_report_hash/Makefile, tools/plist_to_html/Makefile, tools/report-converter/Makefile, tools/tu_collector/Makefile, web/Makefile, web/api/Makefile, web/tests/Makefile
Requirements:
* make (installed with choco, GNU Make 4.3)
* windows git tools in path (for cp, ln and few other tools)
CPython in windows doesn't have 3 postfix in the binary so extra
environment/make variable "PYTHON_BIN" was introduced to tell make
the "correct" python interpreter.
Observations:
$(shell pwd) which was used to detect current directory didnt work as-is because it reports posix path if -W flag is not given, however, someone that triggered an error so defaulting to use ${CURDIR}
=> Makefile updated to work in windows.

web/server/vue-cli/src/components/Report/Report.vue
> Closes #1522
Set the focus to the search bar when pressing Ctrl-F in the Report detail view.
=> [gui] On search event set the focus to the search bar

web/server/vue-cli/src/components/Layout/TheHeader.vue, web/server/vue-cli/src/components/Product/ProductNameColumn.vue, web/server/vue-cli/src/components/Product/index.js, web/server/vue-cli/src/views/Products.vue
Add some links for each product which allow us to jump to
the runs / reports or to the statistics page of the product.
Screenshot:
=> [gui] Add shortcut links to the product page

Makefile, analyzer/Makefile, analyzer/tools/merge_clang_extdef_mappings/Makefile, analyzer/tools/statistics_collector/Makefile, docs/README.md, tools/codechecker_report_hash/Makefile, tools/plist_to_html/Makefile, tools/report-converter/Makefile, tools/tu_collector/Makefile, web/Makefile
Installing some dependencies (psutil) might fail if the virtual environment
was created with the virtualenv command.
See: https://stackoverflow.com/questions/60423668/psutil-fails-to-pip-install-inside-python3-virtualenv-fatal-error-python-h-no
=> create venv with interpreter instead of the virtualenv command

web/server/codechecker_server/api/authentication.py, web/server/codechecker_server/auth/cc_ldap.py
plus minor logging improvements.
=> Fix LDAP authentication exception

web/api/Makefile
The thrift api stubs are generated by using docker. If the generation
is done we can remove the docker container automatically to not mess up
our system with exited containers.
=> [web] Remove docker container after API generation is done

docs/README.md
=> [doc] Show command line features in the main readme

web/api/js/codechecker-api-js/package.json, web/api/js/codechecker-api-node/package.json, web/api/py/codechecker_api/setup.py, web/api/py/codechecker_api_shared/setup.py, web/api/report_server.thrift, web/requirements.txt, web/requirements_py/db_pg8000/requirements.txt, web/requirements_py/db_psycopg2/requirements.txt, web/requirements_py/dev/requirements.txt, web/requirements_py/osx/requirements.txt, web/server/codechecker_server/api/report_server.py, web/server/vue-cli/package-lock.json, web/server/vue-cli/package.json, web/tests/functional/comment/test_comment.py
The command `CodeChecker cmd results` was not able to fetch all the comments appropriately from the `CodeChecker server`. In many runs, the comments were displayed as `""`, thus making it impossible to use Codechecker as an exporter.
Comments are fetched and formatted appropriately. The comments are fetched with the command
```sh
CodeChecker cmd results <run_name> -o json --details
```
Fixes #3005
=> [api][server] Fix comments for CodeChecker cmd results

docs/web/user_guide.md, web/client/codechecker_client/cmd/cmd.py, web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py
- the html report converted summary was piped into the json file too
which made it not valid
- the other main change is for the other formats (json, gerrit, codeclimate)
if an export directory is set output files will be generated if not
the results are printed to the stdout but only if one format was selected.
resolves #3022
=> [fix][refactor] fix json and html output when both formats are selected

web/server/vue-cli/src/views/ReportDetail.vue, web/server/vue-cli/src/views/Reports.vue
The server will remove reports from the database which have the same
report hash on run update. This can cause problem, when the user saves
the URL which contains a report id which is actually removed from
the database.
For this reason we will save the report hash in the URL and if
no report is found with the report id in the database we will falback
and search the report by report hash.
If the report hash is not in the url or the report can not be found
by the report id or report hash we will display this information to
the user.
Screenshot:
=> [gui] Handle missing report

web/server/codechecker_server/api/report_server.py
Review status is a shared table among runs. When multiple runs
are stored in parallel, there may be a race condition in updating
review status fields. The most common reason of deadlocks is
changing only the date to current date. This condition checks if
something else is also changed other than dates.
=> [server] Change review status date only if necessary

docs/web/authentication.md, web/server/codechecker_server/auth/cc_ldap.py
If LDAP authentication is used in the server and the LDAP server
connection is using LDAPS, then reject the connection if the certificate
is not trusted by the system.
This can be overriden by setting the environment variable
LDAPTLS_REQCERT=never just like in the ldapsearch command.
NOTE: The option used before to skip the SSL certificate verification
was OPT_X_TLS_ALLOW, which is documented in python-ldap as "used
internally by slapd server". Thus the one used now is OPT_X_TLS_NEVER.
Resolves #3082
=> [server] Verify TLS certificate in LDAPS connections

analyzer/codechecker_analyzer/analyzers/clangsa/ctu_manager.py, analyzer/tests/functional/ctu/test_ctu.py, analyzer/tests/functional/ctu/test_files/complex_buildlog.json, analyzer/tests/libtest/env.py
The config file 'invocation-list.yml' may contain line breaks inside
list items. However, this is not properly supported by the analyzer YAML
parser. This fix sets the line width parameter to very high value.
=> [analyzer][fix] Invocation list YAML config no longer break lines

docs/web/authentication.md, web/server/codechecker_server/session_manager.py, web/server/config/server_config.json, web/tests/functional/authentication/test_authentication.py, web/tests/libtest/env.py
This creates new groups that users can belong to if their username
matches some regular expression.
Makes it possible to have all users belonging to a group in order to set
default permissions for products.
Closes #3072.
=> [server] Add regex_groups authentication method

web/server/codechecker_server/server.py
> Closes #3047
The current log output of the server outside verbose mode is not useful
because everything that is related to CodeChecker is accessed through
`/CodeCheckerService`.
This patch will log the API function names too in the following format:
```
[INFO 2020-11-24 11:12] - 127.0.0.1:39506 -- [Anonymous] POST /AdjacentParams/v6.35/CodeCheckerService@getReport
```
=> [server] Print API function name in server logs

codechecker_common/plist_parser.py
_PlistParser.__init__() constructor in plistlib module requires one parameter,
but we passed two.
=> [cli] Bad parameter number to _PlistParser

codechecker_common/output/codeclimate.py, codechecker_common/plist_parser.py, codechecker_common/report.py, web/client/codechecker_client/cmd_line_client.py, web/client/codechecker_client/report_type_converter.py, web/client/tests/unit/test_report_converter.py, web/server/codechecker_server/api/report_server.py, web/server/tests/unit/test_plist_parser.py, web/server/tests/unit/test_report_path_hash.py, web/server/tests/unit/test_store_handler.py
>Closes #3114
For the `plistlib.dump` function a file path was given instead of a
file object.
=> [analyzer] Fix parse and update plist file

web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py
1. Analyze a project to "reports" dir.
2. Store it in run named "hello"
3. CodeChecker cmd diff -b reports -n hello --resolved
This scenario shows all reports which is a bad behavior.
When server side fetches a set of reports from database, it uses a filter
object. If "reportHash" filter attribute is empty list, it means that no
report hash was selected for diffing, i.e. it takes all reports into
account.
=> [client] Diff "resolved" reports of remote to local

web/server/vue-cli/src/components/Statistics/Checker/CheckerStatistics.vue
Wrong field name was used in the CheckerStatistics component and
in compare mode wrong number were shown.
=> [gui] Fix checker statistics difference

web/server/vue-cli/src/components/Statistics/BaseStatisticsTable.vue
If we are for example in the checker statistics page and we set some
filter (run, checker name) and we click on a link we need to keep
the previous run/checker name filters to filter the report.
So all filters set in the statistics view should follow to the Reports view.
=> [gui] Fix links in statistics tables

web/server/codechecker_server/api/report_server.py, web/tests/functional/component/test_component.py
We joined the source component filter values with OR expression
even if the component value was contained only excludes.
E.g:
-*/a.cpp
-*/b.cpp
This patch will fix this problem and if a source component value
contains only skips it will join the value with AND expression.
=> [server] Fix multiple negative file path in source component filter

web/server/codechecker_server/api/report_server.py
Previously all the statistics were queried for the given run ids and sometimes
not the latest one was shown on the GUI for a run. The reason was that no sorting
option was specified for the query and the order was random.
To solve this problem this patch rewrites the whole query part by using a subquery
and it will get statistics for the specific history ids.
=> [server] Fix getting analyzer statistics for runs

web/client/codechecker_client/thrift_call.py
In case of API call exception the client will try to log the API function
name with the parameters. It is possible that one of the argument is too
large to log the full content of it (for example the 'b64zip' parameter of the
'massStoreRun' API function). For this reason we have to truncate the arguments.
=> [client] Truncate arguments before logging it

docs/README.md, docs/web/user_guide.md, web/api/js/codechecker-api-js/package.json, web/api/js/codechecker-api-node/package.json, web/api/py/codechecker_api/setup.py, web/api/py/codechecker_api_shared/setup.py, web/api/report_server.thrift, web/client/codechecker_client/cmd/cmd.py, web/client/codechecker_client/cmd_line_client.py, web/client/codechecker_client/helpers/results.py, web/requirements.txt, web/requirements_py/db_pg8000/requirements.txt, web/requirements_py/db_psycopg2/requirements.txt, web/requirements_py/dev/requirements.txt, web/requirements_py/osx/requirements.txt, web/server/codechecker_server/api/report_server.py, web/server/vue-cli/package-lock.json, web/server/vue-cli/package.json, web/tests/functional/export_import/__init__.py, web/tests/functional/export_import/test_export_import.py
An exclusive command for getting the comments and review statuses for a particular run, in JSON format from CodeChecker Server.  
Multiple run names can be provided for exporting the data simultaneously.
If no run name is provided, by default, data is exported for all the runs
```sh
CodeChecker cmd export -n <run_name-1> <run_name-2>...  2>/dev/null | python -m json.tool > <run_name>.json
```
A command for importing comments and review statuses from a json file into codechecker server
```sh
CodeChecker cmd import -i <path_to_json_file>.json
```
Fixes #3076
=> [cmd][api] Exporter/Importer command for CodeChecker cmd

web/server/codechecker_server/api/report_server.py
The storage API request (`massStoreRun`) is a very heavy operation and most
of the cases when the user stores huge amount of reports to the database it
takes too much time (10-20 minutes) to perform this operation. For this reason
in this patch we will insert some info log to see where the store operation
is.
=> [server] Add more info log to the store API function

docs/web/server_config.md, web/server/codechecker_server/server.py, web/server/codechecker_server/session_manager.py, web/server/config/server_config.json
When using a CodeChecker server with `Docker Swarm` on the server side
we may get a `[Errno 104] Connection reset by peer` exception when for
example the storage takes more than 15 minutes. With the keepalive
parameters we can solve this problem by not destroying the connection
when an operation takes too much time.
=> [server] Configure keepalive

docs/web/user_guide.md, web/api/js/codechecker-api-js/package.json, web/api/js/codechecker-api-node/package.json, web/api/py/codechecker_api/setup.py, web/api/py/codechecker_api_shared/setup.py, web/api/report_server.thrift, web/client/codechecker_client/cmd/cmd.py, web/client/codechecker_client/cmd_line_client.py, web/client/codechecker_client/helpers/results.py, web/requirements.txt, web/requirements_py/db_pg8000/requirements.txt, web/requirements_py/db_psycopg2/requirements.txt, web/requirements_py/dev/requirements.txt, web/requirements_py/osx/requirements.txt, web/server/codechecker_server/api/report_server.py, web/server/vue-cli/package-lock.json, web/server/vue-cli/package.json, web/tests/functional/diff_remote/test_diff_remote.py
Some run tags can be provided by : character when querying for diff
involving reports on the server.
=> [client] Using tags names in diff commands

web/server/vue-cli/src/components/Statistics/Overview/ComponentSeverityStatistics/ComponentSeverityStatistics.vue, web/server/vue-cli/src/components/Statistics/Overview/ComponentSeverityStatistics/ComponentSeverityStatisticsChart.vue, web/server/vue-cli/src/components/Statistics/Overview/OutstandingReportsChart.vue, web/server/vue-cli/src/components/Statistics/Overview/Overview.vue, web/server/vue-cli/src/components/Statistics/Overview/Reports.vue, web/server/vue-cli/src/components/Statistics/Overview/SingleLineWidget.vue, web/server/vue-cli/src/components/TooltipHelpIcon.vue
Add helper tooltips for each widget on the product overview page which
describes the numbers, how these numbers are calculated and what kind of
filter affects these numbers.
=> [gui] Refactoring product overview page

web/server/vue-cli/src/components/Statistics/Overview/OutstandingReportsChart.vue, web/server/vue-cli/src/components/Statistics/Overview/Overview.vue
=> [view] Outstanding reports char day view

web/server/vue-cli/src/components/Report/ReportFilter/Filters/AnalyzerNameFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaseFilter.mixin.js, web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaseSelectOptionFilter.mixin.js, web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineOpenReportsDateFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineRunFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/BugPathLengthFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/CheckerMessageFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/CheckerNameFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/ComparedToDiffTypeFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/DetectionDateFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/DetectionStatusFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/FilePathFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/Layout/FilterToolbar.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/ReportHashFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/ReviewStatusFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SeverityFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SourceComponentFilter.vue
> Part of #2898
Previously all the filter options are collapsed by default. However,
some of them is set by at page load, and these should be opened by default.
=> [gui] Open filters which set during page load

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/ctu/test_ctu.py, docs/analyzer/user_guide.md
Option ctu-ast-mode is only meaningful if ctu mode is active.
Exit early if ctu-ast-mode is specified but ctu mode is not enabled.
=> [cmd] Do not allow ctu-ast-mode in non-CTU mode

web/client/codechecker_client/cmd/store.py
> Closes #2510
Somehow it is possible that the store command tries to write the same
source file to the zip multiple times. This patch will handle that use
case and add a file to the zip if the file is not in there.
=> [cmd] Handle duplication warning at store

.github/workflows/docker.yml
Create docker images automatically with github actions when a new release
is published. It will create a docker image from the published version and
also update the latest tag.
=> [github] Create docker images automatically

analyzer/codechecker_analyzer/buildlog/build_manager.py, analyzer/codechecker_analyzer/cmd/check.py, docs/analyzer/user_guide.md
If not explicitly given the debug log file of ld_logger is placed in
report directory if any. Otherwise parallel "CodeChecker check"
commands would overwrite each other's log files under /tmp which is the
default location for "CodeChecker check".
=> [log] ld_logger debug logs go to report dir

web/server/codechecker_server/api/report_server.py, web/tests/functional/comment/test_comment.py
> Closes #3092 
Commenting on an issue using quotes results to the error
"No closing quotation" because of `shlex.split`.
=> [server] Fix quotes in system comments

analyzer/tools/build-logger/README.md, analyzer/tools/build-logger/src/ldlogger-logger.c, analyzer/tools/build-logger/src/ldlogger-util.c, analyzer/tools/build-logger/src/ldlogger-util.h, analyzer/tools/build-logger/test/test_logger.sh
The build logger did not escape '\\', '\r' and '\n' correctly.
This patch fixes this issue, while preserving the old version.
By default the old version will be used, unless the
`CC_LOGGER_NEW_ESCAPING` environment variable is defined.
It is mentioned in the README.md.
I test both versions in the test files.
Also adds a few tips how to debug such cases with confidence.
=> [fix] Opt-in fix escape in logger in case of backslash, CR, LF

codechecker_common/output/twodim.py
When printing a table (e.g.: `CodeChecker version`) it is possible
that a value is None (e.g.: a package is built from a release zip file
which will not contain git information). In this case when printing the
table the following exception will be raised:
```
unsupported format string passed to NoneType.__format__
```
In this patch we will convert None values to empty string to handle this
use case too.
=> [fix] Handle None when print a table

web/server/vue-cli/src/components/Statistics/Overview/Reports.vue
The number of outstanding reports are not filtered by the BASELINE run filters
because the run ids in the compare data for the API function is not set.
=> [server] Fix filtering number of outstanding reports on the statistics page

web/server/vue-cli/src/components/CopyBtn.vue, web/server/vue-cli/src/components/Report/Report.vue
Add a button to the report detail view beside the file name which can be
used to copy the full file path easily.
Screenshots:
- Before clicking on the copy button:
- After clicking on the copy button:
=> [gui] Add button to copy file path

web/server/vue-cli/src/components/Report/ReportStepMessage.vue
It is possible (for example in case of macro expansion) that the message of a bug step is very long. Previously we put the whole message into one line but it was very hard to read. For this reason with this patch we will break long messages.
Screenshot:
- **Before**
- **After**
=> [gui] Wrap bugstep messages

web/server/vue-cli/src/components/Product/ProductNameColumn.vue, web/server/vue-cli/src/views/Products.vue
Previously a ProductNameColumn component were created (#3100) to show the product
name, description and status but the function which converts the status
enum to string was forget to move to this component. This commit
solves this problem and also removes some unused code.
=> [gui] Fix database status in product name column

.github/workflows/docker.yml
Unfortunately previously the github action which generates docker images
failed because it couldn't find the `entrypoint.sh` file. To solve
this problem we need to set the context parameter to the directory where
the docker file and the entrypoint file can be found.
=> [github] Fix context of the docker github action

analyzer/codechecker_analyzer/buildlog/log_parser.py
The target attribute should be a dictionary which contains strings instead of dictionary of dictionary.
=> [analyzer] Fix target attribute of the log parser

analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/functional/analyze/test_files/failure.c, tools/tu_collector/tu_collector/tu_collector.py
> Closes #3001
When there is a compilation failure, we will try to create a failed zip file
with source files. It is possible that we will try to add the same file
multiple times but on different path: `a/b/c` and `/a/b/../b/c`. In this
case CodeChecker will print out the following warning message:
`UserWarning: Duplicate name:...`
To avoid this problem we normalize the path before inserting it to the
zip file.
=> [analyze] Fix duplication warning when creating failed zip

codechecker_common/output/codeclimate.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py
> Closes #3199
Previously if there was a report for a `a/b/c/file.cpp`, then exporting in
codeclimate format always presented only `file.cpp` as file path. This
prevents correct navigation when viewing the report in GitLab. Using
`--trim-path-prefix` made no effect in `CodeChecker parse` output.
=> [fix] Fix file path in codeclimate output

web/client/codechecker_client/credential_manager.py
If we run multiple CodeChecker commands (login, store) which uses the same
home directory and the CodeChecker session file (`~/.codechecker.session.json`)
does not exist yet the following scenario is possible:
- The first command recognizes that this file doesn't exist yet so it will open
this file for writing.
- Before the first command writes data to the file the second command will be run.
It recognizes that the file exists, so it will read up the file. It expects that
the file is a valid json file but it is empty. So the `token_dict` variable
will be an empty dict, we try to get the `tokens` member of this empty
dictionary (`self.__tokens`) which will be `None`, and when we will try to
iterate over this directory (which is `None` in our case) the CodeChecker will
raise an exception. …
=> [client] Fix creating session file

analyzer/requirements.txt, analyzer/requirements_py/dev/requirements.txt, analyzer/requirements_py/osx/requirements.txt, tools/codechecker_report_hash/codechecker_report_hash/hash.py, tools/codechecker_report_hash/requirements_py/dev/requirements.txt, tools/codechecker_report_hash/tests/Makefile, tools/codechecker_report_hash/tests/unit/codechecker_report_hash/__init__.py, web/requirements.txt, web/requirements_py/dev/requirements.txt, web/requirements_py/osx/requirements.txt
- Add type hints to `codechecker_report_hash` tool.
- Add `mypy` static type checker to the requirements
- Create new targets to check the code with mypy.
=> [tools] Add type hints to codechecker report hash tool

analyzer/codechecker_analyzer/analyzer_context.py
> Closes #3117 and closes #2730
When we try to find compiler binaries from the `PATH` we will resolve the
symlinks by using `os.path.realpath` function. If the compiler
(`g++/gcc/clang`) is a symlink to `ccache` it will think that the compiler
is ccache. When we try to get for example the version of the detected
analyze it will return the version for the ccache binary and not for
the original compiler.
For this reason if the detected compiler binary is `ccache` we will use
the original compiler path instead of resolving the symlink.
=> [analyze] Fix ccache compiler detection

analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzer_context.py, analyzer/codechecker_analyzer/analyzers/analyzer_types.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/checkers.py
> Closes #3141
Handle use cases when no analyzer can be found (clang, clang-tidy) on the user's host machine at all or one of the enabled analyzer is missing.
=> [analyze] Handle no analyzer use cases

web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_remote/__init__.py
> Closes #3182
When diffing two runs from a command-line client, a
`The following source file contents changed since the latest analysis:`
error is shown instead of the diff.
To reproduce the problem we just have to remove the project folder after
storage or use the --trim-path-prefix option during storage and then
just run the diff command with two remote runs.
=> [client] Fix source content change error when diffing remote runs

web/server/vue-cli/e2e/pages/report.js, web/server/vue-cli/src/components/Report/SourceComponent/EditSourceComponentDialog.vue
> Closes #3164
The `Description` field on the Web GUI when editing source components
is a single-line textbox, which makes writing anything longer than six
words needing scroll. For this reason we turn the UI element into a
textarea.
=> [gui] Use textarea at source component description

analyzer/codechecker_analyzer/cmd/parse.py, codechecker_common/output/gerrit.py, web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py
> Closes #3122
Print error messages and stop the command when no mandatory environment variables (`CC_REPO_DIR`, `CC_CHANGED_FILES`) are set when using gerrit output.
=> [client] Handle no mandatory env var when using gerrit output

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/codechecker_analyzer/cmd/log.py, analyzer/codechecker_analyzer/cmd/parse.py, docs/analyzer/user_guide.md
Remove code duplication which is related to epilog from the `CodeChecker check` command.
=> [analyzer] Remove some code duplication from CodeChecker check command

web/server/vue-cli/src/components/Report/Report.vue, web/server/vue-cli/src/components/Report/SelectReviewStatus.vue
> Closes #3128
Show the review status change selector in read-only mode if the
review status change is disabled on the product configuration page
instead of hiding the whole selector.
=> [gui] Show review status selector even if status change is disabled

analyzer/codechecker_analyzer/analyzer_context.py, codechecker_common/singleton.py, web/codechecker_web/shared/webserver_context.py
Use singleton pattern when creating context objects (analyzer/web) to improve the performance.
=> [ref] Use singleton when creating context objects

analyzer/codechecker_analyzer/cmd/analyze.py
> Closes #3180
At the end of the analysis we try to cleanup the metadata file when we
do an incremental analysis. If the source file for a plist doesn't exist,
we try to remove the plist file from the system and from the metadata.
Previously we created a new metadata format but we forgot to modify this
code part where we remove the plist file from this metadata file.
This commit will handle the use case when old and new metadata format
already can be found in report directory during analysis and the
plist file need to be removed.
=> [analyze] Fix cleanup metadata

web/client/codechecker_client/helpers/base.py, web/client/codechecker_client/thrift_call.py, web/tests/functional/cmdline/test_cmdline.py
If `HTTP_PROXY` / `HTTPS_PROXY` environment variables are set and the
URL is invalid (e.g.: it doesn't contains a schema like localhost:8001)
the client will throw the following exception:
```
'NoneType' object has no attribute 'rfind'
File "/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 174, in <module>
main(commands)
File "/codechecker/build/CodeChecker/cc_bin/CodeChecker.py", line 141, in main
sys.exit(args.func(args))
File "//codechecker/build/CodeChecker/lib/python3/codechecker_client/cmd/store.py", line 856, in main
traceback.print_stack()
```
From this error message it is hard to understand the real problem.
Unfortunately Thrift does not handle the use case when invalid proxy format
is used (e.g.: no schema is specified). For this reason we need to verify
the proxy …
=> [client] Handle invalid proxy settings

Makefile, analyzer/Makefile, web/Makefile
> Fixes #3223.
Add the `venv` and `standalone_package` targets for both the `analyze` and the `web` directories.
This allows building only the particular part of CodeCheckerí even for release and use.
This is especially useful if the client doens't want to run the web server. Installing Node and running the Node parts for the web part takes multiple minutes which is not needed if I only want to analyze.
A few missing instructions or badly relative arguments had to be fixed in the existing `package` target for the files.
The analyzer build:
~~~~
whisperity@cc:~/CCh/analyzer$ build/CodeChecker/bin/CodeChecker version
CodeChecker analyzer version:
---------------------------------------------------------------
Kind                 | Version …
=> Allow make "venv" and "standalone_package" in both analyzer and web

tools/report-converter/codechecker_report_converter/spotbugs/output_parser.py, tools/report-converter/tests/unit/spotbugs_output_test_files/Makefile, tools/report-converter/tests/unit/spotbugs_output_test_files/assign.plist, tools/report-converter/tests/unit/spotbugs_output_test_files/assign.xml, tools/report-converter/tests/unit/spotbugs_output_test_files/files/Assign.java
Some SpotBugs bug reports lack the 'start' and 'end' attributes in
their <SourceLine> tags. The converter must not crash in such cases,
but instead take line number in the <SourceLine> tag in the innermost
block. If neither the blocks constin 'start' and 'end' attributes then
take 0 instead. This patch fixes this issue.
=> [report-converter][fix] Fix for the SpotBugs report converter

web/server/vue-cli/src/components/Statistics/BaseStatisticsTable.vue, web/server/vue-cli/src/components/Statistics/Overview/ComponentSeverityStatistics/ComponentSeverityStatistics.vue
Problem: at the Checker statistics page clicking on the red diff number in
the cells when comparing results do not contain for example the checker
name filter.
=> [gui] Set filter properly when clicking on the diff count in the statistics page

tools/report-converter/codechecker_report_converter/spotbugs/output_parser.py
If a bug report does not have a line number and neither of its events
have one then an exception is thrown. This patch fixes the issue.
=> [report-converter][fix] SpotBugs Report Converter Hotfix

analyzer/codechecker_analyzer/analyzers/clangtidy/output_converter.py, analyzer/tests/functional/analyze_and_parse/test_files/Makefile, analyzer/tests/functional/analyze_and_parse/test_files/tidy_alias.cpp, analyzer/tests/functional/analyze_and_parse/test_files/tidy_alias.output
> Closes #2886
When a checker name and the alias of this checker is turned on, Clang Tidy (>v11)
will generate only one report where the checker names are concatenated with `,` mark.
With this patch we will generate multiple reports for each checker name / alias.
=> [clang-tidy] Handle Clang Tidy aliases in plist files

web/tests/functional/diff_local/test_diff_local.py
> This problem comes from this PR: #3240
The `test_non_existent_reports_directory` test assumes that on the default
url (localhost:8001) doesn't run any server. Unfortunately for me a
CodeChecker server was started on this port and this test cases is failed
because the connection between the client and server was successfully
created. To solve this problem we should get a free port on the host
and we need to try to connect to this server. So this test case will
always pass.
=> [test] Fix non existen report directory test

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/parse.py, analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/functional/fixit/test_fixit.py, analyzer/tests/functional/skip/test_skip.py, analyzer/tests/functional/suppress/test_suppress_export.py, docs/analyzer/user_guide.md, docs/web/user_guide.md, web/client/codechecker_client/cmd/cmd.py, web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_local/test_diff_local.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py, web/tests/functional/diff_remote/test_diff_remote.py, web/tests/functional/source_change/test_source_change.py, web/tests/functional/suppress/test_suppress_generation.py, web/tests/libtest/codechecker.py
It is not possible to compute exit code 2 at "CodeChecker analyze"
command efficiently taking suppression into account. So according to the
new exit codes we indicate only the success and failure of analysis by
zero and non-zero exit codes respectively.
Moreover "diff" and "parse" commands have an exit status depending on
whether there is a resulting report.
=> [cmd] Change exit codes

.github/workflows/test.yml, analyzer/Makefile, tools/bazel/.gitignore, tools/bazel/.noserc, tools/bazel/.pypirc, tools/bazel/LICENSE.txt, tools/bazel/MANIFEST.in, tools/bazel/Makefile, tools/bazel/README.md, tools/bazel/bazel_compile_commands/__init__.py, tools/bazel/bazel_compile_commands/bazel_compile_commands.py, tools/bazel/requirements_py/dev/requirements.txt, tools/bazel/setup.py, tools/bazel/tests/Makefile, tools/bazel/tests/projects/BUILD, tools/bazel/tests/projects/inc/inc.h, tools/bazel/tests/projects/main.cc, tools/bazel/tests/unit/__init__.py, tools/bazel/tests/unit/test_compile_commands.py
The tool takes bazel build command as an input parameter
and executes Bazel Action Query (bazel aquery)
to extract all compile commands then saves them
to compile_commands.json file.
=> [tools] Add compilation database generator for Bazel

tools/plist_to_html/plist_to_html/PlistToHtml.py, tools/plist_to_html/requirements_py/dev/requirements.txt, tools/plist_to_html/tests/Makefile, tools/plist_to_html/tests/libtest/env.py, tools/plist_to_html/tests/unit/plist_to_html/plist_to_html_test.py
- Add type hints to `plist-to-html` tool.
- Add `mypy` static type checker to the requirements
- Create new targets to check the code with mypy.
=> [plist2html] Add type hints

tools/report-converter/codechecker_report_converter/spotbugs/output_parser.py
The SpotBugs report converter tries to handle every element in the
<Project> section as a file path. However, if a plugin is used, such as
find-sec-bugs an additional element with <Plugin> tag is also included
in this section with empty text part, which crashes the converter because
it expects a non-empty text. This patch fixes this issue by only
considering tags <Jar>, <AuxClasspathEntry> and <SrcDir>.
=> [report-converter][fix] Fix for SpotBugs Report Conveter with Plugins

web/server/vue-cli/src/components/Statistics/Overview/OutstandingReportsChart.vue, web/server/vue-cli/src/components/Statistics/Overview/Overview.vue
- Add a resolution dropdown selector (day/week/month/year) to the Number of outstanding reports chart.
- Handle wrong values (e.g: the interval should be lower than 31).
- Save interval and resolution to the URL and on page load use these values.
Screenshots:
=> [gui] Allow to change the outstanding reports chart resolution

web/server/codechecker_server/api/report_server.py, web/server/codechecker_server/database/db_cleanup.py, web/server/codechecker_server/server.py, web/tests/functional/db_cleanup/test_db_cleanup.py
=> [server] Cleanup unused data (comments, review statuses)

web/client/codechecker_client/cmd/store.py, web/tests/functional/store/__init__.py, web/tests/functional/store/test_proj/Makefile, web/tests/functional/store/test_proj/project_info.json, web/tests/functional/store/test_store.py
It is possible that the same project is analyzed with different
configuration (e.g.: ctu, non-ctu) to different report directories and
the user want to store these results with one CodeChecker store command.
This command will create a storage zip file with all the plist files in it
under the reports directory. It is possible the the same file name can be
found in multiple report directories so for this reason we need to create a
unique plist file name when we build the zip file.
=> [client] Fix storage of multiple report directory

docs/web/api/README.md, web/server/vue-cli/config/webpack.common.js
Getchecker-api` package version automatically during webpack build
from the module instead of changing it manually on every package update.
=> [web] Get CodeChecker API version automatically in webpack

scripts/test/run_server_performance_test.py
Adding an extra job to performance test: fetching analysis stats.
=> [test] Performance test improvement

web/tests/projects/cpp/Makefile
If an old GCC compiler is installed on a machine which doesn't use C++11
by default, the tests may fail. There are some checkers (e.g.
misc-definitions-in-headers) which report only from C++11. If these
reports are missing with an old compiler then the number of reports will
not be as expected.
=> [test] Compile test project with c++11 explicitly

web/server/codechecker_server/api/report_server.py, web/tests/functional/storage_of_analysis_statistics/test_storage_of_analysis_statistics.py
Unfortunately we can't distinct the failed file paths by using SQL
queries because the list of failed files for a run / analyzer are
stored in one column in a compressed way. For this reason we need to
decompress the value in the Python code before uniqueing and we can use
the `getFailedFiles` function in the `getFailedFilesCount`.
=> [server] Fix failed files uniqueing on the statistics page

codechecker_common/util.py, web/server/codechecker_server/api/report_server.py, web/server/codechecker_server/database/db_cleanup.py
In SQLite there is a setting named SQLITE_LIMIT_COMPOUND_SELECT which
limits the maximal number of compound select statements. In changing
checker severities, we have such an SQL statement of which the size is
proportional to the number of checkers. If this limit is exceeded, then
the query fails. The default limit is 500, so the workaround is to
change severities in this big chunks.
=> [server] Workaround for SQLite limitation in severity change

Makefile, snap/snapcraft.yaml, web/docker/Dockerfile
- The local CodeChecker API packages are specified relative to the `web`
directory. For this reason we need to move to the `web` directory before
the `pip install` command call.
- Fix docker image file.
- Fix snap file.
=> [fix] Local API package installation

web/Makefile
Running make package on a zsh shell currently yields a parse error.
It seems to be because zsh expects a semicolon or a newline, however
the newline is escaped and there is no semicolon.
Adding one makes it work.
=> Add semicolon to web Makefile

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzer.py, web/client/codechecker_client/cmd/store.py, web/server/codechecker_server/api/report_server.py, web/server/codechecker_server/metadata.py, web/server/tests/unit/test_metadata_parser.py, web/server/vue-cli/src/components/Run/AnalyzerStatisticsDialog.vue, web/server/vue-cli/src/components/Run/CheckCommandBtn.vue, web/server/vue-cli/src/components/Run/CheckCommandDialog.vue, web/server/vue-cli/src/components/Run/ExpandedRun.vue, web/server/vue-cli/src/components/Run/RunNameColumn.vue, web/server/vue-cli/src/components/Run/index.js, web/server/vue-cli/src/views/RunList.vue, web/tests/functional/storage_of_analysis_statistics/test_storage_of_analysis_statistics.py, web/tests/functional/store/test_store.py, web/tests/libtest/codechecker.py
> Closes #3273 and closes #3271
=> [web] Fix multiple report dir storage

analyzer/codechecker_analyzer/buildlog/log_parser.py, analyzer/tests/unit/test_option_parser.py
If a -I flag is followed by a path starting with "=" sign, it means that
it's relative to --sysroot. In CodeChecker we tend to convert all paths
to absolute, however, these should be skipped. For example:
-I =/usr/include/my_lib
=> [analyzer] Relative include paths to --sysroot

tools/report-converter/Makefile, tools/report-converter/codechecker_report_converter/analyzer_result.py, tools/report-converter/codechecker_report_converter/cli.py, tools/report-converter/codechecker_report_converter/cppcheck/analyzer_result.py, tools/report-converter/codechecker_report_converter/report.py, tools/report-converter/setup.py
Use the `codechecker_report_hash` module to generate a hash in the `report-converter` to remove code duplication.
=> [report-converter] Use codechecker_report_hash module

analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/cmd/analyzers.py, analyzer/codechecker_analyzer/cmd/checkers.py
> Closes #3296
In case of Clang Static Analyzer we try to get analyzer / checker configuration options by using the `-analyzer-config-help` / `-analyzer-checker-option-help` options which were introduced in Clang 8.
The problem can be reproduced with clang <7 and with the following commands:
```
CodeChecker analyzers --analyzer-config clangsa
CodeChecker checkers --checker-config --analyzers clangsa
```
With this patch we will handle the use case when someone is using an older version of clang which doesn't support these options.
=> [analyzer] Handle getting options for old analyzer version

scripts/test/run_server_performance_test.py
Use the logging module at peformance measurement script and log the timestamp.
=> [script] Use logging module at performance measure script

web/server/codechecker_server/api/report_server.py
The query of reports has the following format:
```.sql
SELECT col1, col2 FROM reports WHERE col IN
(SELECT col FROM reports WHERE conditions);
```
This is the same(?) as
```.sql
SELECT col1, col2 FROM reports WHERE conditions;
```
SQL queries are translated to query strategies by PostgreSQL. This
strategy determines the algorithm for gathering resulting records from
the database. The first query generates a strategy where the inner
select is implemented with a nested loop. Such a nested loop on
"reports" table is so slow that it times out. In this commit the query is
rewritten to the second form.
But even if the second form is used, PostgreSQL may generate a strategy
with inner loop in some cases. The generated strategy not only depends
on the query but on table size and many other things …
=> [server] Faster query for reports

analyzer/codechecker_analyzer/analyzers/clangsa/ctu_manager.py, analyzer/tests/functional/ctu/test_ctu.py
If the key attribute (path) in the invocation-list.yml file is longer then
128 characters the yaml module will mark it as a complex key which is not
supported by the LLVM yaml parser. For this reason we will create an
LLVM compatible yaml dumper class which will mark these keys as non-complex
keys.
=> [analyzer] Fix yaml dumper

web/server/codechecker_server/migrations/report/versions/dabc6998b8f0_analysis_info_table.py
If a product contains too many reports (>5 millions) the analysis info
migration for reports may fail. To prevent this we remove this from
the migration script but keep the analysis info for the run history.
=> [web] Remove analysis info migration for reports

web/server/codechecker_server/api/mass_store_run.py
It is possible when multiple runs are stored simultaneously to the
server with the same analysis command that multiple entries are
stored into the database. In this case we will select the first one.
Using `one_or_none` sqlalchemy function is not an option because it
will raise an exception if multiple entries are exists in the database.
=> [server] Fix getting existing analysis info

.github/workflows/pypi.yml
Download the artifactory to the root folder when running the publish job
to make sure `dist` directory exists.
=> [github] Fix pypi package github action

web/codechecker_web/shared/webserver_context.py, web/server/codechecker_server/api/mass_store_run.py, web/server/codechecker_server/tmp.py, web/tests/functional/storage_of_analysis_statistics/test_storage_of_analysis_statistics.py
Previously the storage zip file is unzipped to the `/tmp` folder. It is
possible that the disk size of the host machine is not so big and when
the unzipped / decompressed zip size is too big that the user will
get `No space left on device` exception.
For this reason we will unzip the zip file to the workspace folder which
can be configured during a server start and it can point to an extra
network drive which size can be bigger than the host machine drive.
This patch also removes our `TemporaryDirectory` class because it is
available in the `tempfile` module since `Python 3.2`.
=> [server] Unzip storage zip file to workspace directory

web/server/codechecker_server/database/run_db_model.py, web/server/codechecker_server/migrations/report/versions/a24461972d2e_add_index_for_report_and_history_id_columns.py
Removing a run got slow after we introduced the analysis info table
in the previous 6.16.0. CodeChecker release. Doing some measurement
on the database I tried to run the following query:
```sh
begin;
explain (analyze,buffers,timing) delete from runs where id=1;
rollback;
```
The output looked like this:
```
QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------
Delete on runs  (cost=0.00..1.51 rows=1 width=6) (actual time=0.048..0.050 rows=0 loops=1)
Buffers: shared hit=3
->  Seq Scan on runs  (cost=0.00..1.51 rows=1 width=6) (actual time=0.020..0.024 rows=1 loops=1)
Filter: (id = 1
Rows Removed by Filter: 40
Buffers: shared hit=1
Planning Time: 0.077 ms
Trigger for constraint fk_reports_run_id_runs on runs: …
```
=> [server] Add index for report and run history id columns

analyzer/tools/build-logger/Makefile.manual
There may not be a `gcc` program, and `CC` may be pointing
at the right one, but this would completely override it,
failing the build.
=> Don't hardcode GCC in build-logger Makefile

docs/web/server_config.md, web/server/codechecker_server/server.py, web/server/codechecker_server/session_manager.py, web/server/config/server_config.json, web/server/vue-cli/e2e/init.workspace.js, web/tests/functional/authentication/test_authentication.py, web/tests/functional/products/test_products.py, web/tests/functional/ssl/test_ssl.py, web/tests/libtest/env.py
In Python Threads are not very useful in our case because it can execute only one statement at the same time even if multiple threads are started. To be able to process multiple API requests simultatenously and use the CPU cores of the machine we will use Processes when starting a CodeChecker server.
=> [server] Use processes instead of threads

web/server/codechecker_server/api/report_server.py, web/tests/functional/export_import/test_export_import.py
It is possible that "comments" table contains two comments with the
same date field. It can occur when importing comments from a file which
contains a comment that has the same date as an existing comment.
The list of comments is returned ordered by dates, however, the order
of comments with the same date is not deterministic. This made the
tests fail sometimes.
=> [server] Comment date collision

MANIFEST.in
https://pypi.org/project/codechecker/ is missing package data files, resulting in errors when running
```
CodeChecker parse -e html ...
```
This PR makes sure the relevant static data files are included.
=> include package data files in python package.

analyzer/codechecker_analyzer/cmd/parse.py, analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py, codechecker_common/output/codeclimate.py, web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py
As requested in https://github.com/Ericsson/codechecker/issues/3342#issuecomment-859601266
=> Add severity to CodeClimate export

web/client/codechecker_client/thrift_call.py
> Closes #3354
It is possible that the `performLogin` API functions throws an exception.
On the client side we print the API function name and the argument list
if an exception happens. The argument list may contain sensitive
information such as password. In this patch we will skip printing
the argument list in this situation.
=> [cli] Do not print sensitive information when exception happens

codechecker_common/cli.py, codechecker_common/cmd_config.py
Multiple cli commands accepts a configuration file paramter (--config).
If someone is using it, from the logs we will not see the full command
what was executed, so it will be hard to start debugging the problem.
For this reason with this patch we will print out the extra options
from this configuration.
=> [cli] Log options in the configuration file

web/docker/Dockerfile
Change permission of the tini and wait-for scripts in the docker image
to have r+w permission for all users.
=> [docker] Change permission of helper script in docker image

docs/supported_code_analyzers.md, docs/tools/report-converter.md, tools/report-converter/codechecker_report_converter/cli.py, tools/report-converter/codechecker_report_converter/sanitizers/leak/__init__.py, tools/report-converter/codechecker_report_converter/sanitizers/leak/analyzer_result.py, tools/report-converter/codechecker_report_converter/sanitizers/leak/output_parser.py, tools/report-converter/tests/unit/lsan_output_test_files/files/lsan.c, tools/report-converter/tests/unit/lsan_output_test_files/lsan.out, tools/report-converter/tests/unit/lsan_output_test_files/lsan.plist, tools/report-converter/tests/unit/test_lsan_parser.py
LeakSanitizer report converter tool for parsing LeakSanitizer output
Fixes #3321
=> [report-converter] LeakSanitizer Parser

web/server/vue-cli/src/mixins/to-csv.mixin.js
It is possible that a checker name contains a hashmark character
(`clang-diagnostic-#warnings`, `clang-diagnostic-#pragma-messages`).
Hashmark is a valid URL character but it starts the hash fragment and
for this reason it needs to be escaped when we export the statistics
to CSV.
=> [gui] Fix exporting checker statistics to CSV

docs/tools/report-converter.md
Update the documentation for Leak Sanitizer by adding the `-o` to the command for generating the plist files using the `report-converter` command as mentioned in https://github.com/Ericsson/codechecker/pull/3368#discussion_r665882971
=> [docs] Fix plist generator command for leak sanitizer

analyzer/codechecker_analyzer/cmd/parse.py, analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py, codechecker_common/util.py
> Closes #3322
Parse subcommand did not apply filter of skip files when --export option  specified a JSON based output format (json, codeclimate, gerrit).
=> [analyzer] Make parse subcommand to work with --skip option correctly

codechecker_common/output/gerrit.py, codechecker_common/tests/unit/test_files/lib.cpp, codechecker_common/tests/unit/test_files/main.cpp, codechecker_common/tests/unit/test_gerrit_converter.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py
- Use source line in the gerrit output instead of the line number at the end of the report message.
- If a report not found in the changed files list, add report to the main message.
=> [cli] Fix gerrit output

docs/web/db_schema_guide.md
The urls pointing to the alembic documentation were outdated in the db_schema_guide.md.
=> [doc] Fix broken alembic urls

web/requirements.txt, web/requirements_py/dev/requirements.txt, web/requirements_py/osx/requirements.txt
> Fixes #3387.
Hopefully this will fix the generated PyPI package missing this dependency and thus not working in a clean venv.
=> [web] Add 'thrift==0.13.0' dependency explicitly

web/server/codechecker_server/migrations/report/versions/f8291ab1d6be_fix_setting_analysis_info_id_seq.py
In the previous release with the analysis info table we introduced a
bug on data migration that the analysis_info_id_seq value is not set
properly and when the database contained some data before migration,
after migration the user will not be able to store data to the database
and he will get an error.
=> [server] Fix setting analysis_info_id_seq

config/checker_profile_map.json
The `MallocOverflow` checker is somewhat controversial, it will warn for a
lot of legitim usage patterns.
E.g.: when the operand of the multiplication of the malloc's parameter
is bounded but the caller's side.
```
if (n > 100)
return;
p = do_allocation=(n);
where do_allocation(n):
return malloc(n * sizeof(MyType));
~ ^ ~~~~~~~~~~~~~~
```
Since the checker is AST-based, it has no way of detecting these cases,
thus it will issue false-positive reports.
As of now, I and @dkrupp decided that this should be removed even from
the sensitive profile until we decide otherwise.
=> [cfg] Remove the MallocOverflow checker from the sensitive profile

analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangsa/clang_options.py, analyzer/codechecker_analyzer/analyzers/clangsa/ctu_autodetection.py, analyzer/codechecker_analyzer/analyzers/clangsa/version.py, analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/unit/test_clang_version_parsing.py, analyzer/tests/unit/test_option_parser.py
> Closes #3113
Handle use cases when the `clang --version` command doesn't have an `InstalledDir` field.
=> [analyzer] Handle clang binary without installed dir

analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/config/test_config.py, codechecker_common/cmd_config.py
> Closes #3384
CodeChecker check didn't recognise options from the config file specified
by the --config option. This patch will solve this problem and add some
extra test cases.
=> [cmd] Fix check command config file support

web/server/codechecker_server/api/mass_store_run.py, web/server/codechecker_server/api/product_server.py, web/server/codechecker_server/api/report_server.py, web/server/codechecker_server/database/config_db_model.py, web/server/codechecker_server/migrations/config/env.py, web/server/codechecker_server/migrations/config/versions/4db450cf38af_add_extra_product_detail_columns.py, web/server/vue-cli/src/views/Products.vue, web/tests/functional/store/test_store.py
Create separate columns for products to store the number of runs and
the latest storage date instead of connecting and getting these
information from each product database.
=> [server] Create columns for product details

analyzer/tests/functional/config/test_config.py
On some systems the test workspace directory is not under HOME
directory so it is not a good choice for testing "trim path prefix".
=> [test] Test workspace is not necessarily under HOME

MANIFEST.in, setup.py
This merge request fix the license declaration in setup.py
The license field should be set to the license identifier and not point to the license file.
Adding the license_files field should be sufficient to include the license in the tarball distribued by PyPi
EDIT: After a test with `make dist`, setting `license_files` in `setup.py` is not enough. The license file should also be included in `MANIFEST.in`
Using the license_files field require setuptools >= v42.0.0, as noted in the [documentation](https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html#metadata) 
Close https://github.com/Ericsson/codechecker/issues/3416
=> [setup.py] Add the license file

web/client/codechecker_client/cmd/store.py
Using process pool to speed up collecting blame information for source files.
> Note: For me it reduced the `CodeChecker store` command run time from `1m58,088s` to `1m15,268s`.
=> [cmd] Improve storage performance of blame information

web/client/codechecker_client/blame_info.py, web/client/codechecker_client/cmd/store.py
It is possible that `git` is not available on the user's system where the
`CodeChecker store` command is executed. In this case importing git module
will fail. With this patch we will handle this use case and print a
warning message to the user.
This patch will also print some information to the user whether collecting
blame information was successfull or if no blame information is available
for source files.
=> [cli] Handle use case when git is not available

web/client/codechecker_client/blame_info.py
It is possible that a repository doesn't have a remote url. With this patch
we will handle this use case and even so store the blame information.
=> [client] Handle use case when a repository doesn't have a remote url on storage

analyzer/codechecker_analyzer/buildlog/log_parser.py
This was seemingly last touched in Ericsson/codechecker#2449 (Ericsson/codechecker@7d93b32edcbe885c391cb59d4e13c3aa4163463a) but it seems like a typo. There's no such flag as `-macros` in neither Clang nor GCC.
> via @steakhal
=> [analyzer] Use `-imacros` flag instead of `-macros`

analyzer/codechecker_analyzer/buildlog/log_parser.py, analyzer/tests/unit/test_log_parser.py
Instead of checking for `@` in the file name, check if a file name
starts with `@`.
Fixes #3463.
Codechecker supports response files. These are files which you can pass to
clang to work around limits in command line length.
Those files names start with a `@`.
The CI/CD solution "Jenkins" creates workspaces by putting `@` in the path name.
A file entry in compile_commands.json could look like:
"file": "/home/workspace/branchname@2/somefile.cpp"
In this case all files in the compile data base are treated as response file.
And the analyzer skips all files and does nothing.
With the help of @csordasmarton this got fixed by checking if a file starts with an `@`.
=> [analyzer] Fix check for response files

web/api/report_server.thrift, web/server/codechecker_server/api/report_server.py
API request which only gets some data from the server but doesn't modifies it
should require PRODUCT_VIEW permission instead of PRODUCT_ACCESS.
=> [server] Change required permission to view access for some API request

.github/workflows/install-deps.sh, analyzer/tests/functional/analyze_and_parse/test_files/Makefile, scripts/test/check_clang.py
The `-Wunused-but-set-variable` and `-Wunused-but-set-parameter` warnings were introduced by https://reviews.llvm.org/D100581, so had to suppress these warnings in the test file to make them forward compatible.
Let's see if the build bots are happy.
=> [test][cfg] Use clang-13 in the CI, uplift tests accordingly

web/server/vue-cli/src/components/Report/ReportFilter/Filters/FilePathFilter.vue
Sometimes the file path filter at the selected items shows weird strings
for report count (`{"buffer": ...}`). This can be reproduced with the
following steps:
- Filter `File path filter` with a regex which matches only one
file path (e.g: `*main.cpp`) and apply the filter.
- Filter again with the same value but now select and apply the regex
filter option.
This commit will solve this problem and converts the report count value
to number properly.
=> [gui] Fix weird file path filter

web/server/vue-cli/src/components/Report/ReportFilter/Filters/CleanupPlanFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/SourceComponentFilter.vue
On the report filter bar for source component and cleanup plans filters
we show a pencil edit icon only if the current user has rights to manage
it. We set the `currentProduct` variable asynchronously, so it is possible
that it will be `null` when we try to get it by using the vuex getter method
and we will try to get the `administrating` property on a `null` value which
is of course throws an error.
=> [gui] Fix console error on reports page

config/labels/analyzers/clang-tidy.json, config/labels/analyzers/clangsa.json
Added labels for new checkers in clang13
for clang static analyzer and clang tidy.
=> Uplifting label file for clang 13

web/server/codechecker_server/api/report_server.py, web/tests/functional/report_viewer_api/test_get_run_results.py
Analyzer default value in the database is `unknown` string  which is not
a valid analyzer name. In this commit we will handle this use case.
=> [server] Fix getting checker labels for 'unknown' analyzer

config/labels/analyzers/clang-tidy.json
cppcoreguidelines-virtual-class-destructor is unstable,
so removing it from the profiles
=> Removing cppcoreguidelines-virtual-class-destructor from the profiles

MANIFEST.in
> Closes #3499
Previously in the `6.18.0` release `plist_to_html` package was removed and
the source code was moved to the `report_converter` module. Unfortunately we
forgot to update the `MANIFEST` file in the root dir of the repository,
so the pypi package isn't contained these static files. This commit will
solve this problem.
=> [fix] Add static files to the pypi package

web/client/codechecker_client/cmd/store.py
Use `print_exc` instead of `print_stack` at the CodeChecker store
command to get proper information about the error.
=> [cli] Use print_exc at store command

analyzer/codechecker_analyzer/cmd/parse.py, analyzer/tests/functional/analyze_and_parse/test_files/multiple_input_filter.output, analyzer/tests/functional/analyze_and_parse/test_files/multiple_input_filter_all.output
=> [cli] Add file filter option for CodeChecker parse

docs/analyzer/user_guide.md
Clang SA uses taint analysis to detect bugs and security issues in code.
This change documents basic taint analysis usage and how to configure the
checker implementing the analysis.
=> [analyzer][doc] Add taint analysis documentation

web/server/vue-cli/src/views/NewFeatures.vue
=> [gui] Add new features section for 6.18.0 release

config/labels/analyzers/clang-tidy.json
This patch partially reverts #3494
The https://github.com/llvm/llvm-project/commit/0685e83534ef8917f277b394da2927cabff8129f fixed the issue about the `cppcoreguidelines-virtual-base-class-destructor` checker, so we can safely include this in the intended profiles.
Special thanks @whisperity for reminding me.
=> Include cppcoreguidelines-virtual-class-destructor in profiles

docs/README.md
Forgetting to install requirements for LDAP or PAM authentication is quite
a subtle problem: the build completes, the server runs fine,
but users can't login. So mention this in the instructions.
Also mention the possibility of building a standalone_package.
=> Mention more details in the build instructions

analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py, tools/report-converter/codechecker_report_converter/report/output/html/html.py
> Closes #3537
`CodeChecker parse ./reports -e html -o html` generates static HTML files
which describe reports in the report directory. Such an HTML file is
generated for each source files and each analyzers even if the given
analyzer doesn't emit any report for the given source file. This *empty*
HTML file contains the static frame of the page and its size is `204K`.
Before 6.18.0 release these files were not generated.
With this patch we will also skip generating these HTML files.
=> [cli] Don't generate HTML files for empty plist files

web/docker/entrypoint.sh
> Closes #3525 and closes #3458
- Print some useful info message in the `entrypoint.sh` script file.
- If the `workspace` directory already exists when the container started, try
to run the given command with the owner of the workspace directory, otherwise
run it with the `codechecker` user.
=> [docker] Fix running docker container with existing volume

docs/web/docker.md, web/docker/Dockerfile
Introduce a new build argument for the docker image called `CC_REPO` which can be used if you would like to build an image from a custom CodeChecker repository, for example from your fork.
=> [docker] New build argument (`CC_REPO`) for docker image

analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py, tools/report-converter/codechecker_report_converter/report/checker_labels.py, tools/report-converter/codechecker_report_converter/report/output/html/html.py, tools/report-converter/codechecker_report_converter/report/output/html/static/js/bugviewer.js, tools/report-converter/tests/unit/output/html/plist_to_html_test.py
Add links to checker documentations in generated static HTML files.
=> [cli] Add checker documentation URLs to static HTML files

tools/report-converter/tests/unit/output/html/plist_to_html_test.py
In one test case related to plist to html conversion we iterate
over multiple plist files, we convert it to HTML files and we also
skip duplicates.
So let's assume that I have two plist files a.plist and b.plist and both
plist files contains the same results. Let's assume that I process the a.plist
file first and convert the reports to HTML. Next if I process the b.plist I will
do not generate HTML file from it because the same reports are already in the HTML
file what we generated for a.plist and we do not generate empty HTML files anymore.
To solve this problem in the test case we will check if we have report, and in this
case the HTML file has to be exist otherwise it hasn't.
=> [test] Fix non-deterministic test in plist to html

web/server/vue-cli/src/components/Statistics/Overview/OutstandingReportsChart.vue
Let's assume that a bug was detected yesterday at 3PM and I want to view
this chart today at 1PM. In day resolution we used the current date as a
starting point and based on the interval length (e.g.: 7 days) we subtract
x days from the current date. For this reason the grap will not show me this
bug which was detected yesteday, but it assumes that is was detected today.
With this patch we will set the starting date to the end of the current date
which will solve this issue.
=> [gui] Fix number of outstanding reports chart

docs/web/docker.md
Added link to basid database setup before deployment of postgres setup .
I guess this link at that place would have saved me a lot of tries... hopefully it is helpful for others, too.
=> [doc] Added link to basic database setup

web/Makefile
The command "make package" fetches and installs JS dependencies in case
the version of some dependencies changed. CodeChecker API is such a
dependency deployed locally in this repo as .tar.gz files. The verison
checking on these files emit slightly different outputs, so npm runs
unnecessarily even if no change happened.
The old output format was valid while we deployed CodeChecker API in
npm.
=> [fix] No rebuild on satisfied requirements

docs/web/user_guide.md, web/client/codechecker_client/cmd/cmd.py, web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_remote/__init__.py, web/tests/functional/diff_remote/test_diff_remote.py
> Fixes #3535.
In certain scenarios, the run name might contain a `:` character that does NOT separate a tag from a name.
Commands such as `server` and `cmd results` accept `:` as a literal in the name, but `cmd diff` previously cut it as the "run tag" separator.
=> [cmd] Allow escaping `:` in run names with `\:`

docs/README.md
=> Certain Errors Fixed

web/server/codechecker_server/api/report_server.py, web/tests/functional/comment/test_comment.py, web/tests/functional/export_import/test_export_import.py, web/tests/functional/store/test_store.py
We are using [`v-html`](https://vuejs.org/v2/api/#v-html) attribute on the UI side to dinamically rendering comments and analyzer commands. This can be very dangerous because it can easily lead to XSS vulnerabilities. To solve this problem the server will always return the escaped version of these values which can be safely rendered on the UI.
=> [server][gui] Escape values for v-html attributes

analyzer/tests/functional/skip/test_skip.py, tools/report-converter/codechecker_report_converter/report/__init__.py
If a skip file was given to the `CodeChecker parse` command and one of
the mentioned file from the bug path was on the skip list we skipped that
report.
Example:
`main.cpp`:
```cpp
#include "lib.h"
int main() {
return foo(0);
}
```
`lib.h`:
```
double foo(int param) {
return 1 / param;
}
```
`skip file content`:
```txt
+*/lib.h
-*
```
In this case if we analyzed this project and run on of the following
command, it returned with no results:
- `CodeChecker parse ./reports --skip skipfile.txt`
- `CodeChecker parse ./reports --file "*/lib.h"`
With this patch we will skip a report only if the last bug step is on the
skip list.
=> [cli] Fix skipping reports

analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py, tools/report-converter/codechecker_report_converter/report/output/gerrit.py, tools/report-converter/tests/unit/output/gerrit/test_gerrit_converter.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py
> Closes #3571
If `CC_REPORT_URL` is defined and `gerrit` format is used at `CodeChecker parse`
or `CodeChecker cmd diff` commands, the output will contain the value of this
environment variable wrapped inside quotes. When this output is sent to gerrit,
it will convert URL links to HTML `a` tags. Unfortunately gerrit will think that
the ending quote is part of the URL, so it will not remove it. This way the
URL will be invalid.
To solve this problem in this patch we will remove the quotes around the URL link.
=> [cli] Fix link in gerrit output

tools/report-converter/codechecker_report_converter/report/output/html/html.py
> Closes #3565.
Previously `id` attribute was not set for source files when generated static
HTML report files for example with the `CodeChecker parse` command.
The JavaScript part used this attributes but it was always `undefined`.
This way if a user opened a report which bug step referenced mulitple different
source files, changing between the bug steps didn't change the source file.
=> [html] Fix static HTML report files

tools/report-converter/codechecker_report_converter/report/parser/plist.py, tools/report-converter/tests/unit/analyzers/cppcheck_output_test_files/divide_zero.expected.plist, tools/report-converter/tests/unit/analyzers/infer_output_test_files/NullDereference.java.plist, tools/report-converter/tests/unit/analyzers/spotbugs_output_test_files/assign.plist, tools/report-converter/tests/unit/analyzers/tidy_output_test_files/tidy2.plist, tools/report-converter/tests/unit/analyzers/tidy_output_test_files/tidy3_hh.plist, tools/report-converter/tests/unit/analyzers/tsan_output_test_files/tsan.plist, web/tests/functional/report_viewer_api/test_get_run_results.py
In the `6.18.0` release #3462 patch introduced a bug that not all of the control points were stored to the server, because the plist format what the report converter produced and the plist parser expected was invalid:
- `range` key was used instead of `ranges`.
- Control events are not stored as separated items but as a single control event.
**Previously:**
**After this patch:**
=> [web] Fix storage of control points

web/server/codechecker_server/api/mass_store_run.py, web/tests/functional/review_status/review_status_files/divide_zero.cpp, web/tests/functional/review_status/review_status_files/divide_zero.plist
It is possible that the *start line* and *end line* of a bug reported by the analyzer are different.
Example:
```cpp
int main()
{
// codechecker_suppress [all] This will not be suppressed because of a bug.
int x = 1 /
0;
return x;
}
```
In the above example the bug start line is where `x` variable is declared and the *end line* is in the next line.
On the server we stored the start line as the line where the report can be found but for suppression we checked whether there is a source code comment above the end line. So if someone inserted a source code comment above the start line the server hasn't suppressed that report.
With this patch we will solve this problem and we will check the source code comment above the start line and not the end line.
=> [server] Fix suppressing bug on the server

tools/report-converter/codechecker_report_converter/report/__init__.py, tools/report-converter/codechecker_report_converter/report/output/plaintext.py, web/client/codechecker_client/cmd_line_client.py, web/client/codechecker_client/report_type_converter.py, web/client/tests/unit/test_report_converter.py, web/tests/functional/diff_remote/__init__.py, web/tests/functional/diff_remote/test_diff_remote.py
> Closes #3567 
Previously if a run is stored to a CodeChecker server where the file paths are
trimmed and this run is given to `CodeChecker cmd diff` command, and
a remote report was in the result set of this command, the plain text output contained
an exception that the client failed to open the source file for reading. This
problem can be easily reproduced with the following steps:
- Log and analyze a project.
- Store the same results to two remote runs and use the `--trim-path-prefix` option.
- Run the following command: `CodeChecker cmd diff -b remote_run1 -n remote_run2 --unresolved`
With this patch if HTML output format is given to the CodeChecker diff command,
we will try to fetch source file contents from the server and use it instead of
trying to get it from the user's local …
=> [cli] Fix source line / file for remote reports

analyzer/codechecker_analyzer/cmd/analyzer_version.py, codechecker_common/cmd/version.py, docs/web/user_guide.md, web/codechecker_web/cmd/web_version.py
> Closes #3551
The output of the `CodeChecker version -o json` command wasn't a valid
JSON format. With this patch we will provide a valid JSON output for this
command.
=> [cli] Fix JSON format of `CodeChecker version` subcommand

docs/web/user_guide.md, web/client/codechecker_client/cmd/cmd.py, web/client/codechecker_client/cmd_line_client.py, web/client/codechecker_client/report_type_converter.py, web/tests/functional/diff_local/test_diff_local.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py, web/tests/functional/diff_remote/test_diff_remote.py
> Closes #1424
Without bug steps it is hard to understood the problem by a programmer.
With this commit we will introduce a new option for the diff command
which can be used to print bug steps similar what we are doing at the
`CodeChecker parse` command.
This patch also solve the problem to print bug steps in HTML files for
reports which comes from a CodeChecker server.
=> [cli] Add `print-steps` option to `CodeChecker cmd diff`

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzers/analyzer_base.py, analyzer/codechecker_analyzer/buildlog/build_manager.py, analyzer/codechecker_analyzer/buildlog/log_parser.py, analyzer/tests/libtest/codechecker.py, analyzer/tests/unit/logparser_test_files/ldlogger response.rsp, analyzer/tests/unit/logparser_test_files/ldlogger-new-at.json, analyzer/tests/unit/logparser_test_files/ldlogger-new-response.json, analyzer/tests/unit/logparser_test_files/ldlogger-new-space.json, analyzer/tests/unit/logparser_test_files/ldlogger-new.json, analyzer/tests/unit/test_log_parser.py
Simply joining command segments is not enough for acquiring a valid
command. One should escape the necessary characters prior to that.
Escaping can be done manually, but using `shlex` is the preferred way
of doing so.
This patch might not fix all of the issues.
There were multiple places where this was not done adequately:
* at calling `intercept-build`
* at parsing the `compile_commands.json`'s `arguments` field
* at extending the command with the referred response file's content
* at extending the command without response files
* at the `libtest/codechecker.py/all_command()` helper function
* at a bunch of other places where a command is being logged - but
for brevity, I've just fixed the two most important places of this
- `analyzer_base.py/analyze()`
- …
=> [fix] Quote command line segment using shlex

analyzer/tools/build-logger/src/ldlogger-util.c, analyzer/tools/build-logger/tests/unit/test_escaping.py
Affected characters:
'\a', '\e', '\t', '\t', '\b', '\f', '\r', '\v', '\n'
And any other control characters between ASCII 0-32.
Keep in mind that we still don't escape Unicode characters.
For reference I recommend the LLVM's implementation:
https://github.com/llvm/llvm-project/blob/ce8022faa365e0a48c2d77085d67bd9800bedb0a/llvm/lib/Support/YAMLParser.cpp#L682-L746
Which is called from https://github.com/llvm/llvm-project/blob/ce8022faa365e0a48c2d77085d67bd9800bedb0a/clang/lib/Driver/ToolChains/Clang.cpp#L2371
=> [fix] Fix ldlogger escaping a bunch of characters

docs/tools/report-converter.md, tools/report-converter/codechecker_report_converter/analyzers/analyzer_result.py, tools/report-converter/codechecker_report_converter/cli.py, tools/report-converter/tests/functional/cmdline/test_cmdline.py, tools/report-converter/tests/functional/cmdline/test_files/Makefile, tools/report-converter/tests/functional/cmdline/test_files/files/b/simple.go, tools/report-converter/tests/functional/cmdline/test_files/simple.out, tools/report-converter/tests/unit/analyzers/test_asan_parser.py, tools/report-converter/tests/unit/analyzers/test_clang_tidy_parser.py, tools/report-converter/tests/unit/analyzers/test_coccinelle_parser.py, tools/report-converter/tests/unit/analyzers/test_cppcheck_parser.py, tools/report-converter/tests/unit/analyzers/test_cpplint_parser.py, tools/report-converter/tests/unit/analyzers/test_eslint_parser.py, tools/report-converter/tests/unit/analyzers/test_golint_parser.py, tools/report-converter/tests/unit/analyzers/test_infer_parser.py, tools/report-converter/tests/unit/analyzers/test_kerneldoc_parser.py, tools/report-converter/tests/unit/analyzers/test_lsan_parser.py, tools/report-converter/tests/unit/analyzers/test_mdl_parser.py, tools/report-converter/tests/unit/analyzers/test_msan_parser.py, tools/report-converter/tests/unit/analyzers/test_pyflakes_parser.py, tools/report-converter/tests/unit/analyzers/test_pylint_parser.py, tools/report-converter/tests/unit/analyzers/test_smatch_parser.py, tools/report-converter/tests/unit/analyzers/test_sparse_parser.py, tools/report-converter/tests/unit/analyzers/test_sphinx_parser.py, tools/report-converter/tests/unit/analyzers/test_spotbugs_parser.py, tools/report-converter/tests/unit/analyzers/test_tsan_parser.py, tools/report-converter/tests/unit/analyzers/test_tslint_parser.py, tools/report-converter/tests/unit/analyzers/test_ubsan_parser.py
This makes the filenames of plist format reports generated by
report-converter include the names of the parent and grandparent
directories as well as the filename, since before if two different
plist files had the same name there was only one of the reports in
the database. Fixes #3436 .
=> Avoid plist filenames being the same

analyzer/codechecker_analyzer/cmd/check.py
If some exception happens during the `CodeChecker check` command we
will get the following exception:
```
UnboundLocalError: local variable 'analysis_exit_status' referenced before assignment
```
This commit solves this problem and initialize this variable to `1` which
identifies a CodeChecker error.
=> [analyze] Proper exit code for CodeChecker check in case of exception

web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py
If the diff contained reports from multiple source files (e.g.: a.cpp + b.cpp)
the `CodeChecker cmd diff` command in HTML format generated HTML files for
each source file but inserted the same list of reports in all of the HTML files.
This can be easily reproduced by creating two source files and insert a report in both
of the source file. Create a compilation database with 2 translation units, analyze
this project and use the diff command to generate HTML output files to a run which is
empty.
This patch will solve this problem and will insert only those reports to a generated
HTML files which are really related to that file.
=> [fix] Fix HTML generation for CodeChecker cmd diff command

analyzer/codechecker_analyzer/buildlog/build_manager.py, analyzer/codechecker_analyzer/buildlog/host_check.py, analyzer/codechecker_analyzer/cmd/log.py
> Closes #1091
1st check if LDlogger is available and use that.
2nd check if intercept-build is available and use that.
3rd Otherwise report an error.
=> Prefer ldlogger over intercept-build

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangsa/ctu_triple_arch.py, analyzer/codechecker_analyzer/analyzers/clangsa/statistics.py, analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/buildlog/build_action.py, analyzer/codechecker_analyzer/buildlog/log_parser.py, analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/unit/test_option_parser.py
CodeChecker collects implicit compiler info, such as implicit include
paths, default target, etc. If a compilation_database.json contains
build actions with different target compilations (or different sysroot,
etc.) then the implicit infos of the first action will be applied to
all build actions.
With this patch every build action gets its own implicit info.
=> [analyzer] Proper handling of multi-target build

analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangsa/clang_options.py, analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/functional/ctu_failure/test_ctu_failure.py, analyzer/tests/projects/ctu_failure/ctu_failure.saargs, analyzer/tests/projects/ctu_failure_with_headers/ctu_failure.saargs, docs/analyzer/checker_and_analyzer_configuration.md
When a Clang Static Analyzer checker is disabled in CodeChecker, clang is invoked with the `analyzer-disable-checker` flag. This allows the user disabling core modeling checkers such as `unix.DynamicMemoryModeling`. This causes malfunctioning of depending checkers.
:exclamation: :exclamation: :exclamation: **Breaking Change:** :exclamation: :exclamation: :exclamation: 
After this patch, `modeling` and `debug` checkers (listed with `clang -cc1 -analyzer-checker-help-developer`)
will not be listed and cannot be disabled through CodeChecker with the `--enable` and `--disable` flags.
They can be enabled/disabled through the Clang Static Analyzer specific `--saargs` flag only.
=> Not allowing disabling modeling checkers in ClangSA

analyzer/codechecker_analyzer/cmd/parse.py, analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py
> Closes #3606
Fix HTML generation for report directory which doesn't contain any analyzer result (plist) file.
=> [cmd] Fix html generation for report directory without plists

analyzer/codechecker_analyzer/analyzers/clangsa/result_handler.py, analyzer/codechecker_analyzer/analyzers/result_handler_base.py, analyzer/tests/functional/analyze/test_analyze.py, docs/analyzer/user_guide.md, tools/report-converter/codechecker_report_converter/report/parser/plist.py, tools/report-converter/codechecker_report_converter/report/report_file.py
Let's suppose that we have the following directory stucture:
```
|- .codechecker
|- compilation_commands.json
|- reports
|- main.cpp
```
And all the file paths in the compilation database are relative:
```json
[
{
"file": "main.cpp",
"command": "g++ -c main.cpp -o /dev/null",
"directory": "."
}
]
```
If we run the `CodeChecker analyze` command on this project, ClangSA analyzer
will generate a plist file where the file path will be relative to the directory
where the analyzer was called on.
After the plist files are produced, report converter will try to post-process these
files and creates absolute paths from the relative paths.
With this patch now we will create absolute paths based on the following values:
- Current directory (`os.getcwd()`) where the CodeChecker command was executed.
- …
=> [analyzer] Handle relative file paths in compilation database

scripts/debug_tools/prepare_all_cmd_for_ctu.py, scripts/debug_tools/prepare_compiler_info.py
There are multiple changes in this commit:
- Expect 'compilation_database.json' instead of 'compile_cmd.json' in
failed zips.
- Uplift the 'compiler_info.json' preparation to the 'new' format.
- Use the expected compiler for '--ctu-collect'.
Since these were broken for quite a while, and these debug scripts are
not for production use, I'm not willing to create tests for this change.
=> [fix] Fix the prepare debug scripts

config/labels/analyzers/clang-tidy.json
It seems like that `bugprone-narrowing-conversions` check is the same as
the `cppcoreguidelines-narrowing-conversions` check.
Check this:
https://github.com/llvm/llvm-project/blob/c63522e6ba7782c335043893ae7cbd37eca24fe5/clang-tools-extra/clang-tidy/bugprone/BugproneTidyModule.cpp#L136-L137
It seems like both of these checks were included in the `extreme`
profile, thus each of these reports were duplicated basically.
Hereby I'm proposing to keep only one of them in the profile to
workaround this issue.
According to Compiler Explorer, clang-tidy reports these issues only
once, with the `[check,alias,alias...]` schema, thus it does the right
thing. However, PR #3238 introduced a logic that splits these reports
into individual reports.
I'm not sure if that is the right way of dealing with …
=> [clang-tidy][cfg] Remove an alias from the extreme profile

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangsa/result_handler.py, analyzer/codechecker_analyzer/analyzers/clangtidy/result_handler.py, analyzer/codechecker_analyzer/analyzers/result_handler_base.py, analyzer/codechecker_analyzer/buildlog/log_parser.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/parse.py, analyzer/codechecker_analyzer/makefile.py, analyzer/codechecker_analyzer/pre_analysis_manager.py, analyzer/tests/functional/skip/test_skip.py, analyzer/tests/unit/test_log_parser.py, analyzer/tests/unit/test_remove_report_from_plist.py, codechecker_common/skiplist_handler.py, tools/report-converter/codechecker_report_converter/report/__init__.py, tools/report-converter/codechecker_report_converter/report/reports.py
> Closes #3595 and closes https://github.com/Ericsson/CodecheckerVSCodePlugin/issues/34
=> Allow --file and skipfile option to be given together and analyze header file

docs/usage.md
This PR fixes the following page (https://codechecker.readthedocs.io/en/latest/usage/)
as follows:
=> docs: fix bullets in usage.md visualizable

analyzer/codechecker_analyzer/analyzers/analyzer_types.py, analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, web/tests/functional/statistics/test_statistics.py
CodeChecker analyze command has --stats flag if there is at least one
checker contating "statisticsbased" in its name. We are using the
checker listing function to determine the list of checkers but by
default it excludes modeling checkers. This default behavior should be
overridden when checking if underlying Clang supports statistics based
checkers.
=> [bugfix] Disappearing --stats flag

analyzer/codechecker_analyzer/buildlog/log_parser.py
A special downstream compiler duplicated the --sysroot option, and
CodeChecker is not aware of the option chosen by this downstream
compiler. Adding these entries enables CodeChecker to not drop or strip
the arguments to this option when interpreted and driven from a
compile_commands.json file.
=> add -sdkroot option to COMPILE_FLAGS structure

analyzer/codechecker_analyzer/analyzers/clangsa/statistics.py
get_analyzer_checkers() should be used for querying checker list because
this can be used for getting modeling checkers too. Pre-analysis depends
on the existence of some modeling checkers.
=> [bugfix] Determine stats capability in pre-analysis

docs/usage.md
This fixes a few spelling and gammar issues I came across while
reading through the usage guide.
Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>
=> [doc] fixing spelling and gammar in usage guide

.github/workflows/test.yml, analyzer/tools/build-logger/tests/Makefile
If someone runs `make -j16 test_unit test_analyzer test_web_sqlite`,
then the command would spuriously fail due to a filesystem race-condition.
The `cp ldlogger build/bin` would basically try to copy a not-yet-existing file,
causing a failure immediately, or later in the test pipeline, when it
exercises the logger. Causing an error similar to this:
```
make[1]: Leaving directory `codechecker/analyzer'
make: *** [test_analyzer] Error 2
make: *** Waiting for unfinished jobs....
```
Let's work around the issue by omitting the `all` target from the `test*` targets.
This way if it's already built, tests should just pass.
=> Pin the number of jobs in some Make targets

analyzer/codechecker_analyzer/buildlog/log_parser.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/analyze/test_analyze.py, docs/analyzer/user_guide.md
We are storing unique compilation actions in a map which uses the overriden
`__hash__` and `__eq__` methods on the `BuildAction` class.
For this we used the following logic:
```py
if action.__hash__ not in uniqued_build_actions:
uniqued_build_actions[action.__hash__] = action
```
In this case we didn't called the function but we checked whether the
function is in the map. Before `Python 3.9` this solution somehow worked
but in later Python versions it will not unique compilation actions properly.
To solve this problem we will use the following logic:
```py
if action not in uniqued_build_actions:
uniqued_build_actions[action] = action
```
Under the hood the Python interpreter will call the overriden dunder functions.
=> [analyzer] Fix uniqueing compilation commands

analyzer/tests/functional/ctu/test_ctu.py, analyzer/tests/functional/ctu_failure/test_ctu_failure.py, analyzer/tests/libtest/codechecker.py
CTU related tests should be forced in an environment which contains
an underlying Clang that supports this feature. Automatic detection
is not enough because there may be a bug in the automatic
detection itself.
=> [test] Environment variable on forcing ctu related tests

web/client/codechecker_client/blame_info.py
The python git library may throw not only `TypeError` exceptions but
`ValueError` exceptions as well. For example when the `HEAD` file exists
in the `.git` directory but the user who is running the `CodeChecker store`
command doesn't have permission to this file.
To solve this problem we will catch all the exceptions when getting the
tracking branch and remote url.
=> [web] Fix exceptions during blame information storage

analyzer/codechecker_analyzer/buildlog/log_parser.py
It turns out that it is used `analyzer/codechecker_analyzer/buildlog/log_parser.py:1312` as follows:
```python
elif build_action_uniqueing ==\
CompileActionUniqueingType.SOURCE_ALPHA:
if action.source not in uniqued_build_actions:
uniqued_build_actions[action.source] = action
elif action.output <\
uniqued_build_actions[action.source].output:
uniqued_build_actions[action.source] = action
```
Thus, the original comment was misleading. Let's fix that.
=> Update SOURCE_ALPHA doc comment

web/server/codechecker_server/cmd/server.py
Hi, this closes #3657. 
if default port is not available, and the user didn't ask for a specific one - let the os find a port.
=> Find unused port for codechecker server

tools/report-converter/codechecker_report_converter/report/hash.py, tools/report-converter/tests/unit/parser/plist/test_report_path_hash.py, tools/report-converter/tests/unit/report_hash/codechecker_report_hash_test.py, web/tests/functional/report_viewer_api/test_files/run.plist, web/tests/functional/report_viewer_api/test_hash_clash.py
`report_path_hash()` is used for generating a report specific hash for
determining if a bugreport should be saved in the database or not.
We skip duplicate bugreports.
Unfortunately, in some cases clangsa produced plists where an included
file had a context-insensitive bugreport at the exact same
file:row:col:checker, but different bug hash.
Previously, on the first was stored into the database, thus the
associated bug hash was nondeterministically choosen, causing a weird
behavior.
Imagine you store the same report directory different runs to the
server. One would expect that the diff between those runs is empty.
It was not the case!
By adding the report hash to the `report_path_hash` calculation,
seemingly identical reports - with different report hashes - now will be
considered …
=> [fix][clang][server] Add report hash to the report_path_hash

.github/workflows/config_coverage.yml, .github/workflows/config_label_check.py
A CI job which we can use to check if the latest LLVM version (as available in the official PPA) has some checkers added which we haven't set a severity for. The job fails if this list is not empty. :slightly_smiling_face: I added the option to filter checkers, groups, etc. we don't seem to care about.
~~In addition, the job also lists all the checkers we know a severity for, but the checker no longer exists. While these are reported, the CI isn't set up to fail if this is the case.~~ This option exists in the script, but is disabled by default.
=> [CI] Add a job that checks coverage of checker labelling

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/arg.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/config/test_config.py
Previous to this patch, multiple analyzer configs could be specified
like this:
CodeChecker analyze ./compile_commands.json -o ./reports -c --verbose debug \
--analyzers clang-tidy \
--analyzer-config clang-tidy:HeaderFilterRegex=".*" clang-tidy:AnalyzeTemporaryDtors="true"
However, if you specifiy --analyzer-config more than once, the only the
last one counts, like many other flags.
The problem is that --analyzer-config may be specified from both the CLI
and a CodeChecker config file, and even in this case, only one of these
would count.
Also, the -analyzer-config flag from the Clang Static Analyzer works
differently, as multiple -analyzer-configs in the invocation and
appended, not overwritten. Coming from that space, that philosophy feels
more intuitive to me, and I think other users …
=> [config][CLI] Merge, and don't override when multiple --analyzer-configs are specified

.github/workflows/config_coverage.yml
GitHub seems to have modified the base Ubuntu image which now comes with a specific version of `clang-tidy` pre-installed.
The change happened last week because the job 10 days ago was successfully executed, while 3 days ago (last Sunday), we started observing the following failures across multiple projects:
```
update-alternatives: error: alternative clang-tidy can't be slave of clang: it is a master alternative
Error: Process completed with exit code 2.
```
Changing over to registering two top-level alternatives entries fixes the issue.
> Mirrors whisperity/CodeChecker-Action#3
=> [CI] Fix install of PPA `clang-tidy` in config coverage job

Makefile, codechecker_common/cli.py
Created a new target for easier and probably faster development
workflow. Instead of copying the modules of CodeCheker in the build
directory, this target will create a symbolic link to them.
Invoking make with the new `dev_package` and setting the `CC_LIB_DIR`
environment variable with
`export CC_LIB_DIR=/path/to/codechecker/build/CodeChecker/lib/python3`
makes your build folder in a way, that your changes in the python
source code takes effect immediately in CodeChecker (upon restarting
the CodeChecker service  and without invoking `make package` again).
=> [feat] Add dev_package target

analyzer/codechecker_analyzer/pre_analysis_manager.py
Print debug logs in a quoted form so it is processable manually easily.
=> [log] Improve some debug log

config/labels/analyzers/clang-tidy.json
The location of clang-tidy documentations changed. Until now they were
at the same directory level, but they have been organized to separate
directories based on their main group names.
Fixes #3701
=> [doc] Clang-tidy doc URLs changed

web/server/codechecker_server/api/report_server.py
When filtering for reports that occur anywhere on the bugpath (i.e.
not just the last point is in a given file) then searching for files
containing no reports is necessary.
=> [fix] File filter count for files with 0 reports

.github/workflows/config_coverage.yml
Enables the weekly "checker coverage" CI job for Cppcheck labels.
> Closes #3723.
=> [CI][analyzer] Run coverage check for Cppcheck checkers

web/server/vue-cli/src/components/Statistics/Checker/CheckerStatistics.vue, web/server/vue-cli/src/components/Statistics/Component/ComponentStatistics.vue, web/server/vue-cli/src/components/Statistics/Overview/Overview.vue, web/server/vue-cli/src/components/Statistics/Severity/SeverityStatistics.vue, web/server/vue-cli/src/components/Statistics/UniqueStatWarning.vue
The help message of "number of outstanding reports" is changed.
Also the information about the interpretation of numbers in unique mode
on the statistics page is less conspicuous.
=> [gui] Minor label improvements in the GUI

analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py
Cppcheck can emit more reports. The trade-off is a worse false positive ratio.
=> [feat] Add inconclusive analyzer option to Cppcheck

web/client/codechecker_client/cmd/cmd.py, web/server/codechecker_server/api/report_server.py, web/server/codechecker_server/server.py, web/tests/functional/delete_runs/test_delete_runs.py
In order to improve the load times of certain pages of the CodeChecker
GUI, we cache some information instead of querrying it. For instance, we
don't make a query for how many runs there are in each product every
time when the product page is opened, but rather have a config database
that already has this number.
The idea was that every time a run is added, the num_of_run column is
incremented, and whenever one or more runs were deleted, it is
appropriately decreased. However, this latter operation was faulty, and
no matter how many runs were deleted, the number was only decreased by
one.
Since this number was never actualized by the real number of runs, over
the course of months, these numbers could have (and did!) diverge by
hundreds.
This patch, in addition to fixing the run deletion …
=> [fix][db][web] Correctly decrease the num_of_run field in the config db when runs are deleted

analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py, analyzer/tests/functional/analyze_and_parse/test_files/Makefile, analyzer/tests/functional/analyze_and_parse/test_files/cppcheck_include.cpp, analyzer/tests/functional/analyze_and_parse/test_files/cppcheck_include.output, analyzer/tests/functional/analyze_and_parse/test_files/cppcheck_undef_include.output, analyzer/tests/functional/analyze_and_parse/test_files/includes/simple.h
Compiler paramters in format of -I </path/to/file> were handled
incorrectly in Cppcheck. Only the -I part were included in the analyzer
command resulting in a failing analysis.
=> [fix] Fix compiler params with space for Cppcheck

web/server/codechecker_server/api/report_server.py, web/tests/functional/report_viewer_api/test_report_counting.py
The error happened when getFileCounts() function got a filter where both
"filepath" and "componentNames" fields were used.
=> [bugfix] Invalid SQL query when filter for file and source component.

analyzer/codechecker_analyzer/analyzers/clangsa/ctu_triple_arch.py, analyzer/tests/functional/ctu/test_ctu.py, analyzer/tests/functional/ctu/test_files/buildlog.json
The implicit include paths should be added after the user-defined flags
and include paths even in the pre-ctu phase, otherwise the build commands
will not be equivalent with the original ones.
=> [bugfix] Fix system include path order

analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py, analyzer/tests/functional/analyze/test_analyze.py
Analyzer tests were missing for the cppcheck standard forwarding. The standard translation is also tested in case of a gnu** standard is given.
Also added a small change in the business logic for handling the standard parameter. This should make it more robust against future refactoring.
=> [analyzer] Tests for Cppcheck standard handling

analyzer/codechecker_analyzer/analysis_manager.py
The cppcheck needs the original environment
when invoked. This quick fix restores it
at analyzer invocation.
=> Quick fix for cppcheck environment

web/server/codechecker_server/api/report_server.py, web/server/codechecker_server/server.py
This getDiffResultsHash() function is returning a set of reports based on what are they compared to in a "CodeChecker cmd diff" command. Earlier this function didn't consider false positive and intentional reports as closed reports. The client's behavior also changed from CodeChecker 6.20.0 and this behavior is adapted to the new server behavior. The problem is that the old client works correcly only with the old server. For this reason we are branching based on the client's version.
=> [bugfix] Old client has different behavior with new server

web/server/codechecker_server/api/report_server.py
In a previous commit (f6d0fedaf14b583df7bd26078a8a22b557be57c6) we fixed a bug, which was about getting the difference of false positive reports in a baseline to a local directory. For further details see the message of that commit. However, another bug still remained in the system, when the diff command compared a report directory to a specific run tag. This case is fixed by this commit.
=> [bugfix] Different behavior of diff when run tags are provided

web/server/codechecker_server/api/mass_store_run.py, web/tests/functional/review_status/test_review_status.py
When a review status is set in the GUI then a new entry is inserted to review_statuses table. Every time the same report is stored, its review status date was updated. This date shouldn't be updated, because not the storage sets a review status rule's date.
=> [bugfix] Don't update review status date

analyzer/codechecker_analyzer/pre_analysis_manager.py
Exceptions thrown in a thread pool by default stay in the thread pool
(won't be re-raised at the call to map_async or similar functions).
However, you can query whether an exception occured with the help of
AsyncResult.successful().
This patch is simple -- don't pretend that pre-analysis exceptions can
be ignored, just because they run asyncronously, exceptions there are
just as severe as elsewhere.
=> [ctu] Don't silently ignore exceptions thrown in pre-analysis

analyzer/codechecker_analyzer/analyzer_context.py, analyzer/config/analyzer_version.json, analyzer/tests/functional/analyze/test_analyze.py, scripts/build/extend_version_file.py, web/codechecker_web/shared/webserver_context.py, web/config/web_version.json
This patch is largely the same as d24c22cd, but without the rc fields actually being used in the json files. Credit to Tibor Brunner.
=> [cfg] Allow for release candidate status to be also specified

codechecker_common/util.py
When called with a set, the chunks function gave back as many chunks, as the length of the list.
=> [fix] Fix chunks function not working on certain iterables

analyzer/tests/functional/host_check/test_host_check.py
..as that is a frontend flag. Not sure why this test ever passed!
=> Add -Xclang to test_host_check.py

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, docs/analyzer/checker_and_analyzer_configuration.md, docs/analyzer/user_guide.md
> Closes #3757 
> cc @dilyanpalauzov @ryao
Hopefully this is a good enough solution we can mention in CodeChecker's documentation until Z3 support in official Clang picks up.
=> [analyzer][doc] Mention that Z3 as the constraint solver is highly unstable

tools/report-converter/codechecker_report_converter/source_code_comment_handler.py
The regex search() which intent to find codechecker source code comments are swappable with a much faster string.find() method. This will greatly improve performance of retrieving source code comments from the source files.
=> [refactor] Change the regex search to string search

config/labels/analyzers/clangsa.json
As I complained in
https://github.com/Ericsson/codechecker/issues/2289 back in the day, apiModeling checkers should NEVER be explicitly disabled or enabled. CodeChecker seems to somewhat agree, because all apiModeling checkers we do have records on are present in all profiles. This is still incorrect though.
ApiModeling checkers are similar to core checkers, namely that if you disable them, you cannot expect the analyzer to function properly. However, we have even fewer excuses to disable them, because they are incapable of emitting reports (there is an assert that fires if they would).
However, if they are a part of profile, they can be unintentionally disabled through them.
Removing them from this file wouldn't prevent powerusers from disabling them however, just prevents unintentional …
=> [analyzer][cfg] Don't acknowledge apiModeling checkers

web/client/codechecker_client/cmd_line_client.py, web/tests/functional/cmdline/test_cmdline.py
In detailed view the run name should also be displayed in the JSON output of "CodeChecker cmd results ..." command.
=> [cmd] Run name in command line results

analyzer/tests/unit/test_log_parser.py, codechecker_common/skiplist_handler.py, docs/analyzer/user_guide.md
Hashmark (#) character can be used for commenting lines out in skipfiles. Earlier these lines were excluded with the following message:
"Skipping malformed skipfile pattern: ..."
=> [feat] Comment lines in skipfile

analyzer/codechecker_analyzer/analysis_manager.py
When CodeChecker does an analysis, it collects the results in a folder in plist files. However, when a new analysis is run where the result folder is the same, FOR EACH RESULT FILE a warning is issued about it being overwritten.
This is completely overkill, especially when this is the expected behaviour, like in the case of incremental analysis.
I changed these to debug level. I didn't change the 'info' level for when the '-c' flag is used (that also issues a log message, but in a lower severity), because that feels appropriate.
=> [analyzer] Change the log level to debug when overwriting plist files

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/tests/functional/skip/test_skip.py
When compilation database is generated by intercept build then a build
action in this JSON file contains "arguments" field instead of "command"
which is a list of command-line arguments instead of a single string.
CodeChecker supports only "command" field, so this transformation must
be done in "CodeChecker analyze" command in order to avoid failure
when building SkipHandler with "--file <header_file>" flag.
Fixes #3683
=> [bugfix] Crash with intercept-build based compilation database

web/server/codechecker_server/database/db_cleanup.py
The garbage collection of analysis_info table has been restructured because the original query exceeded a 2min timeout.
=> [db] Garbage collection of analysis_info timeout

analyzer/codechecker_analyzer/buildlog/log_parser.py
Exactly what it says on the tin! This flag, as I understand it, only affects the backend of the compiler.
=> [analyzer] Ignore flag '-mword-relocations'

analyzer/codechecker_analyzer/analyzers/analyzer_types.py, analyzer/codechecker_analyzer/cmd/fixit.py, analyzer/tests/functional/fixit/test_fixit.py
Clang tidy may provide automatically applicable fixits. These can be applied by clang-apply-replacements tool. This tool gets a directory as input which contains .yaml files describing the replacements. If any of these .yaml files can't apply for some reason, then the rest is skipped.
This clang tool is added a flag named --ignore-insert-conflict which ignores the error event and continues the application of further .yaml files. If CodeChecker recognizes the existence of this flag then it will be used, otherwise CodeChecker creates a temporary directory with a single .yaml file and applies them one by one.
=> [fix] Apply all fixits

config/labels/analyzers/clang-tidy.json
bugprone-reserved-identifier and bugprone-macro-parentheses are removed from sensitive profile because they give too many false-positive reports.
=> [cfg] Remove some checkers from sensitive profile

analyzer/tests/functional/fixit/test_fixit.py
In some environments/Python versions the standard input given to subprocess.Popen is handled differently. This fix uses the standard input parameter in a way that it works in every environment.
=> [test] Fix fixit test

web/server/vue-cli/e2e/commands/clearAndSetValue.js, web/server/vue-cli/e2e/pages/product.js, web/server/vue-cli/e2e/pages/report.js, web/server/vue-cli/e2e/specs/reviewStatusRule.js
Wait until the div with class v-overlay__srim disappears from the font
of the search bar.
Should fix #3435
=> [gui] Fix for filter product in gui test

analyzer/requirements.txt, analyzer/requirements_py/dev/requirements.txt, analyzer/requirements_py/osx/requirements.txt, web/requirements.txt, web/requirements_py/db_pg8000/requirements.txt, web/requirements_py/db_psycopg2/requirements.txt, web/requirements_py/dev/requirements.txt, web/requirements_py/osx/requirements.txt
* This change is necessary but not sufficient for Python `3.11` support because `lxml` versions below `4.9.0` are incompatible
* See the `lxml` changelog section about adaptation to `3.10` & `3.11` : https://github.com/lxml/lxml/blob/ff82753bd09408ecfd6cacf7da67257495dc1335/CHANGES.txt#L35
Signed-off-by: Ferenc Géczi <ferenc.gm@gmail.com>
=> [req] Upgrade `lxml` to `4.9.1`

web/client/codechecker_client/cmd/cmd.py, web/tests/functional/diff_local/test_diff_local.py, web/tests/libtest/codechecker.py
When CodeChecker cmd diff is invoked like this:
CodeChecker cmd diff -n new_run
it will crash instead of gracefully exiting and warning about the
missing -b flag. This patch fixes that.
=> [cmd] Gracefully exit instead of crashing when cmd diff is missing a param

analyzer/codechecker_analyzer/analyzer_context.py, analyzer/codechecker_analyzer/buildlog/log_parser.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/parse.py, analyzer/tests/unit/test_log_parser.py, codechecker_common/checker_labels.py, codechecker_common/cmd_config.py, codechecker_common/util.py, tools/report-converter/codechecker_report_converter/report/parser/plist.py, tools/report-converter/codechecker_report_converter/util.py, web/client/codechecker_client/cmd/store.py, web/client/codechecker_client/cmd_line_client.py, web/client/codechecker_client/credential_manager.py, web/client/codechecker_client/metadata.py, web/codechecker_web/shared/webserver_context.py, web/server/codechecker_server/api/mass_store_run.py, web/server/codechecker_server/instance_manager.py, web/server/codechecker_server/metadata.py, web/server/codechecker_server/session_manager.py, web/tests/libtest/env.py
"load_json_or_empty" is a too long name for this function, and the
second part doesn't carry any information.
This function is only used for opening JSON files, so "kind" parameter
is not necessary.
Also move this load_json() function to codechecker_common.util module
because originally it was under report converter tool, but most usages
were in all other parts of CodeChecker. Many times this was the only
dependency towards report_converter.
=> [refactor] Rename and fix load_json_or_empty

analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py
Using Clang option "-stdlib=libc++" failed with:
cppcheck: error: unrecognized command line option: "--std=libc++"
=> Fix error using Clang option '-stdlib=libc++'

docs/script_update.md
Remove three bugs:
- $MASTER_EXISTS vs. $PREVIOUS_EXISTS bug fixed with simpler test
- Using quotes around $ANALYZER_OPTIONS when calling CodeChecker results in an error
- Fix escaping and indentation of $DIFF_CMD
- we could use <<- and a real tab to indent END but the web formatting doesn't preserve the tab
Fix style issues:
- Use a variable instead of a file to store $WAS_OUTPUT
- Remove superfluous curly braces.
=> Fix three bugs and a couple of style issues

web/server/codechecker_server/api/report_server.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py
Suppose we have a server with two non-empty, non-identical runs, Example1 and Example2. The following invocation:
CodeChecker cmd diff -o rows --url localhost/Default -n "Example2" -b "Example1" --new --uniqueing on
would have crashed at a thrift call level. If uniqueing wasn't on, the crash was abscent as well.
The root of the problem wasn't on the thrift level, however, but rather that a thrift function was invoked with None values, when said parameters mustn't have been None.
Specifically, these values were the file ID's of some reports. The file ID, column and row numbers of a report are None in the ReportData with uniqueing, but are proper values otherwise.
This makes some sense -- if 10 reports have the same report hash, by uniquing we obtain a report that describes 10 reports, so …
=> [cmd] Fix a crash with CodeChecker cmd diff --unique on

analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py
=> [bugfix] Don't convert cppcheck parameters to absolute path

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/analyzers/config_handler.py, analyzer/codechecker_analyzer/analyzers/cppcheck/config_handler.py, analyzer/codechecker_analyzer/cmd/checkers.py, analyzer/tests/functional/cmdline/test_cmdline.py
--warnings flag made "CodeChecker checkers" print clang-diagnostic... checkers. Now this is deprecated, because all these warnings are considered as normal checker names.
The corresponding codes have been moved under clang-tidy config handler instead of the top-level file.
=> [cmd] Deprecate --warnings flag

analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/codechecker_analyzer/cmd/checkers.py, docs/analyzer/user_guide.md, docs/web/user_guide.md, web/client/codechecker_client/cmd/cmd.py, web/client/codechecker_client/cmd_line_client.py
Some flags are removed from the code base that are deprecated for a while.
Also, the deprecation of --ctu-reanalyze-on-failure is undone, because it will not be deprecated in the near future, probably.
=> [cmd] Remove some deprecated flags.

docs/README.md
While running build steps inside `ubuntu:22.04` container, `python3-setuptools` is also required.
=> README.md: add `python3-setuptools` dependency

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, docs/analyzer/user_guide.md
CodeChecker analyze --tidy-config is a rarely used and redundant flag. ClangTidy options can be given through .clang-tidy file, --analyzer-config, --checker-config and --tidyargs flags.
=> [cmd] Remove --tidy-config flag

analyzer/codechecker_analyzer/analyzers/clangtidy/config_handler.py, analyzer/tests/unit/test_checker_handling.py, web/tests/functional/detection_status/test_detection_status.py, web/tests/libtest/codechecker.py
Seems like I never tested this well enough in
https://github.com/Ericsson/codechecker/pull/3698, because I could
negate a condition in config_handler.py and no tests broke. This broke
in https://github.com/Ericsson/codechecker/pull/3820, however, when
hicpp-* was mistakenly not understood to be a checker, which caused an
error (instead of a warning).
=> [fix] Fix a condition about checkers being compiler warnings 

web/server/vue-cli/src/App.vue
Due that the keep-alive component cache is used wrapping the router view, the products page was cached after logout.
Now the keep-alive inclusion list is dynamically adjusted according to the user authentication state.
The cache is only kept for one login session.
=> [web] Fix stale permission caching

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, docs/analyzer/user_guide.md
Its been a while since we rewrote these docs. Much has changed in CodeChecker since -- we started natively supporting analyzers other than clang, with even more along the way. Also, we never really wrote it down how to enable/disable checkers with the use of labels/guidelines. I also took on the liberty to use a great trick to make documentations easier to read.
Brace yourselves: they are... paragraphs. Crazy, right?
=> [docs] Reword what labels, guidelines, checkers mean, and their enabling

analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
The `-arch` flag was passed to the clangsa analyze command with a trailing space. This resulted in a wrong invocation, where the command inculded this flag like this: `'arch ' arm64`.
Fixes #3847
=> [fix] Pass arch flag correctly

web/server/codechecker_server/api/mass_store_run.py
This pull request tries to optimize the store process by trimming down on the python access layer of SQLAlchemy.
Consists of two parts:
1. Only get the review status rules from the source code in the initial time of the report storage. After all the reports were added to the database, in a separate steps first get all applying review status rules from the server, then do a "bulk update" of all the newly stored reports, where a GUI based review status rule applies.
2. Cache the severity of the reports. Before this patch, a relatively expensive search of the checker labels were done, for every report being stored. Due to the nature of the analysis results, the number of reports greatly outweigh the number of type of reports (checkers), by caching this severity level can improve the store …
=> Further enhancements to speed up the store procedure

analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py, analyzer/codechecker_analyzer/arg.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/functional/cmdline/test_cmdline.py, docs/analyzer/user_guide.md
"CodeChecker analyze" command has a --checker-config flag. The parameter
of this flag should be in the following format:
`<analyzer>:<checker>:<option>=<value>`
clang-tidy tool requires a "." character between the checker and the
option, so CodeChecker should convert it from : to .
The format of --checker-config (and --analyzer-config) is now checked
at the command line parsing phase, so it is done with a common algorithm
for all analyzer tools.
Earlier the default value of --analyzer-config was
"clang-tidy:HeaderFilterRegex='.*'", so clang-tidy analysis of header
files is also done. This is not a default value for the flag anymore,
but it is handled under clang-tidy module.
=> [bugfix] Required format for --checker-config

analyzer/codechecker_analyzer/buildlog/log_parser.py
Should fix unwanted insertion of -isystem includes.
=> Forward --driver-mode compiler flag to the analyzer

analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/analyze/test_analyze.py
Altough discouraged, if someone really insists on having a soft warning when a checker is supplied to --enable or --disable, they can use the new flag '--no-missing-checker-error', which is disabled by default.
=> [analyzer] Add a new flag to demote missing checker errors to a warning

web/server/codechecker_server/api/report_server.py, web/server/vue-cli/src/components/Report/ReportFilter/Filters/TestcaseFilter.vue, web/server/vue-cli/src/components/Report/ReportFilter/Filters/index.js, web/server/vue-cli/src/components/Report/ReportFilter/ReportFilter.vue, web/server/vue-cli/src/views/Reports.vue, web/tests/functional/component/test_component.py, web/tests/functional/db_cleanup/test_db_cleanup.py, web/tests/functional/detection_status/test_detection_status.py, web/tests/functional/diff_remote/test_diff_remote.py, web/tests/functional/dynamic_results/test_dynamic_results.py, web/tests/functional/extended_report_data/test_extended_report_data.py, web/tests/functional/report_viewer_api/test_get_run_results.py, web/tests/functional/report_viewer_api/test_hash_clash.py, web/tests/functional/report_viewer_api/test_remove_run_results.py, web/tests/functional/report_viewer_api/test_report_counting.py, web/tests/functional/report_viewer_api/test_report_filter.py, web/tests/functional/run_tag/test_run_tag.py, web/tests/libtest/thrift_client_to_db.py, web/tests/projects/dynamic/main.c_clang-tidy_0212cbc2c7194b7a5d431a18ff51bb1c.plist, web/tests/projects/dynamic/main.c_clangsa_0212cbc2c7194b7a5d431a18ff51bb1c.plist, web/tests/projects/dynamic/main.c_cppcheck_0212cbc2c7194b7a5d431a18ff51bb1c.plist
Dynamic analyzers may produce .plist files which contain the timestamps
when the report was emitted, The timestamps of independent test
executions can overlap. They can be separated by choosing a testcase
during which they were emitted. This patch introduces a testcase filter.
=> Dynamic results annotation filter

analyzer/codechecker_analyzer/analyzer_context.py, web/codechecker_web/shared/webserver_context.py
Version number was misprinted because of improper checking of rc value in version files.
=> Fix version printing

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangtidy/config_handler.py, analyzer/codechecker_analyzer/analyzers/config_handler.py, analyzer/tests/functional/analyze_and_parse/test_files/compiler_warning_simple.output, analyzer/tests/functional/analyze_and_parse/test_files/compiler_warning_wno_group.output, analyzer/tests/functional/analyze_and_parse/test_files/compiler_warning_wno_simple1.output, analyzer/tests/functional/analyze_and_parse/test_files/compiler_warning_wno_simple2.output, analyzer/tests/functional/analyze_and_parse/test_files/compiler_warning_wunused.output, analyzer/tests/unit/test_checker_handling.py, web/tests/functional/report_viewer_api/test_get_run_results.py, web/tests/functional/report_viewer_api/test_report_counting.py, web/tests/functional/report_viewer_api/test_report_filter.py, web/tests/projects/cpp/project_info.json
Previously the handling of clang-diagnostics was flawed because tidy cannot enable compiler warnings when specified  as a checker, only suppression of the resulting reports are available:
From the official [clang-tidy docs](https://clang.llvm.org/extra/clang-tidy/):
> Clang diagnostics are treated in a similar way as check diagnostics. Clang diagnostics are displayed by clang-tidy and can be filtered out using the -checks= option. However, the -checks= option does not affect compilation arguments, so it cannot turn on Clang warnings which are not already turned on in the build configuration. The -warnings-as-errors= option upgrades any warnings emitted under the -checks= flag to errors (but it does not enable any checks itself).
After this patch all of these checkers will be treated as …
=> [fix] Treat clang-diagnostic-* checkers as compiler flags

web/server/vue-cli/src/views/NewFeatures.vue
Turns out we had this fun habit for several releases, but forgot about it in the last few.
=> [doc] Make every second release highlight green

web/server/codechecker_server/api/report_server.py
This is the query produced by the modified logic:
```sql
SELECT
reports.id AS reports_id, 
reports.file_id AS reports_file_id, 
reports.run_id AS reports_run_id, 
reports.bug_id AS reports_bug_id, 
reports.checker_id AS reports_checker_id, 
reports.checker_cat AS reports_checker_cat, 
reports.bug_type AS reports_bug_type, 
reports.severity AS reports_severity, 
reports.line AS reports_line, 
reports."column" AS reports_column, 
reports.path_length AS reports_path_length, 
reports.analyzer_name AS reports_analyzer_name, 
reports.checker_message AS reports_checker_message, 
reports.detection_status AS reports_detection_status, 
reports.review_status AS reports_review_status, 
reports.review_status_author AS reports_review_status_author, 
reports.review_status_message AS …
```
=> [fix][server] Fix webapp crash when using component filter

.github/workflows/test.yml, web/requirements_py/dev/requirements.txt, web/server/tests/unit/test_ccldap.py
Mockldap dependency is not supported for a long time. It can't be
installed to the latest Ubuntu versions, due to some of its old version
implicit dependencies (funcparserlib). For this reason the usage of
mockldap module has been eliminated and a simplified mock class has been
introduced instead with hardcoded return values.
This error could be reproduced by "make venv_dev" command which emitted
this error message:
"error in funcparserlib setup command: use_2to3 is invalid."
Fixes https://github.com/Ericsson/codechecker/issues/3892
=> [test] Get rid of mockldap

Makefile
In the Makefile, the `package_gerrit_skiplist` target copies a script to a directory created in the `package_dir_structure` target. However, `package_gerrit_skiplist` does not have a dependency on `package_dir_structure`, and it is possible that `package_gerrit_skiplist` is run before the directory created in `package_dir_structure` actually exists. This can be reproduced by running `make` with multiple jobs (e.g `make -j16`)
=> Makefile: package_gerrit_skiplist should depend on package_dir_structure

web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_local/test_diff_local.py
CodeChecker cmd diff is a little out of whack right now, which is discussed in length here: #3884
One of the reasons why it was possible for this problem to fester into this state is that our testing methodology for diffs (really, the entirety of CodeChecker) is really-really poor. Cmdline diff in particular (though not unique in this manner) were done by literally calling CodeChecker, and reparsing its stdout and stderr by string matching whether we see what we want. 
That is weak even for a python project.
Part of the problem is that key functions/classes in CodeChecker take the ominous "args" argument, which contains the set of user arguments, as well as our defaults. We parse a tiny bit of "args" (possibly redundantly), and then pass it onto another function, that does the same. This …
=> [NFC] Factor args out of the diff logic for unit tests

web/server/vue-cli/e2e/commands/clearAndSetValue.js, web/server/vue-cli/e2e/pages/product.js, web/server/vue-cli/e2e/specs/reportDetail.js, web/server/vue-cli/e2e/specs/reports.js, web/server/vue-cli/e2e/specs/reviewStatusRule.js, web/server/vue-cli/e2e/specs/runs.js
The order of two testcases was swapped, and some of the click() calls
got a 100 msec pause inserted before them.
I've yet to discover the reason why these momentary pauses fix the
shadowing, but it looks like it is working.
=> [fix] One more attempt to fix gui tests

analyzer/codechecker_analyzer/buildlog/log_parser.py
-fno-lifetime-dse is not known by clang.
=> [analyzer] Yet another unknown gcc flag

config/labels/analyzers/cppcheck.json
This checker gives a lot of false positive reports mainly because cppcheck doesn't support the analysis on different target architectures.
=> [analyzer] Disable cppcheck-preprocessorErrorDirective explicitly

.github/workflows/snap.yml
The deployment process failed for the last two release.
This patch intend to fix it.
=> Update Snapstore publish action

tools/report-converter/codechecker_report_converter/analyzers/spotbugs/analyzer_result.py
The `report-converter` fail with an exception when a SpotBugs input has a `<SourceLine>` element without a `source_path` attribute.
---
Example for an element like above explained from a SpotBugs run:
```xml
<Method classname="org.w3c.dom.Element" name="getAttribute" signature="(Ljava/lang/String;)Ljava/lang/String;" isStatic="false" role="METHOD_RETURN_VALUE_OF">
<SourceLine classname="org.w3c.dom.Element"/>
<Message>Return value of org.w3c.dom.Element.getAttribute(String) of type String</Message>
</Method>
```
In this case the `report-converter` failed with the following exception:
```text
Traceback (most recent call last):
File "<personal path>\codechecker\tools\report-converter\codechecker_report_converter\cli.py", line 243, in <module>
main()
File "<personal …
```
=> Fix exception when SourceLine has no source_path attribute

web/server/vue-cli/e2e/specs/reports.js
The overlay bug still occured in at least the following two runs:
https://github.com/Ericsson/codechecker/actions/runs/5045215504
https://github.com/Ericsson/codechecker/actions/runs/5046478584?pr=3915
=> [fix] Fix newly surfaced gui test error during cleanup plan testing

web/api/report_server.thrift, web/client/codechecker_client/cmd_line_client.py, web/server/codechecker_server/api/report_server.py, web/tests/functional/report_viewer_api/test_remove_run_results.py
"CodeChecker cmd del ..." command gives no feedback if no run was deleted based on the given parameters, however, this would be an important feedback for the users.
=> [cmd] Warning message on no run delete.

analyzer/codechecker_analyzer/buildlog/log_parser.py, analyzer/tests/unit/test_option_parser.py
If an assember command is analyzed then the recognized language remains None which can't be provided after -x flag in a subprocess.Popen call. So -x is added to the command if the recognized language is not None.
Fixes #3670
Fixes #3730
=> [analyzer] Fix crash when an assembler command is analyzed

analyzer/codechecker_analyzer/analyzer_context.py, analyzer/codechecker_analyzer/env.py, analyzer/tests/unit/test_log_parser.py, analyzer/tools/build-logger/README.md, analyzer/tools/build-logger/tests/unit/__init__.py, analyzer/tools/build-logger/tests/unit/test_paths.py
It can happen that a build system overwrites the LD_LIBRARY_PATH environment variable, this could result in the following error:
```
“ERROR: ld.so: object 'ldlogger.so' from LD_PRELOAD cannot be preloaded: ignored”
```
=> [analyzer] Use absolute path to logger.so in LD_PRELOAD

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/tests/unit/test_checker_option_parsing.py
Starting with LLVM15 / clang-tidy-15, the output of `--dump-config` has changed, and the old parser failed to parse the options in the new format. We need full YAML parsing now, the format looks like this:
```
---
Checks:          'clang-diagnostic-*,clang-analyzer-*,*'
AnalyzeTemporaryDtors: false
FormatStyle:     none
[…]
CheckOptions:
performance-unnecessary-value-param.IncludeStyle: llvm
readability-suspicious-call-argument.PrefixSimilarAbove: '30'
[…]
```
This solution implements a simple trial-and-error approach: It first tries the old parsing version, and if that fails, it tries the new one. This seems a lot simpler than first trying to figure out the clang-tidy version by e.g. parsing the output of `clang-tidy --version`.
=> [analyzer][cmd] Adapt to new clang-tidy checker options format.

tools/report-converter/codechecker_report_converter/analyzers/analyzer_result.py, tools/report-converter/codechecker_report_converter/cli.py, tools/report-converter/codechecker_report_converter/report/parser/plist.py, tools/report-converter/tests/functional/cmdline/test_cmdline.py, tools/report-converter/tests/functional/cmdline/test_files/test_outputs/simple1.out, tools/report-converter/tests/functional/cmdline/test_files/test_outputs/subdir/simple2.out, tools/report-converter/tests/functional/cmdline/test_files/test_outputs/subdir/simple3.out, tools/report-converter/tests/unit/analyzers/test_asan_parser.py, tools/report-converter/tests/unit/analyzers/test_clang_tidy_parser.py, tools/report-converter/tests/unit/analyzers/test_coccinelle_parser.py, tools/report-converter/tests/unit/analyzers/test_cppcheck_parser.py, tools/report-converter/tests/unit/analyzers/test_cpplint_parser.py, tools/report-converter/tests/unit/analyzers/test_eslint_parser.py, tools/report-converter/tests/unit/analyzers/test_golint_parser.py, tools/report-converter/tests/unit/analyzers/test_infer_parser.py, tools/report-converter/tests/unit/analyzers/test_kerneldoc_parser.py, tools/report-converter/tests/unit/analyzers/test_lsan_parser.py, tools/report-converter/tests/unit/analyzers/test_mdl_parser.py, tools/report-converter/tests/unit/analyzers/test_msan_parser.py, tools/report-converter/tests/unit/analyzers/test_pyflakes_parser.py, tools/report-converter/tests/unit/analyzers/test_pylint_parser.py, tools/report-converter/tests/unit/analyzers/test_roslynator_parser.py, tools/report-converter/tests/unit/analyzers/test_smatch_parser.py, tools/report-converter/tests/unit/analyzers/test_sparse_parser.py, tools/report-converter/tests/unit/analyzers/test_sphinx_parser.py, tools/report-converter/tests/unit/analyzers/test_spotbugs_parser.py, tools/report-converter/tests/unit/analyzers/test_tsan_parser.py, tools/report-converter/tests/unit/analyzers/test_tslint_parser.py, tools/report-converter/tests/unit/analyzers/test_ubsan_parser.py
Sometimes dynamic analysis is executed for the code base several times with different parameters. The output of these analyses may go to different log files which are given to report-converter one-by-one. If there are reports for the same source file in different log output files then the resulting .plist files will be overwritten at a subsequent execution of report-converter.
In this patch we make it possible to give multiple log files or directories containing log files to the report-converter. The reports in these files and directories will be collected all and will be converted to .plist without overriding the ones coming from a different log file.
=> [report-converter] Enable multiple input for report-converter

analyzer/tests/Makefile, analyzer/tools/build-logger/tests/Makefile, analyzer/tools/merge_clang_extdef_mappings/tests/Makefile, analyzer/tools/statistics_collector/tests/Makefile, docs/tests.md, tools/bazel/tests/Makefile, tools/report-converter/tests/Makefile, tools/tu_collector/tests/Makefile, web/tests/Makefile
Previously, unless you wanted to directly invoke pytest (and even before
that, nosetests), you had to edit the corresponding config file in order
to provide additional args to pytest.
Invoking pytest directly is possible, but cumbersome -- you need to
remove the workspace directory, set environmental variables `REPO_ROOT`,
`BUILD_DIR`, `TEST_PROJ` and `TEST_CLANG_VERSION`.
I am not saying this is ideal, maybe we should make direct invocation a
little less painful, but until we do that, I added support for another
environmental variable, `EXTRA_PYTEST_ARGS`. For instance the following
invocation selects only the test matching 'test_source_suppress_export':
```
EXTRA_PYTEST_ARGS="-k test_source_suppress_export" TEST=tests/functional/suppress make test_analyzer_feature
```
=> [test] Allow additional pytest args to be given through make targets

tools/report-converter/codechecker_report_converter/analyzers/sanitizers/address/parser.py, tools/report-converter/codechecker_report_converter/analyzers/sanitizers/parser.py, tools/report-converter/codechecker_report_converter/analyzers/sanitizers/ub/parser.py, tools/report-converter/tests/unit/analyzers/ubsan_output_test_files/ubsan1.plist, tools/report-converter/tests/unit/analyzers/ubsan_output_test_files/ubsan2.plist
When UBsan and Asan tools emit a report then the checker name is
UndefinedBehaviorSanitizer and AddressSanitizer respectively. This could
be more granular, because the checker message could determine which
"checker" emitted it. By "checker" we mean these:
-fsanitize=alignment
-fsanitize=bool
...
=> Introduce sanitizer checker names

web/server/vue-cli/src/components/Report/ReportTree/ReportDetailFormatter.js
Previous to this commit, CodeChecker GUI didn't recognize that when a message starts with "Returning;", it may also signal that we are exiting a function.
```cpp
#include <iostream>
void f(int *ptr) {
delete ptr;
}
void g() {
int *ptr = new int;
f(ptr);
*ptr = 5;
}
```
=> [GUI] Pop the call stack when the message starts with "Returning;"

tools/report-converter/codechecker_report_converter/analyzers/sanitizers/parser.py, tools/report-converter/codechecker_report_converter/report/__init__.py, tools/report-converter/codechecker_report_converter/report/hash.py, tools/report-converter/tests/unit/analyzers/asan_output_test_files/asan.plist, tools/report-converter/tests/unit/analyzers/tsan_output_test_files/tsan.plist
Some dynamic analyzers, like sanitizers generate dynamic parts in the checker message (e.g. memory addresses). These are changing in every execution of the analyer. Since the checker message is part of the report hash, the hash changes too. This is bad, because the report itself is supposed to be the same.
The report converter can provide a static_message field for the report which is a stable version of the checker message. If this field is given then it will be used for hash generation.
=> [feat] Exclude dynamic parts of checker message in hash generation

analyzer/codechecker_analyzer/pre_analysis_manager.py, analyzer/tests/functional/ctu/test_ctu.py
When the compilation command database contains the build information of a file in a non-existing directory then the pre-analysis phase of CTU shouldn't fail.
=> [fix] Analysis shouldn't fail on non-existing directory

web/server/codechecker_server/api/mass_store_run.py, web/tests/functional/__init__.py, web/tests/functional/diff_cmdline/__init__.py, web/tests/functional/diff_cmdline/test_diff_cmdline.py
We usually test CodeChecker diff by making API calls that one can find
in report_server.py. However, `CodeChecker cmd diff` doesn't invoke
these plainly, but rather wraps it in various functions, for which we
never had proper tests. Until now!
I also made sure to include (almost all) cases discussed here:
https://github.com/Ericsson/codechecker/issues/3884
=> [test] Add missing tests for cmdline diffing, and display a bug for tag diffs

analyzer/codechecker_analyzer/arg.py
Shows:
```
should be<analyzer>:<checker>:<option>=<value>
```
=> Error message: Add a missing space

analyzer/tools/build-logger/src/ldlogger-logger.c
Trying to compile the project in a docker alpine environment using GCC 13.1.1 and got the following error:
```
× Building wheel for codechecker (pyproject.toml) did not run successfully.
11.35   │ exit code: 1
11.35   ╰─> [29 lines of output]
11.35       running bdist_wheel
11.35       running build
11.35       running build_ext
11.35       building 'codechecker_analyzer.ld_logger.lib.ldlogger' extension
11.35       creating build
11.35       creating build/temp.linux-x86_64-cpython-311
11.35       creating build/temp.linux-x86_64-cpython-311/analyzer
11.35       creating build/temp.linux-x86_64-cpython-311/analyzer/tools
11.35       creating build/temp.linux-x86_64-cpython-311/analyzer/tools/build-logger
11.35       creating build/temp.linux-x86_64-cpython-311/analyzer/tools/build-logger/ …
```
=> [logger] + add missing header fcntl.h

analyzer/requirements.txt, analyzer/requirements_py/dev/requirements.txt, analyzer/requirements_py/osx/requirements.txt, codechecker_common/requirements_py/dev/requirements.txt, web/requirements.txt
PyYAML 6.0 is broken with the new Cython 3.0 release. See yaml/pyyaml#601.
As a side note: it would be helpful if `install_requires` in `setup.py` didn't contain `==` requirements. These prevent downstream projects from upgrading versions of things like PyYAML until codechecker makes a new release.
=> [req] Upgrade PyYAML to 6.0.1

web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_cmdline/test_diff_cmdline.py
Source code suppressions seem to work funny (meaning: really buggy) in the context of diffs. An earlier PR, #3944 fixed a similar issue in the local-local diff case: we forgot to take source code suppressions into account for the baseline set.
The issue is somewhat worse for local-remote and remote-local diffs, as discussed in issue #3884.
As a feature, this should be comically simple: calculate the set of outstanding reports from the "baseline" and the "new" sets. Suppose these sets are called O(baseline) and O(new). Then, calculating diffs should be this easy:
* NEW: O(new) - O(baseline)
* RESOLVED: O(baseline) - O(new)
* UNRESOLVED: The intersection of O(baseline) and O(new)
But, for historical and performance reasons, the way we do this is far, far more convoluted. We use two API …
=> [cmd] Fix FP annotations in the case of local-remote diffs

web/server/vue-cli/src/components/Run/RunFilterToolbar.vue, web/server/vue-cli/src/store/modules/run.js
Previously only the run history was affected, when the analyzed before/after options were set. This resulted in a confusing view when the displayed run entries last analyzed date would show outside of the specified date.
This patch fixes this issue as it will hide those runs where the before/after criteria is not met.
fixes #3962
=> [gui] Update run filter when setting the filter options

web/server/vue-cli/src/components/Report/Report.vue
To highlight selected bubble on the report page currently we use only a 2px dashed border. It is hard to detect the active chip section when there are many bubbles in one report file. The active bubble is more highlighted when its opacity is 100 and 70% for the others. The font-weight is bold for active and lighter for non actives. The current modifications emphasize the selected bubble more then the dashed border.
=> [GUI] Change the selected bubble's brightness

.github/workflows/config_coverage.yml, .github/workflows/docker.yml, .github/workflows/pypi.yml, .github/workflows/snap.yml, .github/workflows/test.yml
This change limits the scope of GITHUB_TOKENs to "read-only" for all contexts for the checker actions.
This is one part of adopting security best practices of the OpenSSF based on the ScoreCard tool [1] as outlined in issue #3977.
Moreover, this PR only updates one workflow. For the other workflows, we need to determine if read-only is feasible or if some actions must be run with write permissions.
[1] https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
=> [check actions] setting GITHUB_TOKEN permissions to read

web/tests/functional/diff_cmdline/test_diff_cmdline.py
My previous commit that added cmdline tests targeted local-local, remote-local and local-remote diffs, and remote-remote diffs to a lesser extent. It also added 2 cases related to tags.
This PR adds cases from this issue: #3884, specifically demonstrating the table found in section "Tag diffs" -> "Remote-Remote" _before_ the addition of a third tag.
=> [test] Add several more cmdline tests for tag diffs

analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/tests/unit/test_checker_handling.py
When --stats flag is given to "CodeChecker analyze" these two statistics-based checkers are enabled by default:
- statisticsbased.SpecialReturnValue
- statisticsbased.UncheckedReturnValue
These can't be disabled even with `-d/--disable` if they were enabled by `--stats`.
This patch fixes this bug: now users can disable either statistics-based checker, even if --stats is used.
=> [bugfix] Allow the disabling of statisticsbased checkers

analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/analyze/test_analyze.py, docs/analyzer/user_guide.md
Sometimes users want to execute exactly one checker. This can be done by disabling all checkers and then enabling that one. Some analyzers fail if no checker is enabled. For example, if the user wants to enable one ClangSA checker and disable everything else explicitly, then ClangTidy fails.
After this patch an analyzer will not be triggered if all of its checkers are disabled.
[cmd] Add --disable-all flag
Add --disable-all flag which disables all checkers of all analyzers. It
is equilent to using "--disable default".
Should be merged after #3949.
=> [bugfix] Don't trigger analyzer without enabled checkers

web/server/vue-cli/e2e/specs/reportDetail.js, web/server/vue-cli/src/components/Report/Report.vue, web/server/vue-cli/src/components/Report/ReportStepMessage.vue
Currently on the report detail page there is a red error bubble where we can click on the checker documentation button to have more information about the error. The button click triggers a modal that contains already known information and the real checker documentation URL. 
The modal is unnecessary and it has two steps to navigate to the effective documentation. To reduce the step numbers, there are some modifications in the Report and the ReportStepMessage components. 
When the report page is loaded the first thing is to create an errorChecker, then getting its documentation and passing it to ReportStepMessage via props. The ReportStepMessage component present the checker documentation button if the URL exists. The button refers to the checker error documentation without displaying a …
=> [GUI] Jump directly to documentation url without error modal

web/server/codechecker_server/api/report_server.py, web/tests/functional/diff_cmdline/test_diff_cmdline.py, web/tests/functional/diff_remote/test_diff_remote.py
Despite only two lines of code, this patch is many things all in once:
* We fix a bug where diffing tags returned unexpected (and percieved to
be incorrect) results,
* We redefine what we expect from diffing tags,
* We redefine the expected heaviour around review status rules.
Previously, we regarded review status rules are a timeless property, but
what is even more true, we didn't really know what we expect from them
when it came to diffing tags. This lead to confusion on the developer
side and on the user side as well, and lead to whack-a-mole issues and
patches like https://github.com/Ericsson/codechecker/issues/3675, that was more driven by what users expected from
this feature than a comprehensive plan.
This is okay -- the review status feature and the tag feature grew in
their own …
=> [fix] Refine when a report is regarded as outstanding for tags

web/server/codechecker_server/api/mass_store_run.py
In concurrent storage of two runs containing the same files leads to
duplicate key constraint violation. Some DBMSs can gracefully handle
this issue by supporting "ON CONFLICT DO NOTHING" clause at INSERT
statement.
=> [db] Eliminating duplicate key constraint violations

web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_cmdline/test_diff_cmdline.py
Ideally, when we use CodeChecker cmd diff, we should return exactly what
the server API calls return. We obviously can't do that when either the
baseline or the newline result contains a local directory, since they
are not on the server. In that case, we need to parse the results, check
for review status rules on the server, etc.
However, when both operands _are_ on the server, there is no need to do
additional filtering, lets just trust that the server returns correct
results. If not, we should fix it the server.
Depends on #3995.
=> [diff] Fix a CLI remote-remote bug where we checked the detection status 

Makefile
The `config` folder under `build/CodeChecker` wasn't symlinked before when using `dev_package` target of make, and resulted in  mystical errors occurring in case the developer forgot to manually update  the config contents.
This patch adds symlinking in short of one file which is created build time, (`commands.json`)
=> [QoL] Add config folder contents to the dev_package target

analyzer/codechecker_analyzer/analyzer_context.py, analyzer/tests/unit/test_log_parser.py, analyzer/tools/build-logger/tests/unit/__init__.py
=> replace os.uname() with platform.uname() for Windows support

web/server/vue-cli/src/views/Reports.vue
The "timestamp" and "testcase" columns are only needed for a special test case, therefore, they can be removed if their content is completely empty. When the "formattedReports" prop is changed, the values are verified again. If a report had timestamp or testcase, the columns would be displayed again.
=> [GUI] Unnecessary reports columns

analyzer/codechecker_analyzer/cmd/parse.py
The feature can be useful to speed up the parse process when you want to parse one or more specified files. The VSCode Plugin also runs the 'parse --file' command, so the correction can solve the slow file verification problem. It uses metadata.json for plist mapping if the result_source_files section is not empty and contains the pairing of source files and plist files. Before the new feature, the process read all existing plist files to find the specified source file's reports.
=> Parse file speed up

Makefile
This reverts commit 1ae30cd8c222f43bec1af774779527677e7bbca2.
The reason of this revert is that the original "make package" executed
this scrip too:
${PYTHON_BIN} ./scripts/build/extend_version_file.py -r $(ROOT) \
$(CC_BUILD_DIR)/config/analyzer_version.json \
$(CC_BUILD_DIR)/config/web_version.json
This command modifies the version json files, without this the CodeChecker
commands raise an error during usage.. However, if this modification is
done through the symlinks, then the original json files are modified too,
and shown as changed files in "git status".
=> Revert "Add config folder contents to the dev_package target"

web/client/codechecker_client/cmd_line_client.py, web/tests/functional/diff_cmdline/test_diff_cmdline.py
We already do this on the GUI, but on the cmdline, we default the
detection status to NEW, REOPENED and UNRESOLVED. This makes sense for
runs (where we check whether a report is outstanding at the time of the
query), but not for tags (as a report can have a RESOLVED detection
status but still be outstanding at the time of the tag).
=> [cmd][diff] Ignore detection status for tags

web/server/codechecker_server/api/report_server.py
If the query could not return a report, commentCount would be referenced before assignemt.
The more interesting question is, how could one obtain a reportId on the gui that is nonexistant.
=> [fix] Fix commentCount related error in gui

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
Running codechecker and giving extra arguments for clang-tidy containing environmental variables fails. This issue seems to stem from that `env.replace_env_var` is use without an argument in `analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py`. This should fix it.
**To reproduce the issue, run the following:**
With the file `main.c` containing:
```
#include <stdio.h>
int main(void){
int i = BUILDVAR;
printf("Hello world!\n\tBUILDVAR=%d\n", i  );
return 0;
}
```
and the file `.clangtidy_extra_flags.txt containing:
```
--extra-arg="-DBUILDVAR=$(MY_ENV_VAR)"
```
1. Set the environmental varible `MY_ENV_VAR`
```
export MY_ENV_VAR=55
```
2. Run the following command
```
CodeChecker check -b "gcc main.c -DBUILDVAR=$MY_ENV_VAR" --tidyargs .clangtidy_extra_flags.txt
```
This should …
=> [fix][clang-tidy] Fix env var replace for extra args

analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/tests/unit/test_checker_handling.py, docs/analyzer/user_guide.md
Analyzer config options can be forwarded to the analyzers by --saargs and --tidyargs flags. This was missing for Cppcheck, so --cppcheckargs flag has now been introduced.
Fixes #3936
=> [enhancement] --cppcheckargs flag was missing

web/client/codechecker_client/cmd/store.py
> Related to #3672, but does not implement it.
This is a partial solution that attempts to gracefully kill an ongoing `CodeChecker store` client if the reply to the `massStoreRun()` API call does not arrive in a timely manner. After reaching the timeout, the client throws an exception onto itself and presents an understandable error message about the situation. This implementation is temporary; thus, the timeout is a hard-coded limit.
The client still exits with a failure in these cases because there are no guarantees (and no deterministic ways to check) whether the timeout happened because the TCP connection failed and stuck (which is observed in a lot of cases, unfortunately) or whether the server indeed took more time than allotted to process the stored reports. A successful exit …
=> feat(store): Explicitly time the client out if the connection hung

analyzer/tests/functional/analyze_and_parse/test_files/multi_error_skipped_in_cmd.output
The testcase was failing on new clang version which brought in a new checker. This patch makes the test case resilient to clang version changes.
=> Making an analyze and parse testcase checker set independent

analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzers/analyzer_base.py, analyzer/codechecker_analyzer/analyzers/analyzer_types.py, analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py, analyzer/codechecker_analyzer/analyzers/gcc/analyzer.py, analyzer/codechecker_analyzer/cmd/analyzers.py
* Deprecate both `--all` and `--details`, because they were more confusing than useful
* We list all supported (not available) analyzers by default, but print a warning message when its not available.
* We used to query the version of each analyzer binary in a uniform way, but clang, cppcheck, gcc prints their version using different flags, and in different formats. I changed this to call the analyzer plugins' get_binary_version method (which I also implemented in this patch).
=> [analyzers] Deprecate --all and --details for analyzers

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/tests/unit/test_checker_option_parsing.py
The `CodeChecker checkers --checker-config` command did not output the clang-tidy checker options correcly because it left a "." before the actual option.
This patch replaces the dot with a colon.
=> [clang-tidy] Fix Clang tidy checker option output

web/server/vue-cli/src/components/Layout/TheHeader.vue, web/server/vue-cli/src/main.js
Previously when changing between the reports and statistics views the report filter configuration wasn't retained.
This patch implements the feature of retaining the filter configuration between the reports view and the different statistics sub pages.
Fixes #3828
=> [gui] Retain filter configuration between reports and statistics views

analyzer/codechecker_analyzer/analyzer_context.py, analyzer/codechecker_analyzer/analyzers/analyzer_types.py, analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py, analyzer/codechecker_analyzer/analyzers/gcc/analyzer.py, analyzer/codechecker_analyzer/arg.py, analyzer/codechecker_analyzer/cmd/analyze.py, docs/analyzer/user_guide.md
This environmental variable can be used the specify the absolute path of
an analyzer. Similar to https://github.com/Ericsson/codechecker/pull/4041, but this is the only solution we can
realistically get though the door.
Here is a glimpse of how the error messages look like:
```bash
$ CC_ANALYZER_BIN="gccldjkfg:/usr/bi++-13;clangsa;g++:g" CodeChecker check -b "gcc double-free.c -c" -o resultNative/ --analyzers=gcc -c -e extreme
[INFO 2023-10-24 15:22] - Starting build...
[INFO 2023-10-24 15:22] - Using CodeChecker ld-logger.
[INFO 2023-10-24 15:22] - Build finished successfully.
[ERROR 2023-10-24 15:22] - Unsupported analyzer_name name 'gccldjkfg' given to CC_ANALYZER_BIN!
[ERROR 2023-10-24 15:22] - '/usr/bi++-13' is not a path to an analyzer binary given to CC_ANALYZER_BIN!
[ERROR …
```
=> [analyzer] Add support the CC_ANALYZER_BIN env var 

config/labels/analyzers/clang-tidy.json, config/labels/analyzers/clangsa.json
The following checks were analysed on our usual set of ~20 test projects, these produced no crashes and _most_ of them gave sensible results. Personally, I really enjoy the fact that [`bugprone-incorrect-enable-if`](http://clang.llvm.org/extra/clang-tidy/checks/bugprone/incorrect-enable-if.html) is a thing!
* `bugprone-empty-catch`
* `bugprone-incorrect-enable-if`
* `bugprone-non-zero-enum-to-bool-conversion`
* `bugprone-optional-value-conversion`
* `cppcoreguidelines-misleading-capture-default-by-value`
* `cppcoreguidelines-noexcept-destructor`
* `cppcoreguidelines-noexcept-move-operations`
* `cppcoreguidelines-noexcept-swap`
* `performance-noexcept-destructor`
* `performance-noexcept-swap`
* `readability-reference-to-constructed-temporary`
* `core.BitwiseShift`
* …
=> chore(config): Add labels for new checks of Clang SA & Tidy

web/server/codechecker_server/api/mass_store_run.py, web/tests/functional/review_status/test_review_status.py
When a report is suppressed by a source code comment, then it should be stronger than a review status rule with the same bug hash. This is working fine when a new review status rule is set in the GUI for existing reports. Setting a review status rule has effect on the reports which don't have a review status provided in a source code comment.
However, if a new report is stored, then its review status is set based on the review status rule, even if it has a source code comment. This is fixed by this patch: the source code comment should be stronger even in a run store process.
=> [fix] Source code comment over review status rule

tools/report-converter/codechecker_report_converter/analyzers/clang_tidy/parser.py, tools/report-converter/tests/unit/analyzers/test_clang_tidy_parser.py, tools/report-converter/tests/unit/analyzers/tidy_output_test_files/tidy3-clang17.out
clang-tidy version 17 introduced a new fixit diagnostic formatting. The report converter is now prepared to parse this new format. It also still supports the old format.
Fixes #4047
=> [report-converter] Support Clang 17.0+ FixIt in Clang-Tidy

config/labels/analyzers/clang-tidy.json
misc-include-cleaner checker results too many reports and causes an undeterministic failure at storage.
=> Remove a clang-tidy checker from default profile.

analyzer/codechecker_analyzer/analyzers/gcc/analyzer.py
The command "CodeChecker analyzers" fails when a too old gcc doesn't support version getter flags.
=> [fix] Fix stacktrace when gcc analyzer version getter flag is not supported.

docs/analyzer/checker_and_analyzer_configuration.md
This is especially important because we link from the rc1 release page to this doc -- which is currently just a big fat TODO.
=> [docs] Leave a better TODO for gcc docs

web/client/codechecker_client/cmd/store.py
In some cases, spurious exceptions may crop up in the outputs when something goes wrong, and in those cases, threads are usually just given an automatic name like `Thread-1` or so. This patch adds a unique name to the store watchdog so it's clear if that causes an exception (it shouldn't).
=> chore(store): Give a name to the timeout watchdog thread

analyzer/codechecker_analyzer/analyzers/gcc/result_handler.py
...because we need more time to support them. For now, they result in assertion failures when we sanity-check the name of the checker.
=> [gcc] Ignore compiler warnings for the time being

analyzer/codechecker_analyzer/analyzers/gcc/analyzer.py, analyzer/codechecker_analyzer/analyzers/gcc/result_handler.py
The wording in the [GCC
docs](https://gcc.gnu.org/onlinedocs/gcc-13.1.0/gcc/Diagnostic-Message-Formatting-Options.html) is a little confusing, it says
"The ‘sarif-stderr’ and ‘sarif-file’ formats both emit diagnostics in SARIF Version 2.1.0 format, either to stderr, or to a file named source.sarif, respectively."
I thought this will create a sarif file right next to the source file, but in reality, the file is created in the `directory` field of the compilation database file. This patch fixed this by using the stderr output instead of the file output.
=> [gcc][fix] Change gcc's output from file to stderr

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/tests/unit/test_checker_handling.py
**[fix] Bugfix at --enable-all and disable warning**
There was a bug in CodeChecker:
CodeChecker analyze --enable-all --disable clang-diagnostic-unused-variable
This command didn't disable that warning. The problem is that we represent --enable-all with -Weverything in the clang-tidy analyzer command, but -Wno-unused-variable has to be appended too. It was a false assumption that
"clang-tidy -checks='-clang-diagnostic-unused-variable' main.c -- -Weverything" does the job.
**[fix] Fix non-determinism of clang-diagnostic checker appearances**
Earlier we collected the enabled/disabled checkers in a set which
results non-determinism in the appearance of clang-tidy checkers.
Instead of sets we're using lists now.
=> [fix] Bugfix at --enable-all and disable warning

analyzer/codechecker_analyzer/analyzer_context.py
AnalyzerContext.__analyzer_env is lazy initialized via AnalyzerContext.analyzer_env. __parse_CC_ANALYZER_BIN became the first to use it, but erronously accessed the field directly -- which wasn't initialized at that time.
=> [context][fix] Use the property instead of the field for analyzer env

web/server/vue-cli/src/components/Report/Report.vue
There was a bug when the report was loaded. The value of the review status dropdown menu did not change when switching to a report with a different status. 
Now, everytime when the report changes, the reviewData is updated as a computed property.
=> [GUI] Update reviewData when switching between reports

tools/report-converter/codechecker_report_converter/cli.py, tools/report-converter/tests/functional/cmdline/test_cmdline.py
We check (via `nargs`) whether any input paths were given, but we don't actually emit any errors if those paths point nowhere. This can be quite frustrating when the user erronously believes that the input file name was correct, is not given any errors, and left wondering why report-converter is not working.
This patch checks whether those paths actually exist.
=> [report-converter] Check whether input paths exist

analyzer/codechecker_analyzer/analyzer_context.py, analyzer/tests/unit/test_env_var.py
...Mind that this patch is not quite NFC, because I made CC_ANALYZER_BIN find the given executable from path, so we accept "gcc-13" and "/usr/bin/gcc-13" as well. This was rather important for these tests to (hopefully) pass on github as well.
Fixes #4060.
=> [test] Add tests for CC_ANALYZER_BIN

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
When -arch is specified in the compilation commmand '-arch ' was passed to clang-tidy which causes a
parsing error for clang tidy version 17
=> Clang-tidy arch parameter pass fix

scripts/debug_tools/prepare_all_cmd_for_ctu.py, scripts/debug_tools/prepare_analyzer_cmd.py
The default value of ctu-dir and the printing of prepared analyzer
command insteam of writing it to a file was causing issues.
This fixes the script for trivial open source projects.
=> [analyzer][clang][debug] Fix prepare_analyzer_cmd default configuration

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/codechecker_analyzer/pre_analysis_manager.py, analyzer/requirements.txt, analyzer/requirements_py/dev/requirements.txt, analyzer/requirements_py/osx/requirements.txt, codechecker_common/requirements_py/dev/requirements.txt, tools/bazel/requirements_py/dev/requirements.txt, tools/report-converter/codechecker_report_converter/report/checker_labels.py, tools/report-converter/codechecker_report_converter/report/reports.py, tools/report-converter/requirements_py/dev/requirements.txt, tools/tu_collector/requirements_py/dev/requirements.txt, web/requirements.txt, web/requirements_py/dev/requirements.txt, web/requirements_py/osx/requirements.txt, web/server/codechecker_server/server.py, web/tests/functional/authentication/__init__.py, web/tests/functional/cli_config/test_server_config.py, web/tests/functional/db_cleanup/test_db_cleanup.py, web/tests/functional/instance_manager/test_instances.py, web/tests/functional/products/test_config_db_share.py, web/tests/functional/ssl/test_ssl.py, web/tests/functional/storage_of_analysis_statistics/test_storage_of_analysis_statistics.py, web/tests/libtest/codechecker.py
Many functions and members of `multiprocess` lib are exposed dynamically. For this reason pylint is not able to tell what members this lib has (e.g. `multiprocess.Value()`. So these pylint reports have been suppressed.
Another purpose of this commit is to make "superset" relationship for venv_dev: if a CodeChecker developer installs venv_dev, then the content of venv should always be installed. venv_dev just extends them. `multiprocess` was a counterexample for this relationship: it was installed only by `venv` and not `venv_dev`. Such a mistake in the organization of requirements.txt files results missing libraries for developers.
=> [fix] fix venv_dev and multiprocess lib usage

codechecker_common/skiplist_handler.py, tools/report-converter/codechecker_report_converter/report/__init__.py
SkiplistHandler class had a __call__() function which forwarded to
should_skip(), so it didn't really had a real purpose. There was
also a "TODO" in the code to eliminate this function.
=> Eliminate should skip

web/server/vue-cli/e2e/pages/reportDetail.js, web/server/vue-cli/e2e/specs/reportDetail.js, web/server/vue-cli/src/components/Report/Report.vue, web/server/vue-cli/src/components/Report/ReportTree/ReportTree.vue, web/server/vue-cli/src/components/Report/ReportTree/ReportTreeIcon.vue, web/server/vue-cli/src/components/Report/ReportTree/ReportTreeLabel.vue, web/server/vue-cli/src/components/Report/ReportTree/ReportTreeRootItem.js, web/server/vue-cli/src/views/ReportDetail.vue
This PR gives a new report sidebar structure on the report-detail page. There are two main types in the report tree. One of them is the Outstanding category that contains outstanding reports classified into severity groups. The another category is the Closed that contains resolved, and not resolved but closed reports such as false positive, intentional.
Opening the a report-detail page, the report sidebar automatically opens a specific tree where the current report is located. If we changed the review status, the sidebar would react immediately.
=> [GUI] Update report sidebar structure and add review status reactivity

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangsa/result_handler.py, analyzer/codechecker_analyzer/analyzers/clangtidy/result_handler.py, analyzer/codechecker_analyzer/analyzers/cppcheck/result_handler.py, analyzer/codechecker_analyzer/analyzers/gcc/result_handler.py, analyzer/codechecker_analyzer/analyzers/result_handler_base.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/parse.py, analyzer/tests/functional/analyze_and_parse/test_files/Makefile, analyzer/tests/functional/analyze_and_parse/test_files/simple1_review_status1.yaml, analyzer/tests/functional/analyze_and_parse/test_files/simple1_review_status1_glob.yaml, analyzer/tests/functional/analyze_and_parse/test_files/simple1_review_status1_hash.yaml, analyzer/tests/functional/analyze_and_parse/test_files/simple1_review_status_file.output, analyzer/tests/functional/analyze_and_parse/test_files/simple1_review_status_file_glob.output, analyzer/tests/functional/analyze_and_parse/test_files/simple1_review_status_file_hash.output, analyzer/tests/functional/analyze_and_parse/test_files/test_dir/simple1.cpp, analyzer/tests/unit/review_status_config.py, codechecker_common/review_status_handler.py, docs/analyzer/user_guide.md
[feat] Ignore reports in post-processing
Reports can be ignored on filepath or checker name basis. This means
that these reports will not only be considered as "closed" but totally
ignored from the .plist files. These reports are thus invisible for all
other CodeChecker commands like "diff", "parse", "store", etc.
[feat] Change review status config YAML format
The format of the review status config is changed. A version number is
also included to identify the format in case further modifications are
needed in the future.
=> [cfg] Add a config file to change review statuses

web/server/vue-cli/src/components/Report/ReportTree/ReportTree.vue, web/server/vue-cli/src/components/Report/ReportTree/ReportTreeIcon.vue
It is a bug fix to locate correctly both OFF and UNAVAILABLE reports in the sidebar. These kind of reports are not outstanding, so they should be classified as closed.
=> [fix] Fixing OFF and UNAVAILABLE detectionStatus in the report sidebar

web/server/codechecker_server/api/mass_store_run.py
The id was a primary key, that was only assigned after the flush was done. The format string being used was not a flexible one, it was changed to the newer kind of format string, and the printed debug message was changed to a more meaningful one, stating the report hash, and the source file path.
=> Fix debug logging in store

tools/report-converter/codechecker_report_converter/analyzers/sanitizers/ub/parser.py, tools/report-converter/tests/unit/analyzers/test_ubsan_parser.py, tools/report-converter/tests/unit/analyzers/ubsan_output_test_files/ubsan1_nonmatching_msg.out, tools/report-converter/tests/unit/analyzers/ubsan_output_test_files/ubsan1_nonmatching_msg.plist
We forgot to inizialize `checker_name` to its default value, which lead to a read-before-assignment crash.
=> [report-converter][fix] Don't crash when we can't find the checker name for ubsan

tools/report-converter/codechecker_report_converter/report/parser/sarif.py
The Sarif schema has a 'version' field but the template is mis-typed as 'vesion'. Adding the missing 'r' allows the code to be read as Sarif data (e.g. by the VSCode Sarif viewer plugin.
=> Fix typo 'vesion' in sarif conversion template

analyzer/codechecker_analyzer/buildlog/log_parser.py
The `-fno-tree-dominator-opts` GCC option is not recognized by clang.
=> [analyzer] Ignore `-fno-tree-dominator-opts`

tools/report-converter/codechecker_report_converter/analyzers/sanitizers/address/parser.py, tools/report-converter/codechecker_report_converter/analyzers/sanitizers/ub/parser.py, tools/report-converter/tests/unit/analyzers/asan_output_test_files/asan.plist, tools/report-converter/tests/unit/analyzers/test_asan_parser.py, tools/report-converter/tests/unit/analyzers/test_ubsan_parser.py
Sometimes, memory addresses will simply be omitted from the sanitizer error messages. In this case, ` .+ ` will not match the error message, since this matches strings with the minimum length of 3, but the address-less message usually looks like this:
`error on adress  , because`, with only 2 characters there. The fix is simple -- simply change `.+` zo `.*`.
I also added generic messages to asan, because we were missing that.
=> [report-converter] Allow for empty strings in sanitizer error msgs

codechecker_common/review_status_handler.py
During "CodeChecker store" the server checks the review status of reports. Review status may come from source code comments (e.g. // codechecker_suppress [core.DivideZero] This is false positive). The server needs to read the content of source files in order to find these comment sections. However, source code files are not uploaded to the server when both the following conditions hold:
1. They were uploaded earlier with the same content by a previous "CodeChecker store" action.
2. The client realizes that there is no source comment in the source file.
In these cases the server is emitting an error which tells that the source file was not uploaded. This error message is definitely not necessary, since there is no review status comment that could be read by the server or it had been read …
=> [fix] Eliminate unnecessary error logging

analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py, analyzer/tests/unit/test_cppcheck_version_parsing.py
Cppcheck Premium version dumps the version number in the following format:
Cppcheck Premium 1.2.3
CodeChecker couldn't handle the "Premium" word in the middle.
Fixes #4133
=> [fix] Cppcheck premium version check

docs/analyzer/user_guide.md, tools/report-converter/tests/unit/parser/sarif/sarif_test_files/3-Beyond-basics/standard-taxonomy.sarif, web/server/vue-cli/src/views/NewFeatures.vue
There are multiple broken links in the documentation of this project. Here is what I have fixed:
https://github.com/Ericsson/codechecker/blob/master/docs/user_guide.md#source-components --> https://github.com/Ericsson/codechecker/blob/master/docs/web/user_guide.md#source-components-components
https://cwe.mitre.org/data/published/cwe_v3.2.pdf/ --> https://cwe.mitre.org/data/published/cwe_v3.2.pdf
https://github.com/Ericsson/codechecker/blob/master/analyzer/tools/build- --> https://github.com/Ericsson/codechecker/tree/master/analyzer/tools/build-logger
https://github.com/Ericsson/codechecker/blob/master/docs/user_guide.md#cmd --> https://github.com/Ericsson/codechecker/blob/master/docs/web/user_guide.md#cmd
https://github.com/Ericsson/codechecker/blob/master/docs/authentication.md#personal-a …
=> Fix Broken Links In Documentation

analyzer/codechecker_analyzer/analyzer.py
Currently, no gcc checkers are enabled by default, which can make this warning rather annoying:
```
CodeChecker analyze ./compile_commands.json -o reports_test
```
```
[WARNING 2024-01-08 14:56] - Analyzer 'gcc' is enabled but CodeChecker is failed to execute analysis with it: 'Incompatible version: GCC binary found is too old at v9.4.0; minimum version is 13.0.0. Maybe try setting an absolute path to a different analyzer binary via the env variable CC_ANALYZER_BIN?'. Please check your 'PATH' environment variable and the 'config/package_layout.json' file!
```
...even though no checkers were explicitly enabled for gcc. This patch fixes this by disregarding non-functional analyzers if no checkers are enabled for them anyway.
=> [gcc] Don't emit a missing gcc warning if no checkers are enabled

analyzer/codechecker_analyzer/cmd/check.py
The --cppcheckargs flag is missing from under "CodeChecker check". This flag has now been added in order to be consistent with "CodeChecker analyze".
Fixes #4177
=> [fix] --cppcheckargs should be present in "CodeChecker check"

docs/install_macosx.md
I modified the instructions for mac users on M1 processors
=> additional guidance for silicon mac users

web/server/codechecker_server/migrations/report/versions/c3dad71f8e6b_store_information_about_enabled_and_disabled_checkers_for_a_run.py
> Follows up #4089.
The first row in a table with an `AUTOINCREMENT` ID has the value 1, not 0. This was synchronised in the migration script to have `server_default="1"` such that all default constructed `report` rows have a **valid** `FOREIGN KEY` to the `checkers` table (the `__FAKE__` checker). But the hand-written upgrade query filtered for `0` to get a batch of "unhandled rows", essentially preventing appropriate migration.
=> fix(migration): Migrate reports with appropriate default checker ID

web/server/codechecker_server/migrations/report/versions/c3dad71f8e6b_store_information_about_enabled_and_disabled_checkers_for_a_run.py
> Follows up #4089, #4191.
In case a new product is added to an empty server, what happens in the background is a full "migration" from the "empty" state to the newest schema, which results in the log output that is removed by this patch on the standard output of the server.
These lines are not directly needed, but there is no good reason to hide them behind an `if len(...):` check either. In case actual rows are migrated (which never happens when a new product is added to the server), the appropriate output showing the row count of the `UPDATE` statement will be printed to the output normally.
=> fix(migration): Do not emit log output for `checker_id` normalisation

web/server/vue-cli/e2e/specs/reports.js, web/server/vue-cli/src/components/Report/ReportTree/ReportDetailFormatter.js
Previously, all notes of GCC were uncategorized, which lead to function calls not being indented properly. This patch fixes that (though I admit, this JS code isn't my proudest work):
With Clang, its easy to identify loops, but for gcc, not so much, so I skipped it:
=> [gcc][GUI] Fix indentations for gcc fn calls bug reports

tools/report-converter/codechecker_report_converter/report/hash.py, tools/report-converter/codechecker_report_converter/report/parser/plist.py, web/client/codechecker_client/cmd/store.py, web/tests/functional/component/test_component.py, web/tests/functional/dynamic_results/test_dynamic_results.py
We used to zip every result file in the result directory and send it to the server. This is tremendously wasteful, as many report files contained the very same reports (for instance, if the report originated from a header file).
In this patch, I unique all reports, dump them in a tmpfile, and store that to the server. For a clang-tidy --enable-all analysis on xerces, this reduced the size of the zipfile drastically:
BEFORE:
```
Compressing report zip file done (1.6GiB / 62.2MiB).
[...]
real	8m32,381s
user	15m57,436s
sys	0m14,708s
```
AFTER: 
```
Compressing report zip file done (413.0MiB / 9.0MiB).
[...]
real	5m45,621s
user	15m54,858s
sys	0m14,458s
```
While this doesn't speed up CodeChecker parse or CodeChecker diff, it still speeds up the server quite a bit, both for storage and query …
=> [store] Unique reports _before_ storing

web/server/vue-cli/e2e/pages/runs.js, web/server/vue-cli/e2e/specs/runs.js, web/server/vue-cli/src/components/AnalysisInfo/Checker.vue, web/server/vue-cli/src/components/AnalysisInfo/CheckerGroup.vue, web/server/vue-cli/src/components/AnalysisInfoDialog.vue, web/server/vue-cli/src/mixins/api/analysis-info-handling.mixin.js, web/server/vue-cli/src/mixins/api/index.js, web/server/vue-cli/src/mixins/index.js
> Follows up #4156.
Test that for a newly analysed project, the checker status GUI elements appear. Check that, for a few well-defined cases, the status is indeed what we are expecting.
=> test(gui): Add front-end test for checked status in AnalysisInfo dialog

web/server/codechecker_server/migrations/report/versions/c3dad71f8e6b_store_information_about_enabled_and_disabled_checkers_for_a_run.py
Two log messages contained an UTF-8 dash characters that crashed logging in some environment.
=> [fix] Replace UTF-8 dash characters

web/server/codechecker_server/api/report_server.py
When getRunResults() API function queries the reports, the query uses LIMIT and OFFSET for returning the given page of the results due to their huge number. However, it is possible that different pages have overlapping reports. This way the resulting report list may contain duplicate reports.
In this commit we apply an ordering on report id in order to prevent this.
=> [fix] Prevent overlapping report groups

analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py, tools/report-converter/codechecker_report_converter/report/output/html/html.py, tools/report-converter/codechecker_report_converter/report/output/html/static/css/buglist.css, tools/report-converter/codechecker_report_converter/report/output/html/static/index.html, tools/report-converter/codechecker_report_converter/report/output/html/static/js/buglist.js, tools/report-converter/tests/unit/output/html/plist_to_html_test.py, web/tests/functional/diff_local_remote/test_diff_local_remote.py
"CodeChecker parse <report_dir> -e html -o html" command generates a static HTML page showing all reports in the report directory. If the report dir is too big, then the generated HTML is too big and the browser freezes while loading it.
In this commit the logic of the statis HTML page has been restructured in a way, that the reports are not HTML table elements automatically, but first they are stored in a JS object. Only those reports are inserted to the DOM tree that are currently visible based on the sorting and paging.
=> [cmd] Restructure static HTML generation

tools/report-converter/codechecker_report_converter/report/output/html/html.py, tools/report-converter/codechecker_report_converter/report/output/html/static/index.html, tools/report-converter/codechecker_report_converter/report/output/html/static/js/buglist.js
"CodeChecker parse -e html" command produces a static HTML that displays
the reports. However, the dynamic analysis related columns were missing
from this table: testcase and timestamp are now displayed too, if any.
Note: this PR consists of 2 commits. The first one is deployed in another PR (#4168). After that's merged, this one can be rebased.
=> [feat] Display dynamic columns in static HTML 

analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/cmdline/test_cmdline.py, analyzer/tests/unit/test_checker_handling.py
When specifying invalid checker and analyzer config, the CodeChecker analyze command used to give a warning but continued running.
This functionality throws an error and prevents the analysis from running in this case.
CODECHKR-5784
=> Add functionality to validate analyzer and checker options

analyzer/codechecker_analyzer/cmd/analyze.py
Change the log level from info to warning when
nothing was analyzed due to eg an empty
compilation database.
Fixes #4222
=> Display warning if the compilation database is empty

web/server/codechecker_server/api/report_server.py
It's a follow up PR to fix SQL Alchemy query in #4157. PostgreSQL does not support getting a column without adding it to the group by list or using aggregate functions.
=> [fix] Fixing getReportAnnotations subquery

analyzer/tests/functional/cmdline/test_cmdline.py, config/labels/analyzers/clangsa.json, web/tests/functional/report_viewer_api/test_get_run_results.py
The association of SEI CERT C and C++ Coding Standard Rules are updated for the Clang Static Analyzer version 18.
=> Updating clangsa sei cert mapping for clang 18

tools/report-converter/codechecker_report_converter/report/output/html/html.py, tools/report-converter/tests/unit/output/html/plist_to_html_test.py
The links in the static HTML files generated by "CodeChecker parse -e html" should be relative, so the output folder of the above command is portable.
=> [fix] Links in static HTML files should be relative

analyzer/tests/functional/cmdline/test_cmdline.py, config/labels/analyzers/clang-tidy.json, config/labels/analyzers/clangsa.json
> [!IMPORTANT]
>
> :no_entry: **Blocked** by #4224.
Ensure that checkers that target SEI CERT C & C++ guideline rules and recommendations are appropriately labelled as such: `guideline:sei-cert`, `profile:security`, and the guideline label.
In case the checker is implemented through an alias (or even multiple aliases), apply the labels to **only** the **main** checker, and strip the profile and guidelines associations from the aliases. (Due to the lack of proper alias handling in both Clang-Tidy and CodeChecker, firing all aliases would result in multiple detections of the same match.)
Ensure, in addition, that `profile:default` and `profile:sensitive` checkers are also always in the more broad superset profiles `profile:sensitive` and `profile:extreme`.
=>  chore(config): [clang-tidy] Update SEI-CERT Guideline mappings

web/client/codechecker_client/cmd_line_client.py
The following commands may be given the --component flag for filtering on source components:
CodeChecker cmd result
CodeChecker cmd diff
CodeChecker cmd sum
If a non-existing component was used in the filters, then all reports returned.
In this patch an error log message is given for filtering non-existing source components.
=> [cmd] Check for non-existing source components

analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzers/analyzer_types.py
Original patch (that itroduces the crash):
https://github.com/Ericsson/codechecker/pull/4179
Revert attempt in https://github.com/Ericsson/codechecker/pull/4238.
The crash occurs because the original patch tries to create config handlers even if they are not supported. This is playing with fire already, but the crash occured when not even the analyzer binary is found.
In this patch, these analyzers are skipped from checking if they have any checkers enabled.
=> Fix a crash where config handlers were built with missing binaries

web/client/codechecker_client/cmd/store.py
During the storage, the zip files should be stored in one of the report folders instead of `/tmp`. Storing huge zip files can cause storage space saturation in `/tmp`.
`CodeChecker store` would create a new tmp directory in the first given report folder where the zip files can be stored temporarily.
=> [fix] Creating new temporary directory for zip files

web/server/codechecker_server/api/report_server.py
In some rare cases, when an error occurs while deleting 
runs, the number of runs to be deleted is deducted from 
the "Number of runs" value displayed in the
"Products" view, even though some runs do not get
deleted. For this reason, the number of runs could go 
negative upon the next run deletion.
This change is to fix this issue.
=> Make sure that the Number of runs is displayed correctly

analyzer/codechecker_analyzer/analyzer.py, analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py
At every analysis at the defult log level there was a wall of text checker list. It is enough to print this list at the verbose log level and redirect the user to the metadat.json file at default log level.
=> [analyze] Removing long enabled checker list at info log level

web/server/vue-cli/src/components/Statistics/BaseStatisticsTable.vue, web/server/vue-cli/src/components/Statistics/CheckerCoverage/CheckerCoverageStatistics.vue, web/server/vue-cli/src/components/Statistics/CheckerCoverage/CheckerCoverageStatisticsTable.vue
It's an additional PR to integrate the guideline column into checker coverage statistics table. Showing the guideline rule for those checks that cover specific rules e.g. sei-cert or misra-c.
=> [feature] Adding guideline label to Checker Coverage tab

web/server/codechecker_server/database/db_cleanup.py
Rephrasing a query so it doesn't esceed the statement timeout. Special thanks to @cservakt!
=> [db] Faster query for comment garbage collection

web/client/codechecker_client/cmd/store.py
The problem with tempfile.mkstem() is that it opens the created file, and it must be closed through its file descriptor, otherwise some dangling .nfs files remain when CodeChecker is used in an NFS drive. For this reason we use uuid instead.
=> [fix] Use module uuid instead of tempfile

docs/web/user_guide.md, web/client/codechecker_client/cmd/cmd.py, web/client/codechecker_client/cmd_line_client.py
The "anywhere on report path" feature exists in the web GUI. This feature controls --component and --file filters in order to return reports of which the report path not only ends in, but goes through them.
In this commit this feature is added to the CLI, too.
=> [cmd] Add --anywhere-on-report-path flag to CLI

analyzer/codechecker_analyzer/cmd/analyze.py
So far, the file option needed a simple but
necessary workaround to support relative file
paths. With this change, simply entering the
filename in the --file option will be sufficient.
=> Support relative paths in the --file option

analyzer/codechecker_analyzer/buildlog/log_parser.py
`-ffreestanding` and `-fno-freestanding` are common in embedded systems but clang does not support it. This PR adds them both to the ignored GCC compiler flags list.
=> [analyzer] Adds -fno-freestanding to ignored GCC compiler flags

analyzer/codechecker_analyzer/analyzer_context.py, analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py, analyzer/codechecker_analyzer/analyzers/gcc/analyzer.py, analyzer/codechecker_analyzer/buildlog/log_parser.py, analyzer/requirements.txt, analyzer/tests/functional/fixit/test_fixit.py, analyzer/tests/functional/z3/test_z3.py, analyzer/tests/libtest/codechecker.py, analyzer/tests/unit/test_checker_handling.py, codechecker_common/util.py, tools/tu_collector/tu_collector/tu_collector.py, web/tests/functional/statistics/test_statistics.py
Replace:
`distutils.spawn.find_executable` with `shutil.which`
`distutils.version.StrictVersion` with `packaging.version.Version`
`distutils.util.strtobool` with `codechecker_common.util.strtobool`
as distutils is not available in Ubuntu noble.
=> Deprecate distutils

analyzer/codechecker_analyzer/buildlog/log_parser.py
The -mmitigate-rop compilation flag is
unknown by clang, which might cause issues
if the gcc compiler is used. This change
adds -mmitigate-rop to the list of ignored
options to fix these issues.
=> Add -mmitigate-rop to ignored options

analyzer/codechecker_analyzer/buildlog/build_manager.py, analyzer/codechecker_analyzer/cmd/log.py, analyzer/tools/build-logger/README.md, analyzer/tools/build-logger/tests/unit/__init__.py, docs/analyzer/user_guide.md
After make-4.3 the compilers are executed in a way that cc1 binary is also captured by the logger. This accomplishes only a partial phase of the compilation process and this shouldn't be captured. As a solution we use the fact that having a slash (/) in a compiler's name in CC_LOGGER_GCC_LIKE makes a suffix search.
=> [fix] Don't capture cc1 by the logger.

analyzer/tools/merge_clang_extdef_mappings/requirements_py/dev/requirements.txt, analyzer/tools/statistics_collector/requirements_py/dev/requirements.txt, codechecker_common/requirements_py/dev/requirements.txt, tools/bazel/requirements_py/dev/requirements.txt, tools/report-converter/requirements_py/dev/requirements.txt, tools/tu_collector/requirements_py/dev/requirements.txt
Some platforms don't come with pre-installed setuptools module. However, some CodeChecker modules need this library as a dependency.
Fixes #4278
=> [cfg] Add setuptools as a dependency

web/server/codechecker_server/api/report_server.py, web/server/vue-cli/src/components/Statistics/CheckerCoverage/CheckerCoverageStatistics.vue, web/server/vue-cli/src/views/Statistics.vue
The `compare to` filter was turned off for statistics tabs. It is a user request to restore it. Every tabs gets back the filter except checker coverage.
Switching between tabs was problematic. When we want to switch from checker coverage to others tab, it triggers a full page refresh. Now, it is fixed.
The status of the checkere coverage does not show the number of disabled runs for checkers. With this PR, the users can be informed about the number of runs the checker is off and they can also open the disabled runs modal to list them.
=> [fix] Minor fixing for statistics tabs

analyzer/codechecker_analyzer/analyzers/config_handler.py, analyzer/tests/unit/test_checker_handling.py
Currently, checkers can be enabled by checker name prefix. For example, "--enable unix" enables all checkers starting with "unix". However, checkers shouldn't be enabled by suffix match: "--enable Malloc" shouldn't enable "unix.Malloc" checker.
The source of the confusion was that having "unix.Stream" checker in the "default" profile also enabled "alpha.unix.Stream", which is not an intended behavior.
=> [fix] Don't enable checkers by suffix

web/server/codechecker_server/api/report_server.py
Fixing report sorting on unique mode. After modifying the DB schema in #4089 PR, the unique mode query of getRunResults endpoint has been changed, therefore, the report sorting is not working properly.
Now, the unique mode query is redesigned and it use row_number() function to filter unique reports correctly. Where clause is also modified. It is getting rid of report annotation filter. Filtering annotation remains in having clause.
=> [Fix] Report sorting in unique mode

web/server/codechecker_server/api/report_server.py, web/tests/functional/dynamic_results/test_dynamic_results.py, web/tests/projects/dynamic/main.c_cppcheck_0212cbc2c7194b7a5d431a18ff51bb1c.plist
It is allowed now to use wildcards in the report annotation filter. For example, the reports generated by testcases starting with "TC-" can be queried by "TC-*".
=> [fix] Support joker characters at annotation filter

config/labels/analyzers/clang-tidy.json, config/labels/analyzers/clangsa.json, config/labels/analyzers/cppcheck.json
Apply the automatic fixes of invariants such as _"`profile:sensitive` and `profile:extreme` should be present if `profile:default` is present"_ and _"`guideline:sei-cert` should be present if a `sei-cert:RULE-01`-like label is present"_ to the config files, as emitted by #4275.
=> chore(config): Apply invariant fixes from `label-tool`

analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzer_context.py, analyzer/codechecker_analyzer/analyzers/analyzer_base.py, analyzer/codechecker_analyzer/analyzers/analyzer_types.py, analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangsa/version.py, analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py, analyzer/codechecker_analyzer/analyzers/gcc/analyzer.py, analyzer/codechecker_analyzer/cmd/analyzers.py, analyzer/codechecker_analyzer/env.py, analyzer/codechecker_analyzer/host_check.py, analyzer/tests/unit/test_env_var.py
If a pre-package analyzer binary (e.g. clang) is found first, the LD_LIBRARY_PATH must be extended. On the other hand, if the analyzer binary is taken from the users machine, the original environment must be used to execute the binary.
This patch introduces an analyzer binary dependent environment initialization.
=> Analyzer binary dependent environment

analyzer/codechecker_analyzer/analyzers/config_handler.py, analyzer/codechecker_analyzer/checkers.py, analyzer/tests/unit/test_checker_handling.py
Checkers can be enabled by groups, e.g. unix.cstring enables all checkers starting with this prefix. However, unix.cs is not a checker group so this shouldn't be allowed. In this case an error message is printed and analysis doesn't start.
=> [cmd] Checker name prefixes are meant along separator characters

analyzer/codechecker_analyzer/analyzer_context.py, analyzer/codechecker_analyzer/env.py, analyzer/tests/unit/test_log_parser.py, analyzer/tools/build-logger/README.md, analyzer/tools/build-logger/tests/unit/__init__.py, docs/analyzer/user_guide.md
This reverts commit db924b02424c4ed5fc5c0b21af19c848ad45e6f2.
ld_logger.so binary version (32 or 64 bits) must depend on the excuted builder binary version, not on the host machine platform version.
Fixes #4312
=> Revert "[analyzer] Use absolute path to logger.so in LD_PRELOAD"

analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangsa/ctu_triple_arch.py, analyzer/codechecker_analyzer/analyzers/clangsa/statistics.py, analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/libtest/cmd_line.py, analyzer/tests/unit/test_analyzer_command.py, analyzer/tests/unit/test_checker_handling.py, docs/analyzer/user_guide.md
GCC has implicit include paths that are forwarded to Clang. Until now these paths were added with -isystem flag, but sometimes the priority of this is too high: https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html The implicit include paths should be searched the last, so -isystem has been changed to -idirafter.
In case of potential backward compatibility break
--add-gcc-include-dirs-with-isystem has been introduced for "CodeChecker analyze" command.
=> [feat] Implicit include paths added with -idirafter

scripts/result_listing/compare_results.py
The list.sort() function doesn't return a sorted list but sorts inplace.
=> [fix] fix compare_results.py sciprt

analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py
The Cppcheck plugin resets the PATH environment variable. It is usually not a good idea to overwrite PATH instead of extending it. In this specific case it caused an actual error: When tests are executed one after the other, this statement clears that PATH and later tests (e.g. test_env_var.py) run in an environment where PATH is technically empty. This test fails.
=> [fix] Don't reset PATH in Cppcheck plugin

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
It is a fix PR to disable clang-diagnostic-error checker in cli. Now, the users cannot set this checker as enabled with -e.
=> [fix] Disable clang-diagnostic-error checker

analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzer_context.py, analyzer/codechecker_analyzer/analyzers/analyzer_types.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/analyzers.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/codechecker_analyzer/cmd/checkers.py
`CodeChecker analyzers` gives python error for the user if a supported analyzer is missing. In addition, CodeChecker `analyze` and `check` should have provided an error and sys.exit when the specified (with `--analyzers`) analyzer was missing.
With this PR, `CodeChecker analyzers` can give a warning message with `NOT FOUND` status if a supported analyzer can't be found on the machine.
In case of explicitly defined missing analyzer, the `analyze` and `check` command will be failed and will give warrning and error message for the user.
=> [fix] Missing analyzer error

analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/analyzer_context.py, analyzer/codechecker_analyzer/analyzers/analyzer_base.py, analyzer/codechecker_analyzer/analyzers/analyzer_types.py, analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangsa/ctu_autodetection.py, analyzer/codechecker_analyzer/analyzers/clangsa/ctu_manager.py, analyzer/codechecker_analyzer/analyzers/clangsa/version.py, analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py, analyzer/codechecker_analyzer/analyzers/gcc/analyzer.py, analyzer/codechecker_analyzer/cmd/analyzers.py, analyzer/codechecker_analyzer/cmd/checkers.py, analyzer/codechecker_analyzer/cmd/fixit.py, analyzer/codechecker_analyzer/host_check.py, analyzer/tests/unit/test_env_var.py
CodeChecker calls various binaries during analysis: clang, clang-tidy,
clang-extdef-mapping etc.
If the binary is delivered within the CodeChecker package,
LD_LIBRARY_PATH needs to be extended with it.
Otherwise the environment of the caller shell should be used
for excuting binaries.
=> Environment initialization for binaries

analyzer/tests/functional/analyze/test_analyze.py
Test if clang-diagnostic-error checker is disabled in cli.
=> Add test for Disable clang-diagnostic-error checker #4325

.github/workflows/test.yml
The following modification will cancel previous tasks/runs when a new one was pushed.
=> Github Actions: stop previous jobs when a new one was pushed

web/server/codechecker_server/api/mass_store_run.py
With the baseline when storing a ~156 000 for the second time in a new run the storage times out.
(The first storage finishes in in ~10 mins.)
The fixed nested query is causing the statement timeout.
```
hash_24557': 'e7fc0836a60a7c8eb989eb878d94ede2', 'bug_hash_24558': '50bdcad45061c035d58ca2839ceac1f7', 'bug_hash_24559': '114a6dec38b087d904920a3ad623b21f', 'bug_hash_24560': 'f5cabc79de293a2a3fbc9dd27f34b0d0', 'bug_hash_24561': 'b5f377e878c2ccdc8ada7ad31e53ecc3', 'bug_hash_24562': '4636a65fa5ecea3e4c10e35e8a336052', 'bug_hash_24563': '7872b5d1b71a95f032bba792801a7169', 'bug_hash_24564': '344a2b1746647e88ca43ffe4fd8cb2b1', 'bug_hash_24565': 'b57e197a6f17b32ce0da8f164c80377e', 'bug_hash_24566': 'ee77f8d3ebb81445133f3b16447f3c63', 'bug_hash_24567': 'ee6d84b699d692a7baa5f9c301833d02', …
```
=> Speeding up store by removing nested query

web/server/codechecker_server/session_manager.py
If the super_user field was missing from the
config file, CodeChecker authentication failed
for all users.
=> CodeChecker authentication fixed

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzer.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/skip/test_files/simple/skipfile_drop, analyzer/tests/functional/skip/test_skip.py
By default CodeChecker used to filter out all reports from files which were on the skip list. This can hide true positive reports strating from unskipped code and endingin skipped files (typical with CTU and header related findings).
This patch removes the  default report filtering post processing step from CodeChecker analyze --skip SKIPFILE operation.
The legacy functionality is still available with the --drop-reports-from-skipped-files paramer.
This way the reports are not skipped as a post processing step by default.
=> Adding a --drop-reports-from-skipped-files parameter to analyze

web/server/codechecker_server/api/report_server.py
This query runs when filtering by files or components with "anywhere on bugpath" option. In this case the following query was generated:
`SELECT <columns> FROM reports WHERE reports.id IN (id1, id2, ...);`
The ID list at "IN" block can be so huges that it eats up all the memory and times out the query. This ID list is now replaced with a nested select:
`SELECT <columns> FROM reports WHERE reports.id IN
(SELECT report_id FROM <some tables>);`
=> [fix] Better SQL SELECT instead of a timeout query

docs/README.md
Solution was found on https://stackoverflow.com/a/14424226
The documentation should contain libpq-dev dependency
FIXES #4258
=> additional library was required for venv_dev

web/server/codechecker_server/api/product_server.py, web/tests/functional/products/__init__.py, web/tests/functional/products/test_products.py
The getProductConfiguration() function on Product endpoint requires a current product in the URL for checking view permission. The requirement of having view permission has been added in
8953b30f6d17597635ec59bb943683aacb216619. However there is no "current product" in the Product endpoint URL queries, but the product id is provided through a function parameter.
=> [fix] Get product configuration with view permission

analyzer/codechecker_analyzer/analyzers/config_handler.py, analyzer/codechecker_analyzer/checkers.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/unit/test_checker_handling.py, docs/analyzer/user_guide.md
Introduce the -e prefix: option, to improve handling of ambigous parameters.
such as "security" which is a checker prefix group and a profile at the same time
=> Handle ambigous profile/group parameters

tools/report-converter/codechecker_report_converter/report/__init__.py
It is an additional feature for parseing to have report annotation fields when the user wants to export the results to json.
=> [feat] Adding report annotation for json export

web/tests/functional/diff_local_remote/test_diff_local_remote.py
A new Clang version produces a different report message and it breaks the tests. So, another report is chosen for the test which has a more stable message.
=> [test] Fix test with new clang version

tools/report-converter/codechecker_report_converter/report/hash.py, web/tests/functional/dynamic_results/test_dynamic_results.py, web/tests/projects/dynamic/main.c_clang-tidy_0212cbc2c7194b7a5d431a18ff51bb1c.plist
Two report should also be considered different if they differ only in their annotations.
=> [feat] Unique reports by different annotations

web/server/codechecker_server/server.py
The control flow would have meant that self.directory would not be set before calling do_GET().
=> Fix setting www_root in CodeChecher server

tools/report-converter/codechecker_report_converter/report/output/html/static/js/bugviewer.js, web/server/vue-cli/src/components/Report/Report.vue, web/server/vue-cli/src/components/Report/ReportStepMessage.vue
If the last bug path message or location is different than the warning text location render the warning text in the codeview in the web GUI. If this is not the case, the visualization remains the same as before.
New visualization in the static HTML
New visualization in the GUI
=> Render the checker message as an individual elment in the code

analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py, analyzer/tests/functional/analyze/test_analyze.py, codechecker_common/util.py
Cppcheck tool is failing from version 2.15 if "--std=" flag is given an unknown value. For example, "--std=c++0x" is not known, but "--std=c++11" is. Before cppcheck-2.15 the latest known standard version was silently used.
In this patch the unknown standard versions are mapped to the known ones.
=> [fix] Cppcheck unknown C/C++ standard

config/labels/analyzers/clang-tidy.json, config/labels/analyzers/clangsa.json, config/labels/analyzers/cppcheck.json
Since the last release some ClangSA checkers were moved to different packages and some new checkers were introduced. This change updates the label configuration of CodeChecker to reflect this.
I just eyeballed the severities and the profiles, so it's open for suggestions.
Notes:
alpha.security.taint.TaintPropagation does not have a documentation link, so I just put the GenericTaintChecker link as doc-url. Alternatively, we could use doc entry: https://clang.llvm.org/docs/analyzer/user-docs/TaintAnalysisConfiguration.html
With this patch, all the taint-related checkers share the same severity and profiles as the now-removed alpha.security.taint.TaintPropagation.
I put BlockInCriticalSection in the default profile, as I have deemed it not too noisy, and the results were meaningful IMO.
=> [cfg] Update labels file for updated checkers

web/client/codechecker_client/blame_info.py
Both `git check-ignore` and `git blame` will error if run on a symbolic link, so resolve the path before running them.
=> Resolve paths when blaming files

config/labels/analyzers/clangsa.json
The alpha.unix.Chroot checker was promoted in this MR, https://github.com/llvm/llvm-project/pull/117791, so adding severity and documentation links for newly promoted checker.
=> [cfg] Add info for new unix.Chroot Checker

analyzer/codechecker_analyzer/analyzer_context.py, analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py, analyzer/tests/functional/analyze_and_parse/test_files/mixed_arch_driver.c, analyzer/tests/functional/analyze_and_parse/test_files/simple.c, analyzer/tools/build-logger/Makefile, analyzer/tools/build-logger/tests/unit/__init__.py, docs/analyzer/user_guide.md
The issue with logging (see https://github.com/Ericsson/codechecker/issues/4360 for details) came up on my Ubuntu24 machine, where only specifying the <data_files>/ldlogger/lib in the LD_LIBRARY_PATH was not enough for the dynamic loader to load the ldlogger.so inside <data_files>/ldlogger/lib/x86_64, so I observed there is no implicit architecture resolution in the logic of the loader. There were other tests on other distributions where this implicit architecture resolution seems to exist (rhel7, rhel8, ubuntu22, among others).
The solution implemented by this patch is adding all <data_files>/ldlogger/lib/* folders in addition to the current  <data_files>/ldlogger/lib folder to the LD_LIBRARY_PATH.
I have tested it on Ubuntu24, and the multiple .so files that are possibly reachable due …
=> [analyzer] Include arch subdirectories in LD_LIBRARY_PATH for logging

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangtidy/config_handler.py, analyzer/codechecker_analyzer/analyzers/config_handler.py, analyzer/codechecker_analyzer/checkers.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/functional/analyze_and_parse/test_files/compiler_warning_wno_group.output, analyzer/tests/functional/analyze_and_parse/test_files/compiler_warning_wno_simple2.output, analyzer/tests/functional/analyze_and_parse/test_files/compiler_warning_wunused.output, analyzer/tests/unit/test_checker_handling.py, config/labels/analyzers/clang-tidy.json, docs/analyzer/user_guide.md, web/server/vue-cli/src/views/NewFeatures.vue, web/tests/functional/report_viewer_api/__init__.py
This PR fixes the enabling and disabling checker options, focusing on resolving ambiguities in option processing.
Key updates:
**Ambiguity handling:**
> When ambiguous checker options are provided with `-e` or `-d` flags, an error is now raised. The user receives suggestions for specifying the option by using namespaces (checker, prefix, guideline, etc.).
> If a checker name matches multiple checkers as a prefix, it triggers an ambiguity error. Suggestions are provided to help users choose between the checker name or the prefix.
**Additional namespaces:**
>A new `checker` namespace is created. All label types can be a namespace as well, specified with a `:` separator before the checker option.
**Default profile settings improvements:**
> Only those checkers enabled that has …
=> [fix] Resolve checker enable/disable ambiguity

analyzer/codechecker_analyzer/analyzers/analyzer_types.py, analyzer/codechecker_analyzer/cmd/checkers.py
So far, if some analyzer binary was missing,
CodeChecker checkers --checker-config did not
work for any analyzers and threw an error.
With this change, CC will show the available
checker configs, even if some analyzer binary
is missing.
Fixes #4406
=> [fix] Show available checker configs in all cases

web/tests/functional/dynamic_results/test_dynamic_results.py, web/tests/projects/dynamic/main.c_clang-tidy_0212cbc2c7194b7a5d431a18ff51bb1c.plist
There are some tests already which check if two reports with different annotations are considered different reports.
Now we also check if two reports with different report hash are considered different.
=> [test] Add tests for different report hashes

setup.py
CodeChecker offers limited support for static analysis results in Sarif format as of 6.24. This change helps those searching for packages using the keyword sarif.
=> [doc] Add sarif to setup.py

web/server/codechecker_server/database/database.py
On startup, codechecker checks the alembic version of the codechecker database(s) to see if they match the expected value. Prior to this commit, the version found in the database was displayed in the logging, but the expected version was not always displayed. This added an uneccesary complication when debugging a database mismatch (eg during local testing)
As of this commit, the found version and the expected version are both logged
=> [feat][server] Logging: show package schema revision on startup

analyzer/codechecker_analyzer/analyzer.py
CC validates ordered checkers before analyzing, but didn't use to validate the checkers ordered with the "checker:" prefix. With this fix, those will be validated as well.
Fixes #4405
=> [fix] Validate checkers ordered with "checker" prefix

tools/report-converter/setup.py
The report-converter package shows setuptools warnings during build about missing packages when using Python 3.12. This is due to stricter package discovery checks introduced in setuptools 61.0.0 [1], which now warns about directories that could be packages but aren't explicitly configured.
While we could address this with explicit package_data configuration, the package already has a correct MANIFEST.in file that handles static file inclusion.
This change:
- Relies on the existing MANIFEST.in pattern for static files
- Uses find_namespace_packages() to properly handle package structure
- Keeps include_package_data=True to ensure MANIFEST.in is respected
This approach is more maintainable as:
1. All static file patterns are managed in one place (MANIFEST.in)
2. New static files are …
=> [tools] Simplify static file handling in report-converter

analyzer/tools/build-logger/.pylintrc, analyzer/tools/merge_clang_extdef_mappings/.pylintrc, analyzer/tools/statistics_collector/.pylintrc, tools/report-converter/.pylintrc, tools/tu_collector/.pylintrc
The reason for this change is that Pylint gives the following deprecation warning:
UserWarning: Specifying exception names in the overgeneral-exceptions option without module name is deprecated and support for it will be removed in pylint 3.0. Use fully qualified name (maybe 'builtins.BaseException' ?) instead.
=> [test] Modernize Pylint config

web/server/codechecker_server/api/report_server.py
Grouping by the file path takes too long when the user wants to filter the reports by file path filter. The solution can be using `distinct` insted of `group by` to get the first ten files considering the report filter as well. Then it is faster to count the number of reports only for these files..
=> [Fix] Getting file counts query

tools/report-converter/codechecker_report_converter/report/output/plaintext.py
"CodeChecker cmd" commands were crashing if they would print a character that can't be decoded by the current system encoding.
=> [fix] Proper encoding of standard output

web/server/vue-cli/src/components/Report/ReportTree/ReportDetailFormatter.js, web/server/vue-cli/src/components/Report/ReportTree/ReportTreeLabel.vue
No need for truncating long filenames in GUI.
=> [gui] Display full filename

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
For clang-tidy the set of warnings can be queried by a tool named `diagtool`. In some environments `clang` is a symlink to `ccache`. Since CodeChecker tries to find `diagtool` right next to clang, this logic doesn't work, since `diagtool` is usually not next to `ccache`.
In this patch CodeChecker searches `diagtool` in the next element of `PATH` environment variable in case `clang` is a symlink to `ccache`, since `ccache` would do the same, too.
Fixes #4371
=> [fix] Don't crash when diagtool is missing

scripts/debug_tools/crash_clustering/README.md, scripts/debug_tools/crash_clustering/cluster_crashes.py, scripts/debug_tools/crash_clustering/requirements.txt
This tool is specific to the aggregate failzip format, that is specifically emitted by our CI, and uses data analysis techniques, which I am only fleetingly familiar with, so take this as it is: a prototype that can be improved.
What are your thoughts?
=> [debug][scripts] Add experimental script for clustering similar crashes

web/server/vue-cli/src/components/Statistics/BaseStatisticsTable.vue
Ordering by report counts did not work properly on Product overview, checker- and severity statistics page. Now it is fixed.
=> [Fix] Sorting of the statistics

analyzer/codechecker_analyzer/cmd/parse.py, tools/report-converter/codechecker_report_converter/report/output/sarif.py
Hello,
This PR allows to run `CodeChecker parse -e sarif ./results -o sarif.json`.
This PR only uses the `convert` function already present in Sarif Parser (https://github.com/Ericsson/codechecker/blob/master/tools/report-converter/codechecker_report_converter/report/parser/sarif.py#L297) and exposes it to the parser cmd.
This would close #4036 I think (I did not test the output on Github)
=> [cmd] Add support for sarif export in parser cmd

analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py, analyzer/codechecker_analyzer/analyzers/gcc/analyzer.py, analyzer/codechecker_analyzer/analyzers/infer/analyzer.py, analyzer/codechecker_analyzer/arg.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/codechecker_analyzer/env.py, analyzer/tests/functional/analyze/test_analyze.py, analyzer/tests/functional/analyze_and_parse/test_files/saargs_forward.output, analyzer/tests/unit/test_checker_handling.py, codechecker_common/util.py, docs/analyzer/user_guide.md
The `--saargs`, `--tidyargs` and `--cppcheckargs` files are now
deprecated. These config files can now be provided through
`--analyzer-config` flag with a common config named
`cc-verbatim-args-file`.
=> [feat] Introduce cc-verbatim-args-file

analyzer/tests/functional/cmdline/test_cmdline.py, codechecker_common/guidelines.py, config/guidelines/cwe-top-25-2024.yaml, config/guidelines/mitre.license, config/labels/analyzers/clang-tidy.json, config/labels/analyzers/clangsa.json, config/labels/descriptions.json, web/server/vue-cli/src/components/Statistics/Guideline/GuidelineStatistics.vue
Introduce the cwe-top-25 guideline to CodeChecker, which consists of the corresponding clang and clang-tidy checkers of the CWE Top 25 Most Dangerous Software Weaknesses.
=> Add CWE Top 25 guideline

analyzer/tests/unit/test_guidelines.py, config/guidelines/cwe-top-25-2024.yaml, web/server/vue-cli/src/components/Statistics/Guideline/GuidelineStatistics.vue, web/server/vue-cli/src/components/Statistics/Guideline/GuidelineStatisticsTable.vue
It's a minor feature for Guideline stat to have rule title column. The `Title` column on the Guideline stat page is disappeared when there is no title for any rule.
=> [feat] Adding rule title column for Guideline stat

web/server/vue-cli/src/components/Statistics/Guideline/GuidelineStatistics.vue, web/server/vue-cli/src/views/NewFeatures.vue
Speeding up guideline stat parser to have a efficient solution and better UX.
It is not neccessary to create an API request for each checker when the severity is needed to match the ceckers. Only one API request/guideline type is sufficient.
There are some other minor fixes in this PR: solving html indent warrning for NewFeatures and exporting guideline stat to csv with rule title.
=> [Refactor] Guideline stat parser

web/server/vue-cli/src/components/Report/Report.vue
A red bubble belongs to the bug report which contains the report details like its location and message.
This commit fixes two bugs:
- The red bubble was shown even if we changed to a different file.
- Clicking on the report title didn't jump to this red bubble.
=> [fix] Bug report bubble display bugfix

analyzer/codechecker_analyzer/buildlog/log_parser.py
When analyzing Chromium or any other large project, __contains_no_intrinsic_headers is called thousands of times for the same dir names. It is an expensive OS call.
=> Cache __contains_no_intrinsic_headers and thus speedup parse_options ~2x

config/guidelines/owasp-top-10-2021.yaml, config/labels/analyzers/clang-tidy.json, config/labels/analyzers/clangsa.json, web/server/vue-cli/src/components/Statistics/Guideline/GuidelineStatistics.vue
Introduce the owasp-top-10-2021 guideline to CodeChecker, which consists of the corresponding clang and clang-tidy checkers of the OWASP Top 10 Web Application Security Risks (2021).
=> Add OWASP Top 10 guideline

analyzer/requirements.txt, tools/report-converter/requirements_py/dev/requirements.txt, web/requirements.txt
sarif-tools is used to parse sarif results file in Parser class.
v3.0.4 comes with many bug fix, improvements, and new features [1].
[1] https://github.com/microsoft/sarif-tools/releases
Fix #4389
=> [tools] bump sarif-tools version from 1.0.0 to 3.0.4

analyzer/codechecker_analyzer/arg.py, analyzer/codechecker_analyzer/cmd/analyze.py, analyzer/codechecker_analyzer/cmd/check.py, analyzer/tests/functional/z3/test_z3.py, web/tests/functional/statistics/test_statistics.py, web/tests/libtest/codechecker.py
One of the great annoyances with any tool, but in particular with CodeChecker is that we have a habit of hiding, suppressing stuff instead of just telling the user whats up. Such is the case with `--stats`, `--ctu`, etc. These flags can only be used if the clang CodeChecker found supports statistics generation or CTU analysis. However, if you try to invoke CodeChecker with an incompatible flag, you get something like this:
```bash
$ CodeChecker analyze compile_commands.json  --stats -o output
usage: CodeChecker [-h] {analyze} ...
CodeChecker: error: unrecognized arguments: --stats
```
That is nuts! Not only do we emit this message, it doesn't even show up in `--help`. How is a user supposed to know about z3 analyses, if we never show it in the first place? If we did, a user might get a …
=> [cmd] Emit errors instead of hiding flags

tools/report-converter/codechecker_report_converter/analyzers/eslint/analyzer_result.py
ESLint reports may contain bugs with "column": null. Thus, report-converter tool raises an exception:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
We set column number to 0 in such cases.
=> fix(report-converter): Support null column in eslint reports

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py, analyzer/codechecker_analyzer/analyzers/clangtidy/config_handler.py, analyzer/codechecker_analyzer/analyzers/config_handler.py, analyzer/tests/unit/test_checker_handling.py, codechecker_common/checker_labels.py, config/labels/analyzers/clang-tidy.json
Earlier "clang-diagnostic-..." checkers could have been provided with their original "W" warning flag form. For example Wformat vs. clang-diagnostic-format. The "W" form is deprecated for a while and the late CodeChecker versions emit a hard error when using them. For this reason there is no need to distinguish "W" form as a warning anymore.
=> [NFC] Eliminate the "W" form of clang-tidy warnings

web/server/vue-cli/src/views/Reports.vue
The report annotation "chronological_order" uses underscore instead of dash. Due to this mistake chronological order doesn't appear in the GUI.
=> [fix] Display chronological order in GUI

codechecker_common/cli.py
If you are developing CodeChecker, you should likely build the 'dev_package' target instead of 'package', as it symlinks instead of copied implementation files. However, CodeChecker will immediately crash if the CC_LIB_DIR environmental variable is not set.
Based on the comment of @bruntib in #4491, this is a one-line fix. The issue is that CodeChecker (for historical reasons) has a non-standar library layout. Instead of every library being on the same level (codechecker_analyzer, codechecker_client, codechecker_web etc), they are all over the place in the source code. The "package" make target that "builds" CodeChecker solves this by copying the libraries in the same directory, with them finally being on the same level.
The "dev_package" target symlinks instead, so that changes in the …
=> [fix] Fix missing CC_LIB_DIR when dev_package is used

web/server/codechecker_server/api/authentication.py
This line is necessary for the OAuth login flow to work correctly due to the way Microsoft includes data in the `callback_url`.
=> fixed url strip error

docs/web/authentication.md, web/server/codechecker_server/api/authentication.py, web/server/codechecker_server/session_manager.py, web/server/config/server_config.json
integrated fetching of signum from `id_token` so it can be used as username for Microsoft.
Can be configured in configuration file what will be username:
`"username": "mail"` or `"username": "signum"`.
=> integrated signum fetching and using it as optional username

.github/workflows/test.yml, web/server/codechecker_server/session_manager.py, web/server/vue-cli/e2e/specs/reports.js
=> E2E tests are flaky (fix)

analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
We mistakenly used the clangsa binary before checking if it exists. Fix that.
=> [bugfix] Don't crash if clangsa binary is missing

web/server/vue-cli/src/views/Login.vue
- Make the username-password field hidable and toggleable with a link.
- Hide SSO login button if no oauth providers are available & show "normal" auth fields.
=> Make username-password login hidable

web/server/vue-cli/src/views/Login.vue
What have been done:
- If only one oauth provider exists the SSO button reads "Login with <providername>" and without opening the modal redirects straight to the provider login page on click. If more than one exists, the standard SSO Login opens on click with the modal to choose the desired provider.
=> Simplify oauth interface

analyzer/tests/unit/test_option_parser.py
The code has been refactored in the following PR, but the test hasn't.
It doesn't fail now only because of cached `ImplicitCompilerInfo.compiler_versions.get`
Run the only test and see the failure.
commit dcc47a515b56a8a91a350389e994587dcbf423e2
Author: bruntib <bruntib@gmail.com>
Date:   Tue Jan 3 12:45:11 2023 +0100
[refactor] Analyzer context as singleton
=> Fix a legacy mistake in the test

web/client/codechecker_client/client.py, web/client/codechecker_client/cmd_line_client.py, web/tests/functional/authentication/test_authentication.py, web/tests/libtest/codechecker.py
When an announcement message is displayed on the GUI, it will be displayed in the CLI as well whenever the CodeChecker cmd login command is used.
=> [feat] Display announcement message in the CLI

analyzer/codechecker_analyzer/buildlog/build_manager.py, analyzer/codechecker_analyzer/cli/check.py, analyzer/codechecker_analyzer/cli/log.py, analyzer/codechecker_analyzer/env.py, analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py, docs/analyzer/user_guide.md
Allows using absolute paths in LD_PRELOAD instead of relying on LD_LIBRARY_PATH for loading ldlogger.so. Helps when build tools override LD_LIBRARY_PATH during build process.
=> [analyzer] Add --use-absolute-ldpreload-path flag to log command

analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
In some environments "diagtool" doesn't exist with this name, but it exists with a name containing version number: "diagtool-14". In this patch we apply some heuristics to try finding diagtool with this extended name, too.
Fixes #4453
=> [fix] Apply heuristics when diagtool comes with version number

analyzer/codechecker_analyzer/buildlog/log_parser.py
Seems ImplicitCompilerInfo.compiler_versions can be re-set more rarely
=> Fix a code duplication

bin/CodeChecker
This caused a bug when codechecker_bazel rules wiped the environment, and while CodeChecker was invoked with the correct interpreter, it failed to retrieve it from PATH. Lets just reuse the interpreter we were invoked with.
=> [bugfix] Pass the correct interpreter from bin/CodeChecker to the analyzers

docs/web/authentication.md, web/server/codechecker_server/api/authentication.py, web/server/codechecker_server/session_manager.py, web/server/config/server_config.json, web/tests/functional/authentication/test_authentication.py, web/tests/libtest/env.py
A customizable message from the server config file should be shown in cli upon failed authentication via CodeChecker cmd login.
As part of this PR, such message was added to the server config file for feature demonstration. This can be removed before merging.
=> [feat] Return custom message in cli upon failed authentication

docs/web/authentication.md, web/api/README.md, web/codechecker_web/server/__init__.py, web/codechecker_web/server/oauth_templates.py, web/server/codechecker_server/api/authentication.py, web/server/codechecker_server/session_manager.py, web/server/config/server_config.json, web/tests/libtest/env.py
Simplified the configuration of OAuth by introducing variables and templates.
In the general case, the user shouldn't ever need to specify any OAuth endpoint URLs.
Instead of relying on the name of the OAuth provider, the configuration now uses so-called "templates" to specify a behavior when logging in. 
Even if the user wants to override a default URL, `{variables}` such as `{host}` help streamline defining URLs.
Example OAuth configuration using templates:
```jsonc
"method_oauth": {
"enabled": true,
"shared_variables" : {
"host": "https://example.com:8123" // must include protocol
},
"providers" : {
"microsoft": {
"enabled": true,
"client_id": "<ExampleClientID>",
"client_secret": "<ExampleClientSecret>",
"template": "ms_entra/v2.0",
"variables": {
"tenant_id": "common" // replace with …
```
=> Add OAuth templates, simplify OAuth configuration flow

config/labels/analyzers/clang-tidy.json, config/labels/analyzers/clangsa.json, config/labels/analyzers/cppcheck.json
- Add new checks to clang-tidy config.
- Update the ClangSA configuration by adding new webkit-related checks and de-alpha-ed checkers.
- Add new checks to CppCheck config.
- Reorganise a few misplaced (according to alphabetical ordering) entries.
=> [cfg] Update clang-tidy, clangsa and cppcheck configurations

web/server/vue-cli/src/views/Reports.vue
The mentioned columns on the web gui reports table hidden if the unique checkbox is active.
=> [gui] Conditionally hide timestamp, test case and chronological order

analyzer/tools/build-logger/src/ldlogger-tool.c, analyzer/tools/build-logger/tests/unit/test_paths.py
When using GNU make-4.2.1, then compiler binary names are not extended to absolute path. By setting "/cc" to CC_LOGGER_GCC_LIKE we assume that the compiler binary is provided by absolute path, since we are performing a suffix check. However, "/cc" is not suffix of "cc". This patch fixes the issue by virtually extending the compiler binary to absolute path.
=> [ld_logger] Fix suffix match on non-absolute paths

web/server/vue-cli/src/views/Login.vue
When the user was already logged in, the `return_to` directive on the `/login` page was ignored.
=> Fix return_to directive when the user is already logged in

codechecker_common/util.py, docs/web/products.md, docs/web/user_guide.md, web/client/codechecker_client/cli/cmd.py, web/server/codechecker_server/api/product_server.py, web/server/codechecker_server/server.py, web/tests/functional/products/test_config_db_share.py, web/tests/functional/products/test_products.py, web/tests/libtest/codechecker.py
Previously, SQL files could be created anywhere on the server. This change restricts them always to inside the config directory.
The old behavior can be brought back by creating symlinks manually in the config dir.
=> Restrict the SQL database creation to the config directory

web/server/codechecker_server/api/product_server.py, web/server/codechecker_server/server.py, web/server/vue-cli/src/components/Product/EditProductBtn.vue
When the SQLite database file's directory is given as an absolute path that is not under the workspace directory, then a meaningful error message should be printed to the user.
=> [fix] Emit error message when SQLite DB is not under workspace dir

web/server/codechecker_server/routing.py, web/server/vue-cli/src/router/index.js
Previously, endpoint validity was only checked on the backend.
Added a redirect to the 404 page on unknown URLs in general as well.
=> Only respond to valid endpoints on the frontend

analyzer/codechecker_analyzer/buildlog/log_parser.py
Set LC_ALL to C, as the parser will not detect include paths, if the compiler output is localized.
=> Ensure the compiler has no L18Ned output

web/server/codechecker_server/migrations/logging.py
Python "logging" module handles a hierarchy of loggers. Loggers can be given handlers to handle the actual log message. If a logger doesn't have a handler then the parent's handler will be used. "logger.handlers" is an array containing the direct handlers, but "logger.hasHandlers()" returns true even if the parent has a handler. So, the array can be empty and "hasHandlers()" still returns True.
=> [fix] Fix migration logging

.github/workflows/codechecker_master_analysis.yml, .github/workflows/codechecker_pr_analysis.yml, .gitmessage, ci/github_analysis/codechecker_gate_master.sh, ci/github_analysis/codechecker_gate_pr.sh, ci/github_analysis/pylint_analyze.sh
Analyze CodeChecker code with CodeChecker when creating pull-request and compare to master. Fail PR if new issues introduced.
=> [ci] Add CodeChecker analyze to GitHub Actions

analyzer/codechecker_analyzer/analysis_manager.py, analyzer/codechecker_analyzer/analyzer.py
`create_actions_map` is slow because it updates manager.dict() on every iteration via multiprocessing
Before
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.002    0.002  585.945  585.945 /home/zzz/Documents/Projects/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzer.py:165(perform_analysis)
1    1.037    1.037  579.764  579.764 /home/zzz/Documents/Projects/codechecker/build/CodeChecker/lib/python3/codechecker_analyzer/analyzer.py:82(create_actions_map)
340784    0.932    0.000  578.300    0.002 /home/zzz/Documents/Projects/codechecker/venv/lib/python3.13/site-packages/multiprocess/managers.py:809(_callmethod)
170392    0.126    0.000  499.783    0.003 <string>:1(__setitem__)
340792    1.143    0.000  450.775    0.001 …
```
=> [fix] Significant speed-up for create_actions_map and start_workers

web/server/vue-cli/src/components/Icons/SeverityIcon.vue
The original code only updates the color once, so the severity icon in the checker retains the color of the first checker the user opens.
For example, if a `low` severity checker is opened first, the icon will appear green in all checker tabs, regardless of their actual severity:
=> Fix SeverityIcon color error

Makefile, web/server/codechecker_server/api/mass_store_run.py, web/tests/functional/review_status/test_review_status.py
Fix updating fixed_at time on every store command. Now it should only update if there is no fixed_at timestamp present, yet.
=> [fix] Fix updating fixed_at time

analyzer/codechecker_analyzer/buildlog/log_parser.py, analyzer/codechecker_analyzer/cli/analyze.py
See https://github.com/Ericsson/codechecker/pull/4479#issuecomment-2704631041 parse_options is very slow.
In this PR I parallelize calls to it.
=> [fix] Parallelize parse_unique_log to speed-up ~nproc times

docs/usage.md
Let the link point to the same place as it did in 1eaf280
Or maybe the link should point to the heading "Using skip file to narrow analyzed files" in this file. There is a link to the other document if more details are desired.
=> fix link ref in usage.md

config/guidelines/memory-safety.yaml, config/labels/analyzers/clang-tidy.json, config/labels/analyzers/clangsa.json, config/labels/analyzers/cppcheck.json, config/labels/analyzers/gcc.json, config/labels/descriptions.json, web/server/vue-cli/src/components/Statistics/Guideline/GuidelineStatistics.vue
This PR adds a new guideline, `memory-safety`, which can be useful for developers who are interested in catching specifically memory-safety bugs. 
Furthermore, my suggestion (included in the PR) is to raise `unix.MismatchedDeallocator` and `unix.Malloc` to `HIGH` severity. The former _always_ leads to UB on true positives, and the latter almost always.
=> Add memory-safety guideline

.github/workflows/codechecker_pr_analysis.yml, .pylintrc, ci/github_analysis/codechecker_gate_pr.sh, ci/github_analysis/pylint_analyze.sh
Use the same directories and ignores in CC gating as pylint uses when ran with the tests on github. Pylint uses the pylintrc file to set up itself when it comes to disabled checkers.
=> ci: Sync pylint usage of CC gating with style tests

web/server/vue-cli/package-lock.json, web/server/vue-cli/package.json, web/server/vue-cli/src/components/Statistics/Guideline/GuidelineStatisticsTable.vue, web/server/vue-cli/src/mixins/severity.mixin.js
**What have been done:**
In this change, a new UUID was introduced to the guideline statistics page where the items previously did not have any real unique key to use. This UUID field is unique and can be used as a key when displaying or more importantly, sorting the data.
=> Guideline stats sorting issue
