Ericsson/codechecker

- codechecker_lib/debug_reporter.py
fix env variable name collision with module name
> fix debug reporter module

- config/package_layout.json
> fix typo for gdb file

- .gitignore
update gitignore with bzip2 test project build files
> update gitignore with bzip2 test project build files

- codechecker_lib/arg_handler.py
- codechecker_lib/client.py
- codechecker_lib/db_version.py
- codechecker_lib/generic_package_context.py
- config/version.json
- storage_server/report_server.py
- viewer_server/client_db_access_handler.py
- viewer_server/client_db_access_server.py
db version should be also configured in the version config file
Database version update was missing for the release version.
With the new config file it will be easier to modify version if there is a new release or database schema change.
> update version handling

- codechecker_lib/util.py
Updated localhost checker function for postgres.
> Updated localhost checker function for postgres.

- viewer_server/client_db_access_handler.py
Fixes Ericsson/codechecker#23.
> Fix report query (Ericsson/codechecker#23).

- viewer_clients/web-client/scripts/codecheckerviewer/OverviewHeader.js
This fixes Ericsson/codechecker#25
> Do not use ECMAScript 6 initializer notation

- codechecker_lib/log_parser.py
> fix missing module import

- tests/performance_test/run_performance_test.py
add initial performance tester
> initial performance tester

- codechecker_lib/analyzer.py
- db_model/orm_model.py
- docs/user_guide.md
- Add whitelist support
- Glob based pattern matching in skip files
Resolves Ericsson/codechecker#31 and Ericsson/codechecker#41
> Skip file improvements

- docs/user_guide.md
fixes #52 
+restructured documentation for skip and suppressfile
+added description of some options
+describe the distributed check use case
> Fixing the user guide

- storage_server/report_server.py
- viewer_server/client_db_access_handler.py
> update loglevels in case there is a db version mismatch (issue #51)

- codechecker/CodeChecker
- config/package_layout.json
simple modification in the package layout
some additional missing user guide modifications are also added to the develop branch
> move lib files to new directory in the package

- viewer_clients/web-client/scripts/codecheckerviewer/BugStMoTr.js
- viewer_clients/web-client/scripts/codecheckerviewer/CodeCheckerViewer.js
- viewer_clients/web-client/scripts/codecheckerviewer/FileViewBC.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewGrid.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewHeader.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewStore.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewTC.js
- viewer_clients/web-client/scripts/codecheckerviewer/Util.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/Filter.js
- viewer_server/client_db_access_handler.py
* Use async Thrift calls
* Use dynamic loading in bug tree
* Use dynamic loading in grids
* Eliminate some depricated API calls
* Fix sorting in grids
* Fix getReport query in viewer server
* Cleanups
* Add documentation at least for modified parts
* Remove pager (dynamic loading instead)
Resolves Ericsson/codechecker#49
> Rewrite diff and run overview.

- codechecker_lib/analyzer.py
- codechecker_lib/analyzer_env.py
- codechecker_lib/arg_handler.py
- codechecker_lib/checkers.py
- codechecker_lib/client.py
- codechecker_lib/generic_package_context.py
- codechecker_lib/host_check.py
- codechecker_lib/plist_helper.py
- codechecker_lib/plist_parser.py
- codechecker_lib/suppress_file_handler.py
- codechecker_lib/util.py
- viewer_server/client_db_access_handler.py
- viewer_server/client_db_access_server.py
If you are ok with these kind of changes, I will fix the rest and make sure they don't come back.
> Flake8 consistency

- viewer_clients/web-client/scripts/codecheckerviewer/BugStoreModelTree.js
- viewer_clients/web-client/scripts/codecheckerviewer/CodeCheckerViewer.js
- viewer_clients/web-client/scripts/codecheckerviewer/FileViewBC.js
- viewer_clients/web-client/scripts/codecheckerviewer/ListOfRunsGrid.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewGrid.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewHeader.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewTC.js
- viewer_clients/web-client/scripts/codecheckerviewer/Util.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/DiffWidget.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/Filter.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/MenuButton.js
Comments inserted for important parts of WEBGUI Javascript files.
Code formatting made more consistent.
Behaviour of Filter widget changed slightly(now we can delete any filter except the uppermost one.
> WEBGUI: Comments, Formatting, Filter widget changes

- viewer_clients/web-client/scripts/codecheckerviewer/OverviewGrid.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/Filter.js
Functionality of _createQuery() merged into refreshGrid().
Also involved some code restructuring and formatting changes.
> Fixes Ericsson/codechecker#67

- codechecker_lib/debug_reporter.py
> extend generated debug info

- storage_server/report_server.py
create new run entry instead of stopping, if update option is used at check
fixes #57
> do not stop if run entry not found in update check mode

- build_package.py
add some extra debug info and error handling to the package builder
> add some extra debug info and error handling

- .ci/python_requirements
- README.md
- alembic.ini
- build_package.py
- codechecker_lib/client.py
- codechecker_lib/context_base.py
- config/package_layout.json
- config/version.json
- db_migrate/README
- db_migrate/env.py
- db_migrate/script.py.mako
- db_migrate/versions/63efc03c2a5_initial_schema.py
- db_model/orm_model.py
- storage_server/report_server.py
- Add new dependency: alembic
- Add initial schema script
- Set sqlalchemy naming conventions
- Use auto-generated sequences for table ids
> Database migration support

- viewer_clients/web-client/index.html
- viewer_clients/web-client/scripts/codecheckerviewer/CodeCheckerViewer.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewGrid.js
Implemented browser compatibility checking feature, which fixes Ericsson/codechecker#93.
Also corrected an anonymous object creation expression in OverviewGrid.js, because it was a non-standard JavaScript expression that broke IE9 compatibility a few commits before.
> Check browser compatibility

- README.md
- db_migrate/env.py
- docs/db_schema_guide.md
Document how to modify the database schema in backward compatible way.
This resolves Ericsson/codechecker#96
> Add alembic documentation

- codechecker_lib/client.py
- codechecker_lib/generic_package_suppress_handler.py
- codechecker_lib/suppress_file_handler.py
- codechecker_lib/suppress_handler.py
- db_migrate/versions/2b23d1a4fb96_udpate_suppress_handling.py
- db_model/orm_model.py
- storage_server/report_server.py
- test_package.py
- thrift_api/report-storage-server.thrift
- viewer_server/client_db_access_handler.py
Suppress handling is updated because bug hash is not enough to identify a bug.
Source file name is also stored together with the hash in the database and in the suppress file also.
(new and old suppress file format is supported)
> update suppress handling

- codechecker_lib/analyzer.py
- codechecker_lib/arg_handler.py
- codechecker_lib/database_handler.py
- storage_server/report_server.py
- fix some error codes
- delete an unused function
This resolves Ericsson/codechecker#95
> Fix exit status codes in some cases

- .travis.yml
- codechecker_lib/arg_handler.py
- codechecker_lib/client.py
- codechecker_lib/suppress_handler.py
- docs/user_guide.md
- storage_server/report_server.py
- test_unit_test.py
- tests/regression_test/test_hash_clash.py
- tests/unit_test/test_source_suppress.py
- thrift_api/report-storage-server.thrift
> suppression support in the source code

- codechecker/CodeChecker.py
- codechecker_lib/arg_handler.py
- docs/user_guide.md
> Cleanup by default

- docs/user_guide.md
section names were not generated properly by doxygen
> some minimal formatting so it looks better when generated with doxygen

- docs/user_guide.md
Fixes Ericsson/codechecker#113
> Add quickcheck documentation

- test_package.py
- tests/regression_test/test_suppress_file_cmdline.py
- thrift_api/report-viewer-server.thrift
- viewer_server/client_db_access_handler.py
This is part of the Ericsson/codechecker#111
> suppress file path api extension

- viewer_clients/web-client/scripts/codecheckerviewer/ListOfRunsGrid.js
FIXES Ericsson/codechecker#125
> Pretty printing for run duration (HH:MM:SS)

- viewer_clients/web-client/scripts/codecheckerviewer/OverviewHeader.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/Filter.js
> Path filter now sends input as substring by default.

- tests/regression_test/test_regression_report_filter.py
- tests/test_projects/bzip2/project_info.json
- viewer_server/client_db_access_handler.py
case insensitive filtering at server side for file path, checker name, checker message
Ericsson/codechecker#127
> case insensitive filtering

- viewer_server/client_db_access_handler.py
Fixes Ericsson/codechecker#141
> replace unsupported utf8 characters for the viewer

- viewer_server/client_db_access_handler.py
Fixes Ericsson/codechecker#128
> fix filepath in bugpath and bugevent lists

- .ci/python_requirements
- .travis.yml
- README.md
- codechecker_lib/arg_handler.py
- codechecker_lib/debug_reporter.py
- codechecker_lib/host_check.py
- codechecker_lib/util.py
- storage_server/report_server.py
- viewer_server/client_db_access_handler.py
- Add pg8000 support in connection string
- Modify database creation and count() SQL expression to make it pg8000 friendly
- Test with psycopg2 and pg8000 in Travis
Resolves Ericsson/codechecker#147
> pg8000 support

- db_migrate/versions/f6791c2b40d_add_can_delete_to_run_table.py
- db_model/orm_model.py
- thrift_api/report-viewer-server.thrift
- viewer_clients/web-client/scripts/codecheckerviewer/CodeCheckerViewer.js
- viewer_clients/web-client/scripts/codecheckerviewer/ListOfRunsGrid.js
- viewer_server/client_db_access_handler.py
- viewer_server/client_db_access_server.py
This resolves Ericsson/codechecker#151
> Hide runs under removal from the grid immediately

- build_package.py
- use jquery for async communication in Thrift
Fixes Ericsson/codechecker#153
> Use jquery for javascript thrift API

- viewer_clients/web-client/scripts/codecheckerviewer/CodeCheckerViewer.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewGrid.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewHeader.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewTC.js
- viewer_clients/web-client/scripts/codecheckerviewer/Util.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/Filter.js
- viewer_clients/web-client/style/codecheckerviewer.css
Revamped the filters of the Run Overview. The new CheckerInfo Select unifies the functionality of the late CheckerType and Severity Selects. This new Select also refreshes automatically when needed.
Diff Overview filters remain unchanged.
FIXES Ericsson/codechecker#137
> Smart filters

- viewer_clients/cmdline_client/cmd_line_client.py
Auto indentation tool messed up plain text table generator.
Fixing Ericsson/codechecker#159
> fix indentation

- viewer_clients/web-client/scripts/codecheckerviewer/Util.js
Changed getAvailableCheckersForDiff to make Thrift API calls in parallel.
Late fix for Ericsson/codechecker#137.
> Fixed sequential Thrift API calls.

- codechecker_lib/arg_handler.py
fix unique key constraint name to handle error message properly
> fix unique key constraint name

- viewer_server/client_db_access_handler.py
suppress table join was missing, required for filtering
> fix query in getRunResultTypes

- config/checker_severity_map.json
increase severity level for core.CallAndMessage checker
> modify severity level for checker

- external-source-deps/build-logger/src/ldlogger-util.c
This resolves Ericsson/codechecker#166
> Fix logger json apostrophe escaping

- tests/regression_test/test_regression_diff.py
- tests/test_projects/bzip2/project_info.json
- thrift_api/report-viewer-server.thrift
- viewer_server/client_db_access_handler.py
Fixes Ericsson/codechecker#152
> add new api to count diff results and diff result types

- config/checker_severity_map.json
increase severity level for core.uninitialized.UndefReturn
> change checker serverity level for HIGH

- test_package.py
- tests/regression_test/test_suppress_file_cmdline.py
use unique temporary suppress file name for each test run
> unique test suppress file for each test run

- .travis.yml
- README.md
- codechecker/CodeChecker.py
- codechecker_lib/arg_handler.py
- codechecker_lib/client.py
- codechecker_lib/database_handler.py
- codechecker_lib/debug_reporter.py
- codechecker_lib/host_check.py
- codechecker_lib/util.py
- db_model/orm_model.py
- docs/user_guide.md
- external-source-deps/build-logger/src/ldlogger-tool-javac.c
- storage_server/report_server.py
- test_package.py
- viewer_server/client_db_access_handler.py
- viewer_server/client_db_access_server.py
- Move all database server specific code to database_handler.py
- Change check constraint naming convensions to be compatible with SQLite. This is backward compatible because currently there is no check constraint in the database schema.
- Fix Run.mark_finished() to store integer
- Fix suppress queries to use True and False (boolean) instead of strings.
- Fix supress -> suppress typos
- Add sqlite support to package_test
- Add sqlite test to Travis
This resolves Ericsson/codechecker#148
> SQLite support

- codechecker_lib/arg_handler.py
initialize database at server start
migration is also done if required by the server
> initialize database at server start

- db_migrate/versions/453083da7cce_quick_delete.py
- db_model/orm_model.py
Fixes Ericsson/codechecker#173
> Make deleting quicker

- config/checker_severity_map.json
increase severity level for checker core.NonNullParamChecker
> update severity level

- external-source-deps/build-logger/src/ldlogger-tool-gcc.c
- external-source-deps/build-logger/src/ldlogger-tool-javac.c
- external-source-deps/build-logger/src/ldlogger-util.c
- external-source-deps/build-logger/src/ldlogger-util.h
- Modify loggerVectorAddFrom to support insert position
- Add the default arguments after the last -I argument
This fixes Ericsson/codechecker/#182
> Put the default include paths after the last include

- viewer_clients/web-client/scripts/codecheckerviewer/CodeCheckerViewer.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewGrid.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewHeader.js
- viewer_clients/web-client/scripts/codecheckerviewer/Util.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/Filter.js
Updated Diff Overview to match the new functionality and design of the Run Overview.
This made two functions in Util.js obsolete which thus were removed.
FIXES Ericsson/codechecker#161
> Updated Diff Overview

- codechecker_lib/option_parser.py
- test_quickcheck.py
Add support for PowerPC 32/64, and Mips 32/64. Also filter out some unknown, unneeded options.
> Add some cross-compiler support

- viewer_clients/web-client/scripts/codecheckerviewer/BugStoreModelTree.js
- viewer_clients/web-client/scripts/codecheckerviewer/CodeCheckerViewer.js
- viewer_clients/web-client/scripts/codecheckerviewer/Editor.js
- viewer_clients/web-client/scripts/codecheckerviewer/FileViewBC.js
- viewer_clients/web-client/scripts/codecheckerviewer/ListOfRunsGrid.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewGrid.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewHeader.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewStore.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewTC.js
- viewer_clients/web-client/scripts/codecheckerviewer/Util.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/EditorHeader.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/Filter.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/ListOfRunsWidget.js
- viewer_clients/web-client/scripts/codecheckerviewer/widgets/MenuButton.js
Also some consistency changes, general formatting improvements.
> JSHint based reformatting of the source files.

- codechecker_lib/database_handler.py
- codechecker_lib/debug_reporter.py
- storage_server/report_server.py
- viewer_server/client_db_access_server.py
* Refactoring create_engine
* Fix Ericsson/codechecker#198
Fixes Ericsson/codechecker#198
> Refactoring create_engine + fix

- codechecker_lib/database_handler.py
- codechecker_lib/host_check.py
- Add sqlite driver checking to host_check
- Change error message when the selected driver is not available
Fixes Ericsson/codechecker#193
> Check SQLite driver

- viewer_clients/web-client/index.html
FIXES Ericsson/codechecker#146
> Fixed Browser support screen.

- codechecker_lib/arg_handler.py
- codechecker_lib/database_handler.py
- codechecker_lib/db_version.py
- storage_server/report_server.py
- viewer_server/client_db_access_handler.py
Fit the following bugs:
Fix #184 
Fix #199
> Improve database handling

- viewer_clients/web-client/scripts/codecheckerviewer/CodeCheckerViewer.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewTC.js
FIXES Ericsson/codechecker#145
> Grids are now selectable.

- viewer_clients/web-client/scripts/codecheckerviewer/Editor.js
> Removed foldgutters

- viewer_clients/web-client/scripts/codecheckerviewer/FileViewBC.js
FIXES Ericsson/codechecker#129
> Fixed suppressing, also made it async.

- viewer_clients/web-client/scripts/codecheckerviewer/ListOfRunsGrid.js
FIXES Ericsson/codechecker#179
> Fixed run duration, now shows dashes instead of -1 for unfinished or failed runs.

- viewer_server/client_db_access_handler.py
- Refactor sorting to a separate helper method
- In case of sorting by file path, sort by line numer too
Fixes Ericsson/codechecker#118
> When sorting by file path, sort by line number too

- viewer_clients/web-client/scripts/codecheckerviewer/CodeCheckerViewer.js
- viewer_clients/web-client/scripts/codecheckerviewer/FileViewBC.js
- viewer_clients/web-client/scripts/codecheckerviewer/ListOfRunsGrid.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewHeader.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewTC.js
Fixed missing error handling in some instances, also switched to forEach from for where it was applicable.
FIXES Ericsson/codechecker#140
> Error handling, forEach swaps

- build_package.py
- external-source-deps/ext_source_deps_config.json
- split download command it there are additional arguments
- use non https download urls (older wget versions might fail to verify certificate'
> update package building

- codechecker_lib/option_parser.py
add the -fno-strength-reduce flag to the unsupported list
> unsupported flag

- codechecker_lib/database_handler.py
- db_model/orm_model.py
> Fix cascade delete in sqlite.

- codechecker_lib/analyzers/result_handler_plist_to_db.py
fix message if analysis failed, use the analyzer type from the buildaction
> change log message if analysis failed

- codechecker_lib/analysis_manager.py
- codechecker_lib/analyzer.py
- codechecker_lib/analyzer_env.py
- codechecker_lib/analyzers/analyzer_types.py
- codechecker_lib/analyzers/config_handler_clangsa.py
- codechecker_lib/analyzers/result_handler_clang_tidy.py
- codechecker_lib/build_manager.py
- codechecker_lib/checkers.py
- codechecker_lib/host_check.py
- codechecker_lib/log_parser.py
- codechecker_lib/logger.py
- docs/user_guide.md
FIXES Ericsson/codechecker#229
> New loglevel introduced: DEBUG_ANALYZER (between DEBUG and INFO)

- test_package.py
This test generates a simple skip list file just to check if it can be parsed.
Resolves #244
> add simple skip list test

- codechecker_lib/analyzers/result_handler_plist_to_stdout.py
- tests/quickcheck_test/multi_error.en1.output
- tests/quickcheck_test/multi_error.en2.output
- tests/quickcheck_test/multi_error.output
- tests/quickcheck_test/multi_error.steps.output
- tests/quickcheck_test/nofail.output
- tests/quickcheck_test/nofail.steps.output
- tests/quickcheck_test/simple1.output
- tests/quickcheck_test/simple1.steps.output
- tests/quickcheck_test/simple2.output
- tests/quickcheck_test/simple2.steps.output
> Extended quickcheck output

- codechecker_lib/arg_handler.py
- tests/quickcheck_test/multi_error.en1.output
- tests/quickcheck_test/multi_error.en2.output
- tests/quickcheck_test/multi_error.output
- tests/quickcheck_test/multi_error.steps.output
- tests/quickcheck_test/nofail.output
- tests/quickcheck_test/nofail.steps.output
- tests/quickcheck_test/simple1.output
- tests/quickcheck_test/simple1.steps.output
- tests/quickcheck_test/simple2.output
- tests/quickcheck_test/simple2.steps.output
> enable original build output

- tests/quickcheck_test/test.py
test files and subprocess output should be handled as unicode
> process output and test files should be handled as unicode

- viewer_clients/web-client/scripts/codecheckerviewer/BugStoreModelTree.js
- viewer_clients/web-client/scripts/codecheckerviewer/CodeCheckerViewer.js
- viewer_clients/web-client/scripts/codecheckerviewer/FileViewBC.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewGrid.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewHeader.js
- viewer_clients/web-client/scripts/codecheckerviewer/OverviewTC.js
FIXES Ericsson/codechecker#262
> Changed CCV scripts 'importing' to dojo convention.

- codechecker_lib/build_manager.py
empty lines/outputs should be printed better
> use stdout write instead of print

- viewer_clients/web-client/index.html
This is a missing fix for Ericsson/codechecker#268
> Missing index.html fixes for webgui better imports.

- codechecker_lib/analysis_manager.py
- codechecker_lib/analyzer.py
- codechecker_lib/analyzers/analyzer_clang_tidy.py
- codechecker_lib/analyzers/analyzer_clangsa.py
- codechecker_lib/analyzers/analyzer_types.py
- codechecker_lib/analyzers/config_handler_clang_tidy.py
- codechecker_lib/analyzers/config_handler_clangsa.py
- codechecker_lib/client.py
- codechecker_lib/database_handler.py
- codechecker_lib/debug_reporter.py
- codechecker_lib/generic_package_context.py
- codechecker_lib/host_check.py
- codechecker_lib/log_parser.py
- codechecker_lib/suppress_file_handler.py
- db_migrate/versions/453083da7cce_quick_delete.py
- db_migrate/versions/464168cc48ad_remove_bug_hash_type.py
- db_migrate/versions/4e97419519b3_remove_run_id_primary_key_from_skippath_.py
- db_migrate/versions/f6791c2b40d_add_can_delete_to_run_table.py
- storage_server/report_server.py
- tests/performance_test/run_performance_test.py
- tests/regression_test/test_regression_diff.py
- tests/regression_test/test_regression_getall_wrapper.py
- tests/regression_test/test_regression_report_filter.py
- tests/regression_test/test_regression_run_results.py
- tests/regression_test/test_suppress_file_cmdline.py
- tests/test_helper/testlog.py
- viewer_clients/cmdline_client/thrift_helper.py
- viewer_server/client_db_access_handler.py
- viewer_server/client_db_access_server.py
most of the pyflake warnings are cleaned up
unused or missing imports are fixed
resolves #260
> cleanup pyflakes warnings

- viewer_clients/web-client/scripts/codecheckerviewer/BugStoreModelTree.js
- viewer_clients/web-client/scripts/codecheckerviewer/FileViewBC.js
Display both suppressed and unsuppressed bugs in the tree. The
suppressed files are shown in gray color.
> Suppressed and unsuppressed bugs in the tree

- storage_server/report_server.py
Do the filtering in one step instead of two.
> Simplify adding reports.

- storage_server/report_server.py
In case some reports were suppressed the update mode did not cleanup the results properly.
This pull request tires to fix this and some cleanup is done in the source for better understanding.
Stored results should be removed properly in update mode. If the same build action and check command is detected the corresponding results with no other references in the database should be deleted.
> fix update mode

- docs/user_guide.md
> update example for tidyargs

- codechecker_lib/analysis_manager.py
This commit fixes #294.
A build action is considered to be skipped if any of the source files in
the build action is skipped.
> Count skipped actions in the statistics

- db_model/orm_model.py
- docs/deps.md
- storage_server/report_server.py
Various cleanups and small bug fixes.
> Various cleanups and small bug fixes.

- viewer_clients/web-client/scripts/codecheckerviewer/ListOfRunsGrid.js
This commit fixes #312 and fixes #313.
> Resize columns and set alignment of "name" column

- codechecker/CodeChecker
- codechecker_lib/build_manager.py
The analysis process is stopped already but the exit codes were wrong this pull request resolves #323
> fix exit code handling, for the original build and the main script

- tests/test_packages/functional/package_test/__init__.py
For some slower machines more time is needed for PostgreSQL to stop and restart.
> increase wait time in the tests

- codechecker_lib/analysis_manager.py
- codechecker_lib/analyzers/result_handler_base.py
- codechecker_lib/context_base.py
- config/config.json
> use analysis name unique temporary directory for reports

- thrift_api/report_viewer_server.thrift
- viewer_clients/cmdline_client/cmd_line_client.py
- viewer_server/client_db_access_handler.py
The getBuildActions now returns all information about the build actions,
not only the build command.
> BuildAction thrift API

- viewer_clients/cmdline_client/thrift_helper.py
> Better error handling for thrift connections

- tests/functional/package_test/test_regression_getall_wrapper.py
- tests/functional/package_test/test_regression_run_results.py
- tests/test_utils/debug_printer.py
Print more relevant information during the tests to help debugging.
> Print more information during the tests

- build_package.py
Fix for Error druing install #388 issue
> Fix error during install on Linux without scan-build-py

- README.md
> Remove redundant section from the readme

- codechecker_lib/option_parser.py
> Discard -fno-aggressive-loop-optimizations flag.

- viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js
> Remove severity levels from bug view if it has no children.

- viewer_clients/web-client/scripts/codecheckerviewer/ListOfRuns.js
> Order runs by date descending.

- viewer_clients/cmdline_client/cmd_line_client.py
> CSV format output for command line client.

- viewer_clients/cmdline_client/cmd_line_client.py
> Basic filter option in command line client.

- viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js
- viewer_clients/web-client/style/codecheckerviewer.css
> Highlight currently selected bug path event.

- viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js
- viewer_clients/web-client/style/codecheckerviewer.css
> Add bubbles in case the path goes through files.

- codechecker_lib/decorators.py
- codechecker_lib/profiler.py
- storage_server/report_server.py
- tests/functional/package_test/__init__.py
- tests/functional/package_test/test_regression_diff.py
- tests/functional/package_test/test_regression_getall_wrapper.py
- tests/functional/package_test/test_suppress.py
- tests/performance_test/readme.md
- tests/performance_test/run_performance_test
- tests/performance_test/run_performance_test.py
- tests/test_utils/__init__.py
- tests/test_utils/thrift_client_to_db.py
- viewer_server/client_db_access_handler.py
- improve performance test framework
- add new profiler options to CodeChecker
- do some source cleanup
> Improve performance test framework

- codechecker/CodeChecker
- codechecker/CodeChecker.py
- codechecker_lib/analysis_manager.py
- codechecker_lib/analyzer.py
- codechecker_lib/analyzers/analyzer_types.py
- codechecker_lib/analyzers/config_handler_clang_tidy.py
- codechecker_lib/analyzers/result_handler_base.py
- codechecker_lib/analyzers/result_handler_plist_to_db.py
- codechecker_lib/arg_handler.py
- codechecker_lib/build_manager.py
- codechecker_lib/database_handler.py
- codechecker_lib/generic_package_context.py
- codechecker_lib/host_check.py
- codechecker_lib/option_parser.py
- codechecker_lib/session_manager.py
- codechecker_lib/util.py
- docs/package_layout.md
- docs/postgresql_setup.md
- docs/user_guide.md
- storage_server/report_server.py
- viewer_clients/cmdline_client/cmd_line_client.py
- viewer_server/client_auth_handler.py
> Consistent help messages.

- storage_server/report_server.py
- viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js
> Store build and check command only in debug mode.

- codechecker_lib/arg_handler.py
- codechecker_lib/client.py
- storage_server/report_server.py
Cleanups in addition to the fix to #428:
* Removed some unused arguments.
* Fixed some typos.
* Fixed some PEP8 non-formatting related warnings.
* Removed an unused import.
> Update check command in update mode. Minor cleanups.

- codechecker_lib/analyzers/analyzer_base.py
- tests/unit/test_buildcmd_escaping.py
> Use POSIX mode to lex shell command line arguments.

- codechecker_lib/auth/__init__.py
- codechecker_lib/auth/cc_ldap.py
- codechecker_lib/auth/cc_pam.py
- codechecker_lib/session_manager.py
- config/session_config.json
- docs/authentication.md
- viewer_server/client_auth_handler.py
- viewer_server/client_db_access_handler.py
Improvements:
- more fine grained LDAP configuration is available
- base DN to search for user accounts or groups
- configurable account, group, and group membership patterns for LDAP
search
- checking LDAP group membership is supported
Fixes:
- Fixed some module imports (datetime)
- Use the pofiler module to measure the API calls
> Improved LDAP authentication

- Doxyfile.in
- config/version.json
Increase release version to 5.6
> Increase release version to 5.6

- viewer_clients/web-client/scripts/codecheckerviewer/filterHelper.js
> Sort checker filter ComboBox by descending severity.

- codechecker_lib/arg_handler.py
- codechecker_lib/build_manager.py
If multiple CodeChecker instances use the same workspace it might
happend that the same compilation command json file was used
for analysis by multiple CodeCheckers.
> Use unique compilation commands file names for each run

- viewer_clients/cmdline_client/cmd_line_client.py
Instead of letting the Thrift error fall back across the stack and terminate the application, this little fix handles it more gracefully.
If server and client are both supporting authentication: interfaces match and normal business continues.
If server does not support authentication, the client falls back as if the server reported `I don't have authentication enabled` when running `CodeChecker cmd` commands. The `CodeChecker cmd login` command explicitly reports that the server the user tries to connect to does not, at all, support authentication.
Fixes #471
> Fix error when connecting to servers not supporting auth

- .travis.yml
The compressed file was moved to another place.
> Fix llvm,clang download url for OSX in travis

- codechecker/CodeChecker.py
Logger configuration was missing for getting version info
> Fix missing logger configuration for version info

- viewer_clients/web-client/scripts/codecheckerviewer/filterHelper.js
> Bugfix: Filter by severity didn't work.

- viewer_clients/web-client/style/codecheckerviewer.css
> Fix webgui file path having '/' on the right

- viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js
> Don't redraw bugpath if "Show arrows" not selected.

- codechecker_lib/arg_handler.py
> Bugfix: crash in plist parser.

- codechecker/CodeChecker.py
- codechecker_lib/logger.py
- viewer_clients/cmdline_client/cmd_line_client.py
> Cmd verbose log

- README.md
- docs/deps.md
> Readme update for newer Ubuntu and clang

- codechecker_lib/database_handler.py
> Bugfix: database existence checking

- viewer_clients/cmdline_client/cmd_line_client.py
- viewer_clients/cmdline_client/thrift_helper.py
Also, renamed a variable in viewer_cmd/thrift_helper so name matches "serverside" name.
> Unduplicate code in cmd sum and results

- viewer_clients/cmdline_client/cmd_line_client.py
Only the query limit number of results were printed
if json output format was selected.
> fix cmdline client result query (json)

- codechecker_lib/arg_handler.py
> Proper error message in case of used server address.

- Makefile
Should resolve #546 and fixes #554
> Fix thrift gen js typo

- viewer_clients/web-client/scripts/codecheckerviewer/BugViewer.js
> HTML escaping in big viewer

- .gitignore
- codechecker_lib/arg_handler.py
- codechecker_lib/generic_package_context.py
- codechecker_lib/logger.py
- external-source-deps/ext_source_deps_config.json
- scripts/build_package.py
- thrift_api/report_viewer_server.thrift
- viewer_clients/web-client/scripts/codecheckerviewer/codecheckerviewer.js
- viewer_clients/web-client/style/codecheckerviewer.css
- viewer_server/client_db_access_handler.py
- viewer_server/client_db_access_server.py
`CodeChecker server`:
`CodeChecker server --verbose debug`
The same output is added to `CodeChecker version`. In debug mode, extra annotation is showed, while "normal" mode only shows the release tag.
> Show version info in Viewer

- tests/functional/authentication/__init__.py
- tests/functional/diff/__init__.py
- tests/functional/func_template/template__init__.py
- tests/functional/report_server_api/__init__.py
- tests/functional/report_viewer_api/__init__.py
- tests/functional/skip/__init__.py
- tests/functional/suppress/__init__.py
- tests/functional/update/__init__.py
* remove unused variables
* fix printed messages and wait for PostgreSQL shutdown only if PostgreSQL is used
> Test runner cleanup (PostgreSQL)

- .gitignore
(Accidental oversight in #584)
> Fix wrong directive in .gitignore

- Doxyfile.in
- config/package_layout.json
- vendor_projects.json
* clean removed external-source-dep references
* move db_migrate to the lib directory in the built package
* fonts should be downloaded to the vendor dir
Extending #590
> small package layout and vendor handling changes

- Makefile
Fix directory deletion if already exists.
> Makefile fix (thrift generated files)

- libcodechecker/arg_handler.py
- tests/functional/instance_manager/__init__.py
- tests/functional/instance_manager/test_instances.py
Adds tests for #496. Closes #587.
> Add tests for stop server

- tests/functional/instance_manager/test_instances.py
Fix apparent race introduced in #595.
> Remove race capable code, fixing stop-server tests on OSX

- www/scripts/codecheckerviewer/BugViewer.js
> Bugfix of wrong arrow positions.

- .travis.yml
- Makefile
- config/session_client.json
- config/session_config.json
* remove dummy authentication credentials in it enough it they are in the documentation
* cleanup configuration files in each travis run
> Travis and auth cfg cleanup

- docs/user_guide.md
Follow-up for #610, I've extended the user guide with the new log command's documentation.
> Update log command in the user guide

- CONTRIBUTING.md
- scripts/create_new_subcommand.py
Updated contribution guideline with a general request to include enough information for us into issues.
Also for the "contribution" (aka: pull request, new code, etc.) part, I've added documentation about the layout of the program.
> Contribution guideline update

- libcodechecker/analyze/log_parser.py
**Also** fixes a bogus implementation introduced in #632, which will now work properly.
> --add-compiler-defaults retrieve defines for proper standard and address width

- www/scripts/codecheckerviewer/BugViewer.js
> Fix documentation button

- www/scripts/codecheckerviewer/BugViewer.js
> Fix highlight

- www/scripts/codecheckerviewer/BugViewer.js
- www/style/codecheckerviewer.css
Print the step number for each event in the bubble.
> Enumerate bubbles

- libcodechecker/analyze/analyzers/result_handler_plist_to_db.py
Fixes #650.
The plist file store the source and the target of an arrow as two
ranges: the source of the arrow is a (line-col, line-col) pair which
define and a range. The target of the arrow is a range as well. The bug
was that the coloring went from starting point of the source range to
the end pont of the target range. In this commit the two ranges are
added to the database separately.
> Arrow background color fix

- libcodechecker/analyze.py
- libcodechecker/analyze/analyzers/result_handler_plist_to_stdout.py
- libcodechecker/server/client_auth_handler.py
- libcodechecker/server/client_db_access_server.py
- libcodechecker/session_manager.py
> Don't include host name in session token.

- bin/CodeChecker.py
- bin/codechecker-cmd
- docs/user_guide.md
- libcodechecker/cmd.py
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/session_manager.py
Resolve merge conflicts for #666
> Whisperity cmd refurbishing

- libcodechecker/analyze.py
- tests/functional/analyze_and_parse/test_files/multi_error.en1.output
- tests/functional/analyze_and_parse/test_files/multi_error.en2.output
- tests/functional/analyze_and_parse/test_files/multi_error.output
- tests/functional/analyze_and_parse/test_files/multi_error.steps.output
- tests/functional/analyze_and_parse/test_files/multi_error_skipped.output
- tests/functional/analyze_and_parse/test_files/multi_error_suppress.output
- tests/functional/analyze_and_parse/test_files/nofail.output
- tests/functional/analyze_and_parse/test_files/nofail.steps.output
- tests/functional/analyze_and_parse/test_files/simple1.output
- tests/functional/analyze_and_parse/test_files/simple1.steps.output
- tests/functional/analyze_and_parse/test_files/simple2.output
- tests/functional/analyze_and_parse/test_files/simple2.steps.output
- tests/functional/analyze_and_parse/test_files/tidy_check.output
print more information to the user that the analysis is finished and what to do to view the results
> extend analyze command output

- Doxyfile.in
- config/version.json
> increase current work in progress version to 5.9

- libcodechecker/analyze/analysis_manager.py
- tests/functional/analyze/__init__.py
- tests/functional/analyze/test_analyze.py
- tests/functional/analyze/test_files/failure.c
Log analyze failures into failed/<compiled_file.error>
> Fixes #679

- scripts/build_package.py
> Closes #700.
Showed version (assuming `v5.8` is the latest git tag and `5.9.0` is the configured version in the file):
* If not in verbose mode: `5.9`
* If verbose mode: `5.9-4-g[sha-abbrev]` (`-tainted` appended if working directory has local modifications).
> Show config-based version number even if git tag is present

- Doxyfile.in
- config/version.json
There are bug fixes and documentation updates which should go into v5.8 release.
Version will be increased after those modifications.
> Revert "increase current work in progress version to 5.9"

- api/report_server.thrift
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/server/client_db_access_handler.py
- tests/functional/comment/test_comment.py
- tests/functional/delete_runs/test_delete_runs.py
- tests/functional/diff/test_regression_diff.py
- tests/functional/func_template/template_test.py
- tests/functional/report_viewer_api/test_get_run_results.py
- tests/functional/report_viewer_api/test_report_filter.py
- tests/functional/report_viewer_api/test_run_filter.py
- tests/functional/skip/test_skip.py
- tests/functional/suppress/test_suppress.py
- tests/functional/suppress/test_suppress_file_cmdline.py
- tests/functional/update/test_update_mode.py
- tests/performance/run_performance_test.py
- www/scripts/codecheckerviewer/ListOfRuns.js
> Search for run names.

- api/report_server.thrift
- libcodechecker/server/client_db_access_handler.py
- tests/functional/comment/__init__.py
- tests/functional/comment/test_comment.py
- www/scripts/codecheckerviewer/BugViewer.js
- www/scripts/codecheckerviewer/CommentView.js
- www/scripts/codecheckerviewer/ListOfBugs.js
> Use bug id instead of bug hash at commenting in API.

- api/shared.thrift
- libcodechecker/libclient/authentication_helper.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/server/client_auth_handler.py
- libcodechecker/server/client_db_access_handler.py
- tests/functional/authentication/__init__.py
- tests/functional/comment/test_comment.py
- tests/functional/comment_unauth/__init__.py
- tests/functional/comment_unauth/test_comment_unauth.py
- tests/libtest/codechecker.py
- tests/libtest/env.py
- www/scripts/codecheckerviewer/CommentView.js
> Showed logged in user as comment author

- config/package_layout.json
- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzer.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/analyze/analyzers/analyzer_types.py
- libcodechecker/analyze/analyzers/config_handler_clangsa.py
- libcodechecker/analyze/analyzers/ctu_triple_arch.py
- libcodechecker/analyze/ctu_manager.py
- libcodechecker/generic_package_context.py
- libcodechecker/libhandlers/analyze.py
- tests/functional/ctu/__init__.py
- tests/functional/ctu/test_ctu.py
- tests/functional/ctu/test_files/buildlog.json
- tests/functional/ctu/test_files/lib.c
- tests/functional/ctu/test_files/main.c
The final version crushed into one commit with tests.
> CTU implementation

- libcodechecker/orm_model.py
- libcodechecker/server/client_db_access_handler.py
- tests/functional/diff/test_regression_diff.py
- tests/functional/report_viewer_api/test_hash_clash.py
- tests/libtest/debug_printer.py
Bug path events and report points are now ordered by enumeration instead
of storing them as a linked list in the database.
> Bug path ordering by enumeration instead of linked list

- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/util.py
> Fix taking PATH in reverse order in analyzer detection

- tests/functional/ctu/test_ctu.py
> Fix test failure with CTU reparse mode.

- README.md
- docs/cross-compilation.md
- docs/usage.md
> Align howto with current codechecker

- www/scripts/codecheckerviewer/Filter.js
- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/scripts/codecheckerviewer/filterHelper.js
- www/scripts/codecheckerviewer/hashHelper.js
> show filter in the url

- www/scripts/codecheckerviewer/BugViewer.js
- www/style/codecheckerviewer.css
> Indicate bug step number in the left bug step overview tree

- www/scripts/codecheckerviewer/ListOfBugs.js
*Note*: it's sorting the severity by the value not by the string.
> Fix severity sort

- api/report_server.thrift
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/server/client_db_access_handler.py
- tests/functional/detection_status/test_detection_status.py
- tests/functional/diff/test_diff.py
- tests/functional/diff/test_regression_diff.py
- tests/functional/report_viewer_api/__init__.py
- tests/functional/report_viewer_api/test_get_run_results.py
- tests/functional/report_viewer_api/test_hash_clash.py
- tests/functional/report_viewer_api/test_report_counting.py
- tests/functional/report_viewer_api/test_report_filter_v2.py
- tests/functional/report_viewer_api/test_run_filter.py
- tests/libtest/thrift_client_to_db.py
- tests/projects/cpp/project_info.json
- www/scripts/codecheckerviewer/BugViewer.js
- www/scripts/codecheckerviewer/ListOfBugs.js
extend report filtering
* new filter structure and api
* filter in multiple runs
* filter review status
* new api to count multiple metrics on the reports
Part of #687
> extend report filtering

- api/report_server.thrift
- libcodechecker/server/client_db_access_handler.py
- tests/functional/report_viewer_api/test_report_counting.py
Count the reports for the given runs.
> New run report counter api

- libcodechecker/server/client_db_access_handler.py
With the new session handling all of the sessions
should be closed manually for the queries too.
> Close all sessions used to query the database

- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
`get_binary_in_path` can return `False` in that case the debug log fails
> fix log at analyzer detection

- www/scripts/codecheckerviewer/BugViewer.js
> Lazy loading bug viewer report data

- libcodechecker/profiler.py
* new Timer class which can be used to measure code blocks
* print time in seconds for all of the measurements
> extend profiling options

- docs/products.md
- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/cmd/product_client.py
- libcodechecker/libclient/client.py
- libcodechecker/libhandlers/check.py
- libcodechecker/libhandlers/cmd.py
- libcodechecker/libhandlers/store.py
- libcodechecker/util.py
- tests/libtest/codechecker.py
- tests/unit/test_url_understanding.py
> Use --url instead of --host/--port for login and product command-line too

- www/scripts/codecheckerviewer/BugViewer.js
> Show fixed bugs in the report tree under a different folder

- libcodechecker/log/option_parser.py
- tests/functional/analyze/test_analyze.py
- tests/unit/test_option_parser.py
Also, move a test to more appropriate place.
> Fix pep8 issue.

- libcodechecker/libclient/thrift_helper.py
- libcodechecker/libhandlers/store.py
> Store error code when API call fails

- libcodechecker/analyze/log_parser.py
Take language and sysroot into consideration when adding default
includes to the analyze command.
> Add-compiler-defaults improvements

- api/shared.thrift
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/server/client_db_access_handler.py
- libcodechecker/server/run_db_model.py
- tests/functional/report_viewer_api/test_report_counting.py
- tests/functional/review_status/test_review_status.py
- tests/libtest/env.py
- tests/libtest/thrift_client_to_db.py
- tests/projects/cpp/project_info.json
- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/util.js
- www/style/codecheckerviewer.css
> Rename won't fix label to intentional.

- www/scripts/codecheckerviewer/BugFilterView.js
- www/scripts/codecheckerviewer/ListOfBugs.js
Might be a partial solution to #904
> fix setting the CompareData attributes

- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/log_parser.py
- libcodechecker/log/option_parser.py
> Compiler detection improvements. Fixes #921

- libcodechecker/analyze/store_handler.py
- libcodechecker/libhandlers/analyze.py
- libcodechecker/server/client_db_access_handler.py
- libcodechecker/server/run_db_model.py
* skipping reports or analysis should be handled at the analysis part
> skip configuration will not be stored

- api/shared.thrift
- api/v6/report_server.thrift
- libcodechecker/analyze/store_handler.py
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/server/client_db_access_handler.py
- tests/functional/detection_status/test_detection_status.py
- tests/functional/diff/test_diff.py
- tests/functional/report_viewer_api/test_report_counting.py
- tests/functional/report_viewer_api/test_report_filter.py
- tests/functional/review_status/test_review_status.py
- tests/functional/ssl/test_ssl.py
- tests/functional/suppress/test_suppress_generation.py
- tests/performance/run_performance_test.py
- www/scripts/codecheckerviewer/BugFilterView.js
- www/scripts/codecheckerviewer/BugViewer.js
- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/util.js
Closes #849.
I've also removed all the types that are unused.
> Cleanup shared.thrift and move report-specific types to report-server

- www/scripts/codecheckerviewer/BugFilterView.js
> Rename "Baseline" and "Newcheck" labels

- api/v6/report_server.thrift
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/server/client_db_access_handler.py
- libcodechecker/server/run_db_model.py
- tests/functional/diff/test_diff.py
- tests/functional/report_viewer_api/test_report_counting.py
- tests/functional/report_viewer_api/test_report_filter.py
- tests/functional/report_viewer_api/test_run_filter.py
- tests/projects/cpp/Makefile
- tests/projects/cpp/divide_zero_duplicate.cpp
- tests/projects/cpp/path_begin.cpp
- tests/projects/cpp/path_begin1.cpp
- tests/projects/cpp/path_begin2.cpp
- tests/projects/cpp/path_end.h
- tests/projects/cpp/project_info.json
- www/scripts/codecheckerviewer/BugFilterView.js
- www/scripts/codecheckerviewer/BugViewer.js
- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/ListOfRuns.js
- www/scripts/codecheckerviewer/RunHistory.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/scripts/codecheckerviewer/hashHelper.js
- www/style/codecheckerviewer.css
> Optional report uniqueing in the filters

- www/scripts/codecheckerviewer/ListOfRuns.js
Remove Run id from the run list table because it is unnecessary.
> Remove Run id from the run list table

- docs/usage.md
change the old command line arguments to the new in the usage examples
Resolves #954
> update userguide command line examples

- libcodechecker/libhandlers/store.py
It is unnecessary to copy the files to a temporary directory for zipping
them later. The files can go directly to the .zip file.
> Place files directly to ZIP archive

- libcodechecker/server/client_db_access_handler.py
- www/scripts/codecheckerviewer/ListOfBugs.js
> Fix sorting of report list

- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
> Clickable names in checker statistic view

- www/scripts/codecheckerviewer/BugFilterView.js
Report filter doesn't show default values of Diff type properly.
Closes #974
> Fix report filter default values

- www/scripts/codecheckerviewer/BugFilterView.js
- www/scripts/codecheckerviewer/BugViewer.js
- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/ListOfRuns.js
- www/scripts/codecheckerviewer/RunHistory.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/scripts/codecheckerviewer/hashHelper.js
At report filter and checker statistics use run name instead of run id in permalinks.
Closes #620
> Use run name instead of run id in permalinks

- api/v6/report_server.thrift
- libcodechecker/server/client_db_access_handler.py
- libcodechecker/version.py
- www/scripts/codecheckerviewer/ListOfRuns.js
- www/scripts/codecheckerviewer/RunHistory.js
- www/scripts/codecheckerviewer/util.js
- www/scripts/version.js
> Show the latest run tag in the run list table

- www/scripts/codecheckerviewer/BugViewer.js
- www/scripts/codecheckerviewer/ListOfBugs.js
If the user clicks on a bug in the bug viewer, update the url report hash
parameter.
> Update report hash by clicking on a report.

- libcodechecker/analyze/analyzers/result_handler_base.py
- libcodechecker/analyze/analyzers/result_handler_plist_to_stdout.py
- libcodechecker/libhandlers/parse.py
- libcodechecker/output_formatters.py
- tests/functional/analyze_and_parse/test_analyze_and_parse.py
- tests/functional/analyze_and_parse/test_files/multi_error.en1.output
- tests/functional/analyze_and_parse/test_files/multi_error.en2.output
- tests/functional/analyze_and_parse/test_files/multi_error.output
- tests/functional/analyze_and_parse/test_files/multi_error.steps.output
- tests/functional/analyze_and_parse/test_files/multi_error_skipped.output
- tests/functional/analyze_and_parse/test_files/multi_error_suppress.output
- tests/functional/analyze_and_parse/test_files/nofail.output
- tests/functional/analyze_and_parse/test_files/nofail.steps.output
- tests/functional/analyze_and_parse/test_files/saargs_forward.noforward.output
- tests/functional/analyze_and_parse/test_files/saargs_forward.output
- tests/functional/analyze_and_parse/test_files/simple1.output
- tests/functional/analyze_and_parse/test_files/simple1.steps.output
- tests/functional/analyze_and_parse/test_files/simple2.output
- tests/functional/analyze_and_parse/test_files/simple2.steps.output
- tests/functional/analyze_and_parse/test_files/tidy_check.output
> result summary for parse command

- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libhandlers/cmd.py
- tests/functional/diff/test_diff.py
> Local compare mode to multiple runs

- docs/usage.md
Fix some minor issues in the document.
> Spelling and wording changes to "Getting started".

- www/scripts/codecheckerviewer/CheckerStatistics.js
- Do not collect run names in the checker statistics drop down. Show `Multiple runs` text if multiple runs are selected.
- Hide checker statistics drop down on blur and update the list of result at this time.
- In some cases the list of result statistics is not show. This commit also fixes it.
Closes #950 and Closes #979
> Fix checker statistics drop down

- www/scripts/productlist/ListOfProducts.js
- www/scripts/productlist/productlist.js
- www/style/productlist.css
In Firefox (55.0.2 (64-bit)) product listing page throws a too much recursion error.
Closes #912
> Product listing error in Firefox

- README.md
- docs/postgresql_setup.md
- docs/products.md
- docs/user_guide.md
> Closes #1001.
I've updated the psql setup guide to cover the specifics required in psql mode since #857 was implemented.
> Update documentation to cover PostgreSQL-specific nuances

- .travis.yml
fix thrift compiler install in osx travis
> fix osx brew thrift version

- www/scripts/codecheckerviewer/BugFilterView.js
If a run doesn't contain any reports, the GUI lists all available reports. Now it shows nothing.
Closes #1002
> Fix run without reports.

- libcodechecker/analyze/analyzers/result_handler_plist_to_stdout.py
- tests/functional/analyze_and_parse/test_files/multi_error.steps.output
- tests/functional/analyze_and_parse/test_files/simple1.steps.output
- tests/functional/analyze_and_parse/test_files/simple2.steps.output
> Add printing report hash to parse command steps printing

- libcodechecker/cmd/cmd_line_client.py
> Uniqueing the reports at cmd sum command

- libcodechecker/cmd/cmd_line_client.py
Get statistics only for specified runs if run names are given for the cmd sum.
Closes #1026
> Get statistics only for specified runs

- www/scripts/codecheckerviewer/ListOfBugs.js
If a report is already opened and the user clicks on the same report, open
the report tab.
Closes #1018
> Select an alredy opened report again.

- docs/user_guide.md
- libcodechecker/libhandlers/analyze.py
- libcodechecker/libhandlers/check.py
> Check to temp dir if no output dir given

- docs/user_guide.md
- libcodechecker/host_check.py
- libcodechecker/libhandlers/analyze.py
- libcodechecker/libhandlers/check.py
> Analyzer arguments can be provided via check subcommand

- libcodechecker/cmd/cmd_line_client.py
> Fix command line client coding convention

- api/README.md
- docs/architecture.md
- docs/authentication.md
- docs/permissions.md
- docs/postgresql_setup.md
- docs/products.md
- docs/usage.md
- docs/user_guide.md
> Table of content for the docs

- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/style/codecheckerviewer.css
> Add icons for tabs

- libcodechecker/server/api/report_server.py
> Increase storage timeout to 30 minutes

- www/scripts/codecheckerviewer/HeaderPane.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/scripts/productlist/productlist.js
- www/style/codecheckerviewer.css
- Show which permissions are granted to the logged in user.
- Refactoring UI header by removing code duplication.
Closes #875
> Show granted permissions and refactoring UI header

- api/v6/report_server.thrift
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/server/api/report_server.py
- libcodechecker/version.py
- tests/functional/diff/test_diff.py
- tests/functional/report_viewer_api/test_report_counting.py
- www/scripts/codecheckerviewer/BugFilterView.js
- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/version.js
Limit results of the report filter counter functions.
This commit might solves #1053 issue.
> Limit report filter counters

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzers/analyzer_base.py
- libcodechecker/analyze/analyzers/ctu_triple_arch.py
- libcodechecker/analyze/ctu_manager.py
- libcodechecker/util.py
- tests/functional/analyze/test_analyze.py
- tests/functional/analyze/test_files/includes/simple.h
- tests/functional/analyze/test_files/simple.c
- vendor/plist_to_html/Makefile
> Change directory before analysis

- libcodechecker/libhandlers/parse.py
> Change log level of skipping file at parse

- libcodechecker/libhandlers/server.py
- tests/functional/db_cleanup/test_db_cleanup.py
Disable database cleanup on server start for some performance issues.
> Disable db cleanup

- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/ListOfRuns.js
- Set compare data for getRunResults at diff view.
- Set baseline and newcheck filter properly at diff view.
> Fix UI diff

- libcodechecker/libauth/cc_ldap.py
Due to the `log_ldap_error()` context manager silencing the `INVALID_CREDENTIALS` error and only logging it, the authentication procedure could successfully create the `LDAPConnection()` object with the to-be-authenticated user's credentials. A `True` was returned all the time, which made CodeChecker accept **any password** for a user whose DN exists in the Directory.
Thanks to @csordasmarton for revealing this issue.
> Fix LDAP accepting any password for a valid username

- libcodechecker/analyze/analyzer_env.py
- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/analyze/analyzers/ctu_triple_arch.py
> Fix resource_dir issue

- .ci/basic_python_requirements
- .ci/python_requirements
- .ci/python_requirements_psql_pg8000
- .ci/python_requirements_psql_psycopg2
> use newer SQLAlchemy v1.1.11

- libcodechecker/libhandlers/check.py
> --enable-all was not passed from check to analyze.

- libcodechecker/util.py
- tests/unit/test_url_understanding.py
> Follow-up for #1146.
Along with HTTPS URLs defaulting to port `443`, default HTTP URLs to `80`. This does not change the behaviour if **neither** HTTP nor HTTPS is specified, in that case, the port defaults to CodeChecker's own default port, 8001.
This way, the `--url` optstring aligns well with copying a CodeChecker server link from an e-mail or a browser. Browsers don't copy `:80` and `:443` port if the protocol is specified. If CodeChecker runs on a port different than this two, the links you copy from your browser contain that port explicitly, in which case, we understand the URL to have that explicit port.
Default behaviour for local users don't change, as the `default=` value for `--url` opstring is still `"localhost:8001/Default"`, without a protocol specified.
> Default "http://..." URLs to port 80

- api/v6/report_server.thrift
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/server.py
For now diff results are calculated on the client side. This commit creates a new API function to calculate diff hashes based on the given hashes on the server side.
> Increase local diff performance

- libcodechecker/libclient/client.py
- libcodechecker/util.py
- tests/unit/test_url_understanding.py
> Fix understanding host names missing a product name as product name under localhost

- libcodechecker/analyze/log_parser.py
> Fix exception at compiler target detection

- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/ListOfRuns.js
> Enable copy-paste for links

- www/scripts/codecheckerviewer/ListOfRuns.js
> Update run counter after runs has been removed.

- libcodechecker/analyze/store_handler.py
- libcodechecker/server/api/report_server.py
Steps:
- Get all reports for the actual run.
- Hash these reports by bug hash.
- Use this map to set detection status.
- Update bug path and events after reports are processed in a plist.
In my case the storage time reduced from 1 minute to 30 seconds.
> Increase storage performance

- libcodechecker/analyze/log_parser.py
> Remove includes-fixed and intrinsic system includes from search path

- README.md
- docs/false_positives.md
- www/userguide/userguide.md
> Initial version of false positive guide.

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/log_parser.py
- tests/functional/ctu/ctu_failure/test_ctu_failure.py
- tests/libtest/codechecker.py
- tests/projects/ctu_failure_with_headers/buildlog.json
- tests/projects/ctu_failure_with_headers/lib.c
- tests/projects/ctu_failure_with_headers/lib.h
- tests/projects/ctu_failure_with_headers/main.c
Collect headers of dependent TUs.
> Fix ctu collect

- docs/false_positives.md
> Add an example to a section.

- libcodechecker/logger.py
- tests/functional/analyze_and_parse/test_analyze_and_parse.py
> Closes: #1214
Put full date to the log message in the following format: `2017-12-05 10:50`.
> Put full date in log messages

- libcodechecker/server/api/report_server.py
> Closes: 1223
Get file content from the zip folder if it is exists or get the content from the database.
> Fix code suppression

- libcodechecker/analyze/analysis_manager.py
> Change log error to debug

- libcodechecker/libhandlers/check.py
- libcodechecker/server/api/report_server.py
- libcodechecker/util.py
> Closes: #1216
* Using context manager to create and remove temporary created directories.
* Creating temp files with the context manager.
* Removes temporary created build command files from tmp directory when using `CodeChecker check`.
> Removing temporary created directories and files

- api/shared.thrift
- api/v6/products.thrift
- config_db_migrate/env.py
- db_migrate/env.py
- docs/db_schema_guide.md
- docs/usage.md
- docs/user_guide.md
- libcodechecker/cmd/product_client.py
- libcodechecker/libclient/client.py
- libcodechecker/libclient/product_helper.py
- libcodechecker/libhandlers/server.py
- libcodechecker/libhandlers/store.py
- libcodechecker/server/api/product_server.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/database/database.py
- libcodechecker/server/database/database_status.py
- libcodechecker/server/server.py
- libcodechecker/util.py
- tests/functional/products/test_products.py
- tests/libtest/thrift_client_to_db.py
- www/scripts/codecheckerviewer/util.js
- www/scripts/productlist/ListOfProducts.js
Introduce new database statuses.
Status updates are done at the database connect attempts.
Last connection date is removed because a simple refresh
will try to reconnect to the databases.
* Database statuses are shown at server start
* GUI support for database status
* Server command line support for migration and db status check
Resolves #351
> database status and migration feature

- libcodechecker/analyze/plist_parser.py
If report hash was not found in the plist file, update the plist with the report hash. This way the server will always get a plist where the report hash field is filled.
> Update plist file with report hash

- db_migrate/versions/4b38fa14c27b_file_id_index_for_reports.py
- libcodechecker/libhandlers/server.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/database/db_cleanup.py
- libcodechecker/server/database/run_db_model.py
- libcodechecker/server/server.py
Resolves #1131 
Resolves #1130
> refactor file cleanup at server start

- libcodechecker/server/api/report_server.py
- libcodechecker/server/api/store_handler.py
Do not store same reports multiple times.
> Fix same bug path events

- libcodechecker/server/api/report_server.py
- libcodechecker/server/api/store_handler.py
Reverts Ericsson/codechecker#1245
> Revert "Fix same bug path events"

- libcodechecker/analyze/analyzers/ctu_triple_arch.py
> Add --target for ctu-collect

- libcodechecker/server/database/db_cleanup.py
> change the log level for the db file cleanup

- config_db_migrate/versions/8268fc7ca7f4_initial_schema.py
- db_migrate/versions/82ca43f05c10_initial_schema.py
- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/plist_parser.py
- libcodechecker/analyze/tidy_output_converter.py
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libauth/cc_ldap.py
- libcodechecker/libclient/client.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/libhandlers/analyze.py
- libcodechecker/libhandlers/check.py
- libcodechecker/libhandlers/server.py
- libcodechecker/libhandlers/store.py
- libcodechecker/output_formatters.py
- libcodechecker/profiler.py
- libcodechecker/server/api/authentication.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/api/store_handler.py
- libcodechecker/server/database/database.py
- libcodechecker/server/instance_manager.py
- libcodechecker/server/server.py
- libcodechecker/suppress_handler.py
- libcodechecker/util.py
- scripts/build_package.py
- tests/functional/analyze/test_analyze.py
- tests/functional/cmdline/test_cmdline.py
- tests/functional/instance_manager/test_instances.py
- tests/libtest/thrift_client_to_db.py
- tests/tools/add_unicode_comment.py
> **INTERNAL CHANGES**
Fixed all the Codacy issues in the Python code which are not related to `subprocess`. Obviously those can't be fixed as we have to start external processes...
There were some issues left behind which were either mediocre or deliberate (such as using a dummy `/tmp` path in a test.)
Funny thing: Codacy picks up the bad C++ codes we have for testing Clang. :stuck_out_tongue_winking_eye:
> Fix a bunch of Codacy-reported code issues in Python

- www/scripts/codecheckerviewer/BugViewer.js
- www/style/codecheckerviewer.css
If a bug step is clicked in the bug viewer, highlight the actual bug step in the code.
Closes #1244
> Highlight the actual bug step

- www/scripts/codecheckerviewer/BugViewer.js
> Redraw bubbles even if arrows are hidden.

- docs/authentication.md
- docs/usage.md
Removing outdated disclaimer from the authentication md.
Addin reference to authentication configuration from the
main HOWTO.
> Removing outdated disclaimer from the auth doc.

- libcodechecker/report.py
- libcodechecker/util.py
- tests/functional/detection_status/test_detection_status.py
- tests/unit/test_report_line.py
- tests/unit/tidy_output_test_files/tidy1.plist
- tests/unit/tidy_output_test_files/tidy2.plist
- tests/unit/tidy_output_test_files/tidy3.plist
> Closes #1241
Trim the line when generate bug hash for tidy and ignore white spaces.
> Tidy hash generation indented code fix

- tests/functional/ctu/ctu_failure/test_ctu_failure.py
- tests/functional/ctu/test_ctu.py
- tests/libtest/codechecker.py
Trying to fix the mysterious Jenkins error by having better output in case of failing tests.
> Add better diagnostics for ctu tests in case of failure

- libcodechecker/server/api/report_server.py
- libcodechecker/server/api/store_handler.py
* StorageSession was removed an upcoming patch will it make obsolate
(used to check if there is an already running store for a run,
this feature is removed with the cleanup)
* massStoreRun was refactored to multiple methods
> refactor serverside of storing runs

- libcodechecker/libauth/cc_ldap.py
See for further details: https://mail.python.org/pipermail/python-ldap/2012q4/003183.html
> Fix python-ldap not throwing exception on anonymous binds when it should

- scripts/build_package.py
Add the following output to the build script to better trace release creation.
```
[INFO] - This is CodeChecker v6.5 (df359f07632960f12ccb32609ea011ae476fbee4)
[INFO] - Built from Git tags: v6.4 (v6.4-11-gdf359f0)
[INFO] - Baked with Git tag information merged with configured version: 6.5 (6.5-11-gdf359f0)
```
> Explicitly show version information in the build script output

- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/output_formatters.py
Extend output of the `cmd sum` to contain total number of reports.
> Add total section for command line sum

- libcodechecker/libhandlers/server.py
- libcodechecker/output_formatters.py
- libcodechecker/server/server.py
* Print product status table to info log
* Print missing ssl cert log message in one line
> Fix log format

- www/scripts/codecheckerviewer/BugFilterView.js
- www/style/codecheckerviewer.css
> Closes #1165 and Closes #1162
> Support regex based server side filters

- .noserc
- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzer.py
- libcodechecker/analyze/analyzers/analyzer_base.py
- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/analyze/analyzers/analyzer_types.py
- libcodechecker/analyze/host_check.py
- libcodechecker/libhandlers/analyze.py
- tests/functional/ctu_failure/test_ctu_failure.py
This pull request contains multiple changes:
* analysis manager refactoring
* new feature to reanalyze without ctu if ctu fails and the `--ctu-reanalyze-on-failure` option is set
> reanalyze without ctu on ctu failure

- www/scripts/codecheckerviewer/BugViewer.js
> Order reports by line in bug tree

- www/scripts/codecheckerviewer/BugViewer.js
Review status reason dialog should accept ENTER as submit if nothing is entered into text area.
Closes #1354
> Accept ENTER as submit at review status change

- libcodechecker/profiler.py
* output format was changed to be in sync with the other log formats
> fix import in profiler and change output format

- www/scripts/codecheckerviewer/BugViewer.js
Fix pressing ESC in the review status reason window bolds the wrong status.
Closes #1357
> Fix review status selector boldness.

- scripts/build_package.py
- vendor_projects.json
- www/style/codecheckerviewer.css
> Use web safe fonts instead of the google fonts.

- libcodechecker/cmd/cmd_line_client.py
- tests/functional/suppress/test_suppress_generation.py
> Fix suppress import

- libcodechecker/server/permissions.py
> Change existing/removed permission log message

- libcodechecker/server/permissions.py
> Allow product admin to manage other project admins

- libcodechecker/analyze/analysis_manager.py
There are some flags which prevent dependency generation, like -MD or
-MP. One occurrence of these are eliminated, however the build command
may contain these multiple times. These flags have to be eliminated all.
> Fix dependency generator

- api/v6/products.thrift
- libcodechecker/server/api/product_server.py
- libcodechecker/version.py
- www/scripts/codecheckerviewer/ListOfRuns.js
- www/scripts/codecheckerviewer/util.js
- www/scripts/productlist/ListOfProducts.js
- www/scripts/version.js
* Show the number of runs for every product.
* Show the latest date when a run in a product was updated.
> Extend product listing page with new fields

- libcodechecker/cmd/cmd_line_client.py
> Checker name filter will not work properly until #1401 has been merged.
> Filter cmd line checker statistics

- www/scripts/codecheckerviewer/filter/DiffTypeFilter.js
Get diff type label after current diff type is set.
> Fix diff type filter label

- www/scripts/codecheckerviewer/BugViewer.js
* Use CodeMirror `operation` method for clearing bubbles and lines.
* Get report details asynchronously.
> Improve performance of bug path draw

- www/scripts/codecheckerviewer/filter/BugFilterView.js
> Rename File filter to File path filter

- libcodechecker/libauth/cc_ldap.py
Write out current user name on DN lookup failure
> Give a better error message on DN lookup failure

- libcodechecker/libclient/thrift_call.py
host and port is not available at the wrapper after the refactoring
> fix thrift call wrapper host, port

- .ci/basic_python_requirements
- docs/user_guide.md
- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzer.py
- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/analyze/analyzers/config_handler.py
- libcodechecker/analyze/ctu_manager.py
- libcodechecker/analyze/pre_analysis_manager.py
- libcodechecker/analyze/statistics_collector.py
- libcodechecker/host_check.py
- libcodechecker/libhandlers/analyze.py
- libcodechecker/util.py
- tests/functional/analyze/test_analyze.py
- tests/functional/statistics/__init__.py
- tests/functional/statistics/test_statistics.py
- tests/unit/test_statistics_collectors.py
* introduce new pre analysis step
- already existing CTU
- new statistic collector checkers (only collector checkers are enabled)
* new arguments (only active if the specific checkers are available)
- --stats (collect statistics and analyze, enable statistics checkers)
- --stats-collect (only collect statistics)
- --stats-use (only analyze using the previously generated statistics)
* TODO yaml output generation should be done with a python yaml module
Resolves #805
Resolves #1420
Supersedes #967.
> Adding statistics collection support

- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/RunHistory.js
Load run history table asynchronously and only if the user opens the tab.
> Load run history asynchronously

- libcodechecker/server/server.py
If the product doesn't find in the cache, try to get it from the database.
#1464
> Fix server product list mismatch in multi server

- www/scripts/codecheckerviewer/BugViewer.js
> Close #1395 
The last bug path message is highlighted in red color even if the bug path continues later on in another file. This commit highlights last bug path message if it is absolutely last.
> Highlight last bug path message fix

- www/index.html
- www/scripts/codecheckerviewer/BugViewer.js
- www/style/codecheckerviewer.css
Search and highlight occurrences of the selected text.
Screenshot:
> Highlight occurences of the selected text

- libcodechecker/analyze/analyzers/analyzer_clangsa.py
> get analyzer notes as events from clangsa

- libcodechecker/server/api/store_handler.py
- tests/Makefile
- tests/unit/__init__.py
- tests/unit/test_store_handler.py
- www/scripts/codecheckerviewer/BugViewer.js
> fix bug event/path parsing

- libcodechecker/analyze/plist_parser.py
> fix debug log in parse if report is skipped

- api/v6/report_server.thrift
- db_migrate/versions/3793e361a752_source_components.py
- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/cmd/source_component_client.py
- libcodechecker/libclient/thrift_helper.py
- libcodechecker/libhandlers/cmd.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/database/run_db_model.py
- libcodechecker/util.py
- tests/functional/component/__init__.py
- tests/functional/component/test_component.py
- tests/libtest/env.py
- www/scripts/codecheckerviewer/filter/BugFilterView.js
- www/scripts/codecheckerviewer/filter/FilterTooltip.js
- www/scripts/codecheckerviewer/filter/SelectFilter.js
- www/scripts/codecheckerviewer/filter/SelectedFilterItem.js
- www/style/codecheckerviewer.css
> Filter by Source components

- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libhandlers/cmd.py
> Closes #1496
* Create separate filter options for command line.
* Create filter option for run tags and checker message to be more consistent with the UI.
> Create separate filter options for cmd line

- libcodechecker/log/option_parser.py
> handle more gcc/g++ arguments

- api/v6/report_server.thrift
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/server/api/report_server.py
- tests/functional/diff/__init__.py
- tests/functional/diff/test_diff.py
- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/scripts/codecheckerviewer/filter/BugFilterView.js
- www/scripts/codecheckerviewer/filter/RunBaseFilter.js
- www/scripts/codecheckerviewer/filter/RunHistoryTagFilter.js
> Diff two different tagged versions of the same run

- www/scripts/codecheckerviewer/filter/DateFilter.js
- www/scripts/codecheckerviewer/filter/FilterTooltip.js
- www/style/bugfilter.css
- www/style/codecheckerviewer.css
- www/style/icons.css
Add further Detection date filter values:
* This week
* This month
* This year
Closes #1437
> Add further detection date filter values

- www/scripts/codecheckerviewer/BugViewer.js
> Closes #1549
Bug tooltip "Review status" should say what the icon means.
> Show review status meaning at bug tooltip

- www/scripts/codecheckerviewer/BugViewer.js
> Clickable 'Entered call from'

- docs/user_guide.md
- libcodechecker/source_code_comment_handler.py
- tests/functional/analyze_and_parse/test_files/Makefile
- tests/functional/analyze_and_parse/test_files/multi_error_suppress_cstyle.cpp
- tests/functional/analyze_and_parse/test_files/multi_error_suppress_cstyle.output
- tests/unit/source_code_comment_test_files/test_file_1
- tests/unit/source_code_comment_test_files/test_file_3
- tests/unit/test_source_code_comment.py
Review statuses can be set in the C style /**/ comment format too.
> review status C style comment format

- www/scripts/codecheckerviewer/filter/DateFilter.js
> Notify other filters on date filter change

- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libhandlers/parse.py
- vendor/plist_to_html/Makefile
- vendor/plist_to_html/plist_to_html/PlistToHtml.py
- vendor/plist_to_html/plist_to_html/dist/index.html
- vendor/plist_to_html/plist_to_html/dist/js/bugviewer.js
- vendor/plist_to_html/plist_to_html/dist/layout.html
Creating an `index.html` file that lists the found reports which links to the local html pages.
> Generate index.html file by using PlistToHTML

- tests/functional/analyze_and_parse/test_analyze_and_parse.py
splitting up the tests will allow to debug test failures easier
> split up analyze and parse tests

- docs/user_guide.md
Close codeblock in the userguide.
> Fix userguide

- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libhandlers/cmd.py
> Support component filter in the command line

- libcodechecker/libhandlers/check.py
- libcodechecker/libhandlers/parse.py
- tests/functional/analyze_and_parse/test_files/multi_error_skipped.output
* wrong skip file argument name was used in parse command
* fix the test which should have trigger the error
* skip argument was not forwarded by the check command
resolves #1607
> fix skip file arguments

- www/scripts/codecheckerviewer/ListOfBugs.js
> Fix review status hover flows outside viewport

- tests/unit/test_tidy_output_converter.py
- tests/unit/tidy_output_test_files/files/Makefile
- tests/unit/tidy_output_test_files/tidy1_v6.out
- tests/unit/tidy_output_test_files/tidy2_v6.out
- tests/unit/tidy_output_test_files/tidy3.out
* add tidy v6 output tests for the output parser
* add Makefile for easier output generation
> tidy test updates (v6 outputs and Makefile)

- www/scripts/codecheckerviewer/BugViewer.js
Create new jsPlumb instance only if we set a new content for the editor otherwise reset it.
> Increase performance of the UI

- www/scripts/codecheckerviewer/ListOfRuns.js
- www/scripts/codecheckerviewer/TabCount.js
- www/scripts/productlist/ListOfProducts.js
- www/scripts/productlist/productlist.js
- www/style/codecheckerviewer.css
> Closes #1394
* Create a separate module which adds a counter to the tab.
* Show the number of products in the tab.
> Show the number of products in the tab

- www/scripts/codecheckerviewer/HeaderPane.js
> Closes #1390
Clicking on user name in GUI header will show product permissions if product is open.
> Show product permissions by clicking on name in UI

- libcodechecker/server/server.py
- www/scripts/login/login.js
> Persist URL hash fragments across a login redirect

- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/RunHistory.js
- www/scripts/codecheckerviewer/filter/RunBaseFilter.js
> Filter run history based on the selected run filter

- config/checker_severity_map.json
- config/config.md
The report may not indicate a real run-time error so severity decreased to medium.
Severity levels also defined.
> Severity misc-redundant-expression to medium

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/gcc_toolchain.py
- libcodechecker/analyze/log_parser.py
- libcodechecker/log/option_parser.py
- tests/unit/test_gcc_toolchain.py
- tests/unit/test_option_parser.py
--gcc-toolchain flag was not forwarded to the analyzers which
caused that not the right header files were detected
> handle gcc-toolchain flag

- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/CheckerStatisticsFilter.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/scripts/codecheckerviewer/filter/BugFilterView.js
- www/scripts/codecheckerviewer/filter/CheckerMessageFilter.js
- www/scripts/codecheckerviewer/filter/CheckerNameFilter.js
- www/scripts/codecheckerviewer/filter/FileFilter.js
- www/scripts/codecheckerviewer/filter/SourceComponentFilter.js
- www/scripts/codecheckerviewer/hashHelper.js
> Closes #1628 and Closes #1325
> Use bug filter bar at Checker statistics

- libcodechecker/server/api/authentication.py
- libcodechecker/server/session_manager.py
Update group field of all the users token on login.
> Update group field of the users tokens on login

- libcodechecker/server/api/report_server.py
- www/scripts/codecheckerviewer/BugViewer.js
- www/scripts/codecheckerviewer/ListOfBugs.js
- www/scripts/codecheckerviewer/filter/BugFilterView.js
- www/scripts/codecheckerviewer/filter/ReportHashFilter.js
- www/scripts/codecheckerviewer/filter/SelectFilter.js
- www/style/bugfilter.css
- www/style/codecheckerviewer.css
* Show report hash at the Bug overview.
* Filter run results by report hash.
> Filter results by report hash on the GUI

- www/scripts/codecheckerviewer/CheckerStatistics.js
- www/scripts/codecheckerviewer/CheckerStatisticsFilter.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
Enable uniqueing by default at the Checker statistic page.
> Set default filter values at Checker statistics

- api/v6/products.thrift
- libcodechecker/server/api/product_server.py
- libcodechecker/version.py
- www/scripts/productlist/ListOfProducts.js
- www/scripts/version.js
Show run names which are in progress to store at Product page.
> Show run store in progress at Product page

- requirements_py/osx/requirements.txt
> increase scan-build version for osx install

- www/scripts/codecheckerviewer/filter/CheckerMessageFilter.js
- www/scripts/codecheckerviewer/filter/FileFilter.js
- www/scripts/codecheckerviewer/filter/FilterTooltip.js
- www/scripts/codecheckerviewer/filter/RunBaseFilter.js
- www/style/bugfilter.css
- www/userguide/userguide.md
> Extend filter text input field hint with example

- docs/db_schema_guide.md
- libcodechecker/logger.py
- libcodechecker/server/server.py
- scripts/debug_tools/failure_lib.py
Hi there,
I wrote this bot based on the top 10 most misspelled english words.
(https://blog.oxforddictionaries.com/2016/08/02/corpus-misspellings/)
The bot queries, forks, clones, fixes and commits but I manually create the PRs.
All the best,
Jimmy
> Fixed Spelling.

- vendor/plist_to_html/plist_to_html/dist/js/bugviewer.js
> Encode html entities in PlistToHtml parser

- libcodechecker/server/api/report_server.py
> Removing run reports in chunks

- www/scripts/codecheckerviewer/filter/BugFilterView.js
- www/scripts/codecheckerviewer/filter/ReportCount.js
- www/style/bugfilter.css
- www/style/codecheckerviewer.css
* Show `Remove filtered reports` button at the bottom of the filter bar.
* Hide `Remove filtered reports` button from the filter bar if the user doesn't have *storage* permission for the current product.
* Show the *number of results* which will be deleted on the confirmation dialog.
> Hide Remove filtered reports button

- db_migrate/versions/e89887e7d3f0_add_bug_path_length.py
- libcodechecker/server/api/report_server.py
- libcodechecker/server/api/store_handler.py
- libcodechecker/server/database/run_db_model.py
for performace improvement calculate bug path lengths
during the storage not in the report queries
> calculate bug path length at store (schema change)

- libcodechecker/server/instance_manager.py
It is possible when multiple CodeChecker servers are started in the same time that multiple server instances are trying to write to the same `.codechecker.instances.json` file. Some of them will not append but override the already existing entries. This way not all of the running server instances will be registered in the instance file.
This commit solves this problem by locking this file properly.
> Fix instance manager file lock

- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
Some very tiny cleanups. See commit messages for details.
> Tiny cleanups

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzers/analyzer_base.py
- libcodechecker/analyze/analyzers/analyzer_clang_tidy.py
- libcodechecker/analyze/analyzers/analyzer_clangsa.py
- libcodechecker/analyze/analyzers/analyzer_types.py
- libcodechecker/analyze/analyzers/config_handler.py
- libcodechecker/analyze/analyzers/config_handler_clang_tidy.py
- libcodechecker/host_check.py
- libcodechecker/libhandlers/checkers.py
And some more bugfixes along the way for unsupported analyzers.
This is a small step towards https://github.com/Ericsson/codechecker/issues/1760
> Slightly cleaner handling of constructing analyzers

- config/checker_severity_map.json
- config/config.json
> remove duplicate entries from the config files

- libcodechecker/analyze/analyzer.py
- libcodechecker/analyze/log_parser.py
- libcodechecker/libhandlers/analyze.py
It eliminates a lot of useless work for large projects like Chromium with 40K+ targets.
Also it seems to reduce an amount of RAM consumed.
> Don't parse command line options for skipped files.

- libcodechecker/server/api/report_server.py
- www/scripts/codecheckerviewer/filter/FilterTooltip.js
- www/scripts/codecheckerviewer/filter/RunHistoryTagFilter.js
- www/style/bugfilter.css
> This is part of #1777
Add dates to the run tag list at report filter and order run tag list by date in decreasing order.
> Add dates to the run tag list at report filter

- libcodechecker/server/server.py
Check that the given product exist after getting a product at the server.
> Check that the given product exist at server

- docs/db_schema_guide.md
- docs/user_guide.md
- libcodechecker/libhandlers/server.py
Create a new server option to force the server to do the migration without user interaction.
> Do database migration without user interaction

- libcodechecker/server/server.py
> Increase performance of loading products

- www/scripts/codecheckerviewer/BugViewer.js
> Closes #1806
Show bug step enumeration if there is only one bug step.
> Fix bug path numbering

- Makefile
- requirements_py/test/requirements.txt
- tests/requirements.txt
* test requirements should use a specific version
* move test requirements.txt to the other python requirements files
> freeze test requirements and move requirements.txt

- .dockerignore
- docker/Dockerfile.test.sqlite.clang7.bionic
- docker/Dockerfile.test.sqlite.clang7.xenial
- docs/docker.md
New dockerfiles for various ubuntu test environments
xenial, bionic
> new dockerfiles for test environments

- tests/performance/run_server_performance_test.py
Print performance test statistics when the job timed out or killed.
> Print statistics on signal

- libcodechecker/server/server.py
Storing the actually logged in user name in the HTTP response header will allow us to log it in NGINX logs for every requests.
> Set user name in the HTTP response header

- scripts/build_package.py
- vendor_projects.json
* handle site redirects, curl will retry to download from the new location
* silent output
> modify curl arguments for 3pp downloads

- libcodechecker/libhandlers/store.py
- libcodechecker/server/api/report_server.py
- tests/functional/component/test_component.py
> Fix SQL queries where empty sequences are possible

- .travis.yml
Postgresql did not start for some reason in travis ci.
Maybe some image change was done.
> update postgresql in osx travis ci

- docs/user_guide.md
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/libhandlers/cmd.py
- tests/functional/cmdline/__init__.py
- tests/functional/cmdline/test_cmdline.py
> Add run name filter to cmd runs command

- www/index.html
- www/scripts/codecheckerviewer/codecheckerviewer.js
> enable syntax highlighting in the checker doc

- config_db_migrate/versions/3335ff7593cc_disable_review_status_change.py
> Closes #1858
Eliminate `Skipping unsupported ALTER for creation of implicit constraint` warning when upgrading SQLite database with batch operation.
> Fix SQLite migration warning

- www/scripts/codecheckerviewer/BugViewer.js
- www/style/codecheckerviewer.css
> Add left/right arrow to the bug steps in the webui

- libcodechecker/analyze/plist_parser.py
- libcodechecker/cmd/cmd_line_client.py
- libcodechecker/report.py
- libcodechecker/server/api/store_handler.py
- tests/functional/analyze_and_parse/test_files/macros.output
- tests/projects/macros/macros.plist
- vendor/plist_to_html/plist_to_html/PlistToHtml.py
Macro expansions are under `diagnostics` instead of `path`.
> Fix: macros are under diagnosics instead of path

- libcodechecker/log/log_parser.py
All of `ImplicitCompilerInfo`'s members are class attributes, and the whole class 
is used in a static way. Therefore it makes sense to make its methods static. Also,
shorter getter and setter method names avoid some redundancy.
> Make ImplicitCompilerInfo's methods static.

- vendor/plist_to_html/plist_to_html/dist/css/style.css
- vendor/plist_to_html/plist_to_html/dist/js/bugviewer.js
> Highlight current event in the generated html file

- libcodechecker/analyze/analyzers/analyzer_clangsa.py
> enable extra analyzer option (iterator checkers)

- libcodechecker/package_context.py
- libcodechecker/server/database/db_cleanup.py
- libcodechecker/server/server.py
- tests/functional/db_cleanup/__init__.py
- tests/functional/db_cleanup/test_db_cleanup.py
> Common severity for a checker

- libcodechecker/log/log_parser.py
Remove dead code and reference to a file that no longer exists.
> Small log parser fixes.

- www/scripts/codecheckerviewer/filter/DetectionStatusFilter.js
- www/scripts/codecheckerviewer/filter/FilterTooltip.js
- www/scripts/codecheckerviewer/filter/SelectFilter.js
- www/scripts/codecheckerviewer/filter/SelectedFilterItem.js
> Add tooltips to detection status filter items

- libcodechecker/analyze/analysis_manager.py
- libcodechecker/analyze/analyzer.py
Enable statistics based checkers before shared dictionary creation.
> Enable statistics checkers before workers

- api/v6/Makefile
- api/v6/configuration.thrift
- config_db_migrate/versions/dec6feb991e6_new_table_for_server_config.py
- libcodechecker/server/api/config_handler.py
- libcodechecker/server/database/config_db_model.py
- libcodechecker/server/server.py
- tests/functional/server_configuration/__init__.py
- tests/functional/server_configuration/test_server_configuration.py
- tests/libtest/env.py
- tests/libtest/thrift_client_to_db.py
- www/index.html
- www/login.html
- www/products.html
- www/scripts/codecheckerviewer/HeaderPane.js
- www/scripts/codecheckerviewer/codecheckerviewer.js
- www/scripts/login/login.js
- www/scripts/productlist/ListOfProducts.js
- www/scripts/productlist/NotificationView.js
- www/scripts/productlist/productlist.js
- www/style/codecheckerviewer.css
Resolves #1861 
Added frontend part of the issue.
> New notification banner

- www/changelog.html
this feature is posponed to a later release
> remove macro feature from changelog

- libcodechecker/libclient/client.py
- libcodechecker/libclient/thrift_call.py
- libcodechecker/libhandlers/check.py
- libcodechecker/server/server.py
exceptions does not have a message attribute in python3
> python3 compatible exception cleanup

- libcodechecker/logger.py
string.upper is not available in py3
> remove py3 incompatible uppercase conversion

- Makefile
- scripts/build/extend_version_file.py
- scripts/build_package.py
Create a separate python script to extend version file with git information.
> Extend version file with git information

- libcodechecker/libhandlers/analyze.py
During the previous refactoring this if statement
was modified in a wrong way. len() was removed
but the condition was not updated.
> fix action list length check

- scripts/build/create_commands.py
- scripts/build/extend_version_file.py
- scripts/create_new_subcommand.py
Temporarly revert back the scripts to py2 until we
fully switch to py3.
> Revert back package build scripts to py2

- Makefile
- analyzer/tests/Makefile
- webserver/tests/Makefile
> Add pylint and pycodestyle targets

- Makefile
- analyzer/bin/codechecker-analyzer-version
- analyzer/cmd/analyze.py
- analyzer/cmd/analyzer_version.py
- analyzer/cmd/analyzers.py
- analyzer/cmd/check.py
- analyzer/cmd/checkers.py
- analyzer/cmd/log.py
- analyzer/cmd/parse.py
- analyzer/codechecker/analyzer_context.py
- webserver/bin/codechecker-webserver-version
- webserver/client/cmd/store.py
- webserver/client/codechecker/cmdhelper/cmd_line_client.py
- webserver/cmd/webserver_version.py
- webserver/common/__init__.py
- webserver/common/webserver_context.py
- webserver/server/cmd/server.py
- webserver/server/codechecker/server/api/report_server.py
> Part of #1830 
Remove `package_context.py` and create separate contexts for analyzer and server.
> Create separate contexts for analyzer and server

- tools/plist_to_html/plist_to_html/dist/css/style.css
- tools/plist_to_html/plist_to_html/dist/layout.html
> [plist-to-html] Link to index.html

- web/server/codechecker_server/api/authentication.py
- web/server/codechecker_server/session_manager.py
- web/tests/functional/authentication/test_authentication.py
- web/tests/libtest/env.py
This commit fixes the problem, when the user password contains one or more colons.
> Fix authentication

- analyzer/codechecker_analyzer/analyzers/config_handler.py
with this change we can put other files next to the plugins
> load only files with ".so" extension as a plugin

- CONTRIBUTING.md
> Refactoring CONTRIBUTING.md file after split up

- web/server/codechecker_server/api/report_server.py
Call database cleanup function on removeRun api function too.
> Cleanup database on run remove

- .travis.yml
- Makefile
- analyzer/Makefile
- web/Makefile
> Add targets to build analyzer and web separately

- analyzer/Makefile
- web/Makefile
Call build target of plist-to-html on package build
> Fix package build

- tools/plist_to_html/plist_to_html/PlistToHtml.py
- tools/plist_to_html/plist_to_html/static/css/buglist.css
- tools/plist_to_html/plist_to_html/static/index.html
- tools/plist_to_html/plist_to_html/static/js/buglist.js
> [plist-to-html] Ordering reports

- Makefile
- analyzer/requirements_py/dev/requirements.txt
- web/requirements_py/dev/requirements.txt
new makefile target was created and the requirements were updated
> add new mkdocs target to build the documentation

- web/client/codechecker_client/cmd/store.py
- web/tests/functional/suppress/test_suppress_generation.py
> Send all files to the server which contain source code comments

- docs/web/authentication.md
- docs/web/user_guide.md
> Fix authentication documentation

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/unit/test_option_parser.py
> Keep clang flags

- tools/plist_to_html/plist_to_html/static/js/buglist.js
Use selection sort algorithm to sort table element on bug list view generated by plist-to-html to improve the performance.
> Improve plist-to-html sort performance

- analyzer/codechecker_analyzer/cmd/parse.py
- tools/plist_to_html/plist_to_html/PlistToHtml.py
- tools/plist_to_html/plist_to_html/static/css/buglist.css
- tools/plist_to_html/plist_to_html/static/css/bugview.css
- tools/plist_to_html/plist_to_html/static/css/statistics.css
- tools/plist_to_html/plist_to_html/static/css/style.css
- tools/plist_to_html/plist_to_html/static/css/table.css
- tools/plist_to_html/plist_to_html/static/index.html
- tools/plist_to_html/plist_to_html/static/layout.html
- tools/plist_to_html/plist_to_html/static/statistics.html
- tools/plist_to_html/tests/unit/plist_to_html/plist_to_html_test.py
> Closes #1035
Collects and prints the following checker information:
* How many plist reports were processed
* How many analyzer reports are in the plists
* Count the reports for each analyzer checkers
> [plist-to-html] Collect statistics

- tools/plist_to_html/plist_to_html/PlistToHtml.py
- tools/plist_to_html/plist_to_html/static/index.html
- tools/plist_to_html/plist_to_html/static/layout.html
- tools/plist_to_html/plist_to_html/static/statistics.html
> [plist-to-html] Use templates to generate html files

- web/server/www/scripts/codecheckerviewer/filter/DateFilter.js
> Set detection date filter value properly from url

- tools/plist_to_html/plist_to_html/static/js/buglist.js
> [plist-to-html] Fix sorting

- docs/jenkins_gerrit_integration.md
with a reference to the template scripts
> Gerrit-Jenkins integration is extended

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/functional/analyze/test_analyze.py
There should be no whitespace between -isystem and <path>
-isystem<path>
> isystem path was wrong

- docs/web/docker.md
- web/docker/Dockerfile
- web/docker/entrypoint.sh
- web/docker/services/docker-compose.psql.auth.yml
- web/docker/services/docker-compose.psql.yml
- web/docker/services/docker-compose.sqlite.yml
* Add Dockerfile and entrypoint to build a CodeChecker web.
* Add readme how to use CodeChecker web in docker.
> CodeChecker web docker support

- scripts/build/extend_version_file.py
> Solves #2098
This commit solves the problem when trying to build a CodeChecker package from a tarball of a tagged release (not a git repository), rather than from a git clone.
> [fix] Not a git repository when building from tarball

- web/docker/Dockerfile
* Move runtime dependency args to the production stage.
* Install runtime dependencies in the production stage.
* Copy requirements from the build stage.
> [fix] Fix docker runtime dependencies

- Makefile
- docs/tests.md
For easier local testing additional test tartgets were added.
The target names were updated to reflect the new repository structure more.
The test documentation was updated wih examples how to use the
new test targets.
> extend and update the top level test targets

- web/client/codechecker_client/cmd_line_client.py
For now we always did an extra API call in the command line when we tried to get the run results or to do remote run diff. This is unnecessary if the result count is less then the requested limit value so we stop the iteration in this case.
> [cli] Reduce getRunResults API calls in CLI

- web/client/codechecker_client/cmd/store.py
When comparing the source code modification times for each plist
only the source files included in the plist file should be checked.
The source files referred in the plist file important during storage
for that specific plist report.
Previously in the comparison for each plist report all the source
code (from all the plist files) modification times were used
which is not necessary and can lead to storage errors.
The storage of reports could fail because some file
changed which is unrelated for that specific report.
As an additional refactoring the metadata files are collected
separately from the plist report files.
resolves #1987
> fix file modification time check at store

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangsa/config_handler.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- docs/analyzer/checker_and_analyzer_configuration.md
- docs/analyzer/user_guide.md
> [analyzer] Add support for Z3 refutation

- docs/web/user_guide.md
- web/api/v6/report_server.thrift
- web/client/codechecker_client/cmd/cmd.py
- web/client/codechecker_client/cmd_line_client.py
- web/client/codechecker_client/thrift_helper.py
- web/codechecker_web/shared/version.py
- web/server/codechecker_server/api/report_server.py
- web/server/www/scripts/codecheckerviewer/BugViewer.js
- web/server/www/scripts/codecheckerviewer/ListOfBugs.js
- web/server/www/scripts/version.js
- web/tests/functional/component/test_component.py
- web/tests/functional/db_cleanup/test_db_cleanup.py
- web/tests/functional/detection_status/test_detection_status.py
- web/tests/functional/diff/test_diff.py
- web/tests/functional/extended_report_data/test_extended_report_data.py
- web/tests/functional/report_viewer_api/test_get_lines_in_file.py
- web/tests/functional/report_viewer_api/test_get_run_results.py
- web/tests/functional/report_viewer_api/test_hash_clash.py
- web/tests/functional/report_viewer_api/test_report_counting.py
- web/tests/functional/report_viewer_api/test_report_filter.py
- web/tests/functional/run_tag/test_run_tag.py
- web/tests/libtest/thrift_client_to_db.py
> [cli] Extend the CLI to be able to return report details

- web/client/codechecker_client/cmd_line_client.py
Convert report objects to Thrift `ReportData` types when getting diff results in `json` output format.
> [cli] Convert report object to Thrift report data type

- web/server/codechecker_server/api/product_server.py
- web/server/codechecker_server/server.py
There is no need to connect to each product databases when getting the product list because it will cause bad user experience when loading the product listing page.
With this patch first we will try to get product details from the product database by using sqlalchemy and if it is failed we will try to connect to the product which will initiate the actual connection to the database configured for the product and update the database status then we will try to get the product details again.
> [server] Increase performance of getting a product

- web/server/codechecker_server/permissions.py
- web/tests/functional/authentication/__init__.py
- web/tests/functional/authentication/test_authentication.py
- web/tests/libtest/env.py
> [server] Case insensitive group comparison at authorization

- analyzer/codechecker_analyzer/buildlog/log_parser.py
In ImplicitCompilerInfo class we had 3 different dictionaries to store
implicit include paths, the default standard and the target architecture.
Now these are stored in one dictionary.
> Refactoring ImplicitCompilerInfo

- .gitignore
object files were only ignored from some
test directories, ignore them from everywhere.
> Ignore object files from the whole repo

- analyzer/codechecker_analyzer/cmd/checkers.py
> Closes #758 and Closes #1693
> [analyzer] Use diagtool to list clang warnings

- analyzer/codechecker_analyzer/cmd/checkers.py
The merged changed was not rebased and it
introduced the old handling of the environment.
> fix env package handling

- analyzer/codechecker_analyzer/analysis_manager.py
- analyzer/codechecker_analyzer/analyzers/analyzer_base.py
- analyzer/codechecker_analyzer/pre_analysis_manager.py
- bin/CodeChecker
- bin/CodeChecker.py
- scripts/test/run_server_performance_test.py
- web/server/codechecker_server/server.py
For each signal there is a reserved exit code:
http://www.tldp.org/LDP/abs/html/exitcodes.html
The signal numbers can be found here:
http://man7.org/linux/man-pages/man7/signal.7.html
> Exit with proper exit code

- web/server/www/scripts/productlist/ListOfProducts.js
* Create separate functions to format columns of the product listing table.
* Perform case-insensitive sort on `name` and `description` columns.
> Refactoring product listing grid

- analyzer/codechecker_analyzer/analyzers/clangsa/statistics_collector.py
The build actions were used through self which is not
right in that function.
> fix build action handling in statistics_collector

- web/server/www/scripts/codecheckerviewer/CommentView.js
> Honor newlines for comments in the web GUI

- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_autodetection.py
environment should be fowarded for all the subprocess calls
> fix env forwarding for the subprocess in ctu autodetect

- web/server/www/scripts/codecheckerviewer/ListOfRuns.js
- typo: run.runId -> run.runid.
- Missing get() function for the storage object.
- run.runid is not an array.
- checkbox should be checked even if its cell is clicked.
- The deleteRunIds array should be cleared in the async callback
function otherwise it will see an empty array by that time it runs.
Fixes #2234
> Fix run deletion in GUI

- analyzer/codechecker_analyzer/analyzers/clangsa/clang_options.py
> import get_logger in clang_options.py

- web/server/www/scripts/codecheckerviewer/SourceComponentManager.js
> Make placeholder help for source components more descriptive

- web/server/www/scripts/codecheckerviewer/BugViewer.js
> [web] Left indent at Returned allocated memory notes

- web/server/codechecker_server/server.py
- web/server/www/scripts/codecheckerviewer/util.js
> Closes #2307
When an unauthorized user tries to open the report list based on
an URL which was provided by an authorized user, then he only
sees the "loading" label in the web GUI.
To solve this problem we redirect the unauthorized user from the
run list page to the product list page.
> [server] Redirect unauthorized user from run page

- docs/script_daily.md
> [doc] Fix daily script

- docs/web/user_guide.md
- web/client/codechecker_client/cmd/cmd.py
> [cmd] Extend the help message of "CodeChecker cmd del" command

- web/server/www/scripts/codecheckerviewer/CheckerStatistics.js
> [server] Fix double scroll bar on the GUI

- web/server/codechecker_server/session_manager.py
We were not able to edit the announcement header because the
`is_root` field had not set properly. The reason why it didn't
work was that if the user doesn't have a valid session token in
the database we will try to create a local session but we do not
check that the user has an entry in the SystemPermission table.
With this patch we will fix this problem.
> [server] Fix local session creation

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
duplicate of #2347 for the release branch
> '-' was missing from the iterator checkers argument

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_triple_arch.py
- analyzer/codechecker_analyzer/analyzers/clangsa/statistics_collector.py
- analyzer/codechecker_analyzer/analyzers/clangtidy/analyzer.py
- analyzer/tests/functional/analyze/test_analyze.py
Reverts Ericsson/codechecker#2308
> Revert "Replace adding '-isystem' with '-isystem-after'"

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
Reverts Ericsson/codechecker#2348
> Revert "'-' was missing from the iterator checkers argument"

- web/server/codechecker_server/auth/cc_ldap.py
- web/server/codechecker_server/server.py
- web/server/www/scripts/codecheckerviewer/codecheckerviewer.js
> Handle ldap exceptions

- docs/README.md
Add CodeChecker logo to the top of the main README.md file.
> [doc] Format main README.md

- docs/usage.md
> Same as #2380 
Incremental analysis using skip file and gerrit integration possibility
is added to the usage guide.
> Description of incremental analysis using skipfile

- analyzer/codechecker_analyzer/analyzer_context.py
- config/package_layout.json
- docs/package_layout.md
- web/codechecker_web/shared/webserver_context.py
* Remove static section from this config file.
* Remove unnecessary items from runtime section.
> [config] Refactoring package_layout.json file

- config/package_layout.json
Add some entries with the default values to the `package_layout.json`
file which was used by the analyzer and web context.
> [config] Add default values to the package_layout.json

- analyzer/codechecker_analyzer/analysis_manager.py
> [analyze] Delete the ZIP when a new failure ZIP is created for the same analysis

- web/server/www/scripts/codecheckerviewer/ListOfBugs.js
> [server] Fix switching between tabs

- analyzer/codechecker_analyzer/analyzer_context.py
- analyzer/codechecker_analyzer/analyzers/analyzer_types.py
- analyzer/codechecker_analyzer/cmd/checkers.py
> [analyzer] Resolve symlinks of compiler binaries

- .github/labeler.yml
- .github/workflows/label.yml
with github labeler action automatic pull request
labeling can be done based on this configuration
> add label configuration for the github actions

- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/tests/functional/config/__init__.py
- analyzer/tests/functional/config/test_config.py
- bin/CodeChecker.py
- config/codechecker.json
- docs/analyzer/user_guide.md
Allow the configuration from an explicit configuration file. The parameters in the config file will be emplaced as command line arguments.
> [analyze] Allow the configuration from a config file

- analyzer/codechecker_analyzer/cmd/parse.py
- analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py
- codechecker_common/report.py
- docs/analyzer/user_guide.md
> [cmd] Support json output for parse command

- .travis.yml
there were library version problems with libpq in the osx image
upgrading to xcode10 seems to solve the problem
> update to xcode10 in travis

- .travis.yml
The earlier introduced changes to update to a newer clang
works, this commit contains only some cleanup and some
additional comments.
> extra comments for clang compiler change in travis

- tools/tu_collector/tu_collector/tu_collector.py
> Remove fail zip first in case of write mode.

- CODEOWNERS
> [config] Introduce code owners file

- docs/web/user_guide.md
- web/api/v6/report_server.thrift
- web/client/codechecker_client/cmd/cmd.py
- web/client/codechecker_client/cmd_line_client.py
- web/client/codechecker_client/thrift_helper.py
- web/codechecker_web/shared/version.py
- web/server/codechecker_server/api/report_server.py
- web/server/www/scripts/version.js
- web/tests/functional/cmdline/test_cmdline.py
> [web] Update run from CLI

- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
This change was not done at a usage of this attribute.
> args.config has been renamed to args.config_file

- docs/README.md
> add missing info to osx install guide

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/unit/test_log_parser.py
- codechecker_common/skiplist_handler.py
Skipfile normalization now occurs before skiplist handling.
> Skipfile normalization fix

- Makefile
- analyzer/codechecker_analyzer/analyzers/clangsa/clang_options.py
- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_triple_arch.py
- analyzer/codechecker_analyzer/analyzers/clangsa/version.py
- analyzer/tests/functional/analyze/test_analyze.py
- analyzer/tests/unit/ctu_autodetection_test_files/apple_llvm_10_version
- analyzer/tests/unit/test_option_parser.py
This PR should replace #2487
resolves #2486
> Detect clang version on OSX 

- config/config.json
cherry-pick of a0001c3fd8b972f4bdb57d9b02d75f4f589e9c2b for the v6.11.1 release branch
> [cfg] Do not enable all modernize checkers in sensitive profile

- analyzer/codechecker_analyzer/buildlog/log_parser.py
- analyzer/tests/unit/test_option_parser.py
There can be include directories with *intrin.h header files
not only at the implicit includes, this change
filters out any include directories containing *intrin.h header files.
> filter out include directories containing *intrin.h header files

- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- docs/analyzer/user_guide.md
> [refactor] Remove experimental note from the context free hash help message

- web/server/www/scripts/codecheckerviewer/BugViewer.js
Show the full file path at the Bug Viewer page in the title when hovering the mouse over the file path.
> [gui] Show full file path in title at Bug Viewer

- analyzer/codechecker_analyzer/cmd/analyze.py
If the source file for a plist does not exists, remove the plist from the
system and from the metadata.
> [analyzer] Cleanup metadata

- docs/analyzer/user_guide.md
> [doc] Change user in build command of CodeChecker log

- analyzer/requirements.txt
- analyzer/requirements_py/dev/requirements.txt
- analyzer/requirements_py/osx/requirements.txt
- web/requirements.txt
- web/requirements_py/db_pg8000/requirements.txt
- web/requirements_py/db_psycopg2/requirements.txt
- web/requirements_py/dev/requirements.txt
- web/requirements_py/osx/requirements.txt
python 3.8 needs a newer lxml version
resolves #2599
> bump up lxml version

- analyzer/requirements.txt
- analyzer/requirements_py/dev/requirements.txt
- analyzer/requirements_py/osx/requirements.txt
- web/requirements.txt
- web/requirements_py/db_pg8000/requirements.txt
- web/requirements_py/db_psycopg2/requirements.txt
- web/requirements_py/dev/requirements.txt
- web/requirements_py/osx/requirements.txt
bump up psutil version in one commit instead of separate commits created by dependabot
> bump up psutil version from 5.2.2 to 5.6.6

- web/server/codechecker_server/api/report_server.py
- web/tests/functional/detection_status/test_detection_status.py
There was a problem with CodeChecker when .clang-tidy configration
file is used. If we enabled a checker in this config file and we
do not enabled it explicitly in CodeChecker if we stored the results
to the server these reports are marked as OFF.
With this patch if we store a report directory to the server then a
bug which can be found in this report directory can not be marked as
OFF so the detection status will be calculated properly.
> [fix] Fix changing detection status to OFF

- tools/report-converter/codechecker_report_converter/analyzer_result.py
- tools/report-converter/codechecker_report_converter/clang_tidy/analyzer_result.py
- tools/report-converter/codechecker_report_converter/cli.py
- tools/report-converter/codechecker_report_converter/cppcheck/analyzer_result.py
- tools/report-converter/codechecker_report_converter/sanitizers/address/analyzer_result.py
- tools/report-converter/codechecker_report_converter/sanitizers/memory/analyzer_result.py
- tools/report-converter/codechecker_report_converter/sanitizers/thread/analyzer_result.py
- tools/report-converter/codechecker_report_converter/sanitizers/ub/analyzer_result.py
> [report-converter] Improve the help message

- analyzer/tests/functional/analyze_and_parse/test_files/context_free_hash_clang_tidy.output
- analyzer/tests/functional/analyze_and_parse/test_files/context_free_hash_clangsa.output
- analyzer/tests/functional/analyze_and_parse/test_files/context_free_hash_v2_clang_tidy.output
- analyzer/tests/functional/analyze_and_parse/test_files/context_free_hash_v2_clangsa.output
- analyzer/tests/functional/analyze_and_parse/test_files/context_sensitive_hash_clang.output
- analyzer/tests/functional/analyze_and_parse/test_files/context_sensitive_hash_clang_tidy.output
`--analyzer` option was used instead of `--analyzers` option. This commit
fix this problem.
> [test] Fix unrecognized analyzer option in test

- web/server/codechecker_server/server.py
- web/server/codechecker_server/session_manager.py
> [server] Remove unused session salt variable

- web/server/codechecker_server/auth/cc_ldap.py
I got an error when I tried to run a CodeChecker server with a
postgres database, using psycopg2 driver and ldap configration.
```
File "/codechecker/lib/python3/codechecker_server/permissions.py", line 217, in has_permission
groups = self._has_perm_impl(auth_session.groups, True)
File "/codechecker/lib/python3/codechecker_server/permissions.py", line 434, in _has_perm_impl
exists = self.__session.query(query.exists()).scalar()
...
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: text = bytea
LINE 3: ...roduct_id = 5 AND lower(permissions_product.name) IN ('\x6b6...
^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
```
The problem is that when we moved to python3 we forgot to converter
bytes to …
> [server] Convert ldap values to text

- analyzer/tools/build-logger/README.md
- analyzer/tools/build-logger/test/test_logger.sh
> Closes #2636
Update the default values of the `CC_LOGGER_GCC_LIKE` environment variable.
> [ld-logger] Update the documentation

- analyzer/tests/unit/remove_report_test_files/files/empty.h
- analyzer/tests/unit/remove_report_test_files/files/x.cpp
- analyzer/tests/unit/remove_report_test_files/keep_only_empty.expected.plist
- analyzer/tests/unit/remove_report_test_files/keep_only_empty.txt
- analyzer/tests/unit/remove_report_test_files/skip_x_header.expected.plist
- analyzer/tests/unit/remove_report_test_files/x.plist
- analyzer/tests/unit/test_remove_report_from_plist.py
- codechecker_common/plist_parser.py
- web/client/codechecker_client/cmd/store.py
- web/server/codechecker_server/api/report_server.py
- web/tests/functional/skip/test_skip.py
> [client] Do not store empty plist file to the server

- codechecker_common/plist_parser.py
- tools/codechecker_report_hash/codechecker_report_hash/hash.py
- tools/plist_to_html/plist_to_html/PlistToHtml.py
plistlib.load() throws this exception if the plist file is invalid.
> handle plistlib.InvalidFileException during parsing

- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- docs/analyzer/user_guide.md
> [doc] Describe hash generation methods

- tools/tu_collector/tu_collector/tu_collector.py
The logger in the tu_collector was not initialized properly. This way
a lot of message was printed twice to the output. For example:
```
[INFO 2020-04-15 11:56] - [4/4] clangsa analyzed lib.cpp successfully.
INFO:analyzer:[4/4] clangsa analyzed lib.cpp successfully.
```
In this commit the logger will be initialized and a new --verbose option
will be introduced for the logger to debugging.
> [tu-collector] Improve logging

- web/server/codechecker_server/api/report_server.py
If there is already a lock in the database for the given run name which
is already expired and multiple processes are trying to get the lock
entry from the database for update we may get the following exception:
```
could not obtain lock on row in relation "run_locks"
```
Steps to reproduce:
- Put 5 seconds sleep before and after getting run lock entry from the
database in the `__store_run_lock` function.
- Make sure that there is already a run lock in the database for the
given run and it is expired.
- Run two storages which will update the same run.
- Exception will be thrown.
> [server] Fix getting run lock

- web/client/codechecker_client/cmd/store.py
- web/server/codechecker_server/api/report_server.py
Print storage information on the server and client logs.
> [web] Improve storage logs

- analyzer/codechecker_analyzer/arg.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- analyzer/codechecker_analyzer/cmd/log.py
- analyzer/codechecker_analyzer/cmd/parse.py
- analyzer/tools/build-logger/README.md
- codechecker_common/arg.py
- docs/analyzer/user_guide.md
- docs/web/user_guide.md
- web/client/codechecker_client/cmd/cmd.py
- web/client/codechecker_client/cmd/store.py
Show available environment variables in the command line help.
> [cmd] Show available env vars in cmd help

- web/server/codechecker_server/api/report_server.py
> Closes #2655 and Closes #2653
When we use multiple server instances and we try to run multiple storage
to each server which contain at least two same reports which have source
code comments it is possible that the following exception will be thrown:
(psycopg2.extensions.TransactionRollbackError) deadlock detected
Neither of the two processes can continue, and they will wait for each other
indefinitely. PostgreSQL in this case will terminate one transaction with
the above exception. For this reason in case of failure we will wait some
seconds and try to run the storage again.
For more information see #2655 and #2653 issues on github.
> [server] Handle database deadlocks when storing reports

- analyzer/codechecker_analyzer/cmd/check.py
- analyzer/codechecker_analyzer/cmd/parse.py
- analyzer/codechecker_analyzer/suppress_handler.py
- analyzer/tests/functional/analyze_and_parse/test_files/source_code_comments.cpp
- analyzer/tests/functional/analyze_and_parse/test_files/source_code_comments.output
- analyzer/tests/functional/analyze_and_parse/test_files/source_code_comments_all.output
- analyzer/tests/functional/analyze_and_parse/test_files/source_code_comments_all_empty_filter.output
- analyzer/tests/functional/analyze_and_parse/test_files/source_code_comments_confirmed.output
- analyzer/tests/functional/analyze_and_parse/test_files/source_code_comments_false_positive.output
- codechecker_common/source_code_comment_handler.py
- docs/analyzer/user_guide.md
- tools/plist_to_html/plist_to_html/PlistToHtml.py
- tools/plist_to_html/plist_to_html/static/css/bugview.css
- tools/plist_to_html/plist_to_html/static/css/style.css
- tools/plist_to_html/plist_to_html/static/js/buglist.js
- tools/plist_to_html/plist_to_html/static/js/bugviewer.js
- tools/plist_to_html/plist_to_html/static/layout.html
- web/server/codechecker_server/api/report_server.py
- web/server/tests/unit/test_source_code_comment.py
> [cmd] Parse print review status

- analyzer/codechecker_analyzer/analyzers/clangsa/config_handler.py
- analyzer/codechecker_analyzer/analyzers/config_handler.py
- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- analyzer/codechecker_analyzer/env.py
- docs/README.md
- docs/analyzer/user_guide.md
- docs/package_layout.md
> [analyzer] Configure ClangSA plugin directory from env var

- codechecker_common/report.py
- docs/web/user_guide.md
- web/client/codechecker_client/cmd/cmd.py
- web/client/codechecker_client/cmd_line_client.py
- web/tests/functional/diff_local_remote/test_diff_local_remote.py
> [cmd] Support Code Climate format for cmd diff command

- analyzer/codechecker_analyzer/cmd/checkers.py
- analyzer/tests/functional/cmdline/test_cmdline.py
> Fixing profile listing

- web/server/codechecker_server/api/report_server.py
- web/tests/functional/review_status/test_review_status.py
Previously a new system comment was created every time the user stored
results to a run. To prevent this with this patch we will create a new
system comment only if the review status or the message have changed.
> [server] Add new system comment only on review status change

- docs/analyzer/checker_and_analyzer_configuration.md
- docs/analyzer/user_guide.md
Adding some "how-to" documentation about analyzer and checker config options.
> [doc] Extending analyzer and checker config docs

- analyzer/tests/unit/test_statistics_collectors.py
- codechecker_common/plist_parser.py
- web/server/tests/unit/test_source_code_comment.py
E741 ambiguous variable name errors are cleaned up now.
> [refactor] cleanup pycodestyle E741 errors

- tools/report-converter/README.md
- tools/report-converter/codechecker_report_converter/cli.py
> [report-converter] Show default values in the help message

- web/server/codechecker_server/api/report_server.py
Use nested queries to filter by source component filter instead
of getting file ids in separate query and use it in IN clause.
It will drastically improve the query performance.
> [server] Improve source component filter performance

- web/server/vue-cli/src/components/Report/SourceComponent/EditSourceComponentDialog.vue
> Closes #2847
- Validate source component value.
- Trim form values.
- Validate value field only on blur event.
> [gui] Validate source component form

- web/server/vue-cli/config/webpack.dev.js
- web/server/vue-cli/src/router/index.js
This commit adds some alias for the new url routes (login, products) to be
backward compatible with the old UI.
> [vue] Add alias for some urls

- analyzer/codechecker_analyzer/buildlog/build_manager.py
Assume that the environment pickle can be encoded as utf-8
when loaded.
> improve loading the saved build env

- web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaseFilter.mixin.js
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/DetectionDateFilter.vue
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/DetectionDateFilterIcon.vue
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/DetectionDateFilterItems.js
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/SelectOption.vue
With the new UI the preconfigured filter items for detection date filter
disappeared. This patch will implement it again.
> [gui] Show filter items for detection date filter

- web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaseSelectOptionFilter.mixin.js
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/SourceComponentFilter.vue
Show source component value when hovering the mouse over a source
component at the filter bar.
> [gui] Show source component value in tooltip

- web/server/vue-cli/e2e/specs/reports.js
This bug was introduced in #2896.
> [test] Fix test when sorting reports

- web/api/Makefile
- web/api/js/codechecker-api-js/package.json
- web/api/js/codechecker-api-node/package.json
- web/api/products.thrift
- web/api/py/codechecker_api/setup.py
- web/api/py/codechecker_api_shared/setup.py
- web/api/report_server.thrift
- web/api/server_info.thrift
- web/requirements.txt
- web/requirements_py/db_pg8000/requirements.txt
- web/requirements_py/db_psycopg2/requirements.txt
- web/requirements_py/dev/requirements.txt
- web/requirements_py/osx/requirements.txt
- web/server/codechecker_server/api/server_info_handler.py
- web/server/codechecker_server/server.py
- web/server/vue-cli/config/webpack.common.js
- web/server/vue-cli/config/webpack.dev.js
- web/server/vue-cli/package-lock.json
- web/server/vue-cli/package.json
- web/server/vue-cli/src/components/Layout/TheHeader.vue
- web/server/vue-cli/src/services/api/index.js
- web/server/vue-cli/src/services/api/server-info.service.js
- web/server/vue-cli/src/store/index.js
- web/server/vue-cli/src/store/modules/auth.js
- web/server/vue-cli/src/store/modules/product.js
- web/server/vue-cli/src/store/modules/server-info.js
> Closes #2791
Create a new API function under the Authentication API endpoint
which can be used to get the package version without authentication.
> [server] Get package version on the login page

- analyzer/codechecker_analyzer/analyzers/result_handler_base.py
- analyzer/tests/unit/test_result_handler.py
> Don't include gcc -o output in .plist hash

- web/server/vue-cli/src/views/NewFeatures.vue
Extend the New features page with the new features of the 6.14.0
CodeChecker release.
> [gui] Extend new features page with 6.14 features

- docs/README.md
https://github.com/Ericsson/codechecker/blob/master/tools/report-converter/README.md#facebook-infer
is the right link
> Fix the anchor to fb infer

- docs/README.md
- docs/supported_code_analyzers.md
- tools/report-converter/README.md
- tools/report-converter/codechecker_report_converter/cli.py
- tools/report-converter/codechecker_report_converter/coccinelle/__init__.py
- tools/report-converter/codechecker_report_converter/coccinelle/analyzer_result.py
- tools/report-converter/codechecker_report_converter/coccinelle/output_parser.py
- tools/report-converter/tests/unit/coccinelle_output_test_files/files/sample.c
- tools/report-converter/tests/unit/coccinelle_output_test_files/sample.expected.plist
- tools/report-converter/tests/unit/coccinelle_output_test_files/sample.out
- tools/report-converter/tests/unit/test_coccinelle_parser.py
Coccinelle report converter tool for parsing coccinelle output of kernel sources
> Coccinelle parser

- tools/report-converter/README.md
- tools/report-converter/codechecker_report_converter/coccinelle/output_parser.py
- tools/report-converter/tests/unit/coccinelle_output_test_files/sample.expected.plist
- tools/report-converter/tests/unit/coccinelle_output_test_files/sample.out
Patch for Implementing ```checker name``` functionality in Coccinelle Parser
> [report-converter] Support for checker name in Coccinelle Parser

- web/tests/functional/skip/test_skip.py
Skip test is checking whether some reports are really not
stored because they were skipped during analysis with --skip flag.
However, since clang-tidy is not run, there will be no reports from
"clang-diagnostic" checker. These are handled separately here,
otherwise the test would believe they're missing because of --skip
which is not the case.
> [test] Clang diagnostic reports in skip tests

- docs/analyzer/user_guide.md
Add note about meta-codechecker layer with an integration as OpenEmbedded compatible layer.
> [user_guide.md]: Add note about new bitbake integration option

- .travis.yml
the test execution on the osx machines is very instable
> [test] turn off osx tests in travis

- Makefile
- analyzer/codechecker_analyzer/cmd/parse.py
- analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py
- codechecker_common/output/codeclimate.py
- codechecker_common/output/gerrit.py
- codechecker_common/report.py
- codechecker_common/tests/.noserc
- codechecker_common/tests/unit/Makefile
- codechecker_common/tests/unit/__init__.py
- codechecker_common/tests/unit/test_gerrit_converter.py
- docs/analyzer/user_guide.md
- web/client/codechecker_client/cmd_line_client.py
> refactoring and gerrit output for the parse subcommand

- web/server/codechecker_server/api/report_server.py
- web/tests/functional/diff_remote/test_diff_remote.py
> [server] Fix open reports date filter when no run filter is set

- web/server/codechecker_server/api/report_server.py
- web/server/vue-cli/e2e/pages/report.js
- web/server/vue-cli/e2e/specs/reports.js
- web/server/vue-cli/src/components/BulbMessage.vue
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineRunFilter.vue
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineTagItems.vue
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/Items.vue
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/SelectOption.vue
- web/server/vue-cli/src/services/api/cc.service.js
- web/server/vue-cli/src/services/api/index.js
> [gui] Select tag for each run filter item

- web/server/vue-cli/src/components/Report/Report.vue
- web/server/vue-cli/src/components/Report/ReportInfo/ReportInfo.vue
- web/server/vue-cli/src/components/Report/ReportInfo/ReportInfoButton.vue
- web/server/vue-cli/src/components/Report/ReportInfo/ShowReportInfoDialog.vue
- web/server/vue-cli/src/components/Report/ReportInfo/index.js
> [gui] Show report info in dialog at the report detail page

- web/server/vue-cli/src/components/Report/Report.vue
- web/server/vue-cli/src/main.js
- Search and highlight occurrences of the selected text.
- Enable code search.
> [gui] Enable search and highlight occurences of the selected text

- web/client/codechecker_client/cmd_line_client.py
- web/client/codechecker_client/thrift_call.py
If there is some problem on the server side or the
user does not have the proper access rights, handle
the exception returned from the server in the client,
and print some useful error messages.
> [web][client] handle exceptions from the server at the client side

- analyzer/codechecker_analyzer/cmd/analyze.py
- analyzer/codechecker_analyzer/cmd/check.py
- docs/analyzer/user_guide.md
Reverts Ericsson/codechecker#2983
> Revert "[analyzer] Use maximum CPU resources by default during analysis"

- web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineOpenReportsDateFilter.vue
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/DetectionStatusFilter.vue
- web/server/vue-cli/src/components/TooltipHelpIcon.vue
> Closes #3041 and closes #3042
> [gui] Design tooltips

- analyzer/Makefile
- analyzer/tools/statistics_collector/Makefile
- web/api/Makefile
These wrong space characters were introduced in #3045.
> [makefile] Replace wrong space character in makefiles

- web/server/vue-cli/src/components/Report/ReportTree/ReportTree.vue
> [gui] Show review status in Report Tree view

- web/server/vue-cli/src/components/Product/ProductConfigForm.vue
Set database host, port and username fields as mandatory when creating a product
with postgresql database.
> [gui] Set required field for product config form

- analyzer/codechecker_analyzer/buildlog/log_parser.py
> [analyzer] Add -mrecord-mcount$ in log_parser.py

- CODEOWNERS
Unfortunately @gyorb left our company and he is not working on this
project anymore. So for this reason we should remove him from the
code owners list. This way he will not get an automatic review request
for every pull requests and it will not confuse the open source users
why he doesn't review the PR's.
> [github] Update codeowners

- web/server/codechecker_server/api/report_server.py
Review status is a shared table among runs. When multiple runs
are stored in parallel, there may be a race condition in updating
review status fields. The most common reason of deadlocks is
changing only the date to current date. This condition checks if
something else is also changed other than dates.
> [server] Change review status date only if necessary

- tools/report-converter/codechecker_report_converter/cppcheck/analyzer_result.py
Closes #2571.
I'm publishing this as a sign that I managed to find a satisfying solution to the issue raised, but I didn't have the time to write tests just yet. I'll revise this PR later.
> [report-converter] Skip incorrect CppCheck Plist files

- scripts/debug_tools/prepare_analyzer_cmd.py
If no ctu_dir is provided, do not touch it.
> [debug-tools] fix prepare_analyzer_cmd.py

- web/server/vue-cli/e2e/pages/report.js
- web/server/vue-cli/e2e/specs/reports.js
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaselineRunFilter.vue
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/Items.vue
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/SelectOption.vue
> Part of #2898
Clicking on `Apply` button at a filter option should close the options' window.
> [gui] Close filter settings on apply

- analyzer/codechecker_analyzer/analyzers/clangsa/analyzer.py
- analyzer/tests/functional/cmdline/test_cmdline.py
> [analyzer] Fix parsing clangsa analyze help

- codechecker_common/report.py
- web/client/codechecker_client/cmd_line_client.py
- web/tests/functional/diff_local/test_diff_local.py
- web/tests/functional/diff_local_remote/test_diff_local_remote.py
- web/tests/functional/diff_remote/test_diff_remote.py
- web/tests/libtest/codechecker.py
> [client] Handle suppression properly in diff command

- web/server/vue-cli/src/components/Report/Report.vue
It is easier to see where the bug is if we highlight it on the scrollbar too.
Screenshot:
> [gui] Highlight report on the scrollbar

- web/server/codechecker_server/api/report_server.py
Refactore the code and create a common function (`get_analysis_statistics_query`) which can be used multiple places.
> [server] Fix getting analysis statistics

- analyzer/requirements.txt
- analyzer/requirements_py/dev/requirements.txt
- analyzer/requirements_py/osx/requirements.txt
- web/requirements.txt
- web/requirements_py/db_pg8000/requirements.txt
- web/requirements_py/db_psycopg2/requirements.txt
- web/requirements_py/dev/requirements.txt
- web/requirements_py/osx/requirements.txt
> To solve dependabot vulnerability: https://github.com/Ericsson/codechecker/security/dependabot/analyzer/requirements.txt/lxml/open
> [req] Upgrade lxml to 4.6.3

- docs/architecture.md
> delete duplicate line

- docs/README.md
The PostgreSQL database backend setup guide link is broken.
> [fix] PostgreSQL database backend setup guide README link

- scripts/test/run_server_performance_test.py
Handle the following use cases in a better way:
- All the commands are runs succesfully in time.
- One command takes too much time so the script will timeout.
- When the user stops the execution of this script with Ctrl+C.
> [fix] Server performance test script

- docs/README.md
> [doc] Add note for snap package usage

- analyzer/tests/functional/analyze_and_parse/test_analyze_and_parse.py
- analyzer/tests/functional/ctu/test_ctu.py
- analyzer/tests/functional/ctu_failure/test_ctu_failure.py
- analyzer/tests/libtest/codechecker.py
It returns the underlying process return code too.
> [test] Refactor process runner function

- .github/workflows/test.yml
- Makefile
- analyzer/requirements_py/dev/requirements.txt
- analyzer/tests/Makefile
- codechecker_common/requirements_py/dev/requirements.txt
- codechecker_common/tests/unit/Makefile
- web/client/tests/Makefile
- web/requirements_py/dev/requirements.txt
- web/server/tests/Makefile
- web/tests/Makefile
Close #1934 
Run unit test coverage in web, analyzer, and common
> [githubaction] add coverage for unit tests

- tools/plist_to_html/plist_to_html/static/css/style.css
> [plist2html] Scrollable sidebar

- .gitignore
- web/api/Makefile
- web/api/README.md
> [api] Add local package to git automatically and refactore the doc

- analyzer/codechecker_analyzer/cmd/parse.py
- codechecker_common/skiplist_handler.py
- web/server/codechecker_server/api/mass_store_run.py
Skip list handler object handles in its own implementation if not
skipfile was specified in the command line.
> [refactor] Usage of skip list handler is not optional anymore

- web/requirements_py/osx/requirements.txt
> [fix] Typo in thrift package name in requirement file

- config/labels/analyzers/cppcheck.json
- scripts/labels/cppcheck.py
- Create a label file for cppcheck analyzer.
- Add helper script to get labels for cppcheck analyzer.
> [config] Add label file for cppcheck analyzer

- config/labels/analyzers/pylint.json
- scripts/labels/pylint.py
- Create a label file for pylint analyzer.
- Add helper script to get labels for pylint analyzer.
> [config] Add label file for pylint analyzer

- alembic.ini
Extended both the config, and the default product database file.
> [db] Add sqlite config to alembic.ini

- web/server/codechecker_server/api/product_server.py
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/CleanupPlanFilter.vue
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/SourceComponentFilter.vue
- web/server/vue-cli/src/views/Products.vue
Show edit source component and cleanup plans buttons only for users who are either administrators of the current product or have superuser rigths.
> [server][gui] Show edit option only for admins

- docs/README.md
Two typos in the main README are fixed.
> Small typo fix

- docs/usage.md
-Describe what the user should do in case the analysis failed.
-Description about the structure of the failed zip added.
-The local analysis workflow should be part of Step-8 and not an additional step
as it is a server-less alternative
> Update the Usage Guide

- web/server/vue-cli/src/components/Run/RunNameColumn.vue
> [gui] Fix whitespace in run name links

- analyzer/requirements.txt
- analyzer/requirements_py/dev/requirements.txt
- analyzer/requirements_py/osx/requirements.txt
- web/requirements.txt
- web/requirements_py/db_pg8000/requirements.txt
- web/requirements_py/db_psycopg2/requirements.txt
- web/requirements_py/dev/requirements.txt
- web/requirements_py/osx/requirements.txt
> [dep] Upgrade lxml to 4.6.4

- config/labels/analyzers/clang-tidy.json
Additionally the file was changed automatically by the text editor (remove of whitespace and add a newline at the end).
> [config]Add bugprone-unhandled-exception-at-new to default profile.

- web/server/codechecker_server/api/report_server.py
Previously to get filter for `Other (auto-generated)` source component
we build the query on the following way:
- We created a subquery to get files which are included in
one of the components.
- Next we used this subquery to get files which are not in the result of
this subquery.
So the query looked like this:
`Files NOT IN (Files IN (Component_1 OR Component_2 ... OR Component_N))`
In this commit we will simplify this query on the following way:
`(Files NOT IN Component_1) AND (Files NOT IN Component_2) ... AND (Files NOT IN Component_N)`
> [server] Simplify query for `Other` source component

- web/server/codechecker_server/api/report_server.py
Change permission of the stored analysis failure zip files so only
the current user/group will have access to this file.
> [server] Change permission of stored analysis failure files

- docs/analyzer/user_guide.md
> [doc] Extend documentation with implicitly disabled checkers under --enable-all

- analyzer/codechecker_analyzer/cmd/checkers.py
Convert relative `doc_url` value's to absolute file paths in the
`CodeChecker checkers` output. This way other tools can
open and view these documentation files easily.
> [cmd] Relative doc url to absolute file path

- web/server/vue-cli/src/views/NewFeatures.vue
> [gui] Describe new features in 6.19.0

- codechecker_common/requirements_py/dev/requirements.txt
- web/requirements.txt
> [req] Add pyyaml dependency to the web part

- analyzer/config/analyzer_version.json
- setup.py
- snap/snapcraft.yaml
- web/config/web_version.json
> [version] Bump up version to 6.20.0

- analyzer/codechecker_analyzer/analyzers/clangsa/ctu_manager.py
- analyzer/tools/merge_clang_extdef_mappings/codechecker_merge_clang_extdef_mappings/merge_clang_extdef_mappings.py
@Szelethus Could you please commandeer this patch? I guess we'd need some tests for the input files and some unit tests for a common function that is used in both places.
> Fix ctu extdef mapping file with space problem

- web/server/codechecker_server/api/report_server.py
Sometimes run deletion is a slow operation due to cascades and such.
So runs are deleted in separate transactions in order to avoid potential
statement timeouts in a DBMS.
> [server] Delete runs in separate transactions

- Makefile
Exactly what is says on the tin!
> Add a report-converter symlink to the dev_package target

- analyzer/codechecker_analyzer/cmd/check.py
- analyzer/codechecker_analyzer/cmd/parse.py
- docs/analyzer/user_guide.md
- docs/web/user_guide.md
- tools/report-converter/codechecker_report_converter/util.py
- tools/report-converter/tests/unit/util/test_trim_path_prefix.py
- web/client/codechecker_client/cmd/store.py
Exactly what is says on the tin!
> [CLI] Allow Unix shell-style wildcards in --trim-path-prefix

- web/server/codechecker_server/api/report_server.py
- web/tests/functional/report_viewer_api/test_report_counting.py
The SQL statement querying review status counts when filtering reports
in GUI with uniqueing was invalid.
> [bugfix] Review status count error fix

- .github/workflows/install-deps.sh
- .github/workflows/test.yml
18.04 has been deprecated in GitHub actions.
> [test] Update to Ubuntu 20.04 in tests

- tools/report-converter/codechecker_report_converter/report/output/html/html.py
- tools/report-converter/codechecker_report_converter/report/output/html/static/js/bugviewer.js
Close https://github.com/Ericsson/codechecker/issues/3748
> report output html: replace in var data=… </script> with &lt;/script&gt; to produce valid HTML

- web/server/codechecker_server/api/report_server.py
This commit tries to address the everlasting diff runtime, when the report count is large (~60000) and the ReviewStatus count is also substantial.
Two main edits were made, one is in getLinesInSourceFileContents the other is in getReviewStatusRules api endpoints. In getLinesInSourceFileContents my goal was to combine the requests into chunks.
In getReviewStatusRules the goal was also the same, but here a monolithic request was chopped into chunks.
> [fix] Speed up resolved diffing

- analyzer/codechecker_analyzer/cmd/analyzer_version.py
- web/codechecker_web/cmd/web_version.py
This is the output when this commit is rebased on branch release-v6.21.0-rc1.
> Issue a warning about this release being only an RC

- .pylintrc
- analyzer/tools/build-logger/.pylintrc
- analyzer/tools/build-logger/src/ldlogger-logger.c
- analyzer/tools/merge_clang_extdef_mappings/.pylintrc
- analyzer/tools/statistics_collector/.pylintrc
- codechecker_common/checker_labels.py
- docs/web/user_guide.md
- tools/report-converter/.pylintrc
- tools/report-converter/codechecker_report_converter/analyzers/infer/analyzer_result.py
- tools/report-converter/codechecker_report_converter/report/output/html/html.py
- tools/tu_collector/.pylintrc
- web/server/codechecker_server/cmd/server.py
- web/tests/functional/component/test_component.py
> Typos a/an

- web/server/vue-cli/src/components/Report/ReportFilter/Filters/BaseSelectOptionFilter.mixin.js
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/FilePathFilter.vue
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/SelectOption/AnywhereOnReportPath.vue
- web/server/vue-cli/src/components/Report/ReportFilter/Filters/SourceComponentFilter.vue
File filter and source component filters have an "anywhere on report path" option in the web UI. The state of this option is now saved in the URL.
> [gui] Set "anywhere on path" in URL

- analyzer/codechecker_analyzer/analyzers/cppcheck/analyzer.py
fixes https://github.com/Ericsson/codechecker/issues/3811
> cppcheck: allow spaces in path

- web/tests/libtest/codechecker.py
Needed to capture stderr and stdout as well.
> [tests] Change subprocess.call to subprocess.Popen

- analyzer/codechecker_analyzer/analyzer.py
- analyzer/tests/functional/analyze/test_analyze.py
- web/tests/functional/diff_local/test_diff_local.py
Exactly what it says on the tin!
> [analyzer] Promote the missing checker warning to an error

- web/server/vue-cli/src/views/NewFeatures.vue
> [doc] Add 6.22.0 new features in GUI

- web/server/vue-cli/package-lock.json
Should have been done in #3876
> [fix] package-lock.json update due to vuetify version change

- analyzer/codechecker_analyzer/analysis_manager.py
Fixes #3442, where if the SIGINT signal was sent to CodeChecker during a mulithread analysis, zombie processes were left. The problem was that the signal handler actually threw an exception:
free variable 'pool' referenced before assignment in enclosing scope
This patch fixes this by moving signal.signal below the creation of the pool variable.
Also, there is this site I randomly opened that said
"The process pool may take a moment to forcefully kill all child processes, so it is a good practice to call the join() function after calling terminate()."
https://superfastpython.com/multiprocessing-pool-kill-all-tasks/
so I did that, though thats just blindly listening to the article.
> [bugfix] Fix the zombie process issue

- web/server/vue-cli/src/components/Run/RunFilterToolbar.vue
> [GUI] Add a tooltip about Diff

- web/requirements.txt
- web/requirements_py/dev/requirements.txt
See the relevant dependabot report for more context.
https://github.com/Ericsson/codechecker/security/dependabot/81
https://github.com/Ericsson/codechecker/security/dependabot/82
> Bump GitPython version

- analyzer/tools/build-logger/src/ldlogger-hooks.c
The simple idea behind ldlogger is the following -- create a .so file
that we force to be loaded for each program that is executed by adding
it to the LD_PRELOAD environmental variable. In that .so, we shadow
exec* calls with our impostor exec* calls -- instead of the real thing,
our version is called, which logs the compile command, and then calls
the actual system function.
Up to, but not including GNU Make 4.3, only exec* system calls were
used. However, as of 4.3, posix_spawn is used by default, so this patch
adds shadow functions for posix_spawn and the very similar posix_spawnp.
Related discussion: https://github.com/Ericsson/codechecker/discussions/3906
> [ldlogger] Recognize linux_spawn alongside exec* calls

- analyzer/requirements.txt
- analyzer/requirements_py/dev/requirements.txt
- analyzer/requirements_py/osx/requirements.txt
- codechecker_common/requirements_py/dev/requirements.txt
- web/requirements.txt
> [env] Upgrade PyYAML to version 6.0

- web/client/codechecker_client/cmd_line_client.py
- web/tests/functional/diff_cmdline/test_diff_cmdline.py
Pretty much what it says on the tin.
> Fix local local diff src code suppression

- config/labels/analyzers/clang-tidy.json
These added checkers/warnings report violations of SEI-CERT rules.
> [config] Add some checkers to "default" profile

- .github/workflows/pypi.yml
> Update macos in pypi action

- web/client/codechecker_client/blame_info.py
> Fix impossible blame info collection

- analyzer/codechecker_analyzer/buildlog/log_parser.py
A small fix for a crashing logging statement.
> [fix] Error when debug logging skipped actions

- docs/web/db_schema_guide.md
The documentation missing the python path for modifying schema.  
Modified.
> Modified documentation to match current procedures for changing schema

- analyzer/requirements.txt
- scripts/labels/label_tool/requirements.txt
- web/requirements.txt
- web/requirements_py/db_pg8000/requirements.txt
- web/requirements_py/db_psycopg2/requirements.txt
add this upgrade for python 3.13 compatibility
> Update lxml to 5.3.0

- analyzer/codechecker_analyzer/analyzers/analyzer_base.py
- analyzer/tests/unit/test_env_var.py
- web/server/codechecker_server/migrations/config/versions/f59dfe4623fa_clear_legacy_web_sessions.py
The execution environment must be package internal for internal binaries and original for external binaries
> fix the execution environment for binaries 

- web/docker/Dockerfile
The codechecker server faield to connect to to
SSL ldap server without this package
> Add libldap to docker image

- web/server/codechecker_server/api/authentication.py
Graph API group query should have paging
to be able to fetch all groups.
> Add paging to the graph API query

- web/server/codechecker_server/server.py
When HTTPS is not enabled on the server, the connection should not be upgraded via CSP headers.
Fixes #4449.
> Fix CSP when HTTPS is not enabled on the server

- .github/workflows/config_coverage.yml
- .github/workflows/pypi.yml
- .github/workflows/test.yml
- docs/deps.md
- docs/usage.md
- scripts/labels/http_.py
- setup.py
- snap/snapcraft.yaml
- tools/bazel/setup.py
- tools/report-converter/setup.py
- tools/tu_collector/setup.py
Python 3.8 is EOL, bump to 3.9.
Fixes #4549
> [version] Bump python version to 3.9

- web/server/codechecker_server/server.py
So far there were ValueErrors in the server logs when trying to open a product that does not exist. These errors will appear as debug-level log messages from now on to reduce the noise in the logs.
> [fix] Demote product not found errors to debug in the CC logs

- web/server/codechecker_server/session_manager.py
Personal Access Tokens stores groups then creator have when creating the PAT and not synced when some groups were revoked. Sync this on login to prevent group mismatch.
> [feat] Sync group permissions with login provider to prevent out-of-sync groups.

- web/server/vue-cli/src/components/Statistics/Overview/OutstandingReportsChart.vue
Statistics page graph dots route to the reports page to show the issues found on the given date.
> [feat] Show found issues on a given date from statistics
